package com.astryxion.chaospersists.world.biome;

import com.astryxion.chaospersists.core.ChaosPersists;
import com.astryxion.chaospersists.entity.Alosaurus;
import com.astryxion.chaospersists.entity.Baryonyx;
import com.astryxion.chaospersists.entity.Basilisk;
import com.astryxion.chaospersists.entity.Beaver;
import com.astryxion.chaospersists.entity.Bee;
import com.astryxion.chaospersists.entity.Brutalfly;
import com.astryxion.chaospersists.entity.Cassowary;
import com.astryxion.chaospersists.entity.CaterKiller;
import com.astryxion.chaospersists.entity.CaveFisher;
import com.astryxion.chaospersists.entity.Chipmunk;
import com.astryxion.chaospersists.entity.CliffRacer;
import com.astryxion.chaospersists.entity.CloudShark;
import com.astryxion.chaospersists.entity.Cockateil;
import com.astryxion.chaospersists.entity.CreepingHorror;
import com.astryxion.chaospersists.entity.Cryolophosaurus;
import com.astryxion.chaospersists.entity.Dragonfly;
import com.astryxion.chaospersists.entity.DungeonBeast;
import com.astryxion.chaospersists.entity.EmperorScorpion;
import com.astryxion.chaospersists.entity.EnchantedCow;
import com.astryxion.chaospersists.entity.EnderKnight;
import com.astryxion.chaospersists.entity.EnderReaper;
import com.astryxion.chaospersists.entity.EntityButterfly;
import com.astryxion.chaospersists.entity.EntityLunaMoth;
import com.astryxion.chaospersists.entity.Fairy;
import com.astryxion.chaospersists.entity.Firefly;
import com.astryxion.chaospersists.entity.GammaMetroid;
import com.astryxion.chaospersists.entity.GoldCow;
import com.astryxion.chaospersists.entity.GoldFish;
import com.astryxion.chaospersists.entity.Hammerhead;
import com.astryxion.chaospersists.entity.HerculesBeetle;
import com.astryxion.chaospersists.entity.LeafMonster;
import com.astryxion.chaospersists.entity.Leon;
import com.astryxion.chaospersists.entity.LurkingTerror;
import com.astryxion.chaospersists.entity.Mantis;
import com.astryxion.chaospersists.entity.Molenoid;
import com.astryxion.chaospersists.entity.Mothra;
import com.astryxion.chaospersists.entity.Nastysaurus;
import com.astryxion.chaospersists.entity.Ostrich;
import com.astryxion.chaospersists.entity.Peacock;
import com.astryxion.chaospersists.entity.PitchBlack;
import com.astryxion.chaospersists.entity.Pointysaurus;
import com.astryxion.chaospersists.entity.Rat;
import com.astryxion.chaospersists.entity.RedCow;
import com.astryxion.chaospersists.entity.Robot1;
import com.astryxion.chaospersists.entity.Robot2;
import com.astryxion.chaospersists.entity.Robot3;
import com.astryxion.chaospersists.entity.Robot4;
import com.astryxion.chaospersists.entity.Robot5;
import com.astryxion.chaospersists.entity.Rotator;
import com.astryxion.chaospersists.entity.Scorpion;
import com.astryxion.chaospersists.entity.SpitBug;
import com.astryxion.chaospersists.entity.StinkBug;
import com.astryxion.chaospersists.entity.TRex;
import com.astryxion.chaospersists.entity.TerribleTerror;
import com.astryxion.chaospersists.entity.TrooperBug;
import com.astryxion.chaospersists.entity.Urchin;
import com.astryxion.chaospersists.entity.Vortex;
import net.minecraft.world.biome.Biome;

public class BiomeChaosPlains extends BiomeGenUtopianPlains {
  public BiomeChaosPlains() {
    super(ChaosPersists.BiomeChaosID, "Chaos", 353825, 0.7f, 0.5f);
    this.spawnableCreatureList.clear();
    this.spawnableMonsterList.clear();
    this.spawnableWaterCreatureList.clear();
    this.spawnableCaveCreatureList.clear();

    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(EntityButterfly.class, 20, 3, 6));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(EntityLunaMoth.class, 10, 1, 5));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(Cockateil.class, 10, 2, 4));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(Firefly.class, 15, 3, 6));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(CliffRacer.class, 30, 3, 6));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(CloudShark.class, 2, 1, 1));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(GoldFish.class, 10, 2, 4));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(Fairy.class, 5, 2, 4));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(Baryonyx.class, 2, 2, 4));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(Bee.class, 2, 2, 4));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(Cassowary.class, 2, 2, 4));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(Dragonfly.class, 2, 2, 4));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(Peacock.class, 2, 2, 4));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(StinkBug.class, 3, 2, 4));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(Ostrich.class, 1, 1, 2));
    this.spawnableCaveCreatureList.add(new Biome.SpawnListEntry(Chipmunk.class, 1, 1, 2));

    this.spawnableCreatureList.add(new Biome.SpawnListEntry(Beaver.class, 1, 1, 2));
    this.spawnableCreatureList.add(new Biome.SpawnListEntry(RedCow.class, 3, 2, 4));
    this.spawnableCreatureList.add(new Biome.SpawnListEntry(GoldCow.class, 2, 2, 4));
    this.spawnableCreatureList.add(new Biome.SpawnListEntry(EnchantedCow.class, 1, 2, 4));

    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Vortex.class, 1, 1, 2));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(PitchBlack.class, 1, 1, 2));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(TerribleTerror.class, 4, 2, 6));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Alosaurus.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Basilisk.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Robot1.class, 5, 2, 8));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Robot2.class, 2, 1, 4));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Robot3.class, 2, 1, 4));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Robot4.class, 1, 1, 2));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Robot5.class, 2, 3, 5));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(CaterKiller.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(CaveFisher.class, 5, 1, 5));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(CreepingHorror.class, 5, 1, 5));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Cryolophosaurus.class, 5, 1, 5));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Urchin.class, 2, 1, 5));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(DungeonBeast.class, 2, 1, 5));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(EmperorScorpion.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(EnderKnight.class, 2, 1, 2));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(EnderReaper.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Hammerhead.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(HerculesBeetle.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(TrooperBug.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Molenoid.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Mothra.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Brutalfly.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Rat.class, 10, 1, 10));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Rotator.class, 1, 1, 3));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Scorpion.class, 2, 1, 3));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(SpitBug.class, 2, 1, 3));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Nastysaurus.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(TRex.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(LeafMonster.class, 2, 1, 4));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Pointysaurus.class, 2, 1, 4));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Leon.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(Mantis.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(LurkingTerror.class, 1, 1, 1));
    this.spawnableMonsterList.add(new Biome.SpawnListEntry(GammaMetroid.class, 1, 1, 1));

    this.decorator.flowersPerChunk = 2;
    this.decorator.grassPerChunk = 4;
    this.decorator.treesPerChunk = 1;
    this.decorator.bigMushroomsPerChunk = -999;
    this.decorator.mushroomsPerChunk = -999;
    this.decorator.reedsPerChunk = -999;
  }
}
