package com.astryxion.chaospersists.model;

import com.astryxion.chaospersists.entity.TrooperBug;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

public class ModelTrooperBug extends EntityModel<TrooperBug> {
    private final float wingspeed;
    private final ModelPart legintersection;
    private final ModelPart legintersectionb;
    private final ModelPart leg1start;
    private final ModelPart leg1shoulder;
    private final ModelPart leg1shoulderpart2;
    private final ModelPart leg1part1;
    private final ModelPart leg1part1b;
    private final ModelPart leg1elbow;
    private final ModelPart leg1part2;
    private final ModelPart leg1part2b;
    private final ModelPart leg1part2c;
    private final ModelPart leg1part3;
    private final ModelPart leg1part3b;
    private final ModelPart leg1part3c;
    private final ModelPart leg1part3d;
    private final ModelPart leg2start;
    private final ModelPart leg2shoulder;
    private final ModelPart leg2shoulderpart2;
    private final ModelPart leg2part1;
    private final ModelPart leg2part1b;
    private final ModelPart leg2elbow;
    private final ModelPart leg2part2;
    private final ModelPart leg2part2b;
    private final ModelPart leg2part2c;
    private final ModelPart leg2part3;
    private final ModelPart leg2part3b;
    private final ModelPart leg2part3c;
    private final ModelPart leg2part3d;
    private final ModelPart leg3start;
    private final ModelPart leg3shoulder;
    private final ModelPart leg3shoulderpart2;
    private final ModelPart leg3part1;
    private final ModelPart leg3part1b;
    private final ModelPart leg3elbow;
    private final ModelPart leg3part2;
    private final ModelPart leg3part2b;
    private final ModelPart leg3part2c;
    private final ModelPart leg3part3;
    private final ModelPart leg3part3b;
    private final ModelPart leg3part3c;
    private final ModelPart leg3part3d;
    private final ModelPart leg4start;
    private final ModelPart leg4shoulder;
    private final ModelPart leg4shoulderpart2;
    private final ModelPart leg4part1;
    private final ModelPart leg4part1b;
    private final ModelPart leg4elbow;
    private final ModelPart leg4part2;
    private final ModelPart leg4part2b;
    private final ModelPart leg4part2c;
    private final ModelPart leg4part3;
    private final ModelPart leg4part3b;
    private final ModelPart leg4part3c;
    private final ModelPart leg4part3d;
    private final ModelPart jawbase;
    private final ModelPart jawbase2;
    private final ModelPart jawbase3;
    private final ModelPart jawbase4;
    private final ModelPart jawbase5;
    private final ModelPart jawbase6;
    private final ModelPart jawbase7;
    private final ModelPart jawbase8;
    private final ModelPart jawbase9;
    private final ModelPart jawleft;
    private final ModelPart jawright;
    private final ModelPart jawend;
    private final ModelPart headstart;
    private final ModelPart headbase;
    private final ModelPart headbase2;
    private final ModelPart headbase3;
    private final ModelPart headbase4;
    private final ModelPart headbase5;
    private final ModelPart headbase6;
    private final ModelPart headbase7;
    private final ModelPart headbase8;
    private final ModelPart headbase9;
    private final ModelPart headbase10;
    private final ModelPart headleftridge;
    private final ModelPart headrightridge;
    private final ModelPart antenna1;
    private final ModelPart antenna1part2;
    private final ModelPart antenna2;
    private final ModelPart antenna2part2;
    private final ModelPart eyebase1;
    private final ModelPart eye1;
    private final ModelPart eyebase2;
    private final ModelPart eye2;
    private final ModelPart arm1start;
    private final ModelPart arm1part1;
    private final ModelPart arm1part2;
    private final ModelPart arm1part2b;
    private final ModelPart arm1part2c;
    private final ModelPart arm1part3;
    private final ModelPart arm1part3b;
    private final ModelPart arm2start;
    private final ModelPart arm2part1;
    private final ModelPart arm2part2;
    private final ModelPart arm2part2b;
    private final ModelPart arm2part2c;
    private final ModelPart arm2part3;
    private final ModelPart arm2part3b;
    private final ModelPart innermouth;
    private final ModelPart innermouth2;
    private final ModelPart tooth1;
    private final ModelPart tooth2;
    private final ModelPart tooth3;
    private final ModelPart tooth4;
    private final ModelPart tooth5;
    private final ModelPart tooth6;
    private final ModelPart mouthedge1;
    private final ModelPart mouthedge2;
    private final ModelPart mouthedge3;
    private final ModelPart mouthedge4;
    private final ModelPart arm3start;
    private final ModelPart arm3part1;
    private final ModelPart arm3part1b;
    private final ModelPart arm3part1c;
    private final ModelPart arm4start;
    private final ModelPart arm4part1;
    private final ModelPart arm4part1b;
    private final ModelPart arm4part1c;
    private final ModelPart tongue;
    private final ModelPart tonguepart2;
    private final ModelPart upperjawridgeleft;
    private final ModelPart upperjawridgeright;
    private final ModelPart upperjawbaseleft;
    private final ModelPart upperjawbaseright;
    private final ModelPart upperjawbase;
    private final ModelPart upperjawbase2;
    private final ModelPart upperjawbase3;
    private final ModelPart upperjawbase4;
    private final ModelPart upperjawend;
    private final ModelPart upperjawleftend;
    private final ModelPart upperjawrightend;

    public ModelTrooperBug(float wingspeed) {
        this(LayerDefinition.create(createMesh(), 512, 256).bakeRoot(), wingspeed);
    }

    public ModelTrooperBug(ModelPart root, float wingspeed) {
        this.wingspeed = wingspeed;
        this.legintersection = root.getChild("legintersection");
        this.legintersectionb = root.getChild("legintersectionb");
        this.leg1start = root.getChild("leg1start");
        this.leg1shoulder = root.getChild("leg1shoulder");
        this.leg1shoulderpart2 = root.getChild("leg1shoulderpart2");
        this.leg1part1 = root.getChild("leg1part1");
        this.leg1part1b = root.getChild("leg1part1b");
        this.leg1elbow = root.getChild("leg1elbow");
        this.leg1part2 = root.getChild("leg1part2");
        this.leg1part2b = root.getChild("leg1part2b");
        this.leg1part2c = root.getChild("leg1part2c");
        this.leg1part3 = root.getChild("leg1part3");
        this.leg1part3b = root.getChild("leg1part3b");
        this.leg1part3c = root.getChild("leg1part3c");
        this.leg1part3d = root.getChild("leg1part3d");
        this.leg2start = root.getChild("leg2start");
        this.leg2shoulder = root.getChild("leg2shoulder");
        this.leg2shoulderpart2 = root.getChild("leg2shoulderpart2");
        this.leg2part1 = root.getChild("leg2part1");
        this.leg2part1b = root.getChild("leg2part1b");
        this.leg2elbow = root.getChild("leg2elbow");
        this.leg2part2 = root.getChild("leg2part2");
        this.leg2part2b = root.getChild("leg2part2b");
        this.leg2part2c = root.getChild("leg2part2c");
        this.leg2part3 = root.getChild("leg2part3");
        this.leg2part3b = root.getChild("leg2part3b");
        this.leg2part3c = root.getChild("leg2part3c");
        this.leg2part3d = root.getChild("leg2part3d");
        this.leg3start = root.getChild("leg3start");
        this.leg3shoulder = root.getChild("leg3shoulder");
        this.leg3shoulderpart2 = root.getChild("leg3shoulderpart2");
        this.leg3part1 = root.getChild("leg3part1");
        this.leg3part1b = root.getChild("leg3part1b");
        this.leg3elbow = root.getChild("leg3elbow");
        this.leg3part2 = root.getChild("leg3part2");
        this.leg3part2b = root.getChild("leg3part2b");
        this.leg3part2c = root.getChild("leg3part2c");
        this.leg3part3 = root.getChild("leg3part3");
        this.leg3part3b = root.getChild("leg3part3b");
        this.leg3part3c = root.getChild("leg3part3c");
        this.leg3part3d = root.getChild("leg3part3d");
        this.leg4start = root.getChild("leg4start");
        this.leg4shoulder = root.getChild("leg4shoulder");
        this.leg4shoulderpart2 = root.getChild("leg4shoulderpart2");
        this.leg4part1 = root.getChild("leg4part1");
        this.leg4part1b = root.getChild("leg4part1b");
        this.leg4elbow = root.getChild("leg4elbow");
        this.leg4part2 = root.getChild("leg4part2");
        this.leg4part2b = root.getChild("leg4part2b");
        this.leg4part2c = root.getChild("leg4part2c");
        this.leg4part3 = root.getChild("leg4part3");
        this.leg4part3b = root.getChild("leg4part3b");
        this.leg4part3c = root.getChild("leg4part3c");
        this.leg4part3d = root.getChild("leg4part3d");
        this.jawbase = root.getChild("jawbase");
        this.jawbase2 = root.getChild("jawbase2");
        this.jawbase3 = root.getChild("jawbase3");
        this.jawbase4 = root.getChild("jawbase4");
        this.jawbase5 = root.getChild("jawbase5");
        this.jawbase6 = root.getChild("jawbase6");
        this.jawbase7 = root.getChild("jawbase7");
        this.jawbase8 = root.getChild("jawbase8");
        this.jawbase9 = root.getChild("jawbase9");
        this.jawleft = root.getChild("jawleft");
        this.jawright = root.getChild("jawright");
        this.jawend = root.getChild("jawend");
        this.headstart = root.getChild("headstart");
        this.headbase = root.getChild("headbase");
        this.headbase2 = root.getChild("headbase2");
        this.headbase3 = root.getChild("headbase3");
        this.headbase4 = root.getChild("headbase4");
        this.headbase5 = root.getChild("headbase5");
        this.headbase6 = root.getChild("headbase6");
        this.headbase7 = root.getChild("headbase7");
        this.headbase8 = root.getChild("headbase8");
        this.headbase9 = root.getChild("headbase9");
        this.headbase10 = root.getChild("headbase10");
        this.headleftridge = root.getChild("headleftridge");
        this.headrightridge = root.getChild("headrightridge");
        this.antenna1 = root.getChild("antenna1");
        this.antenna1part2 = root.getChild("antenna1part2");
        this.antenna2 = root.getChild("antenna2");
        this.antenna2part2 = root.getChild("antenna2part2");
        this.eyebase1 = root.getChild("eyebase1");
        this.eye1 = root.getChild("eye1");
        this.eyebase2 = root.getChild("eyebase2");
        this.eye2 = root.getChild("eye2");
        this.arm1start = root.getChild("arm1start");
        this.arm1part1 = root.getChild("arm1part1");
        this.arm1part2 = root.getChild("arm1part2");
        this.arm1part2b = root.getChild("arm1part2b");
        this.arm1part2c = root.getChild("arm1part2c");
        this.arm1part3 = root.getChild("arm1part3");
        this.arm1part3b = root.getChild("arm1part3b");
        this.arm2start = root.getChild("arm2start");
        this.arm2part1 = root.getChild("arm2part1");
        this.arm2part2 = root.getChild("arm2part2");
        this.arm2part2b = root.getChild("arm2part2b");
        this.arm2part2c = root.getChild("arm2part2c");
        this.arm2part3 = root.getChild("arm2part3");
        this.arm2part3b = root.getChild("arm2part3b");
        this.innermouth = root.getChild("innermouth");
        this.innermouth2 = root.getChild("innermouth2");
        this.tooth1 = root.getChild("tooth1");
        this.tooth2 = root.getChild("tooth2");
        this.tooth3 = root.getChild("tooth3");
        this.tooth4 = root.getChild("tooth4");
        this.tooth5 = root.getChild("tooth5");
        this.tooth6 = root.getChild("tooth6");
        this.mouthedge1 = root.getChild("mouthedge1");
        this.mouthedge2 = root.getChild("mouthedge2");
        this.mouthedge3 = root.getChild("mouthedge3");
        this.mouthedge4 = root.getChild("mouthedge4");
        this.arm3start = root.getChild("arm3start");
        this.arm3part1 = root.getChild("arm3part1");
        this.arm3part1b = root.getChild("arm3part1b");
        this.arm3part1c = root.getChild("arm3part1c");
        this.arm4start = root.getChild("arm4start");
        this.arm4part1 = root.getChild("arm4part1");
        this.arm4part1b = root.getChild("arm4part1b");
        this.arm4part1c = root.getChild("arm4part1c");
        this.tongue = root.getChild("tongue");
        this.tonguepart2 = root.getChild("tonguepart2");
        this.upperjawridgeleft = root.getChild("upperjawridgeleft");
        this.upperjawridgeright = root.getChild("upperjawridgeright");
        this.upperjawbaseleft = root.getChild("upperjawbaseleft");
        this.upperjawbaseright = root.getChild("upperjawbaseright");
        this.upperjawbase = root.getChild("upperjawbase");
        this.upperjawbase2 = root.getChild("upperjawbase2");
        this.upperjawbase3 = root.getChild("upperjawbase3");
        this.upperjawbase4 = root.getChild("upperjawbase4");
        this.upperjawend = root.getChild("upperjawend");
        this.upperjawleftend = root.getChild("upperjawleftend");
        this.upperjawrightend = root.getChild("upperjawrightend");
    }

    private static MeshDefinition createMesh() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("legintersection", CubeListBuilder.create().texOffs(0, 0).addBox(-9.0f, -2.0f, -9.0f, 18, 4, 18), PartPose.offset(0.0f, 0.0f, 0.0f));
        root.addOrReplaceChild("legintersectionb", CubeListBuilder.create().texOffs(0, 156).addBox(-9.0f, -2.0f, -16.0f, 18, 4, 18), PartPose.offsetAndRotation(0.0f, 0.0f, 7.0f, 0.2230717f, 0.0f, 0.0f));
        root.addOrReplaceChild("leg1start", CubeListBuilder.create().texOffs(55, 0).addBox(-3.0f, -2.5f, -4.0f, 6, 5, 5), PartPose.offsetAndRotation(-7.0f, 0.0f, -7.0f, 0.0f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg1shoulder", CubeListBuilder.create().texOffs(77, 0).addBox(-2.5f, -4.5f, -6.0f, 5, 6, 10), PartPose.offsetAndRotation(-10.0f, 0.0f, -10.0f, -0.5576792f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg1shoulderpart2", CubeListBuilder.create().texOffs(70, 18).addBox(-1.5f, -2.5f, -11.0f, 3, 3, 6), PartPose.offsetAndRotation(-10.0f, 0.0f, -10.0f, -0.4089647f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg1part1", CubeListBuilder.create().texOffs(68, 17).addBox(-2.0f, -2.5f, -23.0f, 4, 3, 26), PartPose.offsetAndRotation(-17.0f, -5.0f, -17.0f, 1.115358f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg1part1b", CubeListBuilder.create().texOffs(19, 23).addBox(-1.5f, 0.5f, -23.0f, 3, 3, 21), PartPose.offsetAndRotation(-17.0f, -5.0f, -17.0f, 1.07818f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg1elbow", CubeListBuilder.create().texOffs(68, 28).addBox(-1.5f, -5.5f, -22.0f, 3, 6, 3), PartPose.offsetAndRotation(-17.0f, -5.0f, -17.0f, 1.115358f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg1part2", CubeListBuilder.create().texOffs(48, 47).addBox(-3.0f, -2.5f, -2.0f, 6, 4, 34), PartPose.offsetAndRotation(-27.0f, 12.0f, -27.0f, 1.784573f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg1part2b", CubeListBuilder.create().texOffs(3, 53).addBox(-2.5f, -2.5f, -2.0f, 5, 4, 33), PartPose.offsetAndRotation(-27.0f, 12.0f, -27.0f, 1.747395f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg1part2c", CubeListBuilder.create().texOffs(48, 86).addBox(-2.0f, -2.5f, -2.0f, 4, 4, 32), PartPose.offsetAndRotation(-27.0f, 12.0f, -27.0f, 1.710216f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg1part3", CubeListBuilder.create().texOffs(0, 91).addBox(-1.5f, -2.5f, -17.0f, 3, 4, 18), PartPose.offsetAndRotation(-32.0f, -17.0f, -32.0f, 1.189716f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg1part3b", CubeListBuilder.create().texOffs(15, 30).addBox(-1.0f, -1.5f, -27.0f, 2, 3, 10), PartPose.offsetAndRotation(-32.0f, -17.0f, -32.0f, 1.189716f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg1part3c", CubeListBuilder.create().texOffs(47, 23).addBox(-0.5f, -0.5f, -34.0f, 1, 2, 7), PartPose.offsetAndRotation(-32.0f, -17.0f, -32.0f, 1.189716f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg1part3d", CubeListBuilder.create().texOffs(0, 23).addBox(-0.5f, 0.5f, -44.0f, 1, 1, 10), PartPose.offsetAndRotation(-32.0f, -17.0f, -32.0f, 1.189716f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg2start", CubeListBuilder.create().texOffs(55, 0).addBox(-3.0f, -2.5f, -4.0f, 6, 5, 5), PartPose.offsetAndRotation(7.0f, 0.0f, -7.0f, 0.0f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg2shoulder", CubeListBuilder.create().texOffs(77, 0).addBox(-2.5f, -4.5f, -6.0f, 5, 6, 10), PartPose.offsetAndRotation(10.0f, 0.0f, -10.0f, -0.5576792f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg2shoulderpart2", CubeListBuilder.create().texOffs(70, 18).addBox(-1.5f, -2.5f, -11.0f, 3, 3, 6), PartPose.offsetAndRotation(10.0f, 0.0f, -10.0f, -0.4089647f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg2part1", CubeListBuilder.create().texOffs(68, 17).addBox(-2.0f, -2.5f, -23.0f, 4, 3, 26), PartPose.offsetAndRotation(17.0f, -5.0f, -17.0f, 1.115358f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg2part1b", CubeListBuilder.create().texOffs(19, 23).addBox(-1.5f, 0.5f, -23.0f, 3, 3, 21), PartPose.offsetAndRotation(17.0f, -5.0f, -17.0f, 1.07818f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg2elbow", CubeListBuilder.create().texOffs(68, 28).addBox(-1.5f, -5.5f, -22.0f, 3, 6, 3), PartPose.offsetAndRotation(17.0f, -5.0f, -17.0f, 1.115358f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg2part2", CubeListBuilder.create().texOffs(48, 47).addBox(-3.0f, -2.5f, -2.0f, 6, 4, 34), PartPose.offsetAndRotation(27.0f, 12.0f, -27.0f, 1.784573f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg2part2b", CubeListBuilder.create().texOffs(3, 53).addBox(-2.5f, -2.5f, -2.0f, 5, 4, 33), PartPose.offsetAndRotation(27.0f, 12.0f, -27.0f, 1.747395f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg2part2c", CubeListBuilder.create().texOffs(48, 86).addBox(-2.0f, -2.5f, -2.0f, 4, 4, 32), PartPose.offsetAndRotation(27.0f, 12.0f, -27.0f, 1.710216f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg2part3", CubeListBuilder.create().texOffs(0, 91).addBox(-1.5f, -2.5f, -17.0f, 3, 4, 18), PartPose.offsetAndRotation(32.0f, -17.0f, -32.0f, 1.189716f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg2part3b", CubeListBuilder.create().texOffs(15, 30).addBox(-1.0f, -1.5f, -27.0f, 2, 3, 10), PartPose.offsetAndRotation(32.0f, -17.0f, -32.0f, 1.189716f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg2part3c", CubeListBuilder.create().texOffs(47, 23).addBox(-0.5f, -0.5f, -34.0f, 1, 2, 7), PartPose.offsetAndRotation(32.0f, -17.0f, -32.0f, 1.189716f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg2part3d", CubeListBuilder.create().texOffs(0, 23).addBox(-0.5f, 0.5f, -44.0f, 1, 1, 10), PartPose.offsetAndRotation(32.0f, -17.0f, -32.0f, 1.189716f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg3start", CubeListBuilder.create().texOffs(55, 0).addBox(-3.0f, -2.5f, -1.0f, 6, 5, 5), PartPose.offsetAndRotation(7.0f, 0.0f, 7.0f, 0.0f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg3shoulder", CubeListBuilder.create().texOffs(114, 0).addBox(-2.5f, -4.5f, -4.0f, 5, 6, 10), PartPose.offsetAndRotation(10.0f, 0.0f, 10.0f, 0.5576851f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg3shoulderpart2", CubeListBuilder.create().texOffs(70, 18).addBox(-1.5f, -2.5f, 5.0f, 3, 3, 6), PartPose.offsetAndRotation(10.0f, 0.0f, 10.0f, 0.4089656f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg3part1", CubeListBuilder.create().texOffs(68, 17).addBox(-2.0f, -2.5f, -3.0f, 4, 3, 26), PartPose.offsetAndRotation(17.0f, -5.0f, 17.0f, -1.115353f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg3part1b", CubeListBuilder.create().texOffs(117, 55).addBox(-1.5f, 0.5f, 2.0f, 3, 3, 21), PartPose.offsetAndRotation(17.0f, -5.0f, 17.0f, -1.078177f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg3elbow", CubeListBuilder.create().texOffs(68, 28).addBox(-1.5f, -5.5f, 19.0f, 3, 6, 3), PartPose.offsetAndRotation(17.0f, -5.0f, 17.0f, -1.115353f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg3part2", CubeListBuilder.create().texOffs(0, 206).addBox(-3.0f, -2.5f, -32.0f, 6, 4, 34), PartPose.offsetAndRotation(27.0f, 12.0f, 27.0f, -1.784582f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg3part2b", CubeListBuilder.create().texOffs(3, 53).addBox(-2.5f, -2.5f, -31.0f, 5, 4, 33), PartPose.offsetAndRotation(27.0f, 12.0f, 27.0f, -1.747389f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg3part2c", CubeListBuilder.create().texOffs(48, 86).addBox(-2.0f, -2.5f, -30.0f, 4, 4, 32), PartPose.offsetAndRotation(27.0f, 12.0f, 27.0f, -1.710213f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg3part3", CubeListBuilder.create().texOffs(0, 178).addBox(-1.5f, -2.5f, -1.0f, 3, 4, 18), PartPose.offsetAndRotation(32.0f, -17.0f, 32.0f, -1.189721f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg3part3b", CubeListBuilder.create().texOffs(12, 62).addBox(-1.0f, -1.5f, 17.0f, 2, 3, 10), PartPose.offsetAndRotation(32.0f, -17.0f, 32.0f, -1.189721f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg3part3c", CubeListBuilder.create().texOffs(47, 32).addBox(-0.5f, -0.5f, 27.0f, 1, 2, 7), PartPose.offsetAndRotation(32.0f, -17.0f, 32.0f, -1.189721f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg3part3d", CubeListBuilder.create().texOffs(0, 23).addBox(-0.5f, 0.5f, 34.0f, 1, 1, 10), PartPose.offsetAndRotation(32.0f, -17.0f, 32.0f, -1.189721f, 0.7853982f, 0.0f));
        root.addOrReplaceChild("leg4start", CubeListBuilder.create().texOffs(55, 0).addBox(-3.0f, -2.5f, -1.0f, 6, 5, 5), PartPose.offsetAndRotation(-7.0f, 0.0f, 7.0f, 0.0f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg4shoulder", CubeListBuilder.create().texOffs(114, 0).addBox(-2.5f, -4.5f, -4.0f, 5, 6, 10), PartPose.offsetAndRotation(-10.0f, 0.0f, 10.0f, 0.5576851f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg4shoulderpart2", CubeListBuilder.create().texOffs(70, 18).addBox(-1.5f, -2.5f, 5.0f, 3, 3, 6), PartPose.offsetAndRotation(-10.0f, 0.0f, 10.0f, 0.4089656f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg4part1", CubeListBuilder.create().texOffs(68, 17).addBox(-2.0f, -2.5f, -3.0f, 4, 3, 26), PartPose.offsetAndRotation(-17.0f, -5.0f, 17.0f, -1.115353f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg4part1b", CubeListBuilder.create().texOffs(117, 55).addBox(-1.5f, 0.5f, 2.0f, 3, 3, 21), PartPose.offsetAndRotation(-17.0f, -5.0f, 17.0f, -1.078177f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg4elbow", CubeListBuilder.create().texOffs(68, 28).addBox(-1.5f, -5.5f, 19.0f, 3, 6, 3), PartPose.offsetAndRotation(-17.0f, -5.0f, 17.0f, -1.115353f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg4part2", CubeListBuilder.create().texOffs(0, 206).addBox(-3.0f, -2.5f, -32.0f, 6, 4, 34), PartPose.offsetAndRotation(-27.0f, 12.0f, 27.0f, -1.784582f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg4part2b", CubeListBuilder.create().texOffs(3, 53).addBox(-2.5f, -2.5f, -31.0f, 5, 4, 33), PartPose.offsetAndRotation(-27.0f, 12.0f, 27.0f, -1.747389f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg4part2c", CubeListBuilder.create().texOffs(48, 86).addBox(-2.0f, -2.5f, -30.0f, 4, 4, 32), PartPose.offsetAndRotation(-27.0f, 12.0f, 27.0f, -1.710213f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg4part3", CubeListBuilder.create().texOffs(0, 178).addBox(-1.5f, -2.5f, -1.0f, 3, 4, 18), PartPose.offsetAndRotation(-32.0f, -17.0f, 32.0f, -1.189721f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg4part3b", CubeListBuilder.create().texOffs(12, 62).addBox(-1.0f, -1.5f, 17.0f, 2, 3, 10), PartPose.offsetAndRotation(-32.0f, -17.0f, 32.0f, -1.189721f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg4part3c", CubeListBuilder.create().texOffs(47, 32).addBox(-0.5f, -0.5f, 27.0f, 1, 2, 7), PartPose.offsetAndRotation(-32.0f, -17.0f, 32.0f, -1.189721f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("leg4part3d", CubeListBuilder.create().texOffs(0, 23).addBox(-0.5f, 0.5f, 34.0f, 1, 1, 10), PartPose.offsetAndRotation(-32.0f, -17.0f, 32.0f, -1.189721f, -0.7853982f, 0.0f));
        root.addOrReplaceChild("jawbase", CubeListBuilder.create().texOffs(104, 0).addBox(-2.0f, -2.0f, -40.0f, 4, 3, 40), PartPose.offsetAndRotation(0.0f, 0.0f, -8.0f, 0.2230717f, 0.0f, 0.0f));
        root.addOrReplaceChild("jawbase2", CubeListBuilder.create().texOffs(133, 44).addBox(-6.0f, -2.0f, -8.0f, 12, 3, 8), PartPose.offsetAndRotation(0.0f, 0.0f, -8.0f, 0.2230705f, 0.0f, 0.0f));
        root.addOrReplaceChild("jawbase3", CubeListBuilder.create().texOffs(96, 55).addBox(-7.0f, -2.0f, -15.0f, 14, 3, 7), PartPose.offsetAndRotation(0.0f, 0.0f, -8.0f, 0.2230705f, 0.0f, 0.0f));
        root.addOrReplaceChild("jawbase4", CubeListBuilder.create().texOffs(96, 47).addBox(-6.0f, -2.0f, -19.0f, 12, 3, 4), PartPose.offsetAndRotation(0.0f, 0.0f, -8.0f, 0.2230705f, 0.0f, 0.0f));
        root.addOrReplaceChild("jawbase5", CubeListBuilder.create().texOffs(104, 32).addBox(-5.0f, -2.0f, -23.0f, 10, 3, 4), PartPose.offsetAndRotation(0.0f, 0.0f, -8.0f, 0.2230705f, 0.0f, 0.0f));
        root.addOrReplaceChild("jawbase6", CubeListBuilder.create().texOffs(104, 25).addBox(-4.0f, -2.0f, -26.0f, 8, 3, 3), PartPose.offsetAndRotation(0.0f, 0.0f, -8.0f, 0.2230705f, 0.0f, 0.0f));
        root.addOrReplaceChild("jawbase7", CubeListBuilder.create().texOffs(104, 19).addBox(-3.0f, -2.0f, -28.0f, 6, 3, 2), PartPose.offsetAndRotation(0.0f, 0.0f, -8.0f, 0.2230705f, 0.0f, 0.0f));
        root.addOrReplaceChild("jawbase8", CubeListBuilder.create().texOffs(104, 150).addBox(-2.0f, -2.0f, -40.0f, 4, 4, 40), PartPose.offsetAndRotation(0.0f, 0.0f, -8.0f, 0.2146755f, 0.1487144f, -0.7679449f));
        root.addOrReplaceChild("jawbase9", CubeListBuilder.create().texOffs(104, 112).addBox(-3.0f, -3.0f, -21.0f, 6, 6, 29), PartPose.offsetAndRotation(0.0f, 0.0f, -8.0f, 0.1031397f, 0.0743623f, -0.837758f));
        root.addOrReplaceChild("jawleft", CubeListBuilder.create().texOffs(76, 61).addBox(-14.0f, -10.0f, -37.0f, 1, 11, 1), PartPose.offsetAndRotation(0.0f, 0.0f, -8.0f, 0.2230717f, -0.3346075f, 0.0f));
        root.addOrReplaceChild("jawright", CubeListBuilder.create().texOffs(71, 61).addBox(13.0f, -10.0f, -37.0f, 1, 11, 1), PartPose.offsetAndRotation(0.0f, 0.0f, -8.0f, 0.2230717f, 0.3346145f, 0.0f));
        root.addOrReplaceChild("jawend", CubeListBuilder.create().texOffs(76, 47).addBox(-0.5f, -11.0f, -39.5f, 1, 12, 1), PartPose.offsetAndRotation(0.0f, 0.0f, -8.0f, 0.2230717f, 0.0f, 0.0f));
        root.addOrReplaceChild("headstart", CubeListBuilder.create().texOffs(92, 87).addBox(-6.5f, -2.0f, -7.0f, 13, 9, 13), PartPose.offset(0.0f, -9.0f, 2.0f));
        root.addOrReplaceChild("headbase", CubeListBuilder.create().texOffs(206, 0).addBox(-8.0f, -2.0f, -6.0f, 16, 13, 24), PartPose.offset(0.0f, -17.0f, -2.0f));
        root.addOrReplaceChild("headbase2", CubeListBuilder.create().texOffs(300, 136).addBox(-8.5f, -2.0f, -6.0f, 17, 1, 34), PartPose.offset(0.0f, -17.0f, -3.0f));
        root.addOrReplaceChild("headbase3", CubeListBuilder.create().texOffs(300, 129).addBox(-9.0f, -2.0f, -6.0f, 18, 1, 39), PartPose.offset(0.0f, -18.0f, -4.0f));
        root.addOrReplaceChild("headbase4", CubeListBuilder.create().texOffs(300, 121).addBox(-9.5f, -2.0f, -6.0f, 19, 1, 45), PartPose.offset(0.0f, -19.0f, -5.0f));
        root.addOrReplaceChild("headbase5", CubeListBuilder.create().texOffs(300, 117).addBox(-10.0f, -2.0f, -6.0f, 20, 1, 47), PartPose.offset(0.0f, -20.0f, -6.0f));
        root.addOrReplaceChild("headbase6", CubeListBuilder.create().texOffs(300, 112).addBox(-11.0f, -2.0f, -6.0f, 22, 1, 50), PartPose.offset(0.0f, -21.0f, -9.0f));
        root.addOrReplaceChild("headbase7", CubeListBuilder.create().texOffs(0, 123).addBox(-8.0f, -7.0f, 0.0f, 16, 8, 24), PartPose.offsetAndRotation(0.0f, -8.0f, 13.0f, 0.5576792f, 0.0f, 0.0f));
        root.addOrReplaceChild("headbase8", CubeListBuilder.create().texOffs(300, 109).addBox(-11.0f, -1.0f, -6.0f, 22, 1, 51), PartPose.offset(0.0f, -23.0f, -9.0f));
        root.addOrReplaceChild("headbase9", CubeListBuilder.create().texOffs(300, 50).addBox(-11.0f, -1.0f, -6.0f, 22, 1, 51), PartPose.offset(0.0f, -24.0f, -9.0f));
        root.addOrReplaceChild("headbase10", CubeListBuilder.create().texOffs(185, 107).addBox(-7.0f, -1.5f, -20.0f, 14, 1, 42), PartPose.offsetAndRotation(0.0f, -24.0f, 7.0f, 0.0261799f, 0.0f, 0.0f));
        root.addOrReplaceChild("headleftridge", CubeListBuilder.create().texOffs(180, 153).addBox(-12.0f, -1.0f, -1.0f, 13, 1, 46), PartPose.offsetAndRotation(0.0f, -22.0f, -9.0f, 0.0743572f, -0.2230717f, 0.1487144f));
        root.addOrReplaceChild("headrightridge", CubeListBuilder.create().texOffs(300, 174).addBox(-1.0f, -1.0f, -1.0f, 13, 1, 46), PartPose.offsetAndRotation(0.0f, -22.0f, -9.0f, 0.0743572f, 0.2230705f, -0.1487195f));
        root.addOrReplaceChild("antenna1", CubeListBuilder.create().texOffs(332, 72).addBox(-3.0f, -1.0f, -1.0f, 5, 2, 2), PartPose.offset(-10.0f, -20.0f, 19.0f));
        root.addOrReplaceChild("antenna1part2", CubeListBuilder.create().texOffs(300, 81).addBox(-3.0f, -1.0f, 1.0f, 2, 2, 9), PartPose.offsetAndRotation(-10.0f, -20.0f, 19.0f, 0.0f, -0.7807508f, 0.0f));
        root.addOrReplaceChild("antenna2", CubeListBuilder.create().texOffs(325, 79).addBox(-2.0f, -1.0f, -1.0f, 5, 2, 2), PartPose.offset(10.0f, -20.0f, 19.0f));
        root.addOrReplaceChild("antenna2part2", CubeListBuilder.create().texOffs(300, 81).addBox(1.0f, -1.0f, 1.0f, 2, 2, 9), PartPose.offsetAndRotation(10.0f, -20.0f, 19.0f, 0.0f, 0.7807556f, 0.0f));
        root.addOrReplaceChild("eyebase1", CubeListBuilder.create().texOffs(300, 121).addBox(-2.5f, -2.5f, -1.5f, 5, 5, 3), PartPose.offsetAndRotation(-6.0f, -14.0f, -8.0f, 0.0f, 0.7807556f, -0.37179f));
        root.addOrReplaceChild("eye1", CubeListBuilder.create().texOffs(0, 0).addBox(-1.0f, -1.0f, -2.5f, 2, 2, 2), PartPose.offsetAndRotation(-6.0f, -14.0f, -8.0f, 0.0f, 0.7807556f, -0.37179f));
        root.addOrReplaceChild("eyebase2", CubeListBuilder.create().texOffs(300, 121).addBox(-2.5f, -2.5f, -1.5f, 5, 5, 3), PartPose.offsetAndRotation(6.0f, -14.0f, -8.0f, 0.0f, -0.7807508f, 0.3717861f));
        root.addOrReplaceChild("eye2", CubeListBuilder.create().texOffs(0, 0).addBox(-1.0f, -1.0f, -2.5f, 2, 2, 2), PartPose.offsetAndRotation(6.0f, -14.0f, -8.0f, 0.0f, -0.7807508f, 0.3717861f));
        root.addOrReplaceChild("arm1start", CubeListBuilder.create().texOffs(300, 93).addBox(-3.0f, -1.5f, -1.5f, 4, 3, 3), PartPose.offset(-9.0f, -20.0f, -3.0f));
        root.addOrReplaceChild("arm1part1", CubeListBuilder.create().texOffs(250, 83).addBox(-2.0f, -1.5f, -16.5f, 3, 3, 18), PartPose.offsetAndRotation(-11.0f, -20.0f, -4.0f, 0.0f, 0.2777036f, 0.0f));
        root.addOrReplaceChild("arm1part2", CubeListBuilder.create().texOffs(250, 83).addBox(-2.0f, -9.5f, -1.5f, 3, 11, 3), PartPose.offsetAndRotation(-15.3f, -20.0f, -20.0f, -0.7807508f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm1part2b", CubeListBuilder.create().texOffs(250, 69).addBox(-2.0f, -15.5f, -3.5f, 3, 8, 3), PartPose.offsetAndRotation(-15.3f, -20.0f, -20.0f, -1.041001f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm1part2c", CubeListBuilder.create().texOffs(300, 66).addBox(-2.0f, -17.5f, 8.5f, 3, 8, 3), PartPose.offsetAndRotation(-15.3f, -20.0f, -19.0f, -0.0743572f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm1part3", CubeListBuilder.create().texOffs(278, 60).addBox(-1.0f, -19.5f, -1.0f, 2, 21, 2), PartPose.offsetAndRotation(-15.8f, -36.0f, -8.0f, 1.561502f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm1part3b", CubeListBuilder.create().texOffs(279, 84).addBox(-0.5f, -10.5f, -1.0f, 1, 12, 2), PartPose.offsetAndRotation(-15.8f, -36.0f, -8.0f, 1.710216f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm2start", CubeListBuilder.create().texOffs(300, 105).addBox(-1.0f, -1.5f, -1.5f, 4, 3, 3), PartPose.offset(9.0f, -20.0f, -3.0f));
        root.addOrReplaceChild("arm2part1", CubeListBuilder.create().texOffs(250, 83).addBox(-2.0f, -1.5f, -16.5f, 3, 3, 18), PartPose.offsetAndRotation(11.0f, -20.0f, -4.0f, 0.0f, -0.2776993f, 0.0f));
        root.addOrReplaceChild("arm2part2", CubeListBuilder.create().texOffs(250, 83).addBox(-2.0f, -9.5f, -1.5f, 3, 11, 3), PartPose.offsetAndRotation(15.3f, -20.0f, -20.0f, -0.7807508f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm2part2b", CubeListBuilder.create().texOffs(250, 69).addBox(-2.0f, -15.5f, -3.5f, 3, 8, 3), PartPose.offsetAndRotation(15.3f, -20.0f, -20.0f, -1.041001f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm2part2c", CubeListBuilder.create().texOffs(300, 66).addBox(-2.0f, -17.5f, 8.5f, 3, 8, 3), PartPose.offsetAndRotation(15.3f, -20.0f, -19.0f, -0.0743572f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm2part3", CubeListBuilder.create().texOffs(287, 60).addBox(-1.0f, -19.5f, -1.0f, 2, 21, 2), PartPose.offsetAndRotation(14.8f, -36.0f, -8.0f, 1.561502f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm2part3b", CubeListBuilder.create().texOffs(279, 84).addBox(-0.5f, -10.5f, -1.0f, 1, 12, 2), PartPose.offsetAndRotation(14.8f, -36.0f, -8.0f, 1.710216f, 0.0f, 0.0f));
        root.addOrReplaceChild("innermouth", CubeListBuilder.create().texOffs(176, 44).addBox(-6.0f, -2.0f, -8.0f, 12, 3, 8), PartPose.offsetAndRotation(0.0f, 0.0f, -12.0f, -1.933289f, 0.0f, 0.0f));
        root.addOrReplaceChild("innermouth2", CubeListBuilder.create().texOffs(159, 4).addBox(-6.0f, -2.0f, -8.0f, 12, 3, 8), PartPose.offsetAndRotation(0.0f, -24.0f, -12.0f, 1.933284f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth1", CubeListBuilder.create().texOffs(0, 6).addBox(-5.0f, 0.0f, -10.0f, 2, 1, 2), PartPose.offsetAndRotation(1.0f, 0.0f, -12.0f, -1.933289f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth2", CubeListBuilder.create().texOffs(0, 6).addBox(1.0f, 0.0f, -10.0f, 2, 1, 2), PartPose.offsetAndRotation(1.0f, 0.0f, -12.0f, -1.933289f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth3", CubeListBuilder.create().texOffs(0, 6).addBox(1.0f, 0.0f, -10.0f, 2, 1, 2), PartPose.offsetAndRotation(-2.0f, 0.0f, -12.0f, -1.933289f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth4", CubeListBuilder.create().texOffs(0, 6).addBox(-4.0f, -2.0f, -10.0f, 2, 1, 2), PartPose.offsetAndRotation(0.0f, -24.0f, -12.0f, 1.933284f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth5", CubeListBuilder.create().texOffs(0, 6).addBox(2.0f, -2.0f, -10.0f, 2, 1, 2), PartPose.offsetAndRotation(0.0f, -24.0f, -12.0f, 1.933284f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth6", CubeListBuilder.create().texOffs(0, 6).addBox(-1.0f, -2.0f, -10.0f, 2, 1, 2), PartPose.offsetAndRotation(0.0f, -24.0f, -12.0f, 1.933284f, 0.0f, 0.0f));
        root.addOrReplaceChild("mouthedge1", CubeListBuilder.create().texOffs(400, 77).addBox(-1.0f, -4.5f, -1.5f, 3, 9, 14), PartPose.offsetAndRotation(9.0f, -12.0f, -6.0f, 0.0f, -0.2230717f, 0.0f));
        root.addOrReplaceChild("mouthedge2", CubeListBuilder.create().texOffs(400, 52).addBox(-2.0f, -4.5f, -1.5f, 3, 9, 14), PartPose.offsetAndRotation(-9.0f, -12.0f, -6.0f, 0.0f, 0.2230717f, 0.0f));
        root.addOrReplaceChild("mouthedge3", CubeListBuilder.create().texOffs(450, 69).addBox(-1.0f, -4.5f, -1.5f, 3, 9, 14), PartPose.offsetAndRotation(8.0f, -6.0f, -7.0f, 0.5576792f, -0.2230717f, 0.0f));
        root.addOrReplaceChild("mouthedge4", CubeListBuilder.create().texOffs(450, 93).addBox(-2.0f, -4.5f, -1.5f, 3, 9, 14), PartPose.offsetAndRotation(-8.0f, -6.0f, -7.0f, 0.5576792f, 0.2230705f, 0.0f));
        root.addOrReplaceChild("arm3start", CubeListBuilder.create().texOffs(335, 85).addBox(-1.0f, -1.5f, -1.5f, 4, 3, 3), PartPose.offset(10.0f, -9.0f, -3.0f));
        root.addOrReplaceChild("arm3part1", CubeListBuilder.create().texOffs(264, 108).addBox(-1.0f, -1.5f, -9.5f, 3, 3, 11), PartPose.offsetAndRotation(13.0f, -9.0f, -3.0f, -0.2602503f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm3part1b", CubeListBuilder.create().texOffs(317, 67).addBox(0.0f, -2.5f, -12.5f, 3, 5, 4), PartPose.offsetAndRotation(13.0f, -9.0f, -3.0f, -0.2602503f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm3part1c", CubeListBuilder.create().texOffs(300, 81).addBox(-2.0f, -2.5f, -12.51f, 3, 5, 0), PartPose.offsetAndRotation(13.0f, -9.0f, -3.0f, -0.2602503f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm4start", CubeListBuilder.create().texOffs(335, 93).addBox(-3.0f, -1.5f, -1.5f, 4, 3, 3), PartPose.offset(-10.0f, -9.0f, -3.0f));
        root.addOrReplaceChild("arm4part1", CubeListBuilder.create().texOffs(300, 51).addBox(-2.0f, -1.5f, -9.5f, 3, 3, 11), PartPose.offsetAndRotation(-13.0f, -9.0f, -3.0f, -0.2602503f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm4part1b", CubeListBuilder.create().texOffs(322, 106).addBox(-3.0f, -2.5f, -12.5f, 3, 5, 4), PartPose.offsetAndRotation(-13.0f, -9.0f, -3.0f, -0.2602503f, 0.0f, 0.0f));
        root.addOrReplaceChild("arm4part1c", CubeListBuilder.create().texOffs(316, 81).addBox(-1.0f, -2.5f, -12.51f, 3, 5, 0), PartPose.offsetAndRotation(-13.0f, -9.0f, -3.0f, -0.2602503f, 0.0f, 0.0f));
        root.addOrReplaceChild("tongue", CubeListBuilder.create().texOffs(0, 49).addBox(-1.0f, -1.0f, -10.0f, 2, 2, 11), PartPose.offset(0.0f, -12.0f, -8.0f));
        root.addOrReplaceChild("tonguepart2", CubeListBuilder.create().texOffs(0, 12).addBox(-1.0f, -1.5f, -8.0f, 2, 3, 1), PartPose.offset(0.0f, -12.0f, -8.0f));
        root.addOrReplaceChild("upperjawridgeleft", CubeListBuilder.create().texOffs(350, 27).addBox(-3.0f, -4.0f, -2.0f, 5, 1, 18), PartPose.offsetAndRotation(0.0f, -22.0f, -33.0f, 0.2602503f, -0.3717861f, 0.0f));
        root.addOrReplaceChild("upperjawridgeright", CubeListBuilder.create().texOffs(350, 27).addBox(-2.0f, -4.0f, -2.0f, 5, 1, 18), PartPose.offsetAndRotation(0.0f, -22.0f, -33.0f, 0.260246f, 0.37179f, 0.0f));
        root.addOrReplaceChild("upperjawbaseleft", CubeListBuilder.create().texOffs(235, 44).addBox(-5.0f, -3.0f, -16.0f, 3, 4, 14), PartPose.offsetAndRotation(0.0f, -22.0f, -35.0f, 0.0f, -0.2230717f, 0.0f));
        root.addOrReplaceChild("upperjawbaseright", CubeListBuilder.create().texOffs(210, 68).addBox(2.0f, -3.0f, -16.0f, 3, 4, 14), PartPose.offsetAndRotation(0.0f, -22.0f, -35.0f, 0.0f, 0.2230767f, 0.0f));
        root.addOrReplaceChild("upperjawbase", CubeListBuilder.create().texOffs(146, 76).addBox(-5.0f, -3.0f, -29.0f, 10, 4, 29), PartPose.offset(0.0f, -22.0f, -10.0f));
        root.addOrReplaceChild("upperjawbase2", CubeListBuilder.create().texOffs(168, 111).addBox(-5.0f, -4.0f, -2.0f, 10, 5, 18), PartPose.offsetAndRotation(0.0f, -22.0f, -33.0f, 0.2602503f, 0.0f, 0.0f));
        root.addOrReplaceChild("upperjawbase3", CubeListBuilder.create().texOffs(300, 0).addBox(-1.5f, -3.01f, -16.0f, 3, 3, 14), PartPose.offsetAndRotation(0.0f, -22.0f, -35.0f, 0.0f, 5.1E-6f, 0.0f));
        root.addOrReplaceChild("upperjawbase4", CubeListBuilder.create().texOffs(45, 161).addBox(-2.0f, -2.0f, -29.0f, 4, 4, 41), PartPose.offsetAndRotation(0.0f, -22.0f, -22.0f, 0.0698132f, -0.0488692f, 0.7807508f));
        root.addOrReplaceChild("upperjawend", CubeListBuilder.create().texOffs(160, 57).addBox(-0.5f, 0.0f, -0.5f, 1, 10, 1), PartPose.offsetAndRotation(0.0f, -20.0f, -50.0f, 0.0f, 5.1E-6f, 0.0f));
        root.addOrReplaceChild("upperjawleftend", CubeListBuilder.create().texOffs(171, 58).addBox(-0.5f, 0.0f, -0.5f, 1, 9, 1), PartPose.offsetAndRotation(-1.0f, -20.0f, -50.0f, -0.1115358f, -1.52433f, 0.0f));
        root.addOrReplaceChild("upperjawrightend", CubeListBuilder.create().texOffs(165, 58).addBox(-0.5f, 0.0f, -0.5f, 1, 9, 1), PartPose.offsetAndRotation(1.0f, -20.0f, -50.0f, -0.1115358f, 1.52433f, 0.0f));
        return mesh;
    }

    @Override
    public void setupAnim(TrooperBug entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        float newangle = 0.0f;
        float upangle = 0.0f;
        float nextangle = 0.0f;
        float pi4 = 1.570795f;
        newangle = entity.getAttacking() == 0 ? Mth.cos((float)(ageInTicks * 0.4f * this.wingspeed)) * 3.1415927f * 0.05f : Mth.cos((float)(ageInTicks * 1.4f * this.wingspeed)) * 3.1415927f * 0.1f;
        this.antenna2part2.yRot = 0.78f + newangle;
        this.antenna1part2.yRot = -0.78f - newangle;
        newangle = entity.getAttacking() == 0 ? Mth.cos((float)(ageInTicks * 0.5f * this.wingspeed)) * 3.1415927f * 0.05f : Mth.cos((float)(ageInTicks * 2.5f * this.wingspeed)) * 3.1415927f * 0.15f;
        this.arm4part1.yRot = newangle;
        this.arm4part1b.yRot = newangle;
        this.arm4part1c.yRot = newangle;
        this.arm3part1.yRot = - newangle;
        this.arm3part1b.yRot = - newangle;
        this.arm3part1c.yRot = - newangle;
        newangle = entity.getAttacking() == 0 ? Mth.cos((float)(ageInTicks * 0.3f * this.wingspeed)) * 3.1415927f * 0.05f : Mth.cos((float)(ageInTicks * 2.6f * this.wingspeed)) * 3.1415927f * 0.2f;
        this.arm1part3.xRot = 1.56f + newangle;
        this.arm1part3b.xRot = 1.56f + newangle;
        this.arm2part3.xRot = 1.56f - newangle;
        this.arm2part3b.xRot = 1.56f - newangle;
        newangle = entity.getAttacking() == 0 ? Mth.cos((float)(ageInTicks * 0.1f * this.wingspeed)) * 3.1415927f * 0.02f : Mth.cos((float)(ageInTicks * 1.0f * this.wingspeed)) * 3.1415927f * 0.1f;
        this.headleftridge.yRot = -0.25f + newangle;
        this.headrightridge.yRot = 0.25f - newangle;
        this.upperjawridgeleft.yRot = -0.372f + newangle;
        this.upperjawridgeright.yRot = 0.372f - newangle;
        newangle = entity.getAttacking() == 0 ? Mth.cos((float)(ageInTicks * 0.3f * this.wingspeed)) * 3.1415927f * 0.015f : Mth.cos((float)(ageInTicks * 2.6f * this.wingspeed)) * 3.1415927f * 0.1f;
        this.jawbase.xRot = 0.22f + newangle;
        this.jawbase2.xRot = 0.22f + newangle;
        this.jawbase3.xRot = 0.22f + newangle;
        this.jawbase4.xRot = 0.22f + newangle;
        this.jawbase5.xRot = 0.22f + newangle;
        this.jawbase6.xRot = 0.22f + newangle;
        this.jawbase7.xRot = 0.22f + newangle;
        this.jawbase8.xRot = 0.2146f + newangle;
        this.jawbase8.yRot = 0.1487f + newangle;
        this.jawbase9.xRot = 0.1f + newangle;
        this.jawbase9.yRot = 0.07f + newangle;
        this.jawend.xRot = 0.22f + newangle;
        this.jawleft.xRot = 0.22f + newangle;
        this.jawright.xRot = 0.22f + newangle;
        newangle = Mth.sin((float)(ageInTicks * 2.0f * this.wingspeed)) * 3.1415927f * 0.12f * limbSwingAmount;
        nextangle = Mth.sin((float)((ageInTicks + 0.1f) * 2.0f * this.wingspeed)) * 3.1415927f * 0.12f * limbSwingAmount;
        upangle = 0.0f;
        if (nextangle > newangle) {
            upangle = Math.abs(Mth.cos((float)(ageInTicks * 2.0f * this.wingspeed)) * 3.1415927f * 0.12f * limbSwingAmount);
        }
        this.doLeftFrontLeg(newangle, upangle);
        this.doLeftRearLeg(- newangle, upangle);
        newangle = Mth.sin((float)((float)((double)(ageInTicks * 2.0f * this.wingspeed) + 3.141592653589793))) * 3.1415927f * 0.12f * limbSwingAmount;
        nextangle = Mth.sin((float)((float)((double)((ageInTicks + 0.1f) * 2.0f * this.wingspeed) + 3.141592653589793))) * 3.1415927f * 0.12f * limbSwingAmount;
        upangle = 0.0f;
        if (nextangle > newangle) {
            upangle = Math.abs(Mth.cos((float)((float)((double)(ageInTicks * 2.0f * this.wingspeed) + 3.141592653589793))) * 3.1415927f * 0.12f * limbSwingAmount);
        }
        this.doRightFrontLeg(- newangle, upangle);
        this.doRightRearLeg(newangle, upangle);
    }

    @Override
    public void renderToBuffer(PoseStack poseStack, VertexConsumer buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        this.legintersection.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.legintersectionb.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1start.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1shoulder.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1shoulderpart2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1part1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1part1b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1elbow.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1part2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1part2b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1part2c.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1part3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1part3b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1part3c.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1part3d.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2start.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2shoulder.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2shoulderpart2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2part1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2part1b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2elbow.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2part2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2part2b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2part2c.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2part3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2part3b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2part3c.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2part3d.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3start.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3shoulder.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3shoulderpart2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3part1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3part1b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3elbow.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3part2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3part2b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3part2c.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3part3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3part3b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3part3c.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3part3d.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4start.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4shoulder.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4shoulderpart2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4part1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4part1b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4elbow.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4part2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4part2b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4part2c.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4part3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4part3b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4part3c.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4part3d.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jawbase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jawbase2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jawbase3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jawbase4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jawbase5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jawbase6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jawbase7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jawbase8.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jawbase9.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jawleft.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jawright.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jawend.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headstart.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headbase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headbase2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headbase3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headbase4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headbase5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headbase6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headbase7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headbase8.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headbase9.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headbase10.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headleftridge.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headrightridge.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.antenna1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.antenna1part2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.antenna2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.antenna2part2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.eyebase1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.eye1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.eyebase2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.eye2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm1start.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm1part1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm1part2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm1part2b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm1part2c.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm1part3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm1part3b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm2start.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm2part1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm2part2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm2part2b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm2part2c.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm2part3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm2part3b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.innermouth.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.innermouth2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mouthedge1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mouthedge2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mouthedge3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mouthedge4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm3start.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm3part1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm3part1b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm3part1c.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm4start.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm4part1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm4part1b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.arm4part1c.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tongue.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tonguepart2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.upperjawridgeleft.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.upperjawridgeright.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.upperjawbaseleft.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.upperjawbaseright.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.upperjawbase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.upperjawbase2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.upperjawbase3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.upperjawbase4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.upperjawend.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.upperjawleftend.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.upperjawrightend.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    }

    private void doRightFrontLeg(float angle, float upangle) {
        this.leg1part1b.yRot = this.leg1part1.yRot = 1.2f + angle;
        this.leg1elbow.yRot = this.leg1part1.yRot;
        this.leg1part2.yRot = this.leg1part1.yRot;
        this.leg1part2b.yRot = this.leg1part1.yRot;
        this.leg1part2c.yRot = this.leg1part1.yRot;
        this.leg1part3.yRot = this.leg1part1.yRot;
        this.leg1part3b.yRot = this.leg1part1.yRot;
        this.leg1part3c.yRot = this.leg1part1.yRot;
        this.leg1part3d.yRot = this.leg1part1.yRot;
        this.leg1part1.xRot = 1.115f + upangle;
        this.leg1part1b.xRot = 1.078f + upangle;
        this.leg1elbow.xRot = this.leg1part1.xRot;
        float dist = 26.0f;
        dist = (float) ((double) dist * Math.cos(this.leg1part1.xRot));
        this.leg1part2b.z = this.leg1part2c.z = (float) ((double) this.leg1part1.z - Math.cos(this.leg1part1.yRot) * (double) dist);
        this.leg1part2.z = this.leg1part2c.z;
        this.leg1part2b.x = this.leg1part2c.x = (float) ((double) this.leg1part1.x - Math.sin(this.leg1part1.yRot) * (double) dist);
        this.leg1part2.x = this.leg1part2c.x;
        this.leg1part2.xRot = 1.871f - upangle;
        this.leg1part2b.xRot = 1.817f - upangle;
        this.leg1part2c.xRot = 1.762f - upangle;
        dist = 32.0f;
        dist = (float) Math.abs((double) dist * Math.cos(this.leg1part2.xRot));
        this.leg1part3c.z = this.leg1part3d.z = (float) ((double) this.leg1part2.z - Math.cos(this.leg1part2.yRot) * (double) dist);
        this.leg1part3b.z = this.leg1part3d.z;
        this.leg1part3.z = this.leg1part3d.z;
        this.leg1part3c.x = this.leg1part3d.x = (float) ((double) this.leg1part2.x - Math.sin(this.leg1part2.yRot) * (double) dist);
        this.leg1part3b.x = this.leg1part3d.x;
        this.leg1part3.x = this.leg1part3d.x;
        this.leg1part3.xRot = 1.08f + upangle;
        this.leg1part3b.xRot = 1.08f + upangle;
        this.leg1part3c.xRot = 1.08f + upangle;
        this.leg1part3d.xRot = 1.08f + upangle;
    }

    private void doLeftFrontLeg(float angle, float upangle) {
        this.leg2part1b.yRot = this.leg2part1.yRot = -1.2f + angle;
        this.leg2elbow.yRot = this.leg2part1.yRot;
        this.leg2part2.yRot = this.leg2part1.yRot;
        this.leg2part2b.yRot = this.leg2part1.yRot;
        this.leg2part2c.yRot = this.leg2part1.yRot;
        this.leg2part3.yRot = this.leg2part1.yRot;
        this.leg2part3b.yRot = this.leg2part1.yRot;
        this.leg2part3c.yRot = this.leg2part1.yRot;
        this.leg2part3d.yRot = this.leg2part1.yRot;
        this.leg2part1.xRot = 1.115f + upangle;
        this.leg2part1b.xRot = 1.078f + upangle;
        this.leg2elbow.xRot = this.leg2part1.xRot;
        float dist = 26.0f;
        dist = (float) ((double) dist * Math.cos(this.leg2part1.xRot));
        this.leg2part2b.z = this.leg2part2c.z = (float) ((double) this.leg2part1.z - Math.cos(this.leg2part1.yRot) * (double) dist);
        this.leg2part2.z = this.leg2part2c.z;
        this.leg2part2b.x = this.leg2part2c.x = (float) ((double) this.leg2part1.x - Math.sin(this.leg2part1.yRot) * (double) dist);
        this.leg2part2.x = this.leg2part2c.x;
        this.leg2part2.xRot = 1.871f - upangle;
        this.leg2part2b.xRot = 1.817f - upangle;
        this.leg2part2c.xRot = 1.762f - upangle;
        dist = 32.0f;
        dist = (float) Math.abs((double) dist * Math.cos(this.leg2part2.xRot));
        this.leg2part3c.z = this.leg2part3d.z = (float) ((double) this.leg2part2.z - Math.cos(this.leg2part2.yRot) * (double) dist);
        this.leg2part3b.z = this.leg2part3d.z;
        this.leg2part3.z = this.leg2part3d.z;
        this.leg2part3c.x = this.leg2part3d.x = (float) ((double) this.leg2part2.x - Math.sin(this.leg2part2.yRot) * (double) dist);
        this.leg2part3b.x = this.leg2part3d.x;
        this.leg2part3.x = this.leg2part3d.x;
        this.leg2part3.xRot = 1.08f + upangle;
        this.leg2part3b.xRot = 1.08f + upangle;
        this.leg2part3c.xRot = 1.08f + upangle;
        this.leg2part3d.xRot = 1.08f + upangle;
    }

    private void doRightRearLeg(float angle, float upangle) {
        this.leg4part1b.yRot = this.leg4part1.yRot = -1.2f + angle;
        this.leg4elbow.yRot = this.leg4part1.yRot;
        this.leg4part2.yRot = this.leg4part1.yRot;
        this.leg4part2b.yRot = this.leg4part1.yRot;
        this.leg4part2c.yRot = this.leg4part1.yRot;
        this.leg4part3.yRot = this.leg4part1.yRot;
        this.leg4part3b.yRot = this.leg4part1.yRot;
        this.leg4part3c.yRot = this.leg4part1.yRot;
        this.leg4part3d.yRot = this.leg4part1.yRot;
        this.leg4part1.xRot = -1.115f + upangle;
        this.leg4part1b.xRot = -1.078f + upangle;
        this.leg4elbow.xRot = this.leg4part1.xRot;
        float dist = 26.0f;
        dist = (float) ((double) dist * Math.cos(this.leg4part1.xRot));
        this.leg4part2b.z = this.leg4part2c.z = (float) ((double) this.leg4part1.z + Math.cos(this.leg4part1.yRot) * (double) dist);
        this.leg4part2.z = this.leg4part2c.z;
        this.leg4part2b.x = this.leg4part2c.x = (float) ((double) this.leg4part1.x + Math.sin(this.leg4part1.yRot) * (double) dist);
        this.leg4part2.x = this.leg4part2c.x;
        this.leg4part2.xRot = -1.871f - upangle;
        this.leg4part2b.xRot = -1.817f - upangle;
        this.leg4part2c.xRot = -1.762f - upangle;
        dist = 32.0f;
        dist = (float) Math.abs((double) dist * Math.cos(this.leg4part2.xRot));
        this.leg4part3c.z = this.leg4part3d.z = (float) ((double) this.leg4part2.z + Math.cos(this.leg4part2.yRot) * (double) dist);
        this.leg4part3b.z = this.leg4part3d.z;
        this.leg4part3.z = this.leg4part3d.z;
        this.leg4part3c.x = this.leg4part3d.x = (float) ((double) this.leg4part2.x + Math.sin(this.leg4part2.yRot) * (double) dist);
        this.leg4part3b.x = this.leg4part3d.x;
        this.leg4part3.x = this.leg4part3d.x;
        this.leg4part3.xRot = -1.08f + upangle;
        this.leg4part3b.xRot = -1.08f + upangle;
        this.leg4part3c.xRot = -1.08f + upangle;
        this.leg4part3d.xRot = -1.08f + upangle;
    }

    private void doLeftRearLeg(float angle, float upangle) {
        this.leg3part1b.yRot = this.leg3part1.yRot = 1.2f + angle;
        this.leg3elbow.yRot = this.leg3part1.yRot;
        this.leg3part2.yRot = this.leg3part1.yRot;
        this.leg3part2b.yRot = this.leg3part1.yRot;
        this.leg3part2c.yRot = this.leg3part1.yRot;
        this.leg3part3.yRot = this.leg3part1.yRot;
        this.leg3part3b.yRot = this.leg3part1.yRot;
        this.leg3part3c.yRot = this.leg3part1.yRot;
        this.leg3part3d.yRot = this.leg3part1.yRot;
        this.leg3part1.xRot = -1.115f + upangle;
        this.leg3part1b.xRot = -1.078f + upangle;
        this.leg3elbow.xRot = this.leg3part1.xRot;
        float dist = 26.0f;
        dist = (float) ((double) dist * Math.cos(this.leg3part1.xRot));
        this.leg3part2b.z = this.leg3part2c.z = (float) ((double) this.leg3part1.z + Math.cos(this.leg3part1.yRot) * (double) dist);
        this.leg3part2.z = this.leg3part2c.z;
        this.leg3part2b.x = this.leg3part2c.x = (float) ((double) this.leg3part1.x + Math.sin(this.leg3part1.yRot) * (double) dist);
        this.leg3part2.x = this.leg3part2c.x;
        this.leg3part2.xRot = -1.871f - upangle;
        this.leg3part2b.xRot = -1.817f - upangle;
        this.leg3part2c.xRot = -1.762f - upangle;
        dist = 32.0f;
        dist = (float) Math.abs((double) dist * Math.cos(this.leg3part2.xRot));
        this.leg3part3c.z = this.leg3part3d.z = (float) ((double) this.leg3part2.z + Math.cos(this.leg3part2.yRot) * (double) dist);
        this.leg3part3b.z = this.leg3part3d.z;
        this.leg3part3.z = this.leg3part3d.z;
        this.leg3part3c.x = this.leg3part3d.x = (float) ((double) this.leg3part2.x + Math.sin(this.leg3part2.yRot) * (double) dist);
        this.leg3part3b.x = this.leg3part3d.x;
        this.leg3part3.x = this.leg3part3d.x;
        this.leg3part3.xRot = -1.08f + upangle;
        this.leg3part3b.xRot = -1.08f + upangle;
        this.leg3part3c.xRot = -1.08f + upangle;
        this.leg3part3d.xRot = -1.08f + upangle;
    }
}
