package com.astryxion.chaospersists.model;

import com.astryxion.chaospersists.entity.PitchBlack;
import com.astryxion.chaospersists.render.RenderInfo;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

public class ModelPitchBlack extends EntityModel<PitchBlack> {
    private final float wingspeed;
    private final ModelPart lclaw1;
    private final ModelPart body;
    private final ModelPart leftleg1;
    private final ModelPart tail1;
    private final ModelPart leftleg2;
    private final ModelPart body2;
    private final ModelPart leftleg3;
    private final ModelPart tail2;
    private final ModelPart tail3;
    private final ModelPart lclaw2;
    private final ModelPart lclaw3;
    private final ModelPart lclaw4;
    private final ModelPart lclaw5;
    private final ModelPart lclaw6;
    private final ModelPart lclaw7;
    private final ModelPart tail4;
    private final ModelPart tail5;
    private final ModelPart tail6;
    private final ModelPart tail7;
    private final ModelPart tail8;
    private final ModelPart tail9;
    private final ModelPart tailpoint1;
    private final ModelPart tailpoint2;
    private final ModelPart llegspike;
    private final ModelPart tailspike1;
    private final ModelPart tailspike2;
    private final ModelPart tailspike3;
    private final ModelPart tailspike4;
    private final ModelPart tailspike5;
    private final ModelPart tailspike6;
    private final ModelPart neck1;
    private final ModelPart neck2;
    private final ModelPart neck3;
    private final ModelPart head1;
    private final ModelPart leye;
    private final ModelPart reye;
    private final ModelPart head2;
    private final ModelPart head3;
    private final ModelPart head4;
    private final ModelPart head5;
    private final ModelPart head6;
    private final ModelPart jaw1;
    private final ModelPart jaw2;
    private final ModelPart jaw3;
    private final ModelPart jaw4;
    private final ModelPart tooth1;
    private final ModelPart tooth2;
    private final ModelPart tooth3;
    private final ModelPart tooth4;
    private final ModelPart tooth5;
    private final ModelPart jaw5;
    private final ModelPart head7;
    private final ModelPart tooth6;
    private final ModelPart tooth7;
    private final ModelPart tooth8;
    private final ModelPart tooth9;
    private final ModelPart tooth10;
    private final ModelPart tooth11;
    private final ModelPart tooth12;
    private final ModelPart tooth13;
    private final ModelPart rightleg1;
    private final ModelPart rightleg2;
    private final ModelPart tooth14;
    private final ModelPart tooth15;
    private final ModelPart tooth16;
    private final ModelPart tooth17;
    private final ModelPart tooth18;
    private final ModelPart tooth19;
    private final ModelPart tooth20;
    private final ModelPart tooth21;
    private final ModelPart tooth22;
    private final ModelPart tooth23;
    private final ModelPart rightleg3;
    private final ModelPart llegspike2;
    private final ModelPart rclaw2;
    private final ModelPart rclaw4;
    private final ModelPart rclaw1;
    private final ModelPart rclaw5;
    private final ModelPart rclaw7;
    private final ModelPart rclaw3;
    private final ModelPart rclaw6;
    private final ModelPart wing1;
    private final ModelPart wing2;
    private final ModelPart wing3;
    private final ModelPart mem1;
    private final ModelPart mem2;
    private final ModelPart mem3;
    private final ModelPart wingclaw1;
    private final ModelPart wingclaw2;
    private final ModelPart wingclaw3;
    private final ModelPart lshoulder;
    private final ModelPart rshoulder;
    private final ModelPart rwing1;
    private final ModelPart rmem1;
    private final ModelPart rwing2;
    private final ModelPart rmem2;
    private final ModelPart rwing3;
    private final ModelPart rmem3;
    private final ModelPart rwingclaw1;
    private final ModelPart rwingclaw2;
    private final ModelPart rwingclaw3;

    public ModelPitchBlack(float f1) {
        this(f1, LayerDefinition.create(createMesh(), 512, 256).bakeRoot());
    }

    public ModelPitchBlack(float wingspeed, ModelPart root) {
        this.wingspeed = wingspeed;
        this.lclaw1 = root.getChild("lclaw1");
        this.body = root.getChild("body");
        this.leftleg1 = root.getChild("leftleg1");
        this.tail1 = root.getChild("tail1");
        this.leftleg2 = root.getChild("leftleg2");
        this.body2 = root.getChild("body2");
        this.leftleg3 = root.getChild("leftleg3");
        this.tail2 = root.getChild("tail2");
        this.tail3 = root.getChild("tail3");
        this.lclaw2 = root.getChild("lclaw2");
        this.lclaw3 = root.getChild("lclaw3");
        this.lclaw4 = root.getChild("lclaw4");
        this.lclaw5 = root.getChild("lclaw5");
        this.lclaw6 = root.getChild("lclaw6");
        this.lclaw7 = root.getChild("lclaw7");
        this.tail4 = root.getChild("tail4");
        this.tail5 = root.getChild("tail5");
        this.tail6 = root.getChild("tail6");
        this.tail7 = root.getChild("tail7");
        this.tail8 = root.getChild("tail8");
        this.tail9 = root.getChild("tail9");
        this.tailpoint1 = root.getChild("tailpoint1");
        this.tailpoint2 = root.getChild("tailpoint2");
        this.llegspike = root.getChild("llegspike");
        this.tailspike1 = root.getChild("tailspike1");
        this.tailspike2 = root.getChild("tailspike2");
        this.tailspike3 = root.getChild("tailspike3");
        this.tailspike4 = root.getChild("tailspike4");
        this.tailspike5 = root.getChild("tailspike5");
        this.tailspike6 = root.getChild("tailspike6");
        this.neck1 = root.getChild("neck1");
        this.neck2 = root.getChild("neck2");
        this.neck3 = root.getChild("neck3");
        this.head1 = root.getChild("head1");
        this.leye = root.getChild("leye");
        this.reye = root.getChild("reye");
        this.head2 = root.getChild("head2");
        this.head3 = root.getChild("head3");
        this.head4 = root.getChild("head4");
        this.head5 = root.getChild("head5");
        this.head6 = root.getChild("head6");
        this.jaw1 = root.getChild("jaw1");
        this.jaw2 = root.getChild("jaw2");
        this.jaw3 = root.getChild("jaw3");
        this.jaw4 = root.getChild("jaw4");
        this.tooth1 = root.getChild("tooth1");
        this.tooth2 = root.getChild("tooth2");
        this.tooth3 = root.getChild("tooth3");
        this.tooth4 = root.getChild("tooth4");
        this.tooth5 = root.getChild("tooth5");
        this.jaw5 = root.getChild("jaw5");
        this.head7 = root.getChild("head7");
        this.tooth6 = root.getChild("tooth6");
        this.tooth7 = root.getChild("tooth7");
        this.tooth8 = root.getChild("tooth8");
        this.tooth9 = root.getChild("tooth9");
        this.tooth10 = root.getChild("tooth10");
        this.tooth11 = root.getChild("tooth11");
        this.tooth12 = root.getChild("tooth12");
        this.tooth13 = root.getChild("tooth13");
        this.rightleg1 = root.getChild("rightleg1");
        this.rightleg2 = root.getChild("rightleg2");
        this.tooth14 = root.getChild("tooth14");
        this.tooth15 = root.getChild("tooth15");
        this.tooth16 = root.getChild("tooth16");
        this.tooth17 = root.getChild("tooth17");
        this.tooth18 = root.getChild("tooth18");
        this.tooth19 = root.getChild("tooth19");
        this.tooth20 = root.getChild("tooth20");
        this.tooth21 = root.getChild("tooth21");
        this.tooth22 = root.getChild("tooth22");
        this.tooth23 = root.getChild("tooth23");
        this.rightleg3 = root.getChild("rightleg3");
        this.llegspike2 = root.getChild("llegspike2");
        this.rclaw2 = root.getChild("rclaw2");
        this.rclaw4 = root.getChild("rclaw4");
        this.rclaw1 = root.getChild("rclaw1");
        this.rclaw5 = root.getChild("rclaw5");
        this.rclaw7 = root.getChild("rclaw7");
        this.rclaw3 = root.getChild("rclaw3");
        this.rclaw6 = root.getChild("rclaw6");
        this.wing1 = root.getChild("wing1");
        this.wing2 = root.getChild("wing2");
        this.wing3 = root.getChild("wing3");
        this.mem1 = root.getChild("mem1");
        this.mem2 = root.getChild("mem2");
        this.mem3 = root.getChild("mem3");
        this.wingclaw1 = root.getChild("wingclaw1");
        this.wingclaw2 = root.getChild("wingclaw2");
        this.wingclaw3 = root.getChild("wingclaw3");
        this.lshoulder = root.getChild("lshoulder");
        this.rshoulder = root.getChild("rshoulder");
        this.rwing1 = root.getChild("rwing1");
        this.rmem1 = root.getChild("rmem1");
        this.rwing2 = root.getChild("rwing2");
        this.rmem2 = root.getChild("rmem2");
        this.rwing3 = root.getChild("rwing3");
        this.rmem3 = root.getChild("rmem3");
        this.rwingclaw1 = root.getChild("rwingclaw1");
        this.rwingclaw2 = root.getChild("rwingclaw2");
        this.rwingclaw3 = root.getChild("rwingclaw3");
    }

    private static MeshDefinition createMesh() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("lclaw1", CubeListBuilder.create().texOffs(300, 111).mirror().addBox(-3.0f, 0.0f, -3.0f, 2, 3, 6), PartPose.offsetAndRotation(7.0f, 21.0f, 11.0f, 0.0f, 0.6632251f, 0.0f));
        root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(400, 26).mirror().addBox(-6.0f, -12.0f, -9.0f, 12, 12, 9), PartPose.offsetAndRotation(0.0f, 0.0f, 9.0f, 0.0698132f, 0.0f, 0.0f));
        root.addOrReplaceChild("leftleg1", CubeListBuilder.create().texOffs(300, 10).mirror().addBox(-1.0f, -5.0f, -20.0f, 5, 10, 10), PartPose.offsetAndRotation(7.0f, 5.0f, 23.0f, -0.5759587f, 0.0f, 0.0f));
        root.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(400, 82).mirror().addBox(-5.0f, -6.0f, 0.0f, 8, 10, 12), PartPose.offsetAndRotation(1.0f, -3.0f, 22.0f, -0.1745329f, 0.0f, 0.0f));
        root.addOrReplaceChild("leftleg2", CubeListBuilder.create().texOffs(300, 31).mirror().addBox(-1.0f, -10.0f, -4.0f, 4, 12, 5), PartPose.offsetAndRotation(7.0f, 5.0f, 23.0f, 0.9773844f, 0.0f, 0.0f));
        root.addOrReplaceChild("body2", CubeListBuilder.create().texOffs(400, 50).mirror().addBox(0.0f, -3.0f, -3.0f, 12, 14, 16), PartPose.offsetAndRotation(-6.0f, -9.0f, 10.0f, -0.1047198f, 0.0f, 0.0f));
        root.addOrReplaceChild("leftleg3", CubeListBuilder.create().texOffs(300, 51).mirror().addBox(-1.0f, -19.0f, 1.0f, 3, 18, 4), PartPose.offsetAndRotation(7.0f, 21.0f, 11.0f, -0.5235988f, 0.0f, 0.0f));
        root.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(400, 106).mirror().addBox(-3.0f, -4.0f, 0.0f, 6, 8, 10), PartPose.offsetAndRotation(0.0f, -2.0f, 33.0f, -0.1396263f, 0.0f, 0.0f));
        root.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(400, 126).mirror().addBox(-2.0f, -2.0f, 0.0f, 4, 5, 10), PartPose.offsetAndRotation(0.0f, -1.0f, 42.0f, -0.1396263f, 0.0f, 0.0f));
        root.addOrReplaceChild("lclaw2", CubeListBuilder.create().texOffs(300, 76).mirror().addBox(-1.0f, -1.0f, -6.0f, 3, 4, 13), PartPose.offset(7.0f, 21.0f, 11.0f));
        root.addOrReplaceChild("lclaw3", CubeListBuilder.create().texOffs(300, 95).mirror().addBox(2.0f, 0.0f, -6.0f, 2, 3, 10), PartPose.offsetAndRotation(7.0f, 21.0f, 11.0f, 0.0f, -0.6632251f, 0.0f));
        root.addOrReplaceChild("lclaw4", CubeListBuilder.create().texOffs(310, 123).mirror().addBox(0.0f, 1.0f, -9.0f, 1, 2, 3), PartPose.offset(7.0f, 21.0f, 11.0f));
        root.addOrReplaceChild("lclaw5", CubeListBuilder.create().texOffs(300, 123).mirror().addBox(-2.5f, 1.0f, -5.0f, 1, 2, 2), PartPose.offsetAndRotation(7.0f, 21.0f, 11.0f, 0.0f, 0.6632251f, 0.0f));
        root.addOrReplaceChild("lclaw6", CubeListBuilder.create().texOffs(322, 123).mirror().addBox(2.5f, 1.0f, -9.0f, 1, 2, 3), PartPose.offsetAndRotation(7.0f, 21.0f, 11.0f, 0.0f, -0.6632251f, 0.0f));
        root.addOrReplaceChild("lclaw7", CubeListBuilder.create().texOffs(333, 123).mirror().addBox(0.0f, 1.0f, 7.0f, 1, 2, 3), PartPose.offset(7.0f, 21.0f, 11.0f));
        root.addOrReplaceChild("tail4", CubeListBuilder.create().texOffs(400, 143).mirror().addBox(-2.0f, -2.0f, 0.0f, 4, 4, 10), PartPose.offsetAndRotation(0.0f, 0.0f, 51.0f, -0.1396263f, 0.0f, 0.0f));
        root.addOrReplaceChild("tail5", CubeListBuilder.create().texOffs(400, 159).mirror().addBox(-1.5f, -2.0f, 0.0f, 3, 3, 10), PartPose.offsetAndRotation(0.0f, 1.0f, 59.0f, -0.1396263f, 0.0f, 0.0f));
        root.addOrReplaceChild("tail6", CubeListBuilder.create().texOffs(400, 180).mirror().addBox(0.0f, 0.0f, 0.0f, 2, 2, 10), PartPose.offsetAndRotation(0.0f, 0.0f, 68.0f, -0.1396263f, 0.1745329f, 0.0f));
        root.addOrReplaceChild("tail7", CubeListBuilder.create().texOffs(400, 180).mirror().addBox(-2.0f, 0.0f, 0.0f, 2, 2, 10), PartPose.offsetAndRotation(0.0f, 0.0f, 68.0f, -0.1396263f, -0.1745329f, 0.0f));
        root.addOrReplaceChild("tail8", CubeListBuilder.create().texOffs(400, 180).mirror().addBox(0.0f, 0.0f, 0.0f, 2, 2, 10), PartPose.offsetAndRotation(-4.0f, 1.0f, 77.0f, -0.1396263f, -0.1745329f, 0.0f));
        root.addOrReplaceChild("tail9", CubeListBuilder.create().texOffs(400, 180).mirror().addBox(0.0f, 0.0f, 0.0f, 2, 2, 10), PartPose.offsetAndRotation(2.0f, 1.0f, 77.0f, -0.1396263f, 0.1745329f, 0.0f));
        root.addOrReplaceChild("tailpoint1", CubeListBuilder.create().texOffs(400, 200).mirror().addBox(-1.0f, -1.0f, 0.0f, 1, 1, 22), PartPose.offsetAndRotation(5.0f, 3.0f, 85.0f, -0.1919862f, 0.1745329f, 0.0f));
        root.addOrReplaceChild("tailpoint2", CubeListBuilder.create().texOffs(400, 200).mirror().addBox(-1.0f, -1.0f, 0.0f, 1, 1, 22), PartPose.offsetAndRotation(-4.0f, 3.0f, 86.0f, -0.1919862f, -0.1745329f, 0.0f));
        root.addOrReplaceChild("llegspike", CubeListBuilder.create().texOffs(300, 131).mirror().addBox(0.0f, -28.0f, 1.0f, 1, 12, 1), PartPose.offsetAndRotation(7.0f, 21.0f, 11.0f, -0.6981317f, 0.0f, 0.0f));
        root.addOrReplaceChild("tailspike1", CubeListBuilder.create().texOffs(400, 230).mirror().addBox(1.0f, -1.0f, 0.0f, 1, 1, 1), PartPose.offsetAndRotation(2.0f, 1.0f, 77.0f, -0.1396263f, 0.1745329f, 0.0f));
        root.addOrReplaceChild("tailspike2", CubeListBuilder.create().texOffs(400, 230).mirror().addBox(1.0f, -1.0f, 6.0f, 1, 1, 1), PartPose.offsetAndRotation(0.0f, 0.0f, 68.0f, -0.1396263f, 0.1745329f, 0.0f));
        root.addOrReplaceChild("tailspike3", CubeListBuilder.create().texOffs(400, 230).mirror().addBox(1.0f, -1.0f, 2.0f, 1, 1, 1), PartPose.offsetAndRotation(0.0f, 0.0f, 68.0f, -0.1396263f, 0.1745329f, 0.0f));
        root.addOrReplaceChild("tailspike4", CubeListBuilder.create().texOffs(400, 230).mirror().addBox(0.0f, -1.0f, 0.0f, 1, 1, 1), PartPose.offsetAndRotation(-4.0f, 1.0f, 77.0f, -0.1396263f, -0.1745329f, 0.0f));
        root.addOrReplaceChild("tailspike5", CubeListBuilder.create().texOffs(400, 230).mirror().addBox(-2.0f, -1.0f, 6.0f, 1, 1, 1), PartPose.offsetAndRotation(0.0f, 0.0f, 68.0f, -0.1396263f, -0.1745329f, 0.0f));
        root.addOrReplaceChild("tailspike6", CubeListBuilder.create().texOffs(400, 230).mirror().addBox(-2.0f, -1.0f, 2.0f, 1, 1, 1), PartPose.offsetAndRotation(0.0f, 0.0f, 68.0f, -0.1396263f, -0.1745329f, 0.0f));
        root.addOrReplaceChild("neck1", CubeListBuilder.create().texOffs(400, 7).mirror().addBox(-4.0f, -4.0f, 0.0f, 8, 8, 8), PartPose.offsetAndRotation(0.0f, -4.0f, -5.0f, 0.0872665f, 0.0f, 0.0f));
        root.addOrReplaceChild("neck2", CubeListBuilder.create().texOffs(375, 10).mirror().addBox(-3.0f, -3.0f, -3.0f, 6, 6, 4), PartPose.offsetAndRotation(0.0f, -4.0f, -5.0f, -0.0523599f, 0.0f, 0.0f));
        root.addOrReplaceChild("neck3", CubeListBuilder.create().texOffs(375, 23).mirror().addBox(-2.0f, -2.0f, -6.0f, 4, 4, 8), PartPose.offsetAndRotation(0.0f, -4.0f, -9.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("head1", CubeListBuilder.create().texOffs(123, 3).mirror().addBox(-18.0f, -1.0f, -12.0f, 36, 1, 12), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("leye", CubeListBuilder.create().texOffs(76, 2).mirror().addBox(18.0f, -1.0f, -13.0f, 3, 3, 15), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("reye", CubeListBuilder.create().texOffs(32, 2).mirror().addBox(-21.0f, -1.0f, -13.0f, 3, 3, 15), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("head2", CubeListBuilder.create().texOffs(140, 18).mirror().addBox(-8.0f, -2.0f, -11.0f, 16, 1, 11), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("head3", CubeListBuilder.create().texOffs(143, 32).mirror().addBox(-2.0f, -4.0f, -14.0f, 4, 4, 16), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("head4", CubeListBuilder.create().texOffs(152, 55).mirror().addBox(-1.0f, -10.0f, -13.0f, 2, 8, 12), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.3665191f, 0.0f, 0.0f));
        root.addOrReplaceChild("head5", CubeListBuilder.create().texOffs(154, 77).mirror().addBox(-0.5f, -18.0f, -11.0f, 1, 9, 9), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.4363323f, 0.0f, 0.0f));
        root.addOrReplaceChild("head6", CubeListBuilder.create().texOffs(160, 97).mirror().addBox(-0.5f, -24.0f, -10.0f, 1, 8, 4), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.6632251f, 0.0f, 0.0f));
        root.addOrReplaceChild("jaw1", CubeListBuilder.create().texOffs(143, 114).mirror().addBox(-2.0f, 1.0f, -14.0f, 4, 4, 15), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.1919862f, 0.0f, 0.0f));
        root.addOrReplaceChild("jaw2", CubeListBuilder.create().texOffs(150, 149).mirror().addBox(-1.0f, 4.0f, -12.0f, 2, 5, 11), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.2617994f, 0.0f, 0.0f));
        root.addOrReplaceChild("jaw3", CubeListBuilder.create().texOffs(154, 168).mirror().addBox(-0.5f, 8.0f, -10.0f, 1, 4, 8), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.3316126f, 0.0f, 0.0f));
        root.addOrReplaceChild("jaw4", CubeListBuilder.create().texOffs(158, 182).mirror().addBox(-0.5f, 11.0f, -7.0f, 1, 4, 4), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.4014257f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth1", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2.0f, 0.0f, -14.0f, 1, 3, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth2", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5f, 0.0f, -14.0f, 1, 2, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth3", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(1.0f, 0.0f, -14.0f, 1, 3, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth4", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2.0f, 0.0f, -12.0f, 1, 3, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth5", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(1.0f, 0.0f, -12.0f, 1, 3, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("jaw5", CubeListBuilder.create().texOffs(151, 135).mirror().addBox(-3.0f, 1.0f, -4.0f, 6, 5, 7), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.1919862f, 0.0f, 0.0f));
        root.addOrReplaceChild("head7", CubeListBuilder.create().texOffs(185, 34).mirror().addBox(-3.0f, -5.0f, -3.0f, 6, 5, 7), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth6", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2.0f, 0.0f, -10.0f, 1, 2, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth7", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(1.0f, 0.0f, -10.0f, 1, 2, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth8", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2.0f, 0.0f, -8.0f, 1, 2, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth9", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(1.0f, 0.0f, -8.0f, 1, 2, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth10", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2.0f, 0.0f, -6.0f, 1, 2, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth11", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(1.0f, 0.0f, -6.0f, 1, 2, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth12", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2.0f, 0.0f, -4.0f, 1, 1, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth13", CubeListBuilder.create().texOffs(-1, 0).mirror().addBox(1.0f, 0.0f, -4.0f, 1, 1, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, -0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightleg1", CubeListBuilder.create().texOffs(250, 10).mirror().addBox(-1.0f, -5.0f, -20.0f, 5, 10, 10), PartPose.offsetAndRotation(-10.0f, 5.0f, 23.0f, -0.5934119f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightleg2", CubeListBuilder.create().texOffs(250, 32).mirror().addBox(0.0f, -10.0f, -4.0f, 4, 12, 5), PartPose.offsetAndRotation(-10.0f, 5.0f, 23.0f, 0.9773844f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth14", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0.5f, -2.0f, -14.0f, 1, 3, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.1919862f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth15", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-1.5f, -2.0f, -14.0f, 1, 3, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.1919862f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth16", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(1.0f, -1.0f, -12.0f, 1, 2, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.1919862f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth17", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2.0f, -1.0f, -12.0f, 1, 2, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.1919862f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth18", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(1.0f, -1.0f, -10.0f, 1, 2, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.1919862f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth19", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2.0f, -1.0f, -10.0f, 1, 2, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.1919862f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth20", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2.0f, -1.0f, -8.0f, 1, 2, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.1919862f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth21", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(1.0f, -1.0f, -8.0f, 1, 2, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.1919862f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth22", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(1.0f, 0.0f, -6.0f, 1, 1, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.1919862f, 0.0f, 0.0f));
        root.addOrReplaceChild("tooth23", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2.0f, 0.0f, -6.0f, 1, 1, 1), PartPose.offsetAndRotation(0.0f, -6.0f, -14.0f, 0.1919862f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightleg3", CubeListBuilder.create().texOffs(250, 52).mirror().addBox(-1.0f, -19.0f, 1.0f, 3, 18, 4), PartPose.offsetAndRotation(-8.0f, 21.0f, 11.0f, -0.5235988f, 0.0f, 0.0f));
        root.addOrReplaceChild("llegspike2", CubeListBuilder.create().texOffs(250, 130).mirror().addBox(0.0f, -28.0f, 1.0f, 1, 12, 1), PartPose.offsetAndRotation(-8.0f, 21.0f, 11.0f, -0.6981317f, 0.0f, 0.0f));
        root.addOrReplaceChild("rclaw2", CubeListBuilder.create().texOffs(250, 76).mirror().addBox(-1.0f, -1.0f, -6.0f, 3, 4, 13), PartPose.offset(-8.0f, 21.0f, 11.0f));
        root.addOrReplaceChild("rclaw4", CubeListBuilder.create().texOffs(250, 123).mirror().addBox(0.0f, 1.0f, -9.0f, 1, 2, 3), PartPose.offset(-8.0f, 21.0f, 11.0f));
        root.addOrReplaceChild("rclaw1", CubeListBuilder.create().texOffs(250, 111).mirror().addBox(2.0f, 0.0f, -4.0f, 2, 3, 6), PartPose.offsetAndRotation(-8.0f, 21.0f, 11.0f, 0.0f, -0.6632251f, 0.0f));
        root.addOrReplaceChild("rclaw5", CubeListBuilder.create().texOffs(261, 123).mirror().addBox(2.5f, 1.0f, -6.0f, 1, 2, 2), PartPose.offsetAndRotation(-8.0f, 21.0f, 11.0f, 0.0f, -0.6632251f, 0.0f));
        root.addOrReplaceChild("rclaw7", CubeListBuilder.create().texOffs(283, 123).mirror().addBox(0.0f, 1.0f, 7.0f, 1, 2, 3), PartPose.offset(-8.0f, 21.0f, 11.0f));
        root.addOrReplaceChild("rclaw3", CubeListBuilder.create().texOffs(250, 95).mirror().addBox(-3.0f, 0.0f, -6.0f, 2, 3, 10), PartPose.offsetAndRotation(-8.0f, 21.0f, 11.0f, 0.0f, 0.6632251f, 0.0f));
        root.addOrReplaceChild("rclaw6", CubeListBuilder.create().texOffs(270, 123).mirror().addBox(-2.5f, 1.0f, -9.0f, 1, 2, 3), PartPose.offsetAndRotation(-8.0f, 21.0f, 11.0f, 0.0f, 0.6632251f, 0.0f));
        root.addOrReplaceChild("wing1", CubeListBuilder.create().texOffs(10, 30).mirror().addBox(-1.0f, -1.0f, -1.0f, 23, 3, 3), PartPose.offsetAndRotation(6.0f, -12.0f, 3.0f, 0.0f, 0.0872665f, -0.1396263f));
        root.addOrReplaceChild("wing2", CubeListBuilder.create().texOffs(10, 40).mirror().addBox(-1.0f, -1.0f, -1.0f, 44, 2, 2), PartPose.offset(27.0f, -15.0f, 1.0f));
        root.addOrReplaceChild("wing3", CubeListBuilder.create().texOffs(10, 50).mirror().addBox(-1.0f, -1.0f, -1.0f, 23, 2, 2), PartPose.offsetAndRotation(70.0f, -15.0f, 1.0f, 0.0f, -0.0872665f, 0.1745329f));
        root.addOrReplaceChild("mem1", CubeListBuilder.create().texOffs(10, 60).mirror().addBox(-2.0f, 0.0f, 0.0f, 24, 1, 21), PartPose.offsetAndRotation(6.0f, -12.0f, 3.0f, 0.0f, 0.0872665f, -0.1396263f));
        root.addOrReplaceChild("mem2", CubeListBuilder.create().texOffs(10, 85).mirror().addBox(0.0f, 0.0f, 0.0f, 43, 1, 21), PartPose.offset(27.0f, -15.0f, 1.0f));
        root.addOrReplaceChild("mem3", CubeListBuilder.create().texOffs(10, 110).mirror().addBox(0.0f, 0.0f, 0.0f, 23, 1, 21), PartPose.offsetAndRotation(70.0f, -15.0f, 1.0f, 0.0f, -0.0872665f, 0.1745329f));
        root.addOrReplaceChild("wingclaw1", CubeListBuilder.create().texOffs(85, 49).mirror().addBox(0.0f, 0.0f, -9.0f, 1, 1, 8), PartPose.offset(70.0f, -15.0f, 1.0f));
        root.addOrReplaceChild("wingclaw2", CubeListBuilder.create().texOffs(67, 50).mirror().addBox(0.0f, 0.0f, -7.0f, 1, 1, 6), PartPose.offsetAndRotation(70.0f, -15.0f, 1.0f, 0.0f, 0.6108652f, 0.0f));
        root.addOrReplaceChild("wingclaw3", CubeListBuilder.create().texOffs(106, 50).mirror().addBox(1.0f, 0.0f, -7.0f, 1, 1, 5), PartPose.offsetAndRotation(69.0f, -15.0f, 1.0f, 0.0f, -0.6108652f, 0.0f));
        root.addOrReplaceChild("lshoulder", CubeListBuilder.create().texOffs(370, 40).mirror().addBox(0.0f, 0.0f, 0.0f, 3, 2, 6), PartPose.offsetAndRotation(3.0f, -13.0f, 1.0f, 0.0698132f, 0.0f, 0.0f));
        root.addOrReplaceChild("rshoulder", CubeListBuilder.create().texOffs(370, 50).mirror().addBox(0.0f, 0.0f, 0.0f, 3, 2, 6), PartPose.offsetAndRotation(-6.0f, -13.0f, 1.0f, 0.0698132f, 0.0f, 0.0f));
        root.addOrReplaceChild("rwing1", CubeListBuilder.create().texOffs(10, 140).mirror().addBox(-22.0f, -1.0f, -1.0f, 23, 3, 3), PartPose.offsetAndRotation(-6.0f, -12.0f, 3.0f, 0.0f, -0.0872665f, 0.1396263f));
        root.addOrReplaceChild("rmem1", CubeListBuilder.create().texOffs(10, 170).mirror().addBox(-22.0f, 0.0f, 0.0f, 24, 1, 21), PartPose.offsetAndRotation(-6.0f, -12.0f, 3.0f, 0.0f, -0.0872665f, 0.1396263f));
        root.addOrReplaceChild("rwing2", CubeListBuilder.create().texOffs(10, 150).mirror().addBox(-43.0f, -1.0f, -1.0f, 44, 2, 2), PartPose.offset(-27.0f, -15.0f, 1.0f));
        root.addOrReplaceChild("rmem2", CubeListBuilder.create().texOffs(10, 195).mirror().addBox(-43.0f, 0.0f, 0.0f, 43, 1, 21), PartPose.offset(-27.0f, -15.0f, 1.0f));
        root.addOrReplaceChild("rwing3", CubeListBuilder.create().texOffs(10, 160).mirror().addBox(-22.0f, -1.0f, -1.0f, 23, 2, 2), PartPose.offsetAndRotation(-70.0f, -15.0f, 1.0f, 0.0f, 0.0872665f, -0.1745329f));
        root.addOrReplaceChild("rmem3", CubeListBuilder.create().texOffs(10, 220).mirror().addBox(-23.0f, 0.0f, 0.0f, 23, 1, 21), PartPose.offsetAndRotation(-70.0f, -15.0f, 1.0f, 0.0f, 0.0872665f, -0.1745329f));
        root.addOrReplaceChild("rwingclaw1", CubeListBuilder.create().texOffs(81, 157).mirror().addBox(0.0f, 0.0f, -9.0f, 1, 1, 8), PartPose.offset(-70.0f, -15.0f, 1.0f));
        root.addOrReplaceChild("rwingclaw2", CubeListBuilder.create().texOffs(64, 160).mirror().addBox(0.0f, 0.0f, -7.0f, 1, 1, 6), PartPose.offsetAndRotation(-70.0f, -15.0f, 1.0f, 0.0f, -0.6108652f, 0.0f));
        root.addOrReplaceChild("rwingclaw3", CubeListBuilder.create().texOffs(103, 159).mirror().addBox(0.0f, 0.0f, -6.0f, 1, 1, 5), PartPose.offsetAndRotation(-70.0f, -15.0f, 1.0f, 0.0f, 0.6108652f, 0.0f));
        return mesh;
    }

    @Override
    public void setupAnim(
            PitchBlack entity,
            float limbSwing,
            float limbSwingAmount,
            float ageInTicks,
            float netHeadYaw,
            float headPitch) {
        float newangle = 0.0f;
        float tailspeed = 0.76f;
        float tailamp = 0.25f;
        float pi4 = 0.7853982f;
        float pscale = entity.getPitchBlackScale();
        RenderInfo r = entity.getRenderInfo();
        newangle = entity.getActivity() != 0 ? Mth.cos((float)(ageInTicks * 0.45f * this.wingspeed / pscale)) * 3.1415927f * 0.24f : - pi4 + Mth.cos((float)(ageInTicks * 0.05f * this.wingspeed / pscale)) * 3.1415927f * 0.02f;
        this.wing1.zRot = newangle;
        this.mem1.zRot = newangle;
        this.wing2.zRot = newangle * 5.0f / 3.0f;
        this.wing2.y = this.wing1.y + (float)Math.sin(this.wing1.zRot) * 21.0f;
        this.wing2.x = this.wing1.x + (float)Math.cos(this.wing1.zRot) * 21.0f;
        this.mem2.zRot = newangle * 5.0f / 3.0f;
        this.mem2.y = this.wing2.y;
        this.mem2.x = this.wing2.x;
        this.wing3.zRot = newangle * 2.0f;
        this.wing3.y = this.wing2.y + (float)Math.sin(this.wing2.zRot) * 43.0f;
        this.wing3.x = this.wing2.x + (float)Math.cos(this.wing2.zRot) * 43.0f;
        this.mem3.zRot = newangle * 2.0f;
        this.mem3.y = this.wing3.y;
        this.mem3.x = this.wing3.x;
        this.wingclaw2.zRot = this.wingclaw3.zRot = newangle * 3.0f / 2.0f;
        this.wingclaw1.zRot = this.wingclaw3.zRot;
        this.wingclaw2.y = this.wingclaw3.y = this.wing3.y;
        this.wingclaw1.y = this.wingclaw3.y;
        this.wingclaw2.x = this.wingclaw3.x = this.wing3.x;
        this.wingclaw1.x = this.wingclaw3.x;
        this.rwing1.zRot = - newangle;
        this.rmem1.zRot = - newangle;
        this.rwing2.zRot = (- newangle) * 5.0f / 3.0f;
        this.rwing2.y = this.rwing1.y - (float)Math.sin(this.rwing1.zRot) * 21.0f;
        this.rwing2.x = this.rwing1.x - (float)Math.cos(this.rwing1.zRot) * 21.0f;
        this.rmem2.zRot = (- newangle) * 5.0f / 3.0f;
        this.rmem2.y = this.rwing2.y;
        this.rmem2.x = this.rwing2.x;
        this.rwing3.zRot = (- newangle) * 2.0f;
        this.rwing3.y = this.rwing2.y - (float)Math.sin(this.rwing2.zRot) * 43.0f;
        this.rwing3.x = this.rwing2.x - (float)Math.cos(this.rwing2.zRot) * 43.0f;
        this.rmem3.zRot = (- newangle) * 2.0f;
        this.rmem3.y = this.rwing3.y;
        this.rmem3.x = this.rwing3.x;
        this.rwingclaw2.zRot = this.rwingclaw3.zRot = (- newangle) * 3.0f / 2.0f;
        this.rwingclaw1.zRot = this.rwingclaw3.zRot;
        this.rwingclaw2.y = this.rwingclaw3.y = this.rwing3.y;
        this.rwingclaw1.y = this.rwingclaw3.y;
        this.rwingclaw2.x = this.rwingclaw3.x = this.rwing3.x;
        this.rwingclaw1.x = this.rwingclaw3.x;
        netHeadYaw %= 360.0f;
        netHeadYaw = entity.getActivity() != 0 ? (netHeadYaw *= 0.2f) : (netHeadYaw *= 0.55f);
        this.neck3.yRot = (float)Math.toRadians(netHeadYaw) * 0.5f;
        this.head3.yRot = this.head4.yRot = (float)Math.toRadians(netHeadYaw);
        this.head2.yRot = this.head4.yRot;
        this.head6.yRot = this.head7.yRot = (this.head1.yRot = this.head4.yRot);
        this.head5.yRot = this.head7.yRot;
        this.jaw4.yRot = this.jaw5.yRot = this.head1.yRot;
        this.jaw3.yRot = this.jaw5.yRot;
        this.jaw2.yRot = this.jaw5.yRot;
        this.jaw1.yRot = this.jaw5.yRot;
        this.tooth4.yRot = this.tooth5.yRot = this.head1.yRot;
        this.tooth3.yRot = this.tooth5.yRot;
        this.tooth2.yRot = this.tooth5.yRot;
        this.tooth1.yRot = this.tooth5.yRot;
        this.tooth9.yRot = this.tooth10.yRot = this.head1.yRot;
        this.tooth8.yRot = this.tooth10.yRot;
        this.tooth7.yRot = this.tooth10.yRot;
        this.tooth6.yRot = this.tooth10.yRot;
        this.tooth14.yRot = this.tooth15.yRot = this.head1.yRot;
        this.tooth13.yRot = this.tooth15.yRot;
        this.tooth12.yRot = this.tooth15.yRot;
        this.tooth11.yRot = this.tooth15.yRot;
        this.tooth19.yRot = this.tooth20.yRot = this.head1.yRot;
        this.tooth18.yRot = this.tooth20.yRot;
        this.tooth17.yRot = this.tooth20.yRot;
        this.tooth16.yRot = this.tooth20.yRot;
        this.tooth22.yRot = this.tooth23.yRot = this.head1.yRot;
        this.tooth21.yRot = this.tooth23.yRot;
        this.reye.yRot = this.leye.yRot = this.head1.yRot;
        if (entity.getAttacking() != 0) {
            newangle = Mth.cos((float)(ageInTicks * 0.85f * this.wingspeed)) * 3.1415927f * 0.16f;
            newangle += 0.5f;
        } else {
            newangle = ageInTicks * 0.7f * this.wingspeed % 6.2831855f;
            if ((newangle = Math.abs(newangle)) < r.rf1) {
                r.ri1 = 0;
                if (entity.level().isClientSide) {
                    if (entity.getRandom().nextInt(20) == 1) {
                        r.ri1 |= 1;
                    }
                }
            }
            r.rf1 = newangle;
            if (r.ri1 != 0) {
                newangle = Mth.sin((float)(ageInTicks * 0.85f * this.wingspeed)) * 3.1415927f * 0.16f;
                newangle += 0.5f;
            } else {
                newangle = pi4 / 4.0f;
            }
        }
        this.jaw4.xRot = this.jaw5.xRot = newangle;
        this.jaw3.xRot = this.jaw5.xRot;
        this.jaw2.xRot = this.jaw5.xRot;
        this.jaw1.xRot = this.jaw5.xRot;
        this.tooth14.xRot = this.tooth15.xRot = newangle;
        this.tooth19.xRot = this.tooth20.xRot = newangle;
        this.tooth18.xRot = this.tooth20.xRot;
        this.tooth17.xRot = this.tooth20.xRot;
        this.tooth16.xRot = this.tooth20.xRot;
        this.tooth22.xRot = this.tooth23.xRot = newangle;
        this.tooth21.xRot = this.tooth23.xRot;
        float clawZ = 7.0f;
        float clawY = 21.0f;
        float clawZamp = 12.0f * pscale;
        float clawYamp = 6.0f * pscale;
        if (entity.getActivity() == 0) {
            float t1 = 0.0f;
            float t2 = 0.0f;
            if ((double)limbSwingAmount > 0.001) {
                newangle = Mth.cos((float)(ageInTicks * 0.75f * this.wingspeed / pscale));
                t1 = Mth.sin((float)(ageInTicks * 0.75f * this.wingspeed / pscale));
            } else {
                newangle = 0.0f;
                t1 = 0.0f;
                t2 = 0.0f;
            }
            if (t1 > 0.0f) {
                t2 = t1 * clawYamp * limbSwingAmount;
                this.lclaw1.y = clawY - t2;
            } else {
                this.lclaw1.y = clawY;
            }
            this.lclaw6.z = this.lclaw7.z = (this.lclaw1.z = clawZ + clawZamp * newangle * limbSwingAmount);
            this.lclaw5.z = this.lclaw7.z;
            this.lclaw4.z = this.lclaw7.z;
            this.lclaw3.z = this.lclaw7.z;
            this.lclaw2.z = this.lclaw7.z;
            this.lclaw6.y = this.lclaw7.y = this.lclaw1.y;
            this.lclaw5.y = this.lclaw7.y;
            this.lclaw4.y = this.lclaw7.y;
            this.lclaw3.y = this.lclaw7.y;
            this.lclaw2.y = this.lclaw7.y;
            this.llegspike.z = this.leftleg3.z = this.lclaw1.z;
            this.llegspike.y = this.leftleg3.y = this.lclaw1.y;
            this.leftleg3.xRot = -0.61f + newangle * 3.1415927f * 0.18f * limbSwingAmount;
            this.llegspike.xRot = -0.785f + newangle * 3.1415927f * 0.18f * limbSwingAmount;
            this.leftleg1.xRot = -0.576f + newangle * 3.1415927f * 0.18f * limbSwingAmount;
            this.leftleg2.xRot = 0.977f + newangle * 3.1415927f * 0.18f * limbSwingAmount;
            this.leftleg1.y = this.leftleg2.y = this.leftleg3.y - (float)Math.cos(this.leftleg3.xRot) * 17.0f + t2 / 2.0f;
            this.leftleg1.z = this.leftleg2.z = this.leftleg3.z - (float)Math.sin(this.leftleg3.xRot) * 17.0f;
            t1 = 0.0f;
            t2 = 0.0f;
            if ((double)limbSwingAmount > 0.001) {
                newangle = Mth.cos((float)(ageInTicks * 0.75f * this.wingspeed / pscale + pi4 * 4.0f));
                t1 = Mth.sin((float)(ageInTicks * 0.75f * this.wingspeed / pscale + pi4 * 4.0f));
            } else {
                newangle = 0.0f;
                t1 = 0.0f;
                t2 = 0.0f;
            }
            if (t1 > 0.0f) {
                t2 = t1 * clawYamp * limbSwingAmount;
                this.rclaw1.y = clawY - t2;
            } else {
                this.rclaw1.y = clawY;
            }
            this.rclaw6.z = this.rclaw7.z = (this.rclaw1.z = clawZ + clawZamp * newangle * limbSwingAmount);
            this.rclaw5.z = this.rclaw7.z;
            this.rclaw4.z = this.rclaw7.z;
            this.rclaw3.z = this.rclaw7.z;
            this.rclaw2.z = this.rclaw7.z;
            this.rclaw6.y = this.rclaw7.y = this.rclaw1.y;
            this.rclaw5.y = this.rclaw7.y;
            this.rclaw4.y = this.rclaw7.y;
            this.rclaw3.y = this.rclaw7.y;
            this.rclaw2.y = this.rclaw7.y;
            this.llegspike2.z = this.rightleg3.z = this.rclaw1.z;
            this.llegspike2.y = this.rightleg3.y = this.rclaw1.y;
            this.rightleg3.xRot = -0.61f + newangle * 3.1415927f * 0.18f * limbSwingAmount;
            this.llegspike2.xRot = -0.785f + newangle * 3.1415927f * 0.18f * limbSwingAmount;
            this.rightleg1.xRot = -0.576f + newangle * 3.1415927f * 0.18f * limbSwingAmount;
            this.rightleg2.xRot = 0.977f + newangle * 3.1415927f * 0.18f * limbSwingAmount;
            this.rightleg1.y = this.rightleg2.y = this.rightleg3.y - (float)Math.cos(this.rightleg3.xRot) * 17.0f + t2 / 2.0f;
            this.rightleg1.z = this.rightleg2.z = this.rightleg3.z - (float)Math.sin(this.rightleg3.xRot) * 17.0f;
            this.lclaw1.xRot = 0.0f;
            this.lclaw7.xRot = 0.0f;
            this.lclaw6.xRot = 0.0f;
            this.lclaw5.xRot = 0.0f;
            this.lclaw4.xRot = 0.0f;
            this.lclaw3.xRot = 0.0f;
            this.lclaw2.xRot = 0.0f;
            this.rclaw1.xRot = 0.0f;
            this.rclaw7.xRot = 0.0f;
            this.rclaw6.xRot = 0.0f;
            this.rclaw5.xRot = 0.0f;
            this.rclaw4.xRot = 0.0f;
            this.rclaw3.xRot = 0.0f;
            this.rclaw2.xRot = 0.0f;
        } else {
            clawZ = 7.0f;
            clawY = 9.0f;
            newangle = entity.getAttacking() != 0 ? Mth.cos((float)(ageInTicks * 0.85f * this.wingspeed / pscale)) * 0.2f : 0.0f;
            this.lclaw1.z = clawZ;
            this.lclaw1.y = clawY + newangle * 30.0f;
            this.lclaw1.xRot = -0.7f + newangle;
            this.lclaw6.z = this.lclaw7.z = this.lclaw1.z;
            this.lclaw5.z = this.lclaw7.z;
            this.lclaw4.z = this.lclaw7.z;
            this.lclaw3.z = this.lclaw7.z;
            this.lclaw2.z = this.lclaw7.z;
            this.lclaw6.y = this.lclaw7.y = this.lclaw1.y;
            this.lclaw5.y = this.lclaw7.y;
            this.lclaw4.y = this.lclaw7.y;
            this.lclaw3.y = this.lclaw7.y;
            this.lclaw2.y = this.lclaw7.y;
            this.lclaw6.xRot = this.lclaw7.xRot = this.lclaw1.xRot;
            this.lclaw5.xRot = this.lclaw7.xRot;
            this.lclaw4.xRot = this.lclaw7.xRot;
            this.lclaw3.xRot = this.lclaw7.xRot;
            this.lclaw2.xRot = this.lclaw7.xRot;
            this.llegspike.z = this.leftleg3.z = this.lclaw1.z;
            this.llegspike.y = this.leftleg3.y = this.lclaw1.y;
            this.leftleg3.xRot = -0.61f + this.lclaw1.xRot;
            this.llegspike.xRot = -0.785f + this.lclaw1.xRot;
            this.leftleg1.xRot = -0.576f - this.lclaw1.xRot / 4.0f;
            this.leftleg2.xRot = 0.977f - this.lclaw1.xRot / 4.0f;
            this.leftleg1.y = this.leftleg2.y = this.leftleg3.y - (float)Math.cos(this.leftleg3.xRot) * 17.0f;
            this.leftleg1.z = this.leftleg2.z = this.leftleg3.z - (float)Math.sin(this.leftleg3.xRot) * 17.0f;
            this.rclaw1.z = clawZ;
            this.rclaw1.y = clawY - newangle * 30.0f;
            this.rclaw1.xRot = -0.7f - newangle;
            this.rclaw6.z = this.rclaw7.z = this.rclaw1.z;
            this.rclaw5.z = this.rclaw7.z;
            this.rclaw4.z = this.rclaw7.z;
            this.rclaw3.z = this.rclaw7.z;
            this.rclaw2.z = this.rclaw7.z;
            this.rclaw6.y = this.rclaw7.y = this.rclaw1.y;
            this.rclaw5.y = this.rclaw7.y;
            this.rclaw4.y = this.rclaw7.y;
            this.rclaw3.y = this.rclaw7.y;
            this.rclaw2.y = this.rclaw7.y;
            this.rclaw6.xRot = this.rclaw7.xRot = this.rclaw1.xRot;
            this.rclaw5.xRot = this.rclaw7.xRot;
            this.rclaw4.xRot = this.rclaw7.xRot;
            this.rclaw3.xRot = this.rclaw7.xRot;
            this.rclaw2.xRot = this.rclaw7.xRot;
            this.llegspike2.z = this.rightleg3.z = this.rclaw1.z;
            this.llegspike2.y = this.rightleg3.y = this.rclaw1.y;
            this.rightleg3.xRot = -0.61f + this.rclaw1.xRot;
            this.llegspike2.xRot = -0.785f + this.rclaw1.xRot;
            this.rightleg1.xRot = -0.576f - this.rclaw1.xRot / 4.0f;
            this.rightleg2.xRot = 0.977f - this.rclaw1.xRot / 4.0f;
            this.rightleg1.y = this.rightleg2.y = this.rightleg3.y - (float)Math.cos(this.rightleg3.xRot) * 17.0f;
            this.rightleg1.z = this.rightleg2.z = this.rightleg3.z - (float)Math.sin(this.rightleg3.xRot) * 17.0f;
        }
        if (entity.getAttacking() != 0) {
            tailspeed = 0.76f / pscale;
            tailamp = 0.25f;
        } else {
            tailspeed = 0.26f / pscale;
            tailamp = 0.08f;
        }
        this.tail1.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed)) * 3.1415927f * tailamp / 2.0f;
        this.tail2.z = this.tail1.z + (float)Math.cos(this.tail1.yRot) * 11.0f;
        this.tail2.x = this.tail1.x - 1.0f + (float)Math.sin(this.tail1.yRot) * 11.0f;
        this.tail2.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed - pi4)) * 3.1415927f * tailamp;
        this.tail3.z = this.tail2.z + (float)Math.cos(this.tail2.yRot) * 9.0f;
        this.tail3.x = this.tail2.x + (float)Math.sin(this.tail2.yRot) * 9.0f;
        this.tail3.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed - 2.0f * pi4)) * 3.1415927f * tailamp;
        this.tail4.z = this.tail3.z + (float)Math.cos(this.tail3.yRot) * 9.0f;
        this.tail4.x = this.tail3.x + (float)Math.sin(this.tail3.yRot) * 9.0f;
        this.tail4.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed - 3.0f * pi4)) * 3.1415927f * tailamp;
        this.tail5.z = this.tail4.z + (float)Math.cos(this.tail4.yRot) * 9.0f;
        this.tail5.x = this.tail4.x + (float)Math.sin(this.tail4.yRot) * 9.0f;
        newangle = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed - 3.0f * pi4)) * 3.1415927f * tailamp;
        this.tail5.yRot = this.tail4.yRot + (newangle /= 2.0f);
        this.tail6.z = this.tail5.z + (float)Math.cos(this.tail5.yRot) * 9.0f;
        this.tail6.x = this.tail5.x + (float)Math.sin(this.tail5.yRot) * 9.0f;
        this.tail6.yRot = 0.174f + this.tail5.yRot + newangle;
        this.tailspike2.z = this.tailspike3.z = this.tail6.z;
        this.tailspike2.x = this.tailspike3.x = this.tail6.x;
        this.tailspike2.yRot = this.tailspike3.yRot = this.tail6.yRot;
        this.tail9.z = this.tail6.z + (float)Math.cos(this.tail6.yRot) * 9.0f;
        this.tail9.x = this.tail6.x + (float)Math.sin(this.tail6.yRot) * 9.0f;
        this.tail9.yRot = this.tail6.yRot + newangle;
        this.tailspike1.z = this.tail9.z;
        this.tailspike1.x = this.tail9.x;
        this.tailspike1.yRot = this.tail9.yRot;
        this.tailpoint1.z = this.tail9.z + (float)Math.cos(this.tail9.yRot) * 9.0f;
        this.tailpoint1.x = this.tail9.x + (float)Math.sin(this.tail9.yRot) * 9.0f;
        this.tailpoint1.yRot = this.tail9.yRot + newangle;
        this.tail7.z = this.tail5.z + (float)Math.cos(this.tail5.yRot) * 9.0f;
        this.tail7.x = this.tail5.x + (float)Math.sin(this.tail5.yRot) * 9.0f;
        this.tail7.yRot = -0.174f + this.tail5.yRot + newangle;
        this.tailspike5.z = this.tailspike6.z = this.tail7.z;
        this.tailspike5.x = this.tailspike6.x = this.tail7.x;
        this.tailspike5.yRot = this.tailspike6.yRot = this.tail7.yRot;
        this.tail8.z = this.tail7.z + (float)Math.cos(this.tail7.yRot) * 9.0f;
        this.tail8.x = this.tail7.x + (float)Math.sin(this.tail7.yRot) * 9.0f;
        this.tail8.yRot = this.tail7.yRot + newangle;
        this.tailspike4.z = this.tail8.z;
        this.tailspike4.x = this.tail8.x;
        this.tailspike4.yRot = this.tail8.yRot;
        this.tailpoint2.z = this.tail8.z + (float)Math.cos(this.tail8.yRot) * 9.0f;
        this.tailpoint2.x = this.tail8.x + (float)Math.sin(this.tail8.yRot) * 9.0f;
        this.tailpoint2.yRot = this.tail8.yRot + newangle;
        entity.setRenderInfo(r);
    }

    @Override
    public void renderToBuffer(
            PoseStack poseStack,
            VertexConsumer buffer,
            int packedLight,
            int packedOverlay,
            float red,
            float green,
            float blue,
            float alpha) {
        this.lclaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftleg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftleg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftleg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail8.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail9.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailpoint1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailpoint2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.llegspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailspike1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailspike2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailspike3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailspike4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailspike5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailspike6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leye.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.reye.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth8.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth9.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth10.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth11.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth12.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth13.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightleg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightleg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth14.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth15.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth16.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth17.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth18.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth19.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth20.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth21.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth22.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth23.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightleg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.llegspike2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mem1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mem2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mem3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wingclaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wingclaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wingclaw3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lshoulder.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rshoulder.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rmem1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rmem2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rmem3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwingclaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwingclaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwingclaw3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    }
}
