package com.astryxion.chaospersists.model;

import com.astryxion.chaospersists.entity.CaterKiller;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

public class ModelCaterKiller extends EntityModel<CaterKiller> {
    private final float wingspeed;
    private CaterKiller animEntity;
    private float animAgeInTicks;
    private float animLimbSwingAmount;
    private final ModelPart Head;
    private final ModelPart falsehead;
    private final ModelPart seg1;
    private final ModelPart ltusk1;
    private final ModelPart ltusk2;
    private final ModelPart rtusk1;
    private final ModelPart rtusk2;
    private final ModelPart ljaw;
    private final ModelPart rjaw;
    private final ModelPart seg1lspike;
    private final ModelPart seg1rspike;
    private final ModelPart seg1ltopspike;
    private final ModelPart seg1rtopspike;
    private final ModelPart seg1lleg;
    private final ModelPart seg1rleg;
    private final ModelPart seg2;
    private final ModelPart seg2lfoot;
    private final ModelPart seg2rfoot;
    private final ModelPart seg2ltopspike;
    private final ModelPart seg2rtopspike;
    private final ModelPart seg2lspike;
    private final ModelPart seg2rspike;
    private final ModelPart seg3;
    private final ModelPart seg3lfoot;
    private final ModelPart seg3rfoot;
    private final ModelPart seg3lspike;
    private final ModelPart seg3rspike;
    private final ModelPart seg3ltopspike;
    private final ModelPart seg3rtopspike;
    private final ModelPart seg3lbackspike;
    private final ModelPart seg3rbackspike;
    public ModelCaterKiller(float f1) {
        this(f1, LayerDefinition.create(createMesh(), 256, 512).bakeRoot());
    }

    public ModelCaterKiller(float wingspeed, ModelPart root) {
        this.wingspeed = wingspeed;
        this.Head = root.getChild("Head");
        this.falsehead = root.getChild("falsehead");
        this.seg1 = root.getChild("seg1");
        this.ltusk1 = root.getChild("ltusk1");
        this.ltusk2 = root.getChild("ltusk2");
        this.rtusk1 = root.getChild("rtusk1");
        this.rtusk2 = root.getChild("rtusk2");
        this.ljaw = root.getChild("ljaw");
        this.rjaw = root.getChild("rjaw");
        this.seg1lspike = root.getChild("seg1lspike");
        this.seg1rspike = root.getChild("seg1rspike");
        this.seg1ltopspike = root.getChild("seg1ltopspike");
        this.seg1rtopspike = root.getChild("seg1rtopspike");
        this.seg1lleg = root.getChild("seg1lleg");
        this.seg1rleg = root.getChild("seg1rleg");
        this.seg2 = root.getChild("seg2");
        this.seg2lfoot = root.getChild("seg2lfoot");
        this.seg2rfoot = root.getChild("seg2rfoot");
        this.seg2ltopspike = root.getChild("seg2ltopspike");
        this.seg2rtopspike = root.getChild("seg2rtopspike");
        this.seg2lspike = root.getChild("seg2lspike");
        this.seg2rspike = root.getChild("seg2rspike");
        this.seg3 = root.getChild("seg3");
        this.seg3lfoot = root.getChild("seg3lfoot");
        this.seg3rfoot = root.getChild("seg3rfoot");
        this.seg3lspike = root.getChild("seg3lspike");
        this.seg3rspike = root.getChild("seg3rspike");
        this.seg3ltopspike = root.getChild("seg3ltopspike");
        this.seg3rtopspike = root.getChild("seg3rtopspike");
        this.seg3lbackspike = root.getChild("seg3lbackspike");
        this.seg3rbackspike = root.getChild("seg3rbackspike");
    }
    public static MeshDefinition createMesh() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();
        partdefinition.addOrReplaceChild("Head", CubeListBuilder.create().texOffs(0, 50).mirror().addBox(-8.0f, -8.0f, -8.0f, 16, 16, 8), PartPose.offsetAndRotation(0.0f, -8.0f, -12.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("falsehead", CubeListBuilder.create().texOffs(0, 100).mirror().addBox(-10.0f, -27.0f, -11.0f, 20, 20, 10), PartPose.offsetAndRotation(0.0f, -8.0f, -12.0f, -0.1570796f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("seg1", CubeListBuilder.create().texOffs(0, 200).mirror().addBox(-14.0f, -31.0f, 0.0f, 28, 32, 14), PartPose.offsetAndRotation(0.0f, -8.0f, -12.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("ltusk1", CubeListBuilder.create().texOffs(0, 140).mirror().addBox(-1.0f, -1.0f, -1.0f, 33, 3, 3), PartPose.offsetAndRotation(9.0f, -25.0f, -19.0f, 0.0f, 0.5585054f, 0.0f));
        partdefinition.addOrReplaceChild("ltusk2", CubeListBuilder.create().texOffs(0, 160).mirror().addBox(0.0f, 0.0f, 0.0f, 20, 1, 1), PartPose.offsetAndRotation(36.0f, -25.0f, -36.0f, 0.0f, 0.8028515f, 0.0f));
        partdefinition.addOrReplaceChild("rtusk1", CubeListBuilder.create().texOffs(0, 150).mirror().addBox(-33.0f, 0.0f, 0.0f, 33, 3, 3), PartPose.offsetAndRotation(-8.0f, -25.0f, -17.0f, 0.0f, -0.5585054f, 0.0f));
        partdefinition.addOrReplaceChild("rtusk2", CubeListBuilder.create().texOffs(0, 170).mirror().addBox(-20.0f, 0.0f, 0.0f, 20, 1, 1), PartPose.offsetAndRotation(-36.0f, -24.0f, -34.0f, 0.0f, -0.8028515f, 0.0f));
        partdefinition.addOrReplaceChild("ljaw", CubeListBuilder.create().texOffs(100, 50).mirror().addBox(0.0f, 0.0f, 0.0f, 1, 7, 4), PartPose.offsetAndRotation(4.0f, -1.0f, -18.0f, 0.0f, 0.0f, 0.1396263f));
        partdefinition.addOrReplaceChild("rjaw", CubeListBuilder.create().texOffs(125, 50).mirror().addBox(0.0f, 0.0f, 0.0f, 1, 7, 4), PartPose.offsetAndRotation(-5.0f, -1.0f, -18.0f, 0.0f, 0.0f, -0.1396263f));
        partdefinition.addOrReplaceChild("seg1lspike", CubeListBuilder.create().texOffs(0, 260).mirror().addBox(-1.0f, -1.0f, -1.0f, 33, 2, 2), PartPose.offsetAndRotation(14.0f, -32.0f, -6.0f, 0.0f, 0.3316126f, -0.122173f));
        partdefinition.addOrReplaceChild("seg1rspike", CubeListBuilder.create().texOffs(0, 270).mirror().addBox(-33.0f, -1.0f, -1.0f, 33, 2, 2), PartPose.offsetAndRotation(-13.0f, -32.0f, -6.0f, 0.0f, -0.3316126f, 0.122173f));
        partdefinition.addOrReplaceChild("seg1ltopspike", CubeListBuilder.create().texOffs(125, 260).mirror().addBox(-2.0f, -8.0f, -2.0f, 4, 9, 4), PartPose.offsetAndRotation(8.0f, -39.0f, -6.0f, 0.0f, 0.0f, 0.1396263f));
        partdefinition.addOrReplaceChild("seg1rtopspike", CubeListBuilder.create().texOffs(150, 260).mirror().addBox(-2.0f, -8.0f, -2.0f, 4, 9, 4), PartPose.offsetAndRotation(-10.0f, -39.0f, -6.0f, 0.0f, 0.0f, -0.1396263f));
        partdefinition.addOrReplaceChild("seg1lleg", CubeListBuilder.create().texOffs(125, 200).mirror().addBox(-1.0f, 0.0f, -1.0f, 2, 16, 2), PartPose.offsetAndRotation(8.0f, -8.0f, -5.0f, 0.0f, 0.0f, 0.1570796f));
        partdefinition.addOrReplaceChild("seg1rleg", CubeListBuilder.create().texOffs(150, 200).mirror().addBox(0.0f, 0.0f, 0.0f, 2, 16, 2), PartPose.offsetAndRotation(-9.0f, -8.0f, -5.0f, 0.0f, 0.0f, -0.1570796f));
        partdefinition.addOrReplaceChild("seg2", CubeListBuilder.create().texOffs(0, 300).mirror().addBox(-20.0f, -17.0f, -9.0f, 40, 34, 18), PartPose.offsetAndRotation(0.0f, -2.0f, 32.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("seg2lfoot", CubeListBuilder.create().texOffs(125, 300).mirror().addBox(-5.0f, 0.0f, -5.0f, 10, 10, 10), PartPose.offsetAndRotation(13.0f, 14.0f, 32.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("seg2rfoot", CubeListBuilder.create().texOffs(175, 300).mirror().addBox(-5.0f, 0.0f, -5.0f, 10, 10, 10), PartPose.offsetAndRotation(-13.0f, 14.0f, 32.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("seg2ltopspike", CubeListBuilder.create().texOffs(100, 360).mirror().addBox(-2.0f, -9.0f, -2.0f, 4, 9, 4), PartPose.offsetAndRotation(14.0f, -18.0f, 32.0f, 0.0f, 0.0f, 0.1396263f));
        partdefinition.addOrReplaceChild("seg2rtopspike", CubeListBuilder.create().texOffs(125, 360).mirror().addBox(-2.0f, -9.0f, -2.0f, 4, 9, 4), PartPose.offsetAndRotation(-14.0f, -18.0f, 32.0f, 0.0f, 0.0f, -0.1396263f));
        partdefinition.addOrReplaceChild("seg2lspike", CubeListBuilder.create().texOffs(0, 360).mirror().addBox(0.0f, -1.0f, -1.0f, 20, 2, 2), PartPose.offsetAndRotation(18.0f, -9.0f, 32.0f, 0.0f, 0.0f, -0.0698132f));
        partdefinition.addOrReplaceChild("seg2rspike", CubeListBuilder.create().texOffs(0, 370).mirror().addBox(-20.0f, -1.0f, -1.0f, 20, 2, 2), PartPose.offsetAndRotation(-18.0f, -9.0f, 32.0f, 0.0f, 0.0f, 0.0698132f));
        partdefinition.addOrReplaceChild("seg3", CubeListBuilder.create().texOffs(0, 400).mirror().addBox(-15.0f, -14.0f, -7.0f, 30, 28, 14), PartPose.offsetAndRotation(0.0f, 3.0f, 48.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("seg3lfoot", CubeListBuilder.create().texOffs(100, 400).mirror().addBox(-4.0f, 0.0f, -6.0f, 8, 8, 12), PartPose.offsetAndRotation(10.0f, 16.0f, 48.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("seg3rfoot", CubeListBuilder.create().texOffs(150, 400).mirror().addBox(-4.0f, 0.0f, -6.0f, 8, 8, 12), PartPose.offsetAndRotation(-10.0f, 16.0f, 48.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("seg3lspike", CubeListBuilder.create().texOffs(0, 450).mirror().addBox(0.0f, -1.0f, -1.0f, 14, 2, 2), PartPose.offsetAndRotation(14.0f, -4.0f, 48.0f, 0.0f, 0.0f, -0.0698132f));
        partdefinition.addOrReplaceChild("seg3rspike", CubeListBuilder.create().texOffs(0, 460).mirror().addBox(-14.0f, -1.0f, -1.0f, 14, 2, 2), PartPose.offsetAndRotation(-14.0f, -4.0f, 48.0f, 0.0f, 0.0f, 0.0698132f));
        partdefinition.addOrReplaceChild("seg3ltopspike", CubeListBuilder.create().texOffs(100, 450).mirror().addBox(-2.0f, -13.0f, -2.0f, 3, 13, 3), PartPose.offsetAndRotation(10.0f, -10.0f, 48.0f, 0.0f, 0.0f, 0.1396263f));
        partdefinition.addOrReplaceChild("seg3rtopspike", CubeListBuilder.create().texOffs(120, 450).mirror().addBox(-2.0f, -13.0f, -2.0f, 3, 13, 3), PartPose.offsetAndRotation(-10.0f, -10.0f, 48.0f, 0.0f, 0.0f, -0.1396263f));
        partdefinition.addOrReplaceChild("seg3lbackspike", CubeListBuilder.create().texOffs(50, 450).mirror().addBox(-2.0f, -20.0f, -2.0f, 4, 20, 4), PartPose.offsetAndRotation(13.0f, -8.0f, 54.0f, -0.9773844f, 0.2792527f, 0.1396263f));
        partdefinition.addOrReplaceChild("seg3rbackspike", CubeListBuilder.create().texOffs(75, 450).mirror().addBox(-2.0f, -20.0f, -2.0f, 4, 20, 4), PartPose.offsetAndRotation(-13.0f, -8.0f, 54.0f, -0.9773844f, -0.3490659f, 0.1396263f));
        return meshdefinition;
    }
    @Override
    public void setupAnim(CaterKiller entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.animEntity = entity;
        this.animAgeInTicks = ageInTicks;
        this.animLimbSwingAmount = limbSwingAmount;
    }

    @Override
    public void renderToBuffer(PoseStack poseStack, VertexConsumer buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        CaterKiller entity = this.animEntity;
        float ageInTicks = this.animAgeInTicks;
        float limbSwingAmount = this.animLimbSwingAmount;
        int i;
        float newangle = 0.0f;
        float headoff = 0.0f;
        float zpi = 0.0f;
        float zdist = 0.0f;
        newangle = entity.getAttacking() != 0 ? Mth.cos((float)(ageInTicks * 1.7f * this.wingspeed)) * 3.1415927f * 0.07f : Mth.cos((float)(ageInTicks * 1.3f * this.wingspeed)) * 3.1415927f * 0.025f;
        this.ljaw.zRot = 0.139f + newangle;
        this.rjaw.zRot = -0.139f - newangle;
        headoff = entity.getAttacking() != 0 ? Mth.cos((float)(ageInTicks * 1.7f * this.wingspeed)) * 8.0f : Mth.cos((float)(ageInTicks * 0.3f * this.wingspeed)) * 2.0f;
        this.Head.y = -8.0f + headoff;
        this.falsehead.y = -8.0f + headoff;
        this.ltusk1.y = -25.0f + headoff;
        this.ltusk2.y = -25.0f + headoff;
        this.rtusk1.y = -25.0f + headoff;
        this.rtusk2.y = -25.0f + headoff;
        this.ljaw.y = -1.0f + headoff;
        this.rjaw.y = -1.0f + headoff;
        newangle = Mth.cos((float)(ageInTicks * 2.11f * this.wingspeed)) * 3.1415927f * 0.08f;
        this.ltusk2.yRot = 0.802f + newangle;
        newangle = Mth.cos((float)(ageInTicks * 2.3f * this.wingspeed)) * 3.1415927f * 0.08f;
        this.rtusk2.yRot = -0.802f + newangle;
        this.Head.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.falsehead.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.ltusk1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.ltusk2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rtusk1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rtusk2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.ljaw.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rjaw.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        for (i = 0; i < 3; ++i) {
            this.seg1.y = -8.0f + headoff / (float)(i + 1) + (float)(8 * i);
            this.seg1lspike.y = -32.0f + headoff / (float)(i + 1) + (float)(8 * i);
            this.seg1rspike.y = -32.0f + headoff / (float)(i + 1) + (float)(8 * i);
            this.seg1ltopspike.y = -39.0f + headoff / (float)(i + 1) + (float)(8 * i);
            this.seg1rtopspike.y = -39.0f + headoff / (float)(i + 1) + (float)(8 * i);
            this.seg1lleg.y = -8.0f + headoff / (float)(i + 1) + (float)(8 * i);
            this.seg1rleg.y = -8.0f + headoff / (float)(i + 1) + (float)(8 * i);
            this.seg1.z = -12 + 14 * i;
            this.seg1lspike.z = -6 + 14 * i;
            this.seg1rspike.z = -6 + 14 * i;
            this.seg1ltopspike.z = -6 + 14 * i;
            this.seg1rtopspike.z = -6 + 14 * i;
            this.seg1lleg.z = -5 + 14 * i;
            this.seg1rleg.z = -5 + 14 * i;
            this.seg1lspike.zRot = newangle = Mth.cos((float)((float)((double)(ageInTicks * 0.91f * this.wingspeed) + 0.39269908169872414 * (double)i))) * 3.1415927f * 0.08f;
            this.seg1rspike.zRot = - newangle;
            newangle = entity.getAttacking() != 0 ? Mth.cos((float)((float)((double)(ageInTicks * 2.91f * this.wingspeed) + 0.39269908169872414 * (double)i))) * 3.1415927f * 0.15f : Mth.cos((float)((float)((double)(ageInTicks * 0.35f * this.wingspeed) + 0.39269908169872414 * (double)i))) * 3.1415927f * 0.04f;
            this.seg1lleg.xRot = newangle;
            this.seg1rleg.xRot = - newangle;
            this.seg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
            this.seg1lspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
            this.seg1rspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
            this.seg1ltopspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
            this.seg1rtopspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
            this.seg1lleg.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
            this.seg1rleg.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        }
        for (i = 0; i < 6; ++i) {
            zdist = Mth.cos((float)(ageInTicks * 1.7f * this.wingspeed + zpi)) * 1.5f * limbSwingAmount;
            this.seg2.z = 39.0f + (16.0f + zdist) * (float)i;
            this.seg2lfoot.z = 39.0f + (16.0f + zdist) * (float)i;
            this.seg2rfoot.z = 39.0f + (16.0f + zdist) * (float)i;
            this.seg2ltopspike.z = 39.0f + (16.0f + zdist) * (float)i;
            this.seg2rtopspike.z = 39.0f + (16.0f + zdist) * (float)i;
            this.seg2lspike.z = 39.0f + (16.0f + zdist) * (float)i;
            this.seg2rspike.z = 39.0f + (16.0f + zdist) * (float)i;
            this.seg2lspike.zRot = newangle = Mth.cos((float)((float)((double)(ageInTicks * 0.4f * this.wingspeed) - 0.39269908169872414 * (double)i))) * 3.1415927f * 0.07f;
            this.seg2rspike.zRot = - newangle;
            this.seg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
            this.seg2lfoot.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
            this.seg2rfoot.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
            this.seg2ltopspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
            this.seg2rtopspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
            this.seg2lspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
            this.seg2rspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
            zpi += 0.7853982f;
        }
        this.seg3lfoot.z = this.seg3.z = this.seg2rspike.z + 16.0f;
        this.seg3rfoot.z = this.seg3.z;
        this.seg3lspike.z = this.seg3.z;
        this.seg3rspike.z = this.seg3.z;
        this.seg3ltopspike.z = this.seg3.z;
        this.seg3rtopspike.z = this.seg3.z;
        this.seg3lbackspike.z = this.seg3.z + 6.0f;
        this.seg3rbackspike.z = this.seg3.z + 6.0f;
        i = 6;
        this.seg3lspike.zRot = newangle = Mth.cos((float)((float)((double)(ageInTicks * 0.4f * this.wingspeed) - 0.39269908169872414 * (double)i))) * 3.1415927f * 0.07f;
        this.seg3rspike.zRot = - newangle;
        newangle = Mth.cos((float)(ageInTicks * 0.81f * this.wingspeed)) * 3.1415927f * 0.04f;
        this.seg3lbackspike.xRot = -0.977f + newangle;
        newangle = Mth.cos((float)(ageInTicks * 0.87f * this.wingspeed)) * 3.1415927f * 0.04f;
        this.seg3rbackspike.xRot = -0.977f + newangle;
        newangle = Mth.cos((float)(ageInTicks * 1.11f * this.wingspeed)) * 3.1415927f * 0.04f;
        this.seg3lbackspike.yRot = 0.28f + newangle;
        newangle = Mth.cos((float)(ageInTicks * 1.3f * this.wingspeed)) * 3.1415927f * 0.04f;
        this.seg3rbackspike.yRot = -0.28f + newangle;
        this.seg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.seg3lfoot.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.seg3rfoot.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.seg3lspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.seg3rspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.seg3ltopspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.seg3rtopspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.seg3lbackspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.seg3rbackspike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    }
}
