package com.astryxion.chaospersists.model;

import com.astryxion.chaospersists.entity.Hydrolisc;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

public class ModelHydrolisc extends EntityModel<Hydrolisc> {
    private final float wingspeed;
    private final ModelPart tail2;
    private final ModelPart tail3;
    private final ModelPart body2;
    private final ModelPart lb2;
    private final ModelPart lb1;
    private final ModelPart spine3;
    private final ModelPart spine4;
    private final ModelPart rb1;
    private final ModelPart rb2;
    private final ModelPart spine1;
    private final ModelPart spine2;
    private final ModelPart lb3;
    private final ModelPart rb3;
    private final ModelPart body1;
    private final ModelPart body0;
    private final ModelPart lf1;
    private final ModelPart rf1;
    private final ModelPart rb6;
    private final ModelPart rb4;
    private final ModelPart rb5;
    private final ModelPart lb6;
    private final ModelPart lb5;
    private final ModelPart lb4;
    private final ModelPart head3;
    private final ModelPart feather3;
    private final ModelPart feather1;
    private final ModelPart feather2;
    private final ModelPart head1;
    private final ModelPart rf2;
    private final ModelPart rf3;
    private final ModelPart rf4;
    private final ModelPart rf5;
    private final ModelPart rf6;
    private final ModelPart lf2;
    private final ModelPart lf3;
    private final ModelPart lf4;
    private final ModelPart lf5;
    private final ModelPart lf6;
    private final ModelPart head2;
    private final ModelPart tail1;

    public ModelHydrolisc(float f1) {
        this(LayerDefinition.create(createMesh(), 64, 128).bakeRoot(), f1);
    }

    public ModelHydrolisc(ModelPart root, float wingspeed) {
        this.wingspeed = wingspeed;
        this.tail2 = root.getChild("tail2");
        this.tail3 = root.getChild("tail3");
        this.body2 = root.getChild("body2");
        this.lb2 = root.getChild("lb2");
        this.lb1 = root.getChild("lb1");
        this.spine3 = root.getChild("spine3");
        this.spine4 = root.getChild("spine4");
        this.rb1 = root.getChild("rb1");
        this.rb2 = root.getChild("rb2");
        this.spine1 = root.getChild("spine1");
        this.spine2 = root.getChild("spine2");
        this.lb3 = root.getChild("lb3");
        this.rb3 = root.getChild("rb3");
        this.body1 = root.getChild("body1");
        this.body0 = root.getChild("body0");
        this.lf1 = root.getChild("lf1");
        this.rf1 = root.getChild("rf1");
        this.rb6 = root.getChild("rb6");
        this.rb4 = root.getChild("rb4");
        this.rb5 = root.getChild("rb5");
        this.lb6 = root.getChild("lb6");
        this.lb5 = root.getChild("lb5");
        this.lb4 = root.getChild("lb4");
        this.head3 = root.getChild("head3");
        this.feather3 = root.getChild("feather3");
        this.feather1 = root.getChild("feather1");
        this.feather2 = root.getChild("feather2");
        this.head1 = root.getChild("head1");
        this.rf2 = root.getChild("rf2");
        this.rf3 = root.getChild("rf3");
        this.rf4 = root.getChild("rf4");
        this.rf5 = root.getChild("rf5");
        this.rf6 = root.getChild("rf6");
        this.lf2 = root.getChild("lf2");
        this.lf3 = root.getChild("lf3");
        this.lf4 = root.getChild("lf4");
        this.lf5 = root.getChild("lf5");
        this.lf6 = root.getChild("lf6");
        this.head2 = root.getChild("head2");
        this.tail1 = root.getChild("tail1");
    }

    public static MeshDefinition createMesh() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();
        partdefinition.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(29, 3).addBox(-1.0f, 0.0f, -0.8f, 2, 8, 2), PartPose.offsetAndRotation(1.0f, 20.0f, 13.53333f, 1.392442f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(39, 0).addBox(-1.0f, -1.0f, -2.0f, 2, 8, 2), PartPose.offsetAndRotation(1.0f, 20.0f, 21.0f, 1.72705f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("body2", CubeListBuilder.create().texOffs(0, 99).addBox(-2.0f, 14.0f, 0.0f, 6, 4, 10), PartPose.offsetAndRotation(0.0f, 0.0f, 0.0f, -0.0523599f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lb2", CubeListBuilder.create().texOffs(45, 13).addBox(0.0f, 0.0f, 3.0f, 3, 2, 5), PartPose.offsetAndRotation(5.0f, 15.0f, 0.0f, -0.4886922f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lb1", CubeListBuilder.create().texOffs(46, 22).addBox(-1.0f, 0.0f, 0.0f, 4, 3, 3), PartPose.offset(5.0f, 15.0f, 0.0f));
        partdefinition.addOrReplaceChild("spine3", CubeListBuilder.create().texOffs(11, 31).addBox(-1.0f, -5.0f, 0.0f, 2, 6, 2), PartPose.offsetAndRotation(1.0f, 14.0f, 6.0f, -1.117011f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("spine4", CubeListBuilder.create().texOffs(0, 30).addBox(-1.0f, -10.5f, -1.0f, 2, 6, 2), PartPose.offsetAndRotation(1.0f, 14.0f, 6.0f, -1.343904f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rb1", CubeListBuilder.create().texOffs(46, 22).addBox(-4.0f, 0.0f, 0.0f, 4, 3, 3), PartPose.offset(-2.0f, 15.0f, 0.0f));
        partdefinition.addOrReplaceChild("rb2", CubeListBuilder.create().texOffs(45, 13).addBox(-4.0f, 0.0f, 2.0f, 3, 2, 5), PartPose.offsetAndRotation(-2.0f, 15.0f, 0.0f, -0.4886922f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("spine1", CubeListBuilder.create().texOffs(33, 19).addBox(-1.0f, -5.0f, 0.0f, 2, 6, 2), PartPose.offsetAndRotation(1.0f, 14.0f, 0.0f, -0.8552113f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("spine2", CubeListBuilder.create().texOffs(21, 19).addBox(-1.0f, -10.5f, -1.5f, 2, 6, 2), PartPose.offsetAndRotation(1.0f, 14.0f, 0.0f, -1.169371f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lb3", CubeListBuilder.create().texOffs(0, 58).addBox(0.0f, -8.0f, -2.0f, 3, 2, 6), PartPose.offsetAndRotation(5.0f, 15.0f, 0.0f, -2.347623f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rb3", CubeListBuilder.create().texOffs(0, 58).addBox(-4.0f, -8.0f, -2.0f, 3, 2, 6), PartPose.offsetAndRotation(-2.0f, 15.0f, 0.0f, -2.347623f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("body1", CubeListBuilder.create().texOffs(0, 79).addBox(-2.0f, 16.0f, -7.0f, 4, 2, 5), PartPose.offset(1.0f, -1.0f, 2.0f));
        partdefinition.addOrReplaceChild("body0", CubeListBuilder.create().texOffs(0, 0).addBox(-1.0f, 14.0f, -13.0f, 4, 3, 10), PartPose.offsetAndRotation(0.0f, 0.0f, 0.0f, 0.0523599f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lf1", CubeListBuilder.create().texOffs(45, 32).addBox(-1.0f, 0.0f, -2.0f, 4, 3, 3), PartPose.offset(4.0f, 14.0f, -7.0f));
        partdefinition.addOrReplaceChild("rf1", CubeListBuilder.create().texOffs(45, 32).addBox(-3.0f, 0.0f, -2.0f, 4, 3, 3), PartPose.offset(-2.0f, 14.0f, -7.0f));
        partdefinition.addOrReplaceChild("rb6", CubeListBuilder.create().texOffs(30, 39).addBox(-3.5f, 7.0f, 2.0f, 2, 3, 1), PartPose.offsetAndRotation(-2.0f, 15.0f, 0.0f, 0.1745329f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rb4", CubeListBuilder.create().texOffs(20, 39).addBox(-2.0f, 3.0f, 6.0f, 1, 4, 1), PartPose.offsetAndRotation(-2.0f, 15.0f, 0.0f, -0.6283185f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rb5", CubeListBuilder.create().texOffs(20, 39).addBox(-4.0f, 3.0f, 6.0f, 1, 4, 1), PartPose.offsetAndRotation(-2.0f, 15.0f, 0.0f, -0.6283185f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lb6", CubeListBuilder.create().texOffs(30, 39).addBox(0.5f, 7.0f, 2.0f, 2, 3, 1), PartPose.offsetAndRotation(5.0f, 15.0f, 0.0f, 0.1745329f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lb5", CubeListBuilder.create().texOffs(20, 39).addBox(2.0f, 3.0f, 6.0f, 1, 4, 1), PartPose.offsetAndRotation(5.0f, 15.0f, 0.0f, -0.6283185f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lb4", CubeListBuilder.create().texOffs(20, 39).addBox(0.0f, 3.0f, 6.0f, 1, 4, 1), PartPose.offsetAndRotation(5.0f, 15.0f, 0.0f, -0.6283185f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("head3", CubeListBuilder.create().texOffs(38, 50).addBox(0.0f, 0.0f, 0.0f, 4, 2, 8), PartPose.offsetAndRotation(-1.0f, 15.0f, -13.0f, 0.5235988f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("feather3", CubeListBuilder.create().texOffs(25, 117).addBox(0.0f, 0.0f, 1.0f, 1, 2, 9), PartPose.offsetAndRotation(1.0f, 12.0f, -8.0f, 0.3490659f, 0.2617994f, 0.0f));
        partdefinition.addOrReplaceChild("feather1", CubeListBuilder.create().texOffs(34, 100).addBox(0.0f, 0.0f, 1.0f, 1, 2, 9), PartPose.offsetAndRotation(0.0f, 12.0f, -8.0f, 0.3490659f, -0.2617994f, 0.0f));
        partdefinition.addOrReplaceChild("feather2", CubeListBuilder.create().texOffs(0, 116).addBox(0.0f, 0.0f, 0.0f, 1, 2, 10), PartPose.offsetAndRotation(0.5f, 11.0f, -6.0f, 0.3490659f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("head1", CubeListBuilder.create().texOffs(38, 41).addBox(0.0f, 0.0f, 0.0f, 4, 3, 4), PartPose.offsetAndRotation(-1.0f, 15.0f, -15.0f, 0.1396263f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rf2", CubeListBuilder.create().texOffs(19, 58).addBox(-3.0f, 0.0f, 0.0f, 3, 3, 6), PartPose.offsetAndRotation(-2.0f, 14.0f, -7.0f, -0.4886922f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rf3", CubeListBuilder.create().texOffs(19, 47).addBox(-3.0f, -7.0f, 0.0f, 3, 3, 6), PartPose.offsetAndRotation(-2.0f, 14.0f, -7.0f, -2.347623f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rf4", CubeListBuilder.create().texOffs(20, 39).addBox(0.0f, 6.0f, 4.0f, 1, 4, 1), PartPose.offsetAndRotation(-3.0f, 14.0f, -7.0f, -0.6283185f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rf5", CubeListBuilder.create().texOffs(20, 39).addBox(-2.0f, 6.0f, 4.0f, 1, 4, 1), PartPose.offsetAndRotation(-3.0f, 14.0f, -7.0f, -0.6283185f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rf6", CubeListBuilder.create().texOffs(30, 39).addBox(-2.5f, 6.0f, 0.0f, 2, 5, 1), PartPose.offsetAndRotation(-2.0f, 14.0f, -7.0f, 0.1745329f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lf2", CubeListBuilder.create().texOffs(19, 58).addBox(0.0f, 0.0f, 0.0f, 3, 3, 6), PartPose.offsetAndRotation(4.0f, 14.0f, -7.0f, -0.4886922f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lf3", CubeListBuilder.create().texOffs(19, 47).addBox(0.0f, -7.0f, 0.0f, 3, 3, 6), PartPose.offsetAndRotation(4.0f, 14.0f, -7.0f, -2.347623f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lf4", CubeListBuilder.create().texOffs(20, 39).addBox(0.0f, 6.0f, 4.0f, 1, 4, 1), PartPose.offsetAndRotation(4.0f, 14.0f, -7.0f, -0.6283185f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lf5", CubeListBuilder.create().texOffs(20, 39).addBox(2.0f, 6.0f, 4.0f, 1, 4, 1), PartPose.offsetAndRotation(4.0f, 14.0f, -7.0f, -0.6283185f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lf6", CubeListBuilder.create().texOffs(30, 39).addBox(0.5f, 6.0f, -2.0f, 2, 5, 1), PartPose.offsetAndRotation(4.0f, 14.0f, -5.0f, 0.1745329f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("head2", CubeListBuilder.create().texOffs(19, 80).addBox(-1.0f, 16.0f, -16.0f, 4, 1, 5), PartPose.offsetAndRotation(0.0f, 0.0f, 0.0f, 0.1047198f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(9, 18).addBox(-1.0f, -1.0f, -3.0f, 2, 8, 2), PartPose.offsetAndRotation(1.0f, 15.0f, 9.0f, 1.095163f, 0.0f, 0.0f));
        return meshdefinition;
    }

    @Override
    public void setupAnim(Hydrolisc entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        float f1 = limbSwingAmount;
        float f2 = ageInTicks;
        float hf = 0.0f;
                float newangle = 0.0f;
                newangle = (double)f1 > 0.1 ? Mth.cos((float)(f2 * 1.3f * this.wingspeed)) * (float)Math.PI * 0.25f * f1 : 0.0f;
                this.lf1.xRot = newangle;
                this.lf2.xRot = newangle - 0.488f;
                this.lf3.xRot = newangle - 2.347f;
                this.lf4.xRot = newangle - 0.628f;
                this.lf5.xRot = newangle - 0.628f;
                this.lf6.xRot = newangle + 0.174f;
                this.rf1.xRot = - newangle;
                this.rf2.xRot = - newangle - 0.488f;
                this.rf3.xRot = - newangle - 2.347f;
                this.rf4.xRot = - newangle - 0.628f;
                this.rf5.xRot = - newangle - 0.628f;
                this.rf6.xRot = - newangle + 0.174f;
                this.lb1.xRot = - newangle;
                this.lb2.xRot = - newangle - 0.488f;
                this.lb3.xRot = - newangle - 2.347f;
                this.lb4.xRot = - newangle - 0.628f;
                this.lb5.xRot = - newangle - 0.628f;
                this.lb6.xRot = - newangle + 0.174f;
                this.rb1.xRot = newangle;
                this.rb2.xRot = newangle - 0.488f;
                this.rb3.xRot = newangle - 2.347f;
                this.rb4.xRot = newangle - 0.628f;
                this.rb5.xRot = newangle - 0.628f;
                this.rb6.xRot = newangle + 0.174f;
                newangle = Mth.cos((float)(f2 * 1.0f * this.wingspeed)) * (float)Math.PI * 0.15f;
                if (entity.isInSittingPose()) {
                    newangle = 0.0f;
                }
                this.tail1.yRot = newangle * 0.25f;
                this.tail2.z = this.tail1.z + (float)Math.cos(this.tail1.yRot) * 5.0f;
                this.tail2.x = this.tail1.x + (float)Math.sin(this.tail1.yRot) * 5.0f;
                this.tail2.yRot = newangle * 0.5f;
                this.tail3.z = this.tail2.z + (float)Math.cos(this.tail2.yRot) * 8.0f;
                this.tail3.x = this.tail2.x + (float)Math.sin(this.tail2.yRot) * 8.0f;
                this.tail3.yRot = newangle * 0.75f;
                hf = (float)entity.getHydroHealth() / entity.getMaxHealth();
                this.feather2.yRot = newangle = Mth.cos((float)(f2 * 1.25f * this.wingspeed * hf)) * (float)Math.PI * 0.2f * hf;
                newangle = Mth.cos((float)(f2 * 0.75f * this.wingspeed * hf)) * (float)Math.PI * 0.2f * hf;
                this.feather1.yRot = newangle - 0.9f;
                this.feather3.yRot = - newangle + 0.9f;
    }

    @Override
    public void renderToBuffer(PoseStack poseStack, VertexConsumer buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        this.tail2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lb2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lb1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spine3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spine4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rb1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rb2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spine1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spine2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lb3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rb3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body0.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lf1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rf1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rb6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rb4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rb5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lb6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lb5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lb4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.feather3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.feather1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.feather2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rf2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rf3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rf4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rf5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rf6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lf2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lf3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lf4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lf5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lf6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    }
}
