package com.astryxion.chaospersists.model;

import com.astryxion.chaospersists.entity.Robot4;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

public class ModelRobot4 extends EntityModel<Robot4> {
    private final float wingspeed;
    private final ModelPart leftfootfront;
    private final ModelPart leftfootbase;
    private final ModelPart leftfootback;
    private final ModelPart leftfoottip;
    private final ModelPart leftshin;
    private final ModelPart leftcalf;
    private final ModelPart leftkneegaurd;
    private final ModelPart leftthigh;
    private final ModelPart rightfootfront;
    private final ModelPart rightfoottip;
    private final ModelPart rightfootbase;
    private final ModelPart rightfootback;
    private final ModelPart rightshin;
    private final ModelPart rightcalf;
    private final ModelPart rightkneegaurd;
    private final ModelPart rightthigh;
    private final ModelPart hips;
    private final ModelPart stomach;
    private final ModelPart chest;
    private final ModelPart neck;
    private final ModelPart head;
    private final ModelPart righttopspinebase;
    private final ModelPart lefttopspinebase;
    private final ModelPart righttopspinetip;
    private final ModelPart lefttopspinetip;
    private final ModelPart middlerightspinebase;
    private final ModelPart middleleftspinebase;
    private final ModelPart middleleftspinetip;
    private final ModelPart middlerightspinetip;
    private final ModelPart torso;
    private final ModelPart rightsholder;
    private final ModelPart leftsholder;
    private final ModelPart rightsholdergaurd;
    private final ModelPart sheildbase;
    private final ModelPart sheildtip;
    private final ModelPart rightupperarm;
    private final ModelPart rightlowerarm;
    private final ModelPart sheildend;
    private final ModelPart leftupperarm;
    private final ModelPart sholdergaurdtip;
    private final ModelPart cannonbase;
    private final ModelPart cannonend;
    private final ModelPart leftcannonpiece;
    private final ModelPart topcannonpiece;
    private final ModelPart rightcannonpiece;
    private final ModelPart bottomcannonpiece;
    private final ModelPart glowycannonbit1;
    private final ModelPart glowycannonbit2;
    private final ModelPart glowycannonbit3;
    private final ModelPart glowycannonbit4;
    private final ModelPart glowycannonbit5;
    private final ModelPart cannonammo;
    private final ModelPart lowerrightspinebase;
    private final ModelPart lowerleftspinebase;
    private final ModelPart lowerrightspinetip;
    private final ModelPart lowerleftspinetip;

    public ModelRobot4(float wingspeed) {
        this(LayerDefinition.create(createMesh(), 512, 512).bakeRoot(), wingspeed);
    }

    public ModelRobot4(ModelPart root, float wingspeed) {
        this.wingspeed = wingspeed;
        this.leftfootfront = root.getChild("leftfootfront");
        this.leftfootbase = root.getChild("leftfootbase");
        this.leftfootback = root.getChild("leftfootback");
        this.leftfoottip = root.getChild("leftfoottip");
        this.leftshin = root.getChild("leftshin");
        this.leftcalf = root.getChild("leftcalf");
        this.leftkneegaurd = root.getChild("leftkneegaurd");
        this.leftthigh = root.getChild("leftthigh");
        this.rightfootfront = root.getChild("rightfootfront");
        this.rightfoottip = root.getChild("rightfoottip");
        this.rightfootbase = root.getChild("rightfootbase");
        this.rightfootback = root.getChild("rightfootback");
        this.rightshin = root.getChild("rightshin");
        this.rightcalf = root.getChild("rightcalf");
        this.rightkneegaurd = root.getChild("rightkneegaurd");
        this.rightthigh = root.getChild("rightthigh");
        this.hips = root.getChild("hips");
        this.stomach = root.getChild("stomach");
        this.chest = root.getChild("chest");
        this.neck = root.getChild("neck");
        this.head = root.getChild("head");
        this.righttopspinebase = root.getChild("righttopspinebase");
        this.lefttopspinebase = root.getChild("lefttopspinebase");
        this.righttopspinetip = root.getChild("righttopspinetip");
        this.lefttopspinetip = root.getChild("lefttopspinetip");
        this.middlerightspinebase = root.getChild("middlerightspinebase");
        this.middleleftspinebase = root.getChild("middleleftspinebase");
        this.middleleftspinetip = root.getChild("middleleftspinetip");
        this.middlerightspinetip = root.getChild("middlerightspinetip");
        this.torso = root.getChild("torso");
        this.rightsholder = root.getChild("rightsholder");
        this.leftsholder = root.getChild("leftsholder");
        this.rightsholdergaurd = root.getChild("rightsholdergaurd");
        this.sheildbase = root.getChild("sheildbase");
        this.sheildtip = root.getChild("sheildtip");
        this.rightupperarm = root.getChild("rightupperarm");
        this.rightlowerarm = root.getChild("rightlowerarm");
        this.sheildend = root.getChild("sheildend");
        this.leftupperarm = root.getChild("leftupperarm");
        this.sholdergaurdtip = root.getChild("sholdergaurdtip");
        this.cannonbase = root.getChild("cannonbase");
        this.cannonend = root.getChild("cannonend");
        this.leftcannonpiece = root.getChild("leftcannonpiece");
        this.topcannonpiece = root.getChild("topcannonpiece");
        this.rightcannonpiece = root.getChild("rightcannonpiece");
        this.bottomcannonpiece = root.getChild("bottomcannonpiece");
        this.glowycannonbit1 = root.getChild("glowycannonbit1");
        this.glowycannonbit2 = root.getChild("glowycannonbit2");
        this.glowycannonbit3 = root.getChild("glowycannonbit3");
        this.glowycannonbit4 = root.getChild("glowycannonbit4");
        this.glowycannonbit5 = root.getChild("glowycannonbit5");
        this.cannonammo = root.getChild("cannonammo");
        this.lowerrightspinebase = root.getChild("lowerrightspinebase");
        this.lowerleftspinebase = root.getChild("lowerleftspinebase");
        this.lowerrightspinetip = root.getChild("lowerrightspinetip");
        this.lowerleftspinetip = root.getChild("lowerleftspinetip");
    }

    private static MeshDefinition createMesh() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("leftfootfront", CubeListBuilder.create().texOffs(20, 50).mirror().addBox(-6.0f, 22.0f, -9.0f, 8, 5, 7), PartPose.offsetAndRotation(-8.0f, -3.0f, 6.0f, 0.0f, 0.0f, 0.0f));
        root.addOrReplaceChild("leftfootbase", CubeListBuilder.create().texOffs(20, 100).mirror().addBox(-4.0f, 22.0f, -4.0f, 4, 5, 5), PartPose.offsetAndRotation(-8.0f, -3.0f, 6.0f, 0.0f, 0.0f, 0.0f));
        root.addOrReplaceChild("leftfootback", CubeListBuilder.create().texOffs(20, 150).mirror().addBox(-4.5f, 22.0f, 1.0f, 5, 5, 4), PartPose.offsetAndRotation(-8.0f, -3.0f, 6.0f, 0.0f, 0.0f, 0.0f));
        root.addOrReplaceChild("leftfoottip", CubeListBuilder.create().texOffs(20, 200).mirror().addBox(-4.5f, 23.0f, -12.0f, 5, 4, 3), PartPose.offsetAndRotation(-8.0f, -3.0f, 6.0f, 0.0f, 0.0f, 0.0f));
        root.addOrReplaceChild("leftshin", CubeListBuilder.create().texOffs(20, 250).mirror().addBox(-5.0f, 10.0f, -9.0f, 6, 13, 6), PartPose.offsetAndRotation(-8.0f, -3.0f, 6.0f, 0.1745329f, 0.0f, 0.0f));
        root.addOrReplaceChild("leftcalf", CubeListBuilder.create().texOffs(20, 300).mirror().addBox(-6.0f, 10.0f, -9.0f, 8, 8, 9), PartPose.offsetAndRotation(-8.0f, -3.0f, 6.0f, 0.1745329f, 0.0f, 0.0f));
        root.addOrReplaceChild("leftkneegaurd", CubeListBuilder.create().texOffs(20, 350).mirror().addBox(-5.5f, 4.0f, -14.0f, 7, 7, 1), PartPose.offsetAndRotation(-8.0f, -3.0f, 6.0f, 0.6283185f, 0.0f, 0.0f));
        root.addOrReplaceChild("leftthigh", CubeListBuilder.create().texOffs(20, 400).mirror().addBox(-5.0f, 0.0f, -4.0f, 6, 13, 8), PartPose.offsetAndRotation(-8.0f, -3.0f, 6.0f, -0.1745329f, 0.1745329f, 0.0f));
        root.addOrReplaceChild("rightfootfront", CubeListBuilder.create().texOffs(20, 450).mirror().addBox(0.0f, 22.0f, -9.0f, 8, 5, 7), PartPose.offsetAndRotation(5.0f, -3.0f, 6.0f, 0.0f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightfoottip", CubeListBuilder.create().texOffs(100, 50).mirror().addBox(1.5f, 23.0f, -12.0f, 5, 4, 3), PartPose.offsetAndRotation(5.0f, -3.0f, 6.0f, 0.0f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightfootbase", CubeListBuilder.create().texOffs(100, 150).mirror().addBox(2.0f, 22.0f, -4.0f, 4, 5, 5), PartPose.offsetAndRotation(5.0f, -3.0f, 6.0f, 0.0f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightfootback", CubeListBuilder.create().texOffs(100, 100).mirror().addBox(1.5f, 22.0f, 1.0f, 5, 5, 4), PartPose.offsetAndRotation(5.0f, -3.0f, 6.0f, 0.0f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightshin", CubeListBuilder.create().texOffs(100, 200).mirror().addBox(1.0f, 10.0f, -9.0f, 6, 13, 6), PartPose.offsetAndRotation(5.0f, -3.0f, 6.0f, 0.1745329f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightcalf", CubeListBuilder.create().texOffs(100, 250).mirror().addBox(0.0f, 10.0f, -10.0f, 8, 8, 9), PartPose.offsetAndRotation(5.0f, -3.0f, 6.0f, 0.1745329f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightkneegaurd", CubeListBuilder.create().texOffs(100, 300).mirror().addBox(0.5f, 4.0f, -15.0f, 7, 7, 1), PartPose.offsetAndRotation(5.0f, -3.0f, 6.0f, 0.6283185f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightthigh", CubeListBuilder.create().texOffs(100, 400).mirror().addBox(0.0f, 0.0f, -5.0f, 6, 13, 8), PartPose.offsetAndRotation(5.0f, -3.0f, 6.0f, -0.1745329f, -0.1745329f, 0.0f));
        root.addOrReplaceChild("hips", CubeListBuilder.create().texOffs(100, 350).mirror().addBox(0.0f, 0.0f, 0.0f, 14, 7, 8), PartPose.offsetAndRotation(-8.0f, -3.0f, 2.0f, 0.1396263f, 0.0f, 0.0f));
        root.addOrReplaceChild("stomach", CubeListBuilder.create().texOffs(100, 450).mirror().addBox(0.0f, 0.0f, 0.0f, 12, 6, 7), PartPose.offsetAndRotation(-7.0f, -9.0f, 2.0f, 0.1396263f, 0.0f, 0.0f));
        root.addOrReplaceChild("chest", CubeListBuilder.create().texOffs(200, 50).mirror().addBox(0.0f, 0.0f, 0.0f, 18, 12, 13), PartPose.offsetAndRotation(-10.0f, -23.0f, -4.0f, 0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(200, 100).mirror().addBox(0.0f, 0.0f, 0.0f, 6, 7, 6), PartPose.offsetAndRotation(-4.0f, -22.0f, -7.0f, 0.8726646f, 0.0f, 0.0f));
        root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(200, 150).mirror().addBox(-3.0f, -3.0f, -5.0f, 6, 6, 8), PartPose.offsetAndRotation(-1.0f, -26.0f, -5.0f, 0.5235988f, 0.0f, 0.0f));
        root.addOrReplaceChild("righttopspinebase", CubeListBuilder.create().texOffs(200, 200).mirror().addBox(0.0f, 0.0f, 0.0f, 2, 8, 2), PartPose.offsetAndRotation(3.0f, -29.0f, 5.0f, -0.1396263f, 0.0f, 0.0f));
        root.addOrReplaceChild("lefttopspinebase", CubeListBuilder.create().texOffs(200, 250).mirror().addBox(0.0f, 0.0f, 0.0f, 2, 8, 2), PartPose.offsetAndRotation(-7.0f, -29.0f, 5.0f, -0.1396263f, 0.0f, 0.0f));
        root.addOrReplaceChild("righttopspinetip", CubeListBuilder.create().texOffs(200, 300).mirror().addBox(0.0f, 0.0f, 0.0f, 1, 8, 1), PartPose.offsetAndRotation(3.5f, -35.0f, 8.0f, -0.3316126f, 0.0f, 0.0f));
        root.addOrReplaceChild("lefttopspinetip", CubeListBuilder.create().texOffs(200, 350).mirror().addBox(0.0f, 0.0f, 0.0f, 1, 8, 1), PartPose.offsetAndRotation(-6.5f, -35.0f, 8.0f, -0.3316126f, 0.0f, 0.0f));
        root.addOrReplaceChild("middlerightspinebase", CubeListBuilder.create().texOffs(200, 400).mirror().addBox(0.0f, 0.0f, 0.0f, 2, 8, 2), PartPose.offsetAndRotation(-6.0f, -25.0f, 14.0f, -0.6981317f, 0.0f, 0.0f));
        root.addOrReplaceChild("middleleftspinebase", CubeListBuilder.create().texOffs(200, 450).mirror().addBox(0.0f, 0.0f, 0.0f, 2, 8, 2), PartPose.offsetAndRotation(2.0f, -25.0f, 14.0f, -0.6981317f, 0.0f, 0.0f));
        root.addOrReplaceChild("middleleftspinetip", CubeListBuilder.create().texOffs(300, 50).mirror().addBox(0.0f, 0.0f, 0.0f, 1, 7, 1), PartPose.offsetAndRotation(2.5f, -28.0f, 18.0f, -0.7853982f, 0.0f, 0.0f));
        root.addOrReplaceChild("middlerightspinetip", CubeListBuilder.create().texOffs(300, 100).mirror().addBox(0.0f, 0.0f, 0.0f, 1, 7, 1), PartPose.offsetAndRotation(-5.5f, -28.0f, 18.0f, -0.7853982f, 0.0f, 0.0f));
        root.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(300, 150).mirror().addBox(0.0f, 0.0f, 0.0f, 14, 6, 10), PartPose.offsetAndRotation(-8.0f, -13.0f, 0.0f, 0.1396263f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightsholder", CubeListBuilder.create().texOffs(300, 200).mirror().addBox(0.0f, -3.0f, -3.0f, 6, 6, 6), PartPose.offsetAndRotation(7.0f, -18.0f, 4.0f, 0.0f, 0.0f, 0.0f));
        root.addOrReplaceChild("leftsholder", CubeListBuilder.create().texOffs(300, 250).mirror().addBox(-6.0f, -3.0f, -3.0f, 6, 6, 6), PartPose.offsetAndRotation(-9.0f, -18.0f, 4.0f, 0.0f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightsholdergaurd", CubeListBuilder.create().texOffs(300, 300).mirror().addBox(8.0f, -4.0f, -4.0f, 4, 12, 9), PartPose.offsetAndRotation(7.0f, -18.0f, 4.0f, -0.2094395f, 0.0f, 0.0f));
        root.addOrReplaceChild("sheildbase", CubeListBuilder.create().texOffs(300, 350).mirror().addBox(8.0f, -4.0f, -30.0f, 3, 12, 19), PartPose.offsetAndRotation(7.0f, -18.0f, 4.0f, 1.047198f, 0.0f, 0.0f));
        root.addOrReplaceChild("sheildtip", CubeListBuilder.create().texOffs(300, 400).mirror().addBox(9.0f, -2.0f, -34.0f, 3, 8, 4), PartPose.offsetAndRotation(6.0f, -18.0f, 4.0f, 1.047198f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightupperarm", CubeListBuilder.create().texOffs(300, 450).mirror().addBox(3.0f, -1.0f, -4.0f, 6, 13, 6), PartPose.offsetAndRotation(7.0f, -18.0f, 4.0f, -0.2094395f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightlowerarm", CubeListBuilder.create().texOffs(350, 50).mirror().addBox(3.0f, 0.0f, -25.0f, 6, 6, 14), PartPose.offsetAndRotation(7.0f, -18.0f, 4.0f, 1.047198f, 0.0f, 0.0f));
        root.addOrReplaceChild("sheildend", CubeListBuilder.create().texOffs(350, 100).mirror().addBox(8.0f, -1.0f, -11.0f, 3, 8, 4), PartPose.offsetAndRotation(7.0f, -18.0f, 4.0f, 1.047198f, 0.0f, 0.0f));
        root.addOrReplaceChild("leftupperarm", CubeListBuilder.create().texOffs(350, 200).mirror().addBox(-9.0f, -1.0f, -4.0f, 6, 15, 6), PartPose.offsetAndRotation(-9.0f, -18.0f, 4.0f, -0.2094395f, 0.0f, 0.0f));
        root.addOrReplaceChild("sholdergaurdtip", CubeListBuilder.create().texOffs(350, 250).mirror().addBox(10.0f, -3.0f, -7.0f, 2, 5, 3), PartPose.offsetAndRotation(7.0f, -18.0f, 4.0f, -0.2094395f, 0.0f, 0.0f));
        root.addOrReplaceChild("cannonbase", CubeListBuilder.create().texOffs(350, 300).mirror().addBox(-4.0f, 0.0f, -4.0f, 8, 12, 8), PartPose.offsetAndRotation(-15.0f, -5.0f, 1.0f, -0.6981317f, 0.0f, 0.0f));
        root.addOrReplaceChild("cannonend", CubeListBuilder.create().texOffs(350, 400).mirror().addBox(-3.0f, 11.0f, -3.0f, 6, 4, 6), PartPose.offsetAndRotation(-15.0f, -5.0f, 1.0f, -0.6981317f, 0.0f, 0.0f));
        root.addOrReplaceChild("leftcannonpiece", CubeListBuilder.create().texOffs(20, 20).mirror().addBox(-5.0f, 11.0f, -1.5f, 3, 6, 3), PartPose.offsetAndRotation(-15.0f, -5.0f, 1.0f, -0.6981317f, 0.0f, 0.0f));
        root.addOrReplaceChild("topcannonpiece", CubeListBuilder.create().texOffs(40, 20).mirror().addBox(-1.5f, 11.0f, -5.0f, 3, 6, 3), PartPose.offsetAndRotation(-15.0f, -5.0f, 1.0f, -0.6981317f, 0.0f, 0.0f));
        root.addOrReplaceChild("rightcannonpiece", CubeListBuilder.create().texOffs(80, 20).mirror().addBox(2.0f, 11.0f, -1.5f, 3, 6, 3), PartPose.offsetAndRotation(-15.0f, -5.0f, 1.0f, -0.6981317f, 0.0f, 0.0f));
        root.addOrReplaceChild("bottomcannonpiece", CubeListBuilder.create().texOffs(100, 20).mirror().addBox(-1.5f, 11.0f, 2.0f, 3, 6, 3), PartPose.offsetAndRotation(-15.0f, -5.0f, 1.0f, -0.6981317f, 0.0f, 0.0f));
        root.addOrReplaceChild("glowycannonbit1", CubeListBuilder.create().texOffs(150, 20).mirror().addBox(-3.5f, 0.0f, -11.0f, 2, 5, 2), PartPose.offsetAndRotation(-15.0f, -5.0f, 1.0f, 0.1745329f, 0.0f, 0.0f));
        root.addOrReplaceChild("glowycannonbit2", CubeListBuilder.create().texOffs(200, 20).mirror().addBox(1.5f, 0.0f, -11.0f, 2, 5, 2), PartPose.offsetAndRotation(-15.0f, -5.0f, 1.0f, 0.1745329f, 0.0f, 0.0f));
        root.addOrReplaceChild("glowycannonbit3", CubeListBuilder.create().texOffs(250, 20).mirror().addBox(-3.0f, -2.0f, -8.0f, 2, 5, 2), PartPose.offsetAndRotation(-15.0f, -5.0f, 1.0f, 0.0872665f, 0.0f, 0.0f));
        root.addOrReplaceChild("glowycannonbit4", CubeListBuilder.create().texOffs(300, 20).mirror().addBox(1.0f, -2.0f, -8.0f, 2, 5, 2), PartPose.offsetAndRotation(-15.0f, -5.0f, 1.0f, 0.0872665f, 0.0f, 0.0f));
        root.addOrReplaceChild("glowycannonbit5", CubeListBuilder.create().texOffs(350, 20).mirror().addBox(-1.0f, -5.0f, -5.0f, 2, 5, 2), PartPose.offsetAndRotation(-15.0f, -5.0f, 1.0f, 0.0f, 0.0f, 0.0f));
        root.addOrReplaceChild("cannonammo", CubeListBuilder.create().texOffs(400, 400).mirror().addBox(-6.0f, 3.0f, 0.0f, 5, 5, 5), PartPose.offsetAndRotation(-15.0f, -5.0f, 1.0f, -0.6981317f, 0.0f, 0.0f));
        root.addOrReplaceChild("lowerrightspinebase", CubeListBuilder.create().texOffs(400, 450).mirror().addBox(0.0f, 0.0f, 0.0f, 2, 8, 2), PartPose.offsetAndRotation(4.0f, -19.0f, 15.0f, -1.047198f, 0.0f, 0.0f));
        root.addOrReplaceChild("lowerleftspinebase", CubeListBuilder.create().texOffs(360, 450).mirror().addBox(0.0f, 0.0f, 0.0f, 2, 8, 2), PartPose.offsetAndRotation(-8.0f, -19.0f, 15.0f, -1.047198f, 0.0f, 0.0f));
        root.addOrReplaceChild("lowerrightspinetip", CubeListBuilder.create().texOffs(250, 100).mirror().addBox(0.0f, 0.0f, 0.0f, 1, 7, 1), PartPose.offsetAndRotation(4.5f, -21.0f, 20.0f, -1.134464f, 0.0f, 0.0f));
        root.addOrReplaceChild("lowerleftspinetip", CubeListBuilder.create().texOffs(150, 100).mirror().addBox(0.0f, 0.0f, 0.0f, 1, 7, 1), PartPose.offsetAndRotation(-7.5f, -21.0f, 20.0f, -1.134464f, 0.0f, 0.0f));
        return mesh;
    }
    @Override
    public void setupAnim(Robot4 e, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        float newangle = 0.0f;
        newangle = (double) limbSwingAmount > 0.1
                ? Mth.cos(ageInTicks * 0.5f * this.wingspeed) * 3.1415927f * 0.15f * limbSwingAmount
                : 0.0f;
        this.leftfootfront.xRot = newangle;
        this.leftfootbase.xRot = newangle;
        this.leftfootback.xRot = newangle;
        this.leftfoottip.xRot = newangle;
        this.leftshin.xRot = newangle;
        this.leftcalf.xRot = newangle + 0.175f;
        this.leftkneegaurd.xRot = newangle + 0.63f;
        this.leftthigh.xRot = newangle - 0.175f;
        this.rightfootfront.xRot = -newangle;
        this.rightfoottip.xRot = -newangle;
        this.rightfootbase.xRot = -newangle;
        this.rightfootback.xRot = -newangle;
        this.rightshin.xRot = -newangle;
        this.rightcalf.xRot = -newangle + 0.175f;
        this.rightkneegaurd.xRot = -newangle + 0.63f;
        this.rightthigh.xRot = -newangle - 0.175f;
        this.head.yRot = (float) Math.toRadians((double) netHeadYaw / 1.5);
        float amp = 0.7853982f;
        if (e.getAttacking() != 0) {
            newangle = Mth.cos((float) Math.toRadians(ageInTicks % 360.0f) * this.wingspeed * 6.0f) * amp;
            newangle = Math.abs(newangle);
            newangle += 0.75f;
        } else {
            newangle = 0.0f;
        }
        if ((double) newangle > (double) amp / 3.0) {
            e.setShielding(1);
        } else {
            e.setShielding(0);
        }
        this.rightsholder.xRot = -newangle;
        this.rightsholdergaurd.xRot = -newangle - 0.21f;
        this.sheildbase.xRot = -newangle + 1.047f;
        this.sheildtip.xRot = -newangle + 1.047f;
        this.rightupperarm.xRot = -newangle - 0.21f;
        this.rightlowerarm.xRot = -newangle + 1.047f;
        this.sheildend.xRot = -newangle + 1.04f;
        this.sholdergaurdtip.xRot = -newangle - 0.21f;
        newangle = e.getAttacking() != 0 ? 0.85f : 0.0f;
        this.leftsholder.xRot = -newangle;
        this.leftupperarm.xRot = -newangle - 0.21f;
        this.cannonbase.xRot = -newangle - 0.7f;
        this.cannonend.xRot = -newangle - 0.7f;
        this.leftcannonpiece.xRot = -newangle - 0.7f;
        this.topcannonpiece.xRot = -newangle - 0.7f;
        this.rightcannonpiece.xRot = -newangle - 0.7f;
        this.bottomcannonpiece.xRot = -newangle - 0.7f;
        this.glowycannonbit1.xRot = -newangle + 0.17f;
        this.glowycannonbit2.xRot = -newangle + 0.17f;
        this.glowycannonbit3.xRot = -newangle + 0.08f;
        this.glowycannonbit4.xRot = -newangle + 0.08f;
        this.glowycannonbit5.xRot = -newangle;
        this.cannonammo.xRot = -newangle - 0.7f;
        double newposy = (double) this.leftsholder.y + Math.cos(this.leftupperarm.xRot) * 14.0;
        double newposz = (double) this.leftsholder.z + Math.sin(this.leftupperarm.xRot) * 14.0;
        this.cannonbase.y = (float) newposy;
        this.cannonbase.z = (float) newposz;
        this.cannonend.y = (float) newposy;
        this.cannonend.z = (float) newposz;
        this.leftcannonpiece.y = (float) newposy;
        this.leftcannonpiece.z = (float) newposz;
        this.topcannonpiece.y = (float) newposy;
        this.topcannonpiece.z = (float) newposz;
        this.rightcannonpiece.y = (float) newposy;
        this.rightcannonpiece.z = (float) newposz;
        this.bottomcannonpiece.y = (float) newposy;
        this.bottomcannonpiece.z = (float) newposz;
        this.glowycannonbit1.y = (float) newposy;
        this.glowycannonbit1.z = (float) newposz;
        this.glowycannonbit2.y = (float) newposy;
        this.glowycannonbit2.z = (float) newposz;
        this.glowycannonbit3.y = (float) newposy;
        this.glowycannonbit3.z = (float) newposz;
        this.glowycannonbit4.y = (float) newposy;
        this.glowycannonbit4.z = (float) newposz;
        this.glowycannonbit5.y = (float) newposy;
        this.glowycannonbit5.z = (float) newposz;
        this.cannonammo.y = (float) newposy;
        this.cannonammo.z = (float) newposz;
    }

    @Override
    public void renderToBuffer(PoseStack poseStack, VertexConsumer buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        this.leftfootfront.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftfootbase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftfootback.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftfoottip.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftshin.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftcalf.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftkneegaurd.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftthigh.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightfootfront.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightfoottip.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightfootbase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightfootback.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightshin.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightcalf.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightkneegaurd.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightthigh.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.hips.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.stomach.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.chest.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.righttopspinebase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lefttopspinebase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.righttopspinetip.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lefttopspinetip.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.middlerightspinebase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.middleleftspinebase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.middleleftspinetip.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.middlerightspinetip.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.torso.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightsholder.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftsholder.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightsholdergaurd.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.sheildbase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.sheildtip.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightupperarm.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightlowerarm.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.sheildend.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftupperarm.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.sholdergaurdtip.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.cannonbase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.cannonend.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftcannonpiece.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.topcannonpiece.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightcannonpiece.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.bottomcannonpiece.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.glowycannonbit1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.glowycannonbit2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.glowycannonbit3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.glowycannonbit4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.glowycannonbit5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.cannonammo.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lowerrightspinebase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lowerleftspinebase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lowerrightspinetip.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lowerleftspinetip.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    }
}
