package com.astryxion.chaospersists.model;

import com.astryxion.chaospersists.entity.CaveFisher;
import com.astryxion.chaospersists.render.RenderInfo;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

public class ModelCaveFisher extends EntityModel<CaveFisher> {
    private final float wingspeed;
    private final ModelPart Nose;
    private final ModelPart EyeLeft;
    private final ModelPart HeadMid;
    private final ModelPart HeadEnd;
    private final ModelPart TailTuft;
    private final ModelPart EyeRight;
    private final ModelPart BodyTopLeft4;
    private final ModelPart BodyTopRight4;
    private final ModelPart BodyTopLeft1;
    private final ModelPart BodyTopRight1;
    private final ModelPart BodyTopRight2;
    private final ModelPart BodyTopLeft2;
    private final ModelPart BodyTopRight3;
    private final ModelPart BodyTopLeft3;
    private final ModelPart HeadBase;
    private final ModelPart TailBase;
    private final ModelPart BodyLow2;
    private final ModelPart BodyLow1;
    private final ModelPart Spine5;
    private final ModelPart Spine1;
    private final ModelPart Spine2;
    private final ModelPart Spine3;
    private final ModelPart Spine4;
    private final ModelPart RightArmSeg4;
    private final ModelPart LeftArmSeg1;
    private final ModelPart LeftArmSeg3;
    private final ModelPart RightArmSeg2;
    private final ModelPart RightArmSeg1;
    private final ModelPart LeftArmSeg5;
    private final ModelPart LeftArmSeg2;
    private final ModelPart LeftClawTop;
    private final ModelPart RightArmSeg3;
    private final ModelPart RightArmSeg5;
    private final ModelPart LeftArmSeg4;
    private final ModelPart LeftClawBase;
    private final ModelPart RightClawBase;
    private final ModelPart LeftClawLow;
    private final ModelPart RightClawTop;
    private final ModelPart RightClawLow;
    private final ModelPart LBLeg1;
    private final ModelPart LBLeg3;
    private final ModelPart RBLeg1;
    private final ModelPart RBLeg3;
    private final ModelPart LBLeg2;
    private final ModelPart RBLeg2;
    private final ModelPart LBLeg4;
    private final ModelPart RBLeg4;
    private final ModelPart RBLeg5;
    private final ModelPart LBLeg6;
    private final ModelPart RBLeg6;
    private final ModelPart LBLeg5;
    private final ModelPart RFLeg1;
    private final ModelPart RFLeg2;
    private final ModelPart RFLeg3;
    private final ModelPart RFLeg4;
    private final ModelPart RFLeg5;
    private final ModelPart RFLeg6;
    private final ModelPart RMLeg1;
    private final ModelPart RMLeg2;
    private final ModelPart RMLeg3;
    private final ModelPart RMLeg4;
    private final ModelPart RMLeg5;
    private final ModelPart RMLeg6;
    private final ModelPart LFLeg1;
    private final ModelPart LFLeg2;
    private final ModelPart LFLeg3;
    private final ModelPart LFLeg4;
    private final ModelPart LFLeg5;
    private final ModelPart LFLeg6;
    private final ModelPart LMLeg1;
    private final ModelPart LMLeg2;
    private final ModelPart LMLeg4;
    private final ModelPart LMLeg3;
    private final ModelPart LMLeg5;
    private final ModelPart LMLeg6;

    public ModelCaveFisher() {
        this(1.0f);
    }

    public ModelCaveFisher(float wingspeed) {
        this(wingspeed, LayerDefinition.create(createMesh(), 64, 32).bakeRoot());
    }

    public ModelCaveFisher(ModelPart root) {
        this(1.0f, root);
    }

    public ModelCaveFisher(float wingspeed, ModelPart root) {
        this.wingspeed = wingspeed;
        this.Nose = root.getChild("Nose");
        this.EyeLeft = root.getChild("EyeLeft");
        this.HeadMid = root.getChild("HeadMid");
        this.HeadEnd = root.getChild("HeadEnd");
        this.TailTuft = root.getChild("TailTuft");
        this.EyeRight = root.getChild("EyeRight");
        this.BodyTopLeft4 = root.getChild("BodyTopLeft4");
        this.BodyTopRight4 = root.getChild("BodyTopRight4");
        this.BodyTopLeft1 = root.getChild("BodyTopLeft1");
        this.BodyTopRight1 = root.getChild("BodyTopRight1");
        this.BodyTopRight2 = root.getChild("BodyTopRight2");
        this.BodyTopLeft2 = root.getChild("BodyTopLeft2");
        this.BodyTopRight3 = root.getChild("BodyTopRight3");
        this.BodyTopLeft3 = root.getChild("BodyTopLeft3");
        this.HeadBase = root.getChild("HeadBase");
        this.TailBase = root.getChild("TailBase");
        this.BodyLow2 = root.getChild("BodyLow2");
        this.BodyLow1 = root.getChild("BodyLow1");
        this.Spine5 = root.getChild("Spine5");
        this.Spine1 = root.getChild("Spine1");
        this.Spine2 = root.getChild("Spine2");
        this.Spine3 = root.getChild("Spine3");
        this.Spine4 = root.getChild("Spine4");
        this.RightArmSeg4 = root.getChild("RightArmSeg4");
        this.LeftArmSeg1 = root.getChild("LeftArmSeg1");
        this.LeftArmSeg3 = root.getChild("LeftArmSeg3");
        this.RightArmSeg2 = root.getChild("RightArmSeg2");
        this.RightArmSeg1 = root.getChild("RightArmSeg1");
        this.LeftArmSeg5 = root.getChild("LeftArmSeg5");
        this.LeftArmSeg2 = root.getChild("LeftArmSeg2");
        this.LeftClawTop = root.getChild("LeftClawTop");
        this.RightArmSeg3 = root.getChild("RightArmSeg3");
        this.RightArmSeg5 = root.getChild("RightArmSeg5");
        this.LeftArmSeg4 = root.getChild("LeftArmSeg4");
        this.LeftClawBase = root.getChild("LeftClawBase");
        this.RightClawBase = root.getChild("RightClawBase");
        this.LeftClawLow = root.getChild("LeftClawLow");
        this.RightClawTop = root.getChild("RightClawTop");
        this.RightClawLow = root.getChild("RightClawLow");
        this.LBLeg1 = root.getChild("LBLeg1");
        this.LBLeg3 = root.getChild("LBLeg3");
        this.RBLeg1 = root.getChild("RBLeg1");
        this.RBLeg3 = root.getChild("RBLeg3");
        this.LBLeg2 = root.getChild("LBLeg2");
        this.RBLeg2 = root.getChild("RBLeg2");
        this.LBLeg4 = root.getChild("LBLeg4");
        this.RBLeg4 = root.getChild("RBLeg4");
        this.RBLeg5 = root.getChild("RBLeg5");
        this.LBLeg6 = root.getChild("LBLeg6");
        this.RBLeg6 = root.getChild("RBLeg6");
        this.LBLeg5 = root.getChild("LBLeg5");
        this.RFLeg1 = root.getChild("RFLeg1");
        this.RFLeg2 = root.getChild("RFLeg2");
        this.RFLeg3 = root.getChild("RFLeg3");
        this.RFLeg4 = root.getChild("RFLeg4");
        this.RFLeg5 = root.getChild("RFLeg5");
        this.RFLeg6 = root.getChild("RFLeg6");
        this.RMLeg1 = root.getChild("RMLeg1");
        this.RMLeg2 = root.getChild("RMLeg2");
        this.RMLeg3 = root.getChild("RMLeg3");
        this.RMLeg4 = root.getChild("RMLeg4");
        this.RMLeg5 = root.getChild("RMLeg5");
        this.RMLeg6 = root.getChild("RMLeg6");
        this.LFLeg1 = root.getChild("LFLeg1");
        this.LFLeg2 = root.getChild("LFLeg2");
        this.LFLeg3 = root.getChild("LFLeg3");
        this.LFLeg4 = root.getChild("LFLeg4");
        this.LFLeg5 = root.getChild("LFLeg5");
        this.LFLeg6 = root.getChild("LFLeg6");
        this.LMLeg1 = root.getChild("LMLeg1");
        this.LMLeg2 = root.getChild("LMLeg2");
        this.LMLeg4 = root.getChild("LMLeg4");
        this.LMLeg3 = root.getChild("LMLeg3");
        this.LMLeg5 = root.getChild("LMLeg5");
        this.LMLeg6 = root.getChild("LMLeg6");
    }

    private static MeshDefinition createMesh() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("Nose", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5f, -0.5f, -12.0f, 1, 1, 6), PartPose.offset(0.0f, 19.0f, -4.0f));
        root.addOrReplaceChild("EyeLeft", CubeListBuilder.create().texOffs(0, 28).mirror().addBox(0.5f, -2.5f, -2.5f, 3, 2, 2), PartPose.offset(0.0f, 19.0f, -4.0f));
        root.addOrReplaceChild("HeadMid", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2.5f, -1.5f, -5.0f, 5, 3, 2), PartPose.offset(0.0f, 19.0f, -4.0f));
        root.addOrReplaceChild("HeadEnd", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2.0f, -1.0f, -6.0f, 4, 2, 1), PartPose.offset(0.0f, 19.0f, -4.0f));
        root.addOrReplaceChild("TailTuft", CubeListBuilder.create().texOffs(0, 23).mirror().addBox(-2.0f, -1.0f, 3.0f, 4, 1, 2), PartPose.offset(0.0f, 19.0f, 10.0f));
        root.addOrReplaceChild("EyeRight", CubeListBuilder.create().texOffs(0, 28).mirror().addBox(-3.5f, -2.5f, -2.5f, 3, 2, 2), PartPose.offset(0.0f, 19.0f, -4.0f));
        root.addOrReplaceChild("BodyTopLeft4", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0.0f, 0.0f, 0.0f, 6, 3, 4), PartPose.offsetAndRotation(0.0f, 16.2f, 7.0f, 0.1047198f, 0.1047198f, 0.1047198f));
        root.addOrReplaceChild("BodyTopRight4", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-5.0f, 0.0f, 0.0f, 6, 3, 4), PartPose.offsetAndRotation(-1.0f, 16.2f, 7.0f, 0.1047198f, -0.1047198f, -0.1047198f));
        root.addOrReplaceChild("BodyTopLeft1", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0.0f, 0.0f, 0.0f, 5, 3, 4), PartPose.offsetAndRotation(0.0f, 16.0f, -4.0f, 0.1745329f, 0.1745329f, 0.1047198f));
        root.addOrReplaceChild("BodyTopRight1", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-5.0f, 0.0f, 0.0f, 5, 3, 4), PartPose.offsetAndRotation(0.0f, 16.0f, -4.0f, 0.1745329f, -0.1745329f, -0.1047198f));
        root.addOrReplaceChild("BodyTopRight2", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-5.0f, 0.0f, 0.0f, 7, 3, 4), PartPose.offsetAndRotation(-1.0f, 16.0f, -1.0f, 0.2094395f, -0.1745329f, -0.1047198f));
        root.addOrReplaceChild("BodyTopLeft2", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-1.0f, 0.0f, 0.0f, 7, 3, 4), PartPose.offsetAndRotation(0.0f, 16.0f, -1.0f, 0.2094395f, 0.1745329f, 0.1047198f));
        root.addOrReplaceChild("BodyTopRight3", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-5.0f, 0.0f, 0.0f, 6, 3, 4), PartPose.offsetAndRotation(-1.0f, 16.0f, 3.0f, 0.1396263f, -0.1396263f, -0.1047198f));
        root.addOrReplaceChild("BodyTopLeft3", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0.0f, 0.0f, 0.0f, 6, 3, 4), PartPose.offsetAndRotation(0.0f, 16.0f, 3.0f, 0.1396263f, 0.1396263f, 0.1047198f));
        root.addOrReplaceChild("HeadBase", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-3.0f, -2.0f, -3.0f, 6, 4, 3), PartPose.offset(0.0f, 19.0f, -4.0f));
        root.addOrReplaceChild("TailBase", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-3.0f, -2.0f, 0.0f, 6, 3, 3), PartPose.offset(0.0f, 19.0f, 10.0f));
        root.addOrReplaceChild("BodyLow2", CubeListBuilder.create().texOffs(34, 0).mirror().addBox(0.0f, 0.0f, 0.0f, 8, 2, 7), PartPose.offset(-4.0f, 18.3f, 3.0f));
        root.addOrReplaceChild("BodyLow1", CubeListBuilder.create().texOffs(34, 0).mirror().addBox(0.0f, 0.0f, 0.0f, 8, 2, 7), PartPose.offset(-4.0f, 18.7f, -4.0f));
        root.addOrReplaceChild("Spine5", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5f, 0.0f, 0.0f, 1, 1, 4), PartPose.offset(0.0f, 16.0f, 8.6f));
        root.addOrReplaceChild("Spine1", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5f, 0.0f, 0.0f, 1, 1, 4), PartPose.offsetAndRotation(0.0f, 16.0f, -4.2f, 0.2443461f, 0.0f, 0.0f));
        root.addOrReplaceChild("Spine2", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5f, 0.0f, 0.0f, 1, 1, 5), PartPose.offsetAndRotation(0.0f, 16.0f, -1.2f, 0.3141593f, 0.0f, 0.0f));
        root.addOrReplaceChild("Spine3", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5f, 0.0f, 0.0f, 1, 1, 6), PartPose.offsetAndRotation(0.0f, 16.0f, 1.8f, 0.2792527f, 0.0f, 0.0f));
        root.addOrReplaceChild("Spine4", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5f, 0.0f, 0.0f, 1, 1, 8), PartPose.offsetAndRotation(0.0f, 16.0f, 3.8f, 0.1745329f, 0.0f, 0.0f));
        root.addOrReplaceChild("RightArmSeg4", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-3.2f, -1.0f, -10.5f, 2, 2, 4), PartPose.offsetAndRotation(-4.7f, 17.5f, -3.0f, 0.0f, 0.0872665f, 0.0f));
        root.addOrReplaceChild("LeftArmSeg1", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(-0.5f, -0.5f, -4.0f, 1, 1, 4), PartPose.offsetAndRotation(4.7f, 17.5f, -3.0f, 0.0f, -0.5235988f, 0.0f));
        root.addOrReplaceChild("LeftArmSeg3", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(1.0f, -0.5f, -8.0f, 1, 1, 3), PartPose.offsetAndRotation(4.7f, 17.5f, -3.0f, 0.0f, -0.1745329f, 0.0f));
        root.addOrReplaceChild("RightArmSeg2", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-1.5f, -1.0f, -6.0f, 2, 2, 4), PartPose.offsetAndRotation(-4.7f, 17.5f, -3.0f, 0.0f, 0.3490659f, 0.0f));
        root.addOrReplaceChild("RightArmSeg1", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(-0.5f, -0.5f, -4.0f, 1, 1, 4), PartPose.offsetAndRotation(-4.7f, 17.5f, -3.0f, 0.0f, 0.5235988f, 0.0f));
        root.addOrReplaceChild("LeftArmSeg5", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(2.4f, -0.5f, -12.0f, 1, 1, 3), PartPose.offset(4.7f, 17.5f, -3.0f));
        root.addOrReplaceChild("LeftArmSeg2", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5f, -1.0f, -6.0f, 2, 2, 4), PartPose.offsetAndRotation(4.7f, 17.5f, -3.0f, 0.0f, -0.3490659f, 0.0f));
        root.addOrReplaceChild("LeftClawTop", CubeListBuilder.create().texOffs(15, 15).mirror().addBox(1.8f, 4.7f, -15.0f, 2, 2, 5), PartPose.offsetAndRotation(4.7f, 17.5f, -3.0f, -0.5410521f, 0.0f, 0.0f));
        root.addOrReplaceChild("RightArmSeg3", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(-2.0f, -0.5f, -8.0f, 1, 1, 3), PartPose.offsetAndRotation(-4.7f, 17.5f, -3.0f, 0.0f, 0.1745329f, 0.0f));
        root.addOrReplaceChild("RightArmSeg5", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(-3.6f, -0.5f, -12.0f, 1, 1, 3), PartPose.offset(-4.7f, 17.5f, -3.0f));
        root.addOrReplaceChild("LeftArmSeg4", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(1.1f, -1.0f, -10.5f, 2, 2, 4), PartPose.offsetAndRotation(4.7f, 17.5f, -3.0f, 0.0f, -0.0872665f, 0.0f));
        root.addOrReplaceChild("LeftClawBase", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(1.8f, -1.0f, -13.0f, 2, 2, 2), PartPose.offset(4.7f, 17.5f, -3.0f));
        root.addOrReplaceChild("RightClawBase", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-4.2f, -1.0f, -13.0f, 2, 2, 2), PartPose.offset(-4.7f, 17.5f, -3.0f));
        root.addOrReplaceChild("LeftClawLow", CubeListBuilder.create().texOffs(25, 25).mirror().addBox(1.8f, -4.3f, -15.0f, 2, 1, 4), PartPose.offsetAndRotation(4.7f, 17.5f, -3.0f, 0.3490659f, 0.0f, 0.0f));
        root.addOrReplaceChild("RightClawTop", CubeListBuilder.create().texOffs(15, 15).mirror().addBox(-4.2f, 4.7f, -15.0f, 2, 2, 5), PartPose.offsetAndRotation(-4.7f, 17.5f, -3.0f, -0.5410521f, 0.0f, 0.0f));
        root.addOrReplaceChild("RightClawLow", CubeListBuilder.create().texOffs(25, 25).mirror().addBox(-4.2f, -4.3f, -15.0f, 2, 1, 4), PartPose.offsetAndRotation(-4.7f, 17.5f, -3.0f, 0.3490659f, 0.0f, 0.0f));
        root.addOrReplaceChild("LBLeg1", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(0.5f, -0.5f, -0.5f, 3, 1, 1), PartPose.offsetAndRotation(5.0f, 18.0f, 8.5f, 0.0f, 0.0f, -0.4363323f));
        root.addOrReplaceChild("LBLeg3", CubeListBuilder.create().texOffs(2, 0).mirror().addBox(5.1f, -1.5f, -1.0f, 3, 1, 2), PartPose.offsetAndRotation(5.0f, 18.0f, 8.5f, 0.0f, 0.0f, -0.5759587f));
        root.addOrReplaceChild("RBLeg1", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(-3.5f, -0.5f, -0.5f, 3, 1, 1), PartPose.offsetAndRotation(-5.0f, 18.0f, 8.5f, 0.0f, 0.0f, 0.4363323f));
        root.addOrReplaceChild("RBLeg3", CubeListBuilder.create().texOffs(2, 0).mirror().addBox(-8.1f, -1.5f, -1.0f, 3, 1, 2), PartPose.offsetAndRotation(-5.0f, 18.0f, 8.5f, 0.0f, 0.0f, 0.5759587f));
        root.addOrReplaceChild("LBLeg2", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(2.5f, 0.5f, -1.0f, 3, 2, 2), PartPose.offsetAndRotation(5.0f, 18.0f, 8.5f, 0.0f, 0.0f, -0.9599311f));
        root.addOrReplaceChild("RBLeg2", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-5.5f, 0.5f, -1.0f, 3, 2, 2), PartPose.offsetAndRotation(-5.0f, 18.0f, 8.5f, 0.0f, 0.0f, 0.9599311f));
        root.addOrReplaceChild("LBLeg4", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(5.0f, -3.0f, -0.5f, 1, 3, 1), PartPose.offsetAndRotation(5.0f, 18.0f, 8.5f, 0.0f, 0.0f, -0.2094395f));
        root.addOrReplaceChild("RBLeg4", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(-6.0f, -3.0f, -0.5f, 1, 3, 1), PartPose.offsetAndRotation(-5.0f, 18.0f, 8.5f, 0.0f, 0.0f, 0.2094395f));
        root.addOrReplaceChild("RBLeg5", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-6.4f, -1.0f, -1.0f, 2, 6, 2), PartPose.offsetAndRotation(-5.0f, 18.0f, 8.5f, 0.0f, 0.0f, 0.1047198f));
        root.addOrReplaceChild("LBLeg6", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(5.5f, 3.0f, -0.5f, 1, 3, 1), PartPose.offset(5.0f, 18.0f, 8.5f));
        root.addOrReplaceChild("RBLeg6", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(-6.5f, 3.0f, -0.5f, 1, 3, 1), PartPose.offset(-5.0f, 18.0f, 8.5f));
        root.addOrReplaceChild("LBLeg5", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(4.6f, -1.0f, -1.0f, 2, 6, 2), PartPose.offsetAndRotation(5.0f, 18.0f, 8.5f, 0.0f, 0.0f, -0.1047198f));
        root.addOrReplaceChild("RFLeg1", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(-3.5f, -0.5f, -0.5f, 3, 1, 1), PartPose.offsetAndRotation(-5.0f, 18.0f, 0.5f, 0.0f, 0.0f, 0.4363323f));
        root.addOrReplaceChild("RFLeg2", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-5.5f, 0.5f, -1.0f, 3, 2, 2), PartPose.offsetAndRotation(-5.0f, 18.0f, 0.5f, 0.0f, 0.0f, 0.9599311f));
        root.addOrReplaceChild("RFLeg3", CubeListBuilder.create().texOffs(2, 0).mirror().addBox(-8.1f, -1.5f, -1.0f, 3, 1, 2), PartPose.offsetAndRotation(-5.0f, 18.0f, 0.5f, 0.0f, 0.0f, 0.5759587f));
        root.addOrReplaceChild("RFLeg4", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(-6.0f, -3.0f, -0.5f, 1, 3, 1), PartPose.offsetAndRotation(-5.0f, 18.0f, 0.5f, 0.0f, 0.0f, 0.2094395f));
        root.addOrReplaceChild("RFLeg5", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-6.4f, -1.0f, -1.0f, 2, 6, 2), PartPose.offsetAndRotation(-5.0f, 18.0f, 0.5f, 0.0f, 0.0f, 0.1047198f));
        root.addOrReplaceChild("RFLeg6", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(-6.5f, 3.0f, -0.5f, 1, 3, 1), PartPose.offset(-5.0f, 18.0f, 0.5f));
        root.addOrReplaceChild("RMLeg1", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(-3.5f, -0.5f, -0.5f, 3, 1, 1), PartPose.offsetAndRotation(-5.0f, 18.0f, 4.5f, 0.0f, 0.0f, 0.4363323f));
        root.addOrReplaceChild("RMLeg2", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-5.5f, 0.5f, -1.0f, 3, 2, 2), PartPose.offsetAndRotation(-5.0f, 18.0f, 4.5f, 0.0f, 0.0f, 0.9599311f));
        root.addOrReplaceChild("RMLeg3", CubeListBuilder.create().texOffs(2, 0).mirror().addBox(-8.1f, -1.5f, -1.0f, 3, 1, 2), PartPose.offsetAndRotation(-5.0f, 18.0f, 4.5f, 0.0f, 0.0f, 0.5759587f));
        root.addOrReplaceChild("RMLeg4", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(-6.0f, -3.0f, -0.5f, 1, 3, 1), PartPose.offsetAndRotation(-5.0f, 18.0f, 4.5f, 0.0f, 0.0f, 0.2094395f));
        root.addOrReplaceChild("RMLeg5", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-6.4f, -1.0f, -1.0f, 2, 6, 2), PartPose.offsetAndRotation(-5.0f, 18.0f, 4.5f, 0.0f, 0.0f, 0.1047198f));
        root.addOrReplaceChild("RMLeg6", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(-6.5f, 3.0f, -0.5f, 1, 3, 1), PartPose.offset(-5.0f, 18.0f, 4.5f));
        root.addOrReplaceChild("LFLeg1", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(0.5f, -0.5f, -0.5f, 3, 1, 1), PartPose.offsetAndRotation(5.0f, 18.0f, 0.5f, 0.0f, 0.0f, -0.4363323f));
        root.addOrReplaceChild("LFLeg2", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(2.5f, 0.5f, -1.0f, 3, 2, 2), PartPose.offsetAndRotation(5.0f, 18.0f, 0.5f, 0.0f, 0.0f, -0.9599311f));
        root.addOrReplaceChild("LFLeg3", CubeListBuilder.create().texOffs(2, 0).mirror().addBox(5.1f, -1.5f, -1.0f, 3, 1, 2), PartPose.offsetAndRotation(5.0f, 18.0f, 0.5f, 0.0f, 0.0f, -0.5759587f));
        root.addOrReplaceChild("LFLeg4", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(5.0f, -3.0f, -0.5f, 1, 3, 1), PartPose.offsetAndRotation(5.0f, 18.0f, 0.5f, 0.0f, 0.0f, -0.2094395f));
        root.addOrReplaceChild("LFLeg5", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(4.6f, -1.0f, -1.0f, 2, 6, 2), PartPose.offsetAndRotation(5.0f, 18.0f, 0.5f, 0.0f, 0.0f, -0.1047198f));
        root.addOrReplaceChild("LFLeg6", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(5.5f, 3.0f, -0.5f, 1, 3, 1), PartPose.offset(5.0f, 18.0f, 0.5f));
        root.addOrReplaceChild("LMLeg1", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(0.5f, -0.5f, -0.5f, 3, 1, 1), PartPose.offsetAndRotation(5.0f, 18.0f, 4.5f, 0.0f, 0.0f, -0.4363323f));
        root.addOrReplaceChild("LMLeg2", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(2.5f, 0.5f, -1.0f, 3, 2, 2), PartPose.offsetAndRotation(5.0f, 18.0f, 4.5f, 0.0f, 0.0f, -0.9599311f));
        root.addOrReplaceChild("LMLeg4", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(5.0f, -3.0f, -0.5f, 1, 3, 1), PartPose.offsetAndRotation(5.0f, 18.0f, 4.5f, 0.0f, 0.0f, -0.2094395f));
        root.addOrReplaceChild("LMLeg3", CubeListBuilder.create().texOffs(2, 0).mirror().addBox(5.1f, -1.5f, -1.0f, 3, 1, 2), PartPose.offsetAndRotation(5.0f, 18.0f, 4.5f, 0.0f, 0.0f, -0.5759587f));
        root.addOrReplaceChild("LMLeg5", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(4.6f, -1.0f, -1.0f, 2, 6, 2), PartPose.offsetAndRotation(5.0f, 18.0f, 4.5f, 0.0f, 0.0f, -0.1047198f));
        root.addOrReplaceChild("LMLeg6", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(5.5f, 3.0f, -0.5f, 1, 3, 1), PartPose.offset(5.0f, 18.0f, 4.5f));
        return mesh;
    }

    @Override
    public void setupAnim(CaveFisher entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        float newangle = 0.0f;
        float upangle = 0.0f;
        float nextangle = 0.0f;
        float pi4 = 1.570795f;
        this.LFLeg1.yRot = newangle = Mth.cos((float)(ageInTicks * 2.0f * this.wingspeed)) * 3.1415927f * 0.12f * limbSwingAmount;
        this.LFLeg2.yRot = newangle;
        this.LFLeg3.yRot = newangle;
        this.LFLeg4.yRot = newangle;
        this.LFLeg5.yRot = newangle;
        this.LFLeg6.yRot = newangle;
        this.RFLeg1.yRot = - newangle;
        this.RFLeg2.yRot = - newangle;
        this.RFLeg3.yRot = - newangle;
        this.RFLeg4.yRot = - newangle;
        this.RFLeg5.yRot = - newangle;
        this.RFLeg6.yRot = - newangle;
        this.LMLeg1.yRot = newangle = Mth.cos((float)(ageInTicks * 2.0f * this.wingspeed - 1.0f * pi4)) * 3.1415927f * 0.12f * limbSwingAmount;
        this.LMLeg2.yRot = newangle;
        this.LMLeg3.yRot = newangle;
        this.LMLeg4.yRot = newangle;
        this.LMLeg5.yRot = newangle;
        this.LMLeg6.yRot = newangle;
        this.RMLeg1.yRot = - newangle;
        this.RMLeg2.yRot = - newangle;
        this.RMLeg3.yRot = - newangle;
        this.RMLeg4.yRot = - newangle;
        this.RMLeg5.yRot = - newangle;
        this.RMLeg6.yRot = - newangle;
        this.LBLeg1.yRot = newangle = Mth.cos((float)(ageInTicks * 2.0f * this.wingspeed - 2.0f * pi4)) * 3.1415927f * 0.12f * limbSwingAmount;
        this.LBLeg2.yRot = newangle;
        this.LBLeg3.yRot = newangle;
        this.LBLeg4.yRot = newangle;
        this.LBLeg5.yRot = newangle;
        this.LBLeg6.yRot = newangle;
        this.RBLeg1.yRot = - newangle;
        this.RBLeg2.yRot = - newangle;
        this.RBLeg3.yRot = - newangle;
        this.RBLeg4.yRot = - newangle;
        this.RBLeg5.yRot = - newangle;
        this.RBLeg6.yRot = - newangle;
        RenderInfo r = entity.getRenderInfo();
        newangle = Mth.cos(ageInTicks * 3.0f * this.wingspeed) * (float) Math.PI * 0.15f;
        nextangle = Mth.cos((ageInTicks + 0.1f) * 3.0f * this.wingspeed) * (float) Math.PI * 0.15f;
        if (nextangle > 0.0f && newangle < 0.0f) {
            r.ri1 = 0;
            if (entity.getAttacking() == 0) {
                r.ri1 = entity.getRandom().nextInt(20);
                r.ri2 = entity.getRandom().nextInt(25);
            } else {
                r.ri1 = entity.getRandom().nextInt(4);
                r.ri2 = entity.getRandom().nextInt(3);
            }
        }
        if (r.ri1 == 1 || r.ri1 == 3) {
            this.doLeftClaw(newangle);
            this.doRightClaw(newangle);
        } else {
            this.doLeftClaw(0.0f);
            this.doRightClaw(0.0f);
        }
        entity.setRenderInfo(r);
    }

    private void doLeftClaw(float angle) {
        float a = Math.abs(angle);
        this.LeftArmSeg1.xRot = a;
        this.LeftArmSeg2.xRot = a;
        this.LeftArmSeg3.xRot = a;
        this.LeftArmSeg4.xRot = a;
        this.LeftArmSeg5.xRot = a;
        this.LeftClawBase.xRot = a;
        this.LeftClawTop.xRot = a - 0.54f;
        this.LeftClawLow.xRot = a + 0.35f;
    }

    private void doRightClaw(float angle) {
        float a = Math.abs(angle);
        this.RightArmSeg1.xRot = a;
        this.RightArmSeg2.xRot = a;
        this.RightArmSeg3.xRot = a;
        this.RightArmSeg4.xRot = a;
        this.RightArmSeg5.xRot = a;
        this.RightClawBase.xRot = a;
        this.RightClawTop.xRot = a - 0.54f;
        this.RightClawLow.xRot = a + 0.35f;
    }

    @Override
    public void renderToBuffer(PoseStack poseStack, VertexConsumer buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        this.Nose.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.EyeLeft.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.HeadMid.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.HeadEnd.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.TailTuft.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.EyeRight.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.BodyTopLeft4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.BodyTopRight4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.BodyTopLeft1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.BodyTopRight1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.BodyTopRight2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.BodyTopLeft2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.BodyTopRight3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.BodyTopLeft3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.HeadBase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.TailBase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.BodyLow2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.BodyLow1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Spine5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Spine1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Spine2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Spine3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Spine4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightArmSeg4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftArmSeg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftArmSeg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightArmSeg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightArmSeg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftArmSeg5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftArmSeg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftClawTop.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightArmSeg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightArmSeg5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftArmSeg4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftClawBase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightClawBase.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftClawLow.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightClawTop.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightClawLow.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LBLeg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LBLeg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RBLeg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RBLeg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LBLeg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RBLeg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LBLeg4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RBLeg4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RBLeg5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LBLeg6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RBLeg6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LBLeg5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RFLeg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RFLeg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RFLeg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RFLeg4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RFLeg5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RFLeg6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RMLeg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RMLeg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RMLeg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RMLeg4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RMLeg5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RMLeg6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LFLeg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LFLeg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LFLeg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LFLeg4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LFLeg5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LFLeg6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LMLeg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LMLeg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LMLeg4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LMLeg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LMLeg5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LMLeg6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    }
}
