package com.astryxion.chaospersists.model;

import com.astryxion.chaospersists.entity.Hammerhead;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

public class ModelHammerhead extends EntityModel<Hammerhead> {
    private final float wingspeed;
    private final ModelPart chest;
    private final ModelPart abdomen;
    private final ModelPart neck;
    private final ModelPart head;
    private final ModelPart snout;
    private final ModelPart neck_armour;
    private final ModelPart horn_base;
    private final ModelPart horn_1;
    private final ModelPart horn_2;
    private final ModelPart horn_R;
    private final ModelPart horn_L;
    private final ModelPart back_armour1;
    private final ModelPart back_armour_2;
    private final ModelPart back_armour_3;
    private final ModelPart back_armour_3R;
    private final ModelPart back_armour_4;
    private final ModelPart back_armour_4R;
    private final ModelPart tail;
    private final ModelPart leg_1R;
    private final ModelPart leg_1;
    private final ModelPart leg_2;
    private final ModelPart leg_2R;
    private final ModelPart leg_3R;
    private final ModelPart leg_3;
    private final ModelPart leg_1Rb;
    private final ModelPart leg_1b;
    private final ModelPart leg_2b;
    private final ModelPart leg_2Rb;
    private final ModelPart leg_3Rb;
    private final ModelPart leg_3b;
    private final ModelPart fan1;
    private final ModelPart Lfan2;
    private final ModelPart Rfan2;
    private final ModelPart Lfan3;
    private final ModelPart Rfan3;
    private final ModelPart Lear;
    private final ModelPart Rear;
    public ModelHammerhead(float f1) {
        this(f1, LayerDefinition.create(createMesh(), 222, 256).bakeRoot());
    }
    public ModelHammerhead(float wingspeed, ModelPart root) {
        this.wingspeed = wingspeed;
        this.chest = root.getChild("chest");
        this.abdomen = root.getChild("abdomen");
        this.neck = root.getChild("neck");
        this.head = root.getChild("head");
        this.snout = root.getChild("snout");
        this.neck_armour = root.getChild("neck_armour");
        this.horn_base = root.getChild("horn_base");
        this.horn_1 = root.getChild("horn_1");
        this.horn_2 = root.getChild("horn_2");
        this.horn_R = root.getChild("horn_R");
        this.horn_L = root.getChild("horn_L");
        this.back_armour1 = root.getChild("back_armour1");
        this.back_armour_2 = root.getChild("back_armour_2");
        this.back_armour_3 = root.getChild("back_armour_3");
        this.back_armour_3R = root.getChild("back_armour_3R");
        this.back_armour_4 = root.getChild("back_armour_4");
        this.back_armour_4R = root.getChild("back_armour_4R");
        this.tail = root.getChild("tail");
        this.leg_1R = root.getChild("leg_1R");
        this.leg_1 = root.getChild("leg_1");
        this.leg_2 = root.getChild("leg_2");
        this.leg_2R = root.getChild("leg_2R");
        this.leg_3R = root.getChild("leg_3R");
        this.leg_3 = root.getChild("leg_3");
        this.leg_1Rb = root.getChild("leg_1Rb");
        this.leg_1b = root.getChild("leg_1b");
        this.leg_2b = root.getChild("leg_2b");
        this.leg_2Rb = root.getChild("leg_2Rb");
        this.leg_3Rb = root.getChild("leg_3Rb");
        this.leg_3b = root.getChild("leg_3b");
        this.fan1 = root.getChild("fan1");
        this.Lfan2 = root.getChild("Lfan2");
        this.Rfan2 = root.getChild("Rfan2");
        this.Lfan3 = root.getChild("Lfan3");
        this.Rfan3 = root.getChild("Rfan3");
        this.Lear = root.getChild("Lear");
        this.Rear = root.getChild("Rear");
    }

    public static MeshDefinition createMesh() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();
        partdefinition.addOrReplaceChild("chest", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-9.0f, -1.0f, 0.0f, 19, 16, 17), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, 0.0349066f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("abdomen", CubeListBuilder.create().texOffs(0, 34).mirror().addBox(-7.5f, 0.0f, 0.0f, 16, 14, 16), PartPose.offsetAndRotation(0.0f, -2.0f, 4.0f, -0.0349066f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(146, 59).mirror().addBox(-6.5f, -0.5f, -12.0f, 14, 13, 13), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, 0.1570796f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("head", CubeListBuilder.create().texOffs(101, 59).mirror().addBox(-6.0f, -0.5f, -21.0f, 13, 11, 9), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, 0.2094395f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("snout", CubeListBuilder.create().texOffs(166, 86).mirror().addBox(-4.0f, -6.0f, -27.0f, 9, 8, 8), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, 0.6108652f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("neck_armour", CubeListBuilder.create().texOffs(73, 0).mirror().addBox(-7.0f, -1.5f, -18.0f, 15, 4, 18), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, 0.1570796f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("horn_base", CubeListBuilder.create().texOffs(49, 35).mirror().addBox(-7.0f, -1.5f, -27.0f, 15, 5, 9), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, 0.0872665f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("horn_1", CubeListBuilder.create().texOffs(122, 23).mirror().addBox(-12.0f, -4.5f, -40.0f, 25, 6, 14), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, 0.1919862f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("horn_2", CubeListBuilder.create().texOffs(106, 44).mirror().addBox(-18.0f, -3.5f, -37.0f, 37, 4, 10), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, 0.1919862f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("horn_R", CubeListBuilder.create().texOffs(158, 0).mirror().addBox(-26.0f, -5.5f, -38.5f, 8, 7, 13), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, 0.1919862f, 0.0f, -0.0174533f));
        partdefinition.addOrReplaceChild("horn_L", CubeListBuilder.create().texOffs(158, 0).mirror().addBox(19.0f, -5.5f, -38.5f, 8, 7, 13), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, 0.1919862f, 0.0f, -0.0174533f));
        partdefinition.addOrReplaceChild("back_armour1", CubeListBuilder.create().texOffs(0, 98).mirror().addBox(-5.0f, -2.5f, -6.0f, 9, 3, 7), PartPose.offsetAndRotation(1.0f, -4.0f, -15.0f, -0.0872665f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("back_armour_2", CubeListBuilder.create().texOffs(0, 65).mirror().addBox(-8.0f, -4.5f, -13.0f, 17, 4, 28), PartPose.offsetAndRotation(0.0f, -1.0f, -3.0f, -0.122173f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("back_armour_3", CubeListBuilder.create().texOffs(15, 104).mirror().addBox(0.5f, -3.5f, -13.0f, 4, 4, 20), PartPose.offsetAndRotation(8.0f, 1.0f, -2.0f, 0.0174533f, 0.1570796f, 0.0f));
        partdefinition.addOrReplaceChild("back_armour_3R", CubeListBuilder.create().texOffs(15, 104).mirror().addBox(-3.5f, -3.5f, -13.0f, 4, 4, 20), PartPose.offsetAndRotation(-8.0f, 1.0f, -2.0f, 0.0174533f, -0.1570796f, 0.0f));
        partdefinition.addOrReplaceChild("back_armour_4", CubeListBuilder.create().texOffs(0, 65).mirror().addBox(1.5f, -1.5f, -3.0f, 3, 4, 10), PartPose.offsetAndRotation(6.0f, 5.0f, -10.0f, -0.1396263f, 0.3490659f, 0.0f));
        partdefinition.addOrReplaceChild("back_armour_4R", CubeListBuilder.create().texOffs(0, 65).mirror().addBox(-1.5f, -1.5f, -3.0f, 3, 4, 10), PartPose.offsetAndRotation(-8.0f, 5.0f, -11.0f, -0.1396263f, -0.3490659f, 0.0f));
        partdefinition.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(66, 52).mirror().addBox(-2.0f, 0.0f, -3.0f, 5, 5, 3), PartPose.offsetAndRotation(0.0f, 0.0f, 20.0f, 0.5061455f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leg_1R", CubeListBuilder.create().texOffs(71, 102).mirror().addBox(-2.5f, -2.5f, -3.0f, 5, 10, 6), PartPose.offsetAndRotation(-9.0f, 11.0f, -10.0f, -0.0872665f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leg_1", CubeListBuilder.create().texOffs(64, 76).mirror().addBox(-1.5f, -2.5f, -3.0f, 5, 10, 6), PartPose.offsetAndRotation(9.0f, 11.0f, -10.0f, -0.0872665f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leg_2", CubeListBuilder.create().texOffs(98, 28).mirror().addBox(-1.5f, -2.5f, -3.0f, 5, 9, 6), PartPose.offsetAndRotation(9.0f, 12.0f, -2.0f, -0.0523599f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leg_2R", CubeListBuilder.create().texOffs(98, 80).mirror().addBox(-1.5f, -2.5f, -3.0f, 5, 9, 6), PartPose.offsetAndRotation(-10.0f, 12.0f, -2.0f, -0.0523599f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leg_3R", CubeListBuilder.create().texOffs(44, 129).mirror().addBox(-3.5f, -2.5f, -3.0f, 5, 11, 8), PartPose.offsetAndRotation(-7.0f, 9.0f, 14.0f, -0.3490659f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leg_3", CubeListBuilder.create().texOffs(44, 99).mirror().addBox(-3.5f, -2.5f, -3.0f, 5, 11, 8), PartPose.offsetAndRotation(10.0f, 9.0f, 14.0f, -0.3490659f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leg_1Rb", CubeListBuilder.create().texOffs(15, 129).mirror().addBox(-2.0f, 5.5f, -3.0f, 4, 8, 5), PartPose.offsetAndRotation(-9.0f, 11.0f, -10.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leg_1b", CubeListBuilder.create().texOffs(15, 110).mirror().addBox(-1.0f, 5.5f, -3.0f, 4, 8, 5), PartPose.offsetAndRotation(9.0f, 11.0f, -10.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leg_2b", CubeListBuilder.create().texOffs(57, 1).mirror().addBox(-1.0f, 5.5f, -3.0f, 4, 7, 5), PartPose.offsetAndRotation(9.0f, 12.0f, -2.0f, 0.0523599f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leg_2Rb", CubeListBuilder.create().texOffs(94, 106).mirror().addBox(-2.0f, 5.5f, -3.0f, 4, 7, 5), PartPose.offsetAndRotation(-9.0f, 12.0f, -2.0f, 0.0523599f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leg_3Rb", CubeListBuilder.create().texOffs(122, 81).mirror().addBox(-2.0f, 6.5f, -5.0f, 4, 9, 5), PartPose.offsetAndRotation(-8.0f, 9.0f, 14.0f, 0.122173f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leg_3b", CubeListBuilder.create().texOffs(122, 0).mirror().addBox(-3.0f, 6.5f, -5.0f, 4, 9, 5), PartPose.offsetAndRotation(10.0f, 9.0f, 14.0f, 0.122173f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("fan1", CubeListBuilder.create().texOffs(0, 109).mirror().addBox(-1.0f, -7.0f, -34.0f, 4, 15, 1), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, -0.1396263f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Lfan2", CubeListBuilder.create().texOffs(0, 109).mirror().addBox(-1.0f, -3.0f, -31.5f, 4, 12, 1), PartPose.offsetAndRotation(0.0f, -1.0f, -14.0f, -0.2094395f, -0.122173f, 0.0f));
        partdefinition.addOrReplaceChild("Rfan2", CubeListBuilder.create().texOffs(0, 109).mirror().addBox(-1.0f, -3.0f, -33.5f, 4, 12, 1), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, -0.2094395f, 0.122173f, 0.0f));
        partdefinition.addOrReplaceChild("Lfan3", CubeListBuilder.create().texOffs(0, 109).mirror().addBox(-1.0f, 4.0f, -32.0f, 4, 9, 1), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, -0.3316126f, -0.2268928f, 0.0f));
        partdefinition.addOrReplaceChild("Rfan3", CubeListBuilder.create().texOffs(0, 109).mirror().addBox(-1.0f, 4.0f, -32.0f, 4, 9, 1), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, -0.3316126f, 0.2443461f, 0.0f));
        partdefinition.addOrReplaceChild("Lear", CubeListBuilder.create().texOffs(0, 80).mirror().addBox(8.5f, 2.5f, -10.0f, 1, 1, 10), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, 0.3665191f, 0.2268928f, 0.0f));
        partdefinition.addOrReplaceChild("Rear", CubeListBuilder.create().texOffs(0, 80).mirror().addBox(-8.5f, 2.5f, -11.0f, 1, 1, 10), PartPose.offsetAndRotation(0.0f, -1.0f, -12.0f, 0.3665191f, -0.2268928f, 0.0f));
        return meshdefinition;
    }
    @Override
    public void setupAnim(Hammerhead entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {

        Hammerhead e = entity;
                float newangle = 0.0f;
        float newangle2 = 0.0f;
        if (limbSwingAmount > 0.1f) {
            newangle = Mth.cos((float)(ageInTicks * 1.3f * this.wingspeed)) * 3.1415927f * 0.1f * limbSwingAmount;
            newangle2 = Mth.cos((float)((float)((double)(ageInTicks * 1.3f * this.wingspeed) + 0.7853981633974483))) * 3.1415927f * 0.1f * limbSwingAmount;
        } else {
            newangle = 0.0f;
        }
        this.leg_1.xRot = -0.087f + newangle;
        this.leg_1b.xRot = newangle;
        this.leg_1R.xRot = -0.087f - newangle;
        this.leg_1Rb.xRot = - newangle;
        this.leg_2.xRot = -0.052f + newangle2;
        this.leg_2b.xRot = newangle2;
        this.leg_2R.xRot = -0.052f - newangle2;
        this.leg_2Rb.xRot = - newangle2;
        this.leg_3.xRot = -0.349f - newangle;
        this.leg_3b.xRot = - newangle;
        this.leg_3R.xRot = -0.349f + newangle;
        this.leg_3Rb.xRot = newangle;
        this.neck_armour.yRot = this.neck.yRot = (float)Math.toRadians(netHeadYaw) * 0.25f;
        this.horn_base.yRot = this.neck.yRot;
        this.horn_1.yRot = this.neck.yRot;
        this.horn_2.yRot = this.neck.yRot;
        this.horn_L.yRot = this.neck.yRot;
        this.horn_R.yRot = this.neck.yRot;
        this.head.yRot = this.neck.yRot;
        this.snout.yRot = this.neck.yRot;
        this.fan1.yRot = this.neck.yRot;
        this.Lfan2.yRot = this.neck.yRot - 0.122f;
        this.Lfan3.yRot = this.neck.yRot - 0.226f;
        this.Rfan2.yRot = this.neck.yRot + 0.122f;
        this.Rfan3.yRot = this.neck.yRot + 0.226f;
        this.Lear.yRot = this.neck.yRot + 0.227f;
        this.Rear.yRot = this.neck.yRot - 0.227f;
        newangle = Mth.cos((float)(ageInTicks * 0.3f * this.wingspeed)) * 3.1415927f * 0.03f;
        this.back_armour_4.yRot = 0.349f + newangle;
        this.back_armour_4R.yRot = -0.349f - newangle;
        newangle = e.getAttacking() != 0 ? Mth.cos((float)(ageInTicks * 1.3f * this.wingspeed)) * 3.1415927f * 0.13f : 0.0f;
        this.neck.xRot = newangle + 0.157f;
        this.neck_armour.xRot = newangle + 0.157f;
        this.horn_base.xRot = newangle + 0.087f;
        this.horn_1.xRot = newangle + 0.192f;
        this.horn_2.xRot = newangle + 0.192f;
        this.horn_L.xRot = newangle + 0.192f;
        this.horn_R.xRot = newangle + 0.192f;
        this.head.xRot = newangle + 0.209f;
        this.snout.xRot = newangle + 0.611f;
        this.fan1.xRot = newangle - 0.139f;
        this.Lfan2.xRot = newangle - 0.209f;
        this.Lfan3.xRot = newangle - 0.331f;
        this.Rfan2.xRot = newangle - 0.209f;
        this.Rfan3.xRot = newangle - 0.331f;
        this.Lear.xRot = newangle + 0.366f;
        this.Rear.xRot = newangle + 0.366f;
    }

    public void renderToBuffer(PoseStack poseStack, VertexConsumer buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        this.chest.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.abdomen.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.snout.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck_armour.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.horn_base.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.horn_1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.horn_2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.horn_R.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.horn_L.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.back_armour1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.back_armour_2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.back_armour_3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.back_armour_3R.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.back_armour_4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.back_armour_4R.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg_1R.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg_1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg_2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg_2R.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg_3R.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg_3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg_1Rb.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg_1b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg_2b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg_2Rb.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg_3Rb.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg_3b.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.fan1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lfan2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Rfan2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lfan3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Rfan3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lear.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Rear.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    }
}
