package com.astryxion.chaospersists.model;

import com.astryxion.chaospersists.entity.Baryonyx;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

public class ModelBaryonyx extends EntityModel<Baryonyx> {
    private final float wingspeed;
    private final ModelPart Shape27;
    private final ModelPart Shape28;
    private final ModelPart Shape29;
    private final ModelPart Shape30;
    private final ModelPart Shape31;
    private final ModelPart Shape32;
    private final ModelPart Shape33;
    private final ModelPart Shape34;
    private final ModelPart Shape35;
    private final ModelPart Shape36;
    private final ModelPart Shape37;
    private final ModelPart Shape38;
    private final ModelPart Shape39;
    private final ModelPart Shape40;
    private final ModelPart Shape41;
    private final ModelPart Shape42;
    private final ModelPart Shape43;
    private final ModelPart Shape44;
    private final ModelPart Shape45;
    private final ModelPart Shape46;
    private final ModelPart Shape47;
    private final ModelPart Shape48;
    private final ModelPart Shape49;
    private final ModelPart Shape50;
    private final ModelPart Shape51;
    private final ModelPart Shape1;
    private final ModelPart Shape2;
    private final ModelPart Shape3;
    private final ModelPart Shape4;
    private final ModelPart Shape5;
    private final ModelPart Shape6;
    private final ModelPart Shape7;
    private final ModelPart Shape8;
    private final ModelPart Shape9;
    private final ModelPart Shape10;
    private final ModelPart Shape11;
    private final ModelPart Shape12;
    private final ModelPart Shape13;
    private final ModelPart Shape14;
    private final ModelPart Shape15;
    private final ModelPart Shape16;
    private final ModelPart Shape17;
    private final ModelPart Shape18;
    private final ModelPart Shape19;
    private final ModelPart Shape20;
    private final ModelPart Shape21;
    private final ModelPart Shape22;
    private final ModelPart Shape23;
    private final ModelPart Shape24;
    private final ModelPart Shape25;
    private final ModelPart Shape26;
    private final ModelPart Shape52;

    public ModelBaryonyx(float wingspeed) {
        this(LayerDefinition.create(createMesh(), 128, 128).bakeRoot(), wingspeed);
    }

    public ModelBaryonyx(ModelPart root, float wingspeed) {
        this.wingspeed = wingspeed;
        this.Shape27 = root.getChild("Shape27");
        this.Shape28 = root.getChild("Shape28");
        this.Shape29 = root.getChild("Shape29");
        this.Shape30 = root.getChild("Shape30");
        this.Shape31 = root.getChild("Shape31");
        this.Shape32 = root.getChild("Shape32");
        this.Shape33 = root.getChild("Shape33");
        this.Shape34 = root.getChild("Shape34");
        this.Shape35 = root.getChild("Shape35");
        this.Shape36 = root.getChild("Shape36");
        this.Shape37 = root.getChild("Shape37");
        this.Shape38 = root.getChild("Shape38");
        this.Shape39 = root.getChild("Shape39");
        this.Shape40 = root.getChild("Shape40");
        this.Shape41 = root.getChild("Shape41");
        this.Shape42 = root.getChild("Shape42");
        this.Shape43 = root.getChild("Shape43");
        this.Shape44 = root.getChild("Shape44");
        this.Shape45 = root.getChild("Shape45");
        this.Shape46 = root.getChild("Shape46");
        this.Shape47 = root.getChild("Shape47");
        this.Shape48 = root.getChild("Shape48");
        this.Shape49 = root.getChild("Shape49");
        this.Shape50 = root.getChild("Shape50");
        this.Shape51 = root.getChild("Shape51");
        this.Shape1 = root.getChild("Shape1");
        this.Shape2 = root.getChild("Shape2");
        this.Shape3 = root.getChild("Shape3");
        this.Shape4 = root.getChild("Shape4");
        this.Shape5 = root.getChild("Shape5");
        this.Shape6 = root.getChild("Shape6");
        this.Shape7 = root.getChild("Shape7");
        this.Shape8 = root.getChild("Shape8");
        this.Shape9 = root.getChild("Shape9");
        this.Shape10 = root.getChild("Shape10");
        this.Shape11 = root.getChild("Shape11");
        this.Shape12 = root.getChild("Shape12");
        this.Shape13 = root.getChild("Shape13");
        this.Shape14 = root.getChild("Shape14");
        this.Shape15 = root.getChild("Shape15");
        this.Shape16 = root.getChild("Shape16");
        this.Shape17 = root.getChild("Shape17");
        this.Shape18 = root.getChild("Shape18");
        this.Shape19 = root.getChild("Shape19");
        this.Shape20 = root.getChild("Shape20");
        this.Shape21 = root.getChild("Shape21");
        this.Shape22 = root.getChild("Shape22");
        this.Shape23 = root.getChild("Shape23");
        this.Shape24 = root.getChild("Shape24");
        this.Shape25 = root.getChild("Shape25");
        this.Shape26 = root.getChild("Shape26");
        this.Shape52 = root.getChild("Shape52");
    }

    private static MeshDefinition createMesh() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("Shape27", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, -10.0f));
        root.addOrReplaceChild("Shape28", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, -7.0f));
        root.addOrReplaceChild("Shape29", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, -4.0f));
        root.addOrReplaceChild("Shape30", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, -1.0f));
        root.addOrReplaceChild("Shape31", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 2.0f));
        root.addOrReplaceChild("Shape32", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 5.0f));
        root.addOrReplaceChild("Shape33", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 8.0f));
        root.addOrReplaceChild("Shape34", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 11.0f));
        root.addOrReplaceChild("Shape35", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 14.0f));
        root.addOrReplaceChild("Shape36", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 17.0f));
        root.addOrReplaceChild("Shape37", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 20.0f));
        root.addOrReplaceChild("Shape38", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 23.0f));
        root.addOrReplaceChild("Shape39", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 26.0f));
        root.addOrReplaceChild("Shape40", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 29.0f));
        root.addOrReplaceChild("Shape41", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 32.0f));
        root.addOrReplaceChild("Shape42", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 35.0f));
        root.addOrReplaceChild("Shape43", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 38.0f));
        root.addOrReplaceChild("Shape44", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 41.0f));
        root.addOrReplaceChild("Shape45", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -17.0f, 44.0f));
        root.addOrReplaceChild("Shape46", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -12.0f, -11.0f));
        root.addOrReplaceChild("Shape47", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -13.0f, -13.0f));
        root.addOrReplaceChild("Shape48", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -15.0f, -15.0f));
        root.addOrReplaceChild("Shape49", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 1), PartPose.offset(0.0f, -16.0f, -16.0f));
        root.addOrReplaceChild("Shape50", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 1, 1), PartPose.offset(0.0f, -19.0f, -17.0f));
        root.addOrReplaceChild("Shape51", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 0, 1, 1), PartPose.offset(0.0f, -19.0f, -19.0f));
        root.addOrReplaceChild("Shape1", CubeListBuilder.create().texOffs(0, 0).addBox(0.0f, 0.0f, 0.0f, 10, 17, 25), PartPose.offset(-5.0f, -15.0f, -10.0f));
        root.addOrReplaceChild("Shape2", CubeListBuilder.create().texOffs(0, 93).addBox(-3.0f, 0.0f, -11.0f, 6, 10, 11), PartPose.offsetAndRotation(0.0f, -10.0f, -6.0f, -0.1919862f, 0.0f, 0.0f));
        root.addOrReplaceChild("Shape3", CubeListBuilder.create().texOffs(29, 110).addBox(-2.0f, -9.0f, -8.0f, 4, 9, 8), PartPose.offsetAndRotation(0.0f, -10.0f, -11.0f, 0.7504916f, 0.0f, 0.0f));
        root.addOrReplaceChild("Shape4", CubeListBuilder.create().texOffs(54, 108).addBox(0.0f, 0.0f, 0.0f, 6, 7, 12), PartPose.offset(-3.0f, -18.0f, -28.0f));
        root.addOrReplaceChild("Shape5", CubeListBuilder.create().texOffs(54, 86).addBox(0.0f, 0.0f, 0.0f, 3, 6, 15), PartPose.offset(-1.5f, -17.5f, -43.0f));
        root.addOrReplaceChild("Shape6", CubeListBuilder.create().texOffs(0, 43).addBox(0.0f, 0.0f, 0.0f, 8, 11, 8), PartPose.offset(-4.0f, -15.0f, 15.0f));
        root.addOrReplaceChild("Shape7", CubeListBuilder.create().texOffs(0, 63).addBox(0.0f, 0.0f, 0.0f, 6, 6, 23), PartPose.offset(-3.0f, -15.0f, 23.0f));
        root.addOrReplaceChild("Shape8", CubeListBuilder.create().texOffs(47, 0).addBox(0.0f, 0.0f, 0.0f, 2, 5, 3), PartPose.offset(5.0f, 0.0f, -7.0f));
        root.addOrReplaceChild("Shape9", CubeListBuilder.create().texOffs(49, 10).addBox(0.0f, 0.0f, 0.0f, 2, 6, 2), PartPose.offsetAndRotation(5.1f, 3.0f, -6.0f, -0.3839724f, 0.0f, 0.0f));
        root.addOrReplaceChild("Shape10", CubeListBuilder.create().texOffs(13, 17).addBox(0.0f, 0.0f, 0.0f, 2, 4, 3), PartPose.offset(5.0f, 7.0f, -8.0f));
        root.addOrReplaceChild("Shape11", CubeListBuilder.create().texOffs(0, 17).addBox(0.0f, 0.0f, -2.0f, 1, 1, 2), PartPose.offset(5.0f, 8.0f, -8.0f));
        root.addOrReplaceChild("Shape12", CubeListBuilder.create().texOffs(0, 21).addBox(0.0f, 0.0f, 0.0f, 1, 1, 1), PartPose.offset(5.0f, 9.0f, -11.0f));
        root.addOrReplaceChild("Shape13", CubeListBuilder.create().texOffs(95, 36).addBox(0.0f, 0.0f, 0.0f, 3, 21, 13), PartPose.offset(5.0f, -15.0f, 2.0f));
        root.addOrReplaceChild("Shape14", CubeListBuilder.create().texOffs(36, 94).addBox(0.0f, 0.0f, -3.0f, 3, 5, 3), PartPose.offset(-1.5f, -17.0f, -43.0f));
        root.addOrReplaceChild("Shape15", CubeListBuilder.create().texOffs(113, 71).addBox(0.0f, 18.0f, 8.0f, 3, 18, 4), PartPose.offsetAndRotation(5.0f, -15.0f, 2.0f, -0.1745329f, 0.0f, 0.0f));
        root.addOrReplaceChild("Shape16", CubeListBuilder.create().texOffs(13, 11).addBox(-2.0f, 0.0f, 0.0f, 2, 1, 3), PartPose.offset(5.0f, 10.0f, -8.0f));
        root.addOrReplaceChild("Shape17", CubeListBuilder.create().texOffs(0, 74).addBox(0.0f, 35.0f, -1.0f, 3, 3, 6), PartPose.offset(5.0f, -15.0f, 2.0f));
        root.addOrReplaceChild("Shape18", CubeListBuilder.create().texOffs(58, 0).addBox(-2.0f, 0.0f, 0.0f, 2, 5, 3), PartPose.offset(-5.0f, 0.0f, -7.0f));
        root.addOrReplaceChild("Shape19", CubeListBuilder.create().texOffs(59, 10).addBox(-2.0f, 0.0f, 0.0f, 2, 6, 2), PartPose.offsetAndRotation(-5.1f, 3.0f, -6.0f, -0.3839724f, 0.0f, 0.0f));
        root.addOrReplaceChild("Shape20", CubeListBuilder.create().texOffs(71, 5).addBox(-2.0f, 0.0f, 0.0f, 2, 4, 3), PartPose.offset(-5.0f, 7.0f, -8.0f));
        root.addOrReplaceChild("Shape21", CubeListBuilder.create().texOffs(71, 0).addBox(0.0f, 0.0f, 0.0f, 2, 1, 3), PartPose.offset(-5.0f, 10.0f, -8.0f));
        root.addOrReplaceChild("Shape22", CubeListBuilder.create().texOffs(0, 10).addBox(-1.0f, 0.0f, -2.0f, 1, 1, 2), PartPose.offset(-5.0f, 8.0f, -8.0f));
        root.addOrReplaceChild("Shape23", CubeListBuilder.create().texOffs(0, 14).addBox(-1.0f, 0.0f, 0.0f, 1, 1, 1), PartPose.offset(-5.0f, 9.0f, -11.0f));
        root.addOrReplaceChild("Shape24", CubeListBuilder.create().texOffs(95, 0).addBox(-3.0f, 0.0f, 0.0f, 3, 22, 13), PartPose.offset(-5.0f, -15.0f, 2.0f));
        root.addOrReplaceChild("Shape25", CubeListBuilder.create().texOffs(96, 71).addBox(-3.0f, 18.0f, 8.0f, 3, 18, 4), PartPose.offsetAndRotation(-5.0f, -15.0f, 2.0f, -0.1745329f, 0.0f, 0.0f));
        root.addOrReplaceChild("Shape26", CubeListBuilder.create().texOffs(0, 64).addBox(-3.0f, 35.0f, -1.0f, 3, 3, 6), PartPose.offset(-5.0f, -15.0f, 2.0f));
        root.addOrReplaceChild("Shape52", CubeListBuilder.create().texOffs(9, 0).addBox(0.0f, 0.0f, 0.0f, 0, 2, 2), PartPose.offset(0.0f, -19.0f, -30.0f));
        return mesh;
    }

    @Override
    public void setupAnim(Baryonyx entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        float newangle = 0.0f;
        newangle = (double)limbSwingAmount > 0.1 ? Mth.cos((float)(ageInTicks * 1.3f * this.wingspeed)) * 3.1415927f * 0.15f * limbSwingAmount : 0.0f;
        this.Shape24.xRot = newangle;
        this.Shape25.xRot = -0.17f + newangle;
        this.Shape26.xRot = newangle;
        this.Shape13.xRot = - newangle;
        this.Shape15.xRot = -0.17f - newangle;
        this.Shape17.xRot = - newangle;
        this.Shape21.zRot = newangle = Mth.cos((float)(ageInTicks * 0.7f * this.wingspeed)) * 3.1415927f * 0.25f;
        this.Shape16.zRot = - newangle;
    }

    @Override
    public void renderToBuffer(PoseStack poseStack, VertexConsumer buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        this.Shape27.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape28.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape29.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape30.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape31.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape32.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape33.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape34.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape35.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape36.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape37.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape38.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape39.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape40.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape41.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape42.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape43.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape44.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape45.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape46.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape47.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape48.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape49.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape50.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape51.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape8.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape9.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape10.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape11.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape12.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape13.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape14.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape15.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape16.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape17.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape18.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape19.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape20.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape21.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape22.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape23.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape24.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape25.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape26.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Shape52.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    }
}
