package com.astryxion.chaospersists.model;

import com.astryxion.chaospersists.entity.ThePrinceTeen;
import com.astryxion.chaospersists.render.RenderInfo;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

public class ModelThePrinceTeen extends EntityModel<ThePrinceTeen> {
    private final float wingspeed;
    private ThePrinceTeen animEntity;
    private float animAgeInTicks;
    private float animLimbSwingAmount;
    private float animNetHeadYaw;
    private float animHeadPitch;
    private final ModelPart body;
    private final ModelPart leftleg1;
    private final ModelPart tail1;
    private final ModelPart leftleg2;
    private final ModelPart body2;
    private final ModelPart leftleg3;
    private final ModelPart tail2;
    private final ModelPart tail3;
    private final ModelPart lclaw2;
    private final ModelPart lclaw4;
    private final ModelPart lclaw5;
    private final ModelPart lclaw6;
    private final ModelPart lclaw7;
    private final ModelPart tail4;
    private final ModelPart tail5;
    private final ModelPart neck1;
    private final ModelPart neck3;
    private final ModelPart head3;
    private final ModelPart jaw1;
    private final ModelPart jaw5;
    private final ModelPart head7;
    private final ModelPart rightleg1;
    private final ModelPart rightleg2;
    private final ModelPart rightleg3;
    private final ModelPart rclaw2;
    private final ModelPart rclaw4;
    private final ModelPart rclaw5;
    private final ModelPart rclaw7;
    private final ModelPart rclaw6;
    private final ModelPart wing1;
    private final ModelPart wing2;
    private final ModelPart mem1;
    private final ModelPart mem2;
    private final ModelPart lshoulder;
    private final ModelPart rshoulder;
    private final ModelPart rwing1;
    private final ModelPart rmem1;
    private final ModelPart rwing2;
    private final ModelPart rmem2;
    private final ModelPart neck4;
    private final ModelPart neck5;
    private final ModelPart wing3;
    private final ModelPart mem3;
    private final ModelPart rwing3;
    private final ModelPart rmem3;
    private final ModelPart wing4;
    private final ModelPart mem4;
    private final ModelPart rwing4;
    private final ModelPart rmem4;
    private final ModelPart Tailspike1;
    private final ModelPart Tailspike2;
    private final ModelPart Tailspike3;
    private final ModelPart headfin;
    private final ModelPart backfin1;
    private final ModelPart backfin2;
    private final ModelPart neck3L;
    private final ModelPart neck4L;
    private final ModelPart neck3R;
    private final ModelPart neck4R;
    private final ModelPart neck5L;
    private final ModelPart neck5R;
    private final ModelPart jaw5L;
    private final ModelPart jaw5R;
    private final ModelPart head7L;
    private final ModelPart headfinL;
    private final ModelPart headfinR;
    private final ModelPart head7R;
    private final ModelPart jaw1L;
    private final ModelPart jaw1R;
    private final ModelPart head3L;
    private final ModelPart head3R;
    public ModelThePrinceTeen(float f1) {
        this(f1, LayerDefinition.create(createMesh(), 512, 256).bakeRoot());
    }

    public ModelThePrinceTeen(float wingspeed, ModelPart root) {
        this.wingspeed = wingspeed;
        this.body = root.getChild("body");
        this.leftleg1 = root.getChild("leftleg1");
        this.tail1 = root.getChild("tail1");
        this.leftleg2 = root.getChild("leftleg2");
        this.body2 = root.getChild("body2");
        this.leftleg3 = root.getChild("leftleg3");
        this.tail2 = root.getChild("tail2");
        this.tail3 = root.getChild("tail3");
        this.lclaw2 = root.getChild("lclaw2");
        this.lclaw4 = root.getChild("lclaw4");
        this.lclaw5 = root.getChild("lclaw5");
        this.lclaw6 = root.getChild("lclaw6");
        this.lclaw7 = root.getChild("lclaw7");
        this.tail4 = root.getChild("tail4");
        this.tail5 = root.getChild("tail5");
        this.neck1 = root.getChild("neck1");
        this.neck3 = root.getChild("neck3");
        this.head3 = root.getChild("head3");
        this.jaw1 = root.getChild("jaw1");
        this.jaw5 = root.getChild("jaw5");
        this.head7 = root.getChild("head7");
        this.rightleg1 = root.getChild("rightleg1");
        this.rightleg2 = root.getChild("rightleg2");
        this.rightleg3 = root.getChild("rightleg3");
        this.rclaw2 = root.getChild("rclaw2");
        this.rclaw4 = root.getChild("rclaw4");
        this.rclaw5 = root.getChild("rclaw5");
        this.rclaw7 = root.getChild("rclaw7");
        this.rclaw6 = root.getChild("rclaw6");
        this.wing1 = root.getChild("wing1");
        this.wing2 = root.getChild("wing2");
        this.mem1 = root.getChild("mem1");
        this.mem2 = root.getChild("mem2");
        this.lshoulder = root.getChild("lshoulder");
        this.rshoulder = root.getChild("rshoulder");
        this.rwing1 = root.getChild("rwing1");
        this.rmem1 = root.getChild("rmem1");
        this.rwing2 = root.getChild("rwing2");
        this.rmem2 = root.getChild("rmem2");
        this.neck4 = root.getChild("neck4");
        this.neck5 = root.getChild("neck5");
        this.wing3 = root.getChild("wing3");
        this.mem3 = root.getChild("mem3");
        this.rwing3 = root.getChild("rwing3");
        this.rmem3 = root.getChild("rmem3");
        this.wing4 = root.getChild("wing4");
        this.mem4 = root.getChild("mem4");
        this.rwing4 = root.getChild("rwing4");
        this.rmem4 = root.getChild("rmem4");
        this.Tailspike1 = root.getChild("Tailspike1");
        this.Tailspike2 = root.getChild("Tailspike2");
        this.Tailspike3 = root.getChild("Tailspike3");
        this.headfin = root.getChild("headfin");
        this.backfin1 = root.getChild("backfin1");
        this.backfin2 = root.getChild("backfin2");
        this.neck3L = root.getChild("neck3L");
        this.neck4L = root.getChild("neck4L");
        this.neck3R = root.getChild("neck3R");
        this.neck4R = root.getChild("neck4R");
        this.neck5L = root.getChild("neck5L");
        this.neck5R = root.getChild("neck5R");
        this.jaw5L = root.getChild("jaw5L");
        this.jaw5R = root.getChild("jaw5R");
        this.head7L = root.getChild("head7L");
        this.headfinL = root.getChild("headfinL");
        this.headfinR = root.getChild("headfinR");
        this.head7R = root.getChild("head7R");
        this.jaw1L = root.getChild("jaw1L");
        this.jaw1R = root.getChild("jaw1R");
        this.head3L = root.getChild("head3L");
        this.head3R = root.getChild("head3R");
    }
    public static MeshDefinition createMesh() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();
        partdefinition.addOrReplaceChild("body", CubeListBuilder.create().texOffs(400, 26).mirror().addBox(-12.5f, -12.0f, -9.0f, 25, 12, 9), PartPose.offsetAndRotation(0.0f, 0.0f, 9.0f, 0.0698132f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leftleg1", CubeListBuilder.create().texOffs(300, 10).mirror().addBox(-1.0f, -1.0f, -3.0f, 5, 9, 9), PartPose.offsetAndRotation(14.0f, -8.0f, 13.0f, -0.5759587f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(400, 82).mirror().addBox(-9.0f, -6.0f, 0.0f, 18, 10, 12), PartPose.offsetAndRotation(0.0f, -3.0f, 22.0f, -0.1745329f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leftleg2", CubeListBuilder.create().texOffs(300, 31).mirror().addBox(-1.0f, 6.0f, -7.0f, 4, 12, 5), PartPose.offsetAndRotation(14.0f, -8.0f, 13.0f, 0.9773844f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("body2", CubeListBuilder.create().texOffs(400, 50).mirror().addBox(0.0f, -3.0f, -3.0f, 26, 14, 16), PartPose.offsetAndRotation(-13.0f, -9.0f, 10.0f, -0.1047198f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("leftleg3", CubeListBuilder.create().texOffs(300, 51).mirror().addBox(-1.0f, -1.0f, -2.0f, 3, 19, 4), PartPose.offsetAndRotation(14.0f, 7.0f, 22.0f, -0.5235988f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(400, 106).mirror().addBox(-5.0f, -4.0f, 0.0f, 10, 7, 10), PartPose.offsetAndRotation(0.0f, -2.0f, 33.0f, -0.1396263f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(400, 126).mirror().addBox(-3.0f, -2.0f, 0.0f, 6, 5, 10), PartPose.offsetAndRotation(0.0f, -2.0f, 42.0f, -0.1396263f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lclaw2", CubeListBuilder.create().texOffs(300, 76).mirror().addBox(-3.0f, 0.0f, -3.0f, 7, 3, 8), PartPose.offsetAndRotation(14.0f, 21.0f, 13.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lclaw4", CubeListBuilder.create().texOffs(310, 123).mirror().addBox(0.0f, 1.0f, -7.0f, 1, 2, 4), PartPose.offsetAndRotation(14.0f, 21.0f, 13.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lclaw5", CubeListBuilder.create().texOffs(297, 123).mirror().addBox(-2.5f, 1.0f, -7.0f, 1, 2, 4), PartPose.offsetAndRotation(14.0f, 21.0f, 13.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lclaw6", CubeListBuilder.create().texOffs(322, 123).mirror().addBox(2.5f, 1.0f, -7.0f, 1, 2, 4), PartPose.offsetAndRotation(14.0f, 21.0f, 13.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lclaw7", CubeListBuilder.create().texOffs(334, 123).mirror().addBox(0.0f, 1.0f, 5.0f, 1, 2, 3), PartPose.offsetAndRotation(14.0f, 21.0f, 13.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("tail4", CubeListBuilder.create().texOffs(400, 143).mirror().addBox(-2.0f, -2.0f, 0.0f, 4, 4, 10), PartPose.offsetAndRotation(0.0f, 0.0f, 51.0f, -0.1396263f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("tail5", CubeListBuilder.create().texOffs(400, 159).mirror().addBox(-1.5f, -2.0f, 0.0f, 3, 3, 10), PartPose.offsetAndRotation(0.0f, 2.0f, 59.0f, -0.1396263f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("neck1", CubeListBuilder.create().texOffs(400, 7).mirror().addBox(-12.0f, -4.0f, 0.0f, 24, 8, 8), PartPose.offsetAndRotation(0.0f, -7.0f, -5.0f, 0.0872665f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("neck3", CubeListBuilder.create().texOffs(365, 5).mirror().addBox(-3.0f, -3.0f, -9.0f, 6, 6, 10), PartPose.offsetAndRotation(0.0f, -8.0f, -5.0f, 0.0174533f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("head3", CubeListBuilder.create().texOffs(143, 149).mirror().addBox(-2.0f, -3.0f, -15.0f, 4, 4, 17), PartPose.offsetAndRotation(0.0f, -6.0f, -34.0f, -0.2443461f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("jaw1", CubeListBuilder.create().texOffs(143, 173).mirror().addBox(-1.5f, 1.0f, -14.0f, 3, 2, 12), PartPose.offsetAndRotation(0.0f, -6.0f, -34.0f, 0.1919862f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("jaw5", CubeListBuilder.create().texOffs(144, 206).mirror().addBox(-2.5f, 1.0f, -3.0f, 5, 2, 6), PartPose.offsetAndRotation(0.0f, -6.0f, -34.0f, 0.1919862f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("head7", CubeListBuilder.create().texOffs(144, 192).mirror().addBox(-3.0f, -4.0f, -3.0f, 6, 5, 7), PartPose.offsetAndRotation(0.0f, -6.0f, -34.0f, -0.2443461f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rightleg1", CubeListBuilder.create().texOffs(250, 10).mirror().addBox(-1.0f, -1.0f, -3.0f, 5, 9, 9), PartPose.offsetAndRotation(-17.0f, -8.0f, 13.0f, -0.5934119f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rightleg2", CubeListBuilder.create().texOffs(250, 32).mirror().addBox(0.0f, 6.0f, -7.0f, 4, 12, 5), PartPose.offsetAndRotation(-17.0f, -8.0f, 13.0f, 0.9773844f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rightleg3", CubeListBuilder.create().texOffs(250, 52).mirror().addBox(1.0f, 1.0f, -2.0f, 3, 19, 4), PartPose.offsetAndRotation(-17.0f, 5.0f, 23.0f, -0.5235988f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rclaw2", CubeListBuilder.create().texOffs(250, 76).mirror().addBox(-1.0f, 0.0f, -3.0f, 7, 3, 8), PartPose.offsetAndRotation(-17.0f, 21.0f, 13.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rclaw4", CubeListBuilder.create().texOffs(247, 123).mirror().addBox(2.0f, 1.0f, -7.0f, 1, 2, 4), PartPose.offsetAndRotation(-17.0f, 21.0f, 13.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rclaw5", CubeListBuilder.create().texOffs(258, 123).mirror().addBox(-0.5f, 1.0f, -7.0f, 1, 2, 4), PartPose.offsetAndRotation(-17.0f, 21.0f, 13.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rclaw7", CubeListBuilder.create().texOffs(283, 123).mirror().addBox(2.0f, 1.0f, 5.0f, 1, 2, 3), PartPose.offsetAndRotation(-17.0f, 21.0f, 13.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rclaw6", CubeListBuilder.create().texOffs(270, 123).mirror().addBox(4.5f, 1.0f, -7.0f, 1, 2, 4), PartPose.offsetAndRotation(-17.0f, 21.0f, 13.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("wing1", CubeListBuilder.create().texOffs(10, 30).mirror().addBox(-1.0f, -1.0f, -1.0f, 23, 2, 2), PartPose.offsetAndRotation(13.0f, -12.0f, 3.0f, 0.0f, 0.0872665f, 0.0f));
        partdefinition.addOrReplaceChild("wing2", CubeListBuilder.create().texOffs(10, 40).mirror().addBox(-1.0f, -1.0f, -1.0f, 44, 2, 2), PartPose.offsetAndRotation(34.0f, -12.0f, 1.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("mem1", CubeListBuilder.create().texOffs(10, 60).mirror().addBox(-2.0f, 0.0f, 0.0f, 24, 1, 21), PartPose.offsetAndRotation(13.0f, -12.0f, 3.0f, 0.0f, 0.0872665f, 0.0f));
        partdefinition.addOrReplaceChild("mem2", CubeListBuilder.create().texOffs(10, 85).mirror().addBox(0.0f, 0.0f, 0.0f, 43, 1, 21), PartPose.offsetAndRotation(34.0f, -12.0f, 1.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("lshoulder", CubeListBuilder.create().texOffs(370, 78).mirror().addBox(0.0f, 0.0f, 0.0f, 5, 2, 8), PartPose.offsetAndRotation(8.0f, -13.0f, 1.0f, 0.0698132f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rshoulder", CubeListBuilder.create().texOffs(370, 66).mirror().addBox(0.0f, 0.0f, 0.0f, 5, 2, 8), PartPose.offsetAndRotation(-13.0f, -13.0f, 1.0f, 0.0698132f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rwing1", CubeListBuilder.create().texOffs(10, 140).mirror().addBox(-22.0f, -1.0f, -1.0f, 23, 2, 2), PartPose.offsetAndRotation(-13.0f, -12.0f, 3.0f, 0.0f, -0.0872665f, 0.0f));
        partdefinition.addOrReplaceChild("rmem1", CubeListBuilder.create().texOffs(10, 170).mirror().addBox(-22.0f, 0.0f, 0.0f, 24, 1, 21), PartPose.offsetAndRotation(-13.0f, -12.0f, 3.0f, 0.0f, -0.0872665f, 0.0f));
        partdefinition.addOrReplaceChild("rwing2", CubeListBuilder.create().texOffs(10, 150).mirror().addBox(-43.0f, -1.0f, -1.0f, 44, 2, 2), PartPose.offsetAndRotation(-34.0f, -12.0f, 1.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("rmem2", CubeListBuilder.create().texOffs(10, 195).mirror().addBox(-43.0f, 0.0f, 0.0f, 43, 1, 21), PartPose.offsetAndRotation(-34.0f, -12.0f, 1.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("neck4", CubeListBuilder.create().texOffs(366, 23).mirror().addBox(-2.5f, -2.5f, -9.0f, 5, 5, 10), PartPose.offsetAndRotation(0.0f, -8.0f, -14.0f, 0.1396263f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("neck5", CubeListBuilder.create().texOffs(369, 41).mirror().addBox(-2.0f, -2.0f, -9.0f, 4, 4, 10), PartPose.offsetAndRotation(0.0f, -7.0f, -22.0f, 0.1396263f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("wing3", CubeListBuilder.create().texOffs(10, 46).mirror().addBox(0.0f, 0.0f, 0.0f, 44, 2, 2), PartPose.offsetAndRotation(13.0f, -13.0f, 3.0f, 0.0f, 0.0f, -0.3490659f));
        partdefinition.addOrReplaceChild("mem3", CubeListBuilder.create().texOffs(10, 110).mirror().addBox(0.0f, 0.0f, 0.0f, 43, 1, 21), PartPose.offsetAndRotation(13.0f, -12.5f, 5.0f, 0.0f, 0.0f, -0.3490659f));
        partdefinition.addOrReplaceChild("rwing3", CubeListBuilder.create().texOffs(10, 156).mirror().addBox(-43.0f, 0.0f, 0.0f, 44, 2, 2), PartPose.offsetAndRotation(-13.0f, -13.0f, 3.0f, 0.0f, 0.0f, 0.3490659f));
        partdefinition.addOrReplaceChild("rmem3", CubeListBuilder.create().texOffs(10, 221).mirror().addBox(-42.0f, 0.0f, 0.0f, 43, 1, 21), PartPose.offsetAndRotation(-13.0f, -12.5f, 5.0f, 0.0f, 0.0f, 0.3490659f));
        partdefinition.addOrReplaceChild("wing4", CubeListBuilder.create().texOffs(10, 46).mirror().addBox(0.0f, 0.0f, 0.0f, 44, 2, 2), PartPose.offsetAndRotation(13.0f, -12.0f, 3.0f, 0.0f, 0.0f, 0.3490659f));
        partdefinition.addOrReplaceChild("mem4", CubeListBuilder.create().texOffs(10, 110).mirror().addBox(0.0f, 0.0f, 0.0f, 43, 1, 21), PartPose.offsetAndRotation(13.0f, -11.5f, 5.0f, 0.0f, 0.0f, 0.3490659f));
        partdefinition.addOrReplaceChild("rwing4", CubeListBuilder.create().texOffs(10, 156).mirror().addBox(-43.0f, 0.0f, 0.0f, 44, 2, 2), PartPose.offsetAndRotation(-13.0f, -12.0f, 3.0f, 0.0f, 0.0f, -0.3490659f));
        partdefinition.addOrReplaceChild("rmem4", CubeListBuilder.create().texOffs(10, 221).mirror().addBox(-42.0f, 0.0f, 0.0f, 43, 1, 21), PartPose.offsetAndRotation(-13.0f, -11.5f, 5.0f, 0.0f, 0.0f, -0.3490659f));
        partdefinition.addOrReplaceChild("Tailspike1", CubeListBuilder.create().texOffs(150, 0).mirror().addBox(-7.0f, 0.0f, 0.0f, 14, 2, 6), PartPose.offsetAndRotation(0.0f, 2.0f, 69.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Tailspike2", CubeListBuilder.create().texOffs(150, 11).mirror().addBox(-5.0f, 0.0f, 0.0f, 10, 2, 6), PartPose.offsetAndRotation(0.0f, 2.0f, 75.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Tailspike3", CubeListBuilder.create().texOffs(150, 23).mirror().addBox(0.0f, 0.0f, 0.0f, 1, 1, 15), PartPose.offsetAndRotation(0.0f, 2.0f, 80.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("headfin", CubeListBuilder.create().texOffs(150, 216).mirror().addBox(-0.5f, -3.0f, 3.0f, 1, 4, 4), PartPose.offsetAndRotation(0.0f, -6.0f, -34.0f, 0.0872665f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("backfin1", CubeListBuilder.create().texOffs(69, 0).mirror().addBox(-0.5f, 0.0f, 0.0f, 1, 6, 6), PartPose.offsetAndRotation(0.0f, -11.0f, 0.0f, 0.7853982f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("backfin2", CubeListBuilder.create().texOffs(85, 0).mirror().addBox(-0.5f, 0.0f, 0.0f, 1, 4, 4), PartPose.offsetAndRotation(0.0f, -11.0f, 10.0f, 0.7853982f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("neck3L", CubeListBuilder.create().texOffs(365, 100).mirror().addBox(-3.0f, -3.0f, -9.0f, 6, 6, 10), PartPose.offsetAndRotation(8.0f, -8.0f, -5.0f, 0.0174533f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("neck4L", CubeListBuilder.create().texOffs(366, 119).mirror().addBox(-2.5f, -2.5f, -9.0f, 5, 5, 10), PartPose.offsetAndRotation(8.0f, -8.0f, -14.0f, 0.1396263f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("neck3R", CubeListBuilder.create().texOffs(365, 175).mirror().addBox(-3.0f, -3.0f, -9.0f, 6, 6, 10), PartPose.offsetAndRotation(-8.0f, -8.0f, -5.0f, 0.0174533f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("neck4R", CubeListBuilder.create().texOffs(366, 194).mirror().addBox(-2.5f, -2.5f, -9.0f, 5, 5, 10), PartPose.offsetAndRotation(-8.0f, -8.0f, -14.0f, 0.1396263f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("neck5L", CubeListBuilder.create().texOffs(369, 137).mirror().addBox(-2.0f, -2.0f, -9.0f, 4, 4, 10), PartPose.offsetAndRotation(8.0f, -7.0f, -23.0f, 0.1396263f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("neck5R", CubeListBuilder.create().texOffs(369, 212).mirror().addBox(-2.0f, -2.0f, -9.0f, 4, 4, 10), PartPose.offsetAndRotation(-8.0f, -7.0f, -23.0f, 0.1396263f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("jaw5L", CubeListBuilder.create().texOffs(200, 206).mirror().addBox(-2.5f, 1.0f, -3.0f, 5, 2, 6), PartPose.offsetAndRotation(8.0f, -6.0f, -34.0f, 0.1919862f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("jaw5R", CubeListBuilder.create().texOffs(250, 206).mirror().addBox(-2.5f, 1.0f, -3.0f, 5, 2, 6), PartPose.offsetAndRotation(-8.0f, -6.0f, -34.0f, 0.1919862f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("head7L", CubeListBuilder.create().texOffs(200, 192).mirror().addBox(-3.0f, -4.0f, -3.0f, 6, 5, 7), PartPose.offsetAndRotation(8.0f, -6.0f, -34.0f, -0.2443461f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("headfinL", CubeListBuilder.create().texOffs(200, 216).mirror().addBox(-0.5f, -3.0f, 3.0f, 1, 4, 4), PartPose.offsetAndRotation(8.0f, -6.0f, -34.0f, 0.0872665f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("headfinR", CubeListBuilder.create().texOffs(250, 216).mirror().addBox(-0.5f, -3.0f, 3.0f, 1, 4, 4), PartPose.offsetAndRotation(-8.0f, -6.0f, -34.0f, 0.0872665f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("head7R", CubeListBuilder.create().texOffs(250, 192).mirror().addBox(-3.0f, -4.0f, -3.0f, 6, 5, 7), PartPose.offsetAndRotation(-8.0f, -6.0f, -34.0f, -0.2443461f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("jaw1L", CubeListBuilder.create().texOffs(200, 173).mirror().addBox(-1.5f, 1.0f, -14.0f, 3, 2, 12), PartPose.offsetAndRotation(8.0f, -6.0f, -34.0f, 0.1919862f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("jaw1R", CubeListBuilder.create().texOffs(250, 173).mirror().addBox(-1.5f, 1.0f, -14.0f, 3, 2, 12), PartPose.offsetAndRotation(-8.0f, -6.0f, -34.0f, 0.1919862f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("head3L", CubeListBuilder.create().texOffs(200, 149).mirror().addBox(-2.0f, -3.0f, -15.0f, 4, 4, 17), PartPose.offsetAndRotation(8.0f, -6.0f, -34.0f, -0.2443461f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("head3R", CubeListBuilder.create().texOffs(250, 149).mirror().addBox(-2.0f, -3.0f, -15.0f, 4, 4, 17), PartPose.offsetAndRotation(-8.0f, -6.0f, -34.0f, -0.2443461f, 0.0f, 0.0f));
        return meshdefinition;
    }
    @Override
    public void setupAnim(ThePrinceTeen entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.animEntity = entity;
        this.animAgeInTicks = ageInTicks;
        this.animLimbSwingAmount = limbSwingAmount;
        this.animNetHeadYaw = netHeadYaw;
        this.animHeadPitch = headPitch;
    }

    @Override
    public void renderToBuffer(PoseStack poseStack, VertexConsumer buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        ThePrinceTeen entity = this.animEntity;
        float ageInTicks = this.animAgeInTicks;
        float limbSwingAmount = this.animLimbSwingAmount;
        float netHeadYaw = this.animNetHeadYaw;
        float headPitch = this.animHeadPitch;
        float h3;
        float d3;
        RenderInfo r = entity.getRenderInfo();
        float hf = 0.0f;
        float newangle = 0.0f;
        float newangle2 = 0.0f;
        float rnewangle = 0.0f;
        float rnewangle2 = 0.0f;
        float clawangle = 0.0f;
        float tailspeed = 0.26f;
        float tailamp = 0.08f;
        float pi4 = 0.7853982f;
        int current_activity = entity.getActivity();
        boolean useFlightPose =
                (current_activity != 0 || !entity.onGround()) && !entity.isInSittingPose();
        newangle = (double)limbSwingAmount > 0.1 && current_activity == 0 ? Mth.cos((float)(ageInTicks * 1.3f * this.wingspeed)) * 3.1415927f * 0.2f * limbSwingAmount : Mth.cos((float)(ageInTicks * 0.3f * this.wingspeed)) * 3.1415927f * 0.04f;
        if (useFlightPose) {
            newangle = Mth.cos((float)(ageInTicks * 1.4f * this.wingspeed)) * 3.1415927f * 0.4f;
        }
        if (entity.getAttacking() != 0) {
            newangle = Mth.cos((float)(ageInTicks * 1.7f * this.wingspeed)) * 3.1415927f * 0.4f;
        }
        if (entity.onGround() && current_activity == 0 && !entity.isVehicle() && entity.getAttacking() == 0) {
            if ((double)limbSwingAmount > 0.1) {
                newangle = Mth.cos((float)(ageInTicks * 0.35f * this.wingspeed)) * 3.1415927f * 0.05f * limbSwingAmount;
            } else {
                newangle = 0.0f;
            }
        }
        this.wing1.zRot = newangle - 0.4f;
        this.wing2.zRot = newangle * 1.25f - 0.4f;
        this.wing3.zRot = newangle - 0.6f;
        this.wing4.zRot = newangle - 0.2f;
        this.wing2.y = this.wing1.y + (float)Math.sin(this.wing1.zRot) * 22.0f;
        this.wing2.x = this.wing1.x + (float)Math.cos(this.wing1.zRot) * 22.0f;
        this.mem1.zRot = this.wing1.zRot;
        this.mem2.zRot = this.wing2.zRot;
        this.mem3.zRot = this.wing3.zRot;
        this.mem4.zRot = this.wing4.zRot;
        this.mem2.y = this.wing2.y;
        this.mem2.x = this.wing2.x;
        this.rwing1.zRot = - newangle + 0.4f;
        this.rwing2.zRot = (- newangle) * 1.25f + 0.4f;
        this.rwing3.zRot = - newangle + 0.6f;
        this.rwing4.zRot = - newangle + 0.2f;
        this.rwing2.y = this.rwing1.y - (float)Math.sin(this.rwing1.zRot) * 22.0f;
        this.rwing2.x = this.rwing1.x - (float)Math.cos(this.rwing1.zRot) * 22.0f;
        this.rmem1.zRot = this.rwing1.zRot;
        this.rmem2.zRot = this.rwing2.zRot;
        this.rmem3.zRot = this.rwing3.zRot;
        this.rmem4.zRot = this.rwing4.zRot;
        this.rmem2.y = this.rwing2.y;
        this.rmem2.x = this.rwing2.x;
        if ((double)limbSwingAmount > 0.1) {
            newangle = Mth.cos((float)(ageInTicks * 0.55f * this.wingspeed)) * 3.1415927f * 0.25f * limbSwingAmount;
            newangle2 = Mth.cos((float)((float)((double)(ageInTicks * 0.55f * this.wingspeed) + 1.5707963267948966))) * 3.1415927f * 0.25f * limbSwingAmount;
            rnewangle = newangle;
            rnewangle2 = newangle2;
            clawangle = 0.0f;
        } else {
            newangle = 0.0f;
            newangle2 = 0.0f;
            rnewangle = 0.0f;
            rnewangle2 = 0.0f;
            clawangle = 0.0f;
        }
        if (entity.getAttacking() != 0) {
            newangle = Mth.cos((float)(ageInTicks * this.wingspeed)) * 3.1415927f * 0.25f;
            newangle2 = Mth.cos((float)((float)((double)(ageInTicks * this.wingspeed) + 1.5707963267948966))) * 3.1415927f * 0.25f;
            rnewangle = newangle;
            rnewangle2 = newangle2;
            clawangle = 0.0f;
        }
        if (useFlightPose && entity.getAttacking() == 0) {
            newangle = -0.5f;
            newangle2 = -1.25f;
            rnewangle = 0.5f;
            rnewangle2 = 1.25f;
        }
        if (useFlightPose) {
            clawangle = -0.685f;
        }
        this.leftleg1.xRot = newangle - 0.575f;
        this.leftleg2.xRot = newangle + 0.977f;
        this.leftleg3.xRot = newangle2 - 0.523f;
        this.leftleg3.y = this.leftleg2.y + (float)Math.cos(this.leftleg2.xRot) * 14.0f + 6.0f;
        this.leftleg3.z = this.leftleg2.z + (float)Math.sin(this.leftleg2.xRot) * 14.0f;
        this.lclaw2.y = this.leftleg3.y + (float)Math.cos(this.leftleg3.xRot) * 17.0f;
        this.lclaw2.z = this.leftleg3.z + (float)Math.sin(this.leftleg3.xRot) * 17.0f - 1.0f;
        this.lclaw4.y = this.lclaw2.y;
        this.lclaw4.z = this.lclaw2.z;
        this.lclaw5.y = this.lclaw2.y;
        this.lclaw5.z = this.lclaw2.z;
        this.lclaw6.y = this.lclaw2.y;
        this.lclaw6.z = this.lclaw2.z;
        this.lclaw7.y = this.lclaw2.y;
        this.lclaw7.z = this.lclaw2.z;
        this.lclaw2.xRot = clawangle;
        this.lclaw4.xRot = clawangle;
        this.lclaw5.xRot = clawangle;
        this.lclaw6.xRot = clawangle;
        this.lclaw7.xRot = clawangle;
        this.rightleg1.xRot = - rnewangle - 0.575f;
        this.rightleg2.xRot = - rnewangle + 0.977f;
        this.rightleg3.xRot = - rnewangle2 - 0.523f;
        this.rightleg3.y = this.rightleg2.y + (float)Math.cos(this.rightleg2.xRot) * 14.0f + 5.0f;
        this.rightleg3.z = this.rightleg2.z + (float)Math.sin(this.rightleg2.xRot) * 14.0f;
        this.rclaw2.y = this.rightleg3.y + (float)Math.cos(this.rightleg3.xRot) * 17.0f;
        this.rclaw2.z = this.rightleg3.z + (float)Math.sin(this.rightleg3.xRot) * 17.0f - 1.0f;
        this.rclaw4.y = this.rclaw2.y;
        this.rclaw4.z = this.rclaw2.z;
        this.rclaw5.y = this.rclaw2.y;
        this.rclaw5.z = this.rclaw2.z;
        this.rclaw6.y = this.rclaw2.y;
        this.rclaw6.z = this.rclaw2.z;
        this.rclaw7.y = this.rclaw2.y;
        this.rclaw7.z = this.rclaw2.z;
        this.rclaw2.xRot = clawangle;
        this.rclaw4.xRot = clawangle;
        this.rclaw5.xRot = clawangle;
        this.rclaw6.xRot = clawangle;
        this.rclaw7.xRot = clawangle;
        if (entity.getAttacking() != 0) {
            tailspeed = 0.56f;
            tailamp = 0.19f;
        }
        if (entity.isInSittingPose()) {
            tailamp = 0.0f;
        }
        this.tail1.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed)) * 3.1415927f * tailamp / 4.0f;
        this.tail2.z = this.tail1.z + (float)Math.cos(this.tail1.yRot) * 11.0f;
        this.tail2.x = this.tail1.x + (float)Math.sin(this.tail1.yRot) * 11.0f;
        this.tail2.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed - pi4)) * 3.1415927f * tailamp;
        this.tail3.z = this.tail2.z + (float)Math.cos(this.tail2.yRot) * 9.0f;
        this.tail3.x = this.tail2.x + (float)Math.sin(this.tail2.yRot) * 9.0f;
        this.tail3.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed - 2.0f * pi4)) * 3.1415927f * tailamp;
        this.tail4.z = this.tail3.z + (float)Math.cos(this.tail3.yRot) * 9.0f;
        this.tail4.x = this.tail3.x + (float)Math.sin(this.tail3.yRot) * 9.0f;
        this.tail4.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed - 3.0f * pi4)) * 3.1415927f * tailamp;
        newangle = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed - 3.0f * pi4)) * 3.1415927f * tailamp;
        this.tail5.z = this.tail4.z + (float)Math.cos(this.tail4.yRot) * 9.0f;
        this.tail5.x = this.tail4.x + (float)Math.sin(this.tail4.yRot) * 9.0f;
        this.tail5.yRot = this.tail4.yRot + (newangle /= 2.0f);
        this.Tailspike1.z = this.tail5.z + (float)Math.cos(this.tail5.yRot) * 9.0f;
        this.Tailspike1.x = this.tail5.x + (float)Math.sin(this.tail5.yRot) * 9.0f;
        this.Tailspike2.z = this.tail5.z + (float)Math.cos(this.tail5.yRot) * 15.0f;
        this.Tailspike2.x = this.tail5.x + (float)Math.sin(this.tail5.yRot) * 15.0f;
        this.Tailspike1.yRot = this.Tailspike2.yRot = this.tail5.yRot + newangle * 2.0f / 3.0f;
        this.Tailspike3.z = this.Tailspike1.z + (float)Math.cos(this.Tailspike1.yRot) * 11.0f;
        this.Tailspike3.x = this.Tailspike1.x + (float)Math.sin(this.Tailspike1.yRot) * 11.0f;
        this.Tailspike3.yRot = this.Tailspike1.yRot + newangle * 3.0f / 2.0f;
        if (useFlightPose) {
            netHeadYaw = (entity.yRotO - entity.getYRot()) * 10.0f;
            netHeadYaw = - netHeadYaw;
            r.rf1 += (netHeadYaw - r.rf1) / 50.0f;
            if (r.rf1 > 50.0f) {
                r.rf1 = 50.0f;
            }
            if (r.rf1 < -50.0f) {
                r.rf1 = -50.0f;
            }
            netHeadYaw = r.rf1;
        }
        float h2 = h3 = netHeadYaw * 2.0f / 3.0f;
        float h1 = h3;
        float d2 = d3 = headPitch * 2.0f / 3.0f;
        float d1 = d3;
        if (h1 < 0.0f) {
            h2 = h3 = h1 / 2.0f;
            d2 = d3 = d1 / 2.0f;
        } else {
            h2 = h1 = h3 / 2.0f;
            d2 = d1 = d3 / 2.0f;
        }
        this.head7.yRot = (float)Math.toRadians(h2);
        this.head3.yRot = (float)Math.toRadians(h2);
        this.headfin.yRot = (float)Math.toRadians(h2);
        this.jaw5.yRot = (float)Math.toRadians(h2);
        this.jaw1.yRot = (float)Math.toRadians(h2);
        this.neck3.yRot = (float)Math.toRadians(h2) / 8.0f;
        this.neck4.yRot = (float)Math.toRadians(h2) / 4.0f;
        this.neck5.yRot = (float)Math.toRadians(h2) / 2.0f;
        this.head7L.yRot = (float)Math.toRadians(h1);
        this.head3L.yRot = (float)Math.toRadians(h1);
        this.headfinL.yRot = (float)Math.toRadians(h1);
        this.jaw5L.yRot = (float)Math.toRadians(h1);
        this.jaw1L.yRot = (float)Math.toRadians(h1);
        this.neck3L.yRot = (float)Math.toRadians(h1) / 8.0f;
        this.neck4L.yRot = (float)Math.toRadians(h1) / 4.0f;
        this.neck5L.yRot = (float)Math.toRadians(h1) / 2.0f;
        this.head7R.yRot = (float)Math.toRadians(h3);
        this.head3R.yRot = (float)Math.toRadians(h3);
        this.headfinR.yRot = (float)Math.toRadians(h3);
        this.jaw5R.yRot = (float)Math.toRadians(h3);
        this.jaw1R.yRot = (float)Math.toRadians(h3);
        this.neck3R.yRot = (float)Math.toRadians(h3) / 8.0f;
        this.neck4R.yRot = (float)Math.toRadians(h3) / 4.0f;
        this.neck5R.yRot = (float)Math.toRadians(h3) / 2.0f;
        float Rjx = 0.0f;
        float jx = 0.0f;
        float Ljx = 0.0f;
        if (entity.getAttacking() != 0) {
            newangle = Mth.cos((float)(ageInTicks * 0.9f * this.wingspeed)) * 3.1415927f * 0.1f;
            Ljx = 0.25f + newangle;
            newangle = Mth.cos((float)(ageInTicks * 1.1f * this.wingspeed)) * 3.1415927f * 0.1f;
            Rjx = 0.25f + newangle;
            newangle = Mth.cos((float)(ageInTicks * 1.3f * this.wingspeed)) * 3.1415927f * 0.1f;
            jx = 0.25f + newangle;
        } else {
            newangle = Mth.cos((float)(ageInTicks * 0.25f * this.wingspeed)) * 3.1415927f * 0.02f;
            Ljx = 0.1f + newangle;
            newangle = Mth.cos((float)(ageInTicks * 0.3f * this.wingspeed)) * 3.1415927f * 0.02f;
            Rjx = 0.1f + newangle;
            newangle = Mth.cos((float)(ageInTicks * 0.35f * this.wingspeed)) * 3.1415927f * 0.02f;
            jx = 0.1f + newangle;
        }
        this.head7.xRot = (float)Math.toRadians(d2);
        this.head3.xRot = (float)Math.toRadians(d2);
        this.headfin.xRot = (float)Math.toRadians(d2) + 0.5f;
        this.jaw5.xRot = (float)Math.toRadians(d2) + jx;
        this.jaw1.xRot = (float)Math.toRadians(d2) + jx;
        this.head7L.xRot = (float)Math.toRadians(d1);
        this.head3L.xRot = (float)Math.toRadians(d1);
        this.headfinL.xRot = (float)Math.toRadians(d1) + 0.5f;
        this.jaw5L.xRot = (float)Math.toRadians(d1) + Ljx;
        this.jaw1L.xRot = (float)Math.toRadians(d1) + Ljx;
        this.head7R.xRot = (float)Math.toRadians(d3);
        this.head3R.xRot = (float)Math.toRadians(d3);
        this.headfinR.xRot = (float)Math.toRadians(d3) + 0.5f;
        this.jaw5R.xRot = (float)Math.toRadians(d3) + Rjx;
        this.jaw1R.xRot = (float)Math.toRadians(d3) + Rjx;
        d1 = entity.getHead1Ext();
        d2 = entity.getHead2Ext();
        d3 = entity.getHead3Ext();
        this.neck3L.xRot = - (float)Math.toRadians((double)d1 / 3.0);
        this.neck4L.xRot = - (float)Math.toRadians((double)d1 * 2.0 / 3.0);
        this.neck5L.xRot = - (float)Math.toRadians(d1);
        this.neck3.xRot = - (float)Math.toRadians((double)d2 / 3.0);
        this.neck4.xRot = - (float)Math.toRadians((double)d2 * 2.0 / 3.0);
        this.neck5.xRot = - (float)Math.toRadians(d2);
        this.neck3R.xRot = - (float)Math.toRadians((double)d3 / 3.0);
        this.neck4R.xRot = - (float)Math.toRadians((double)d3 * 2.0 / 3.0);
        this.neck5R.xRot = - (float)Math.toRadians(d3);
        this.neck4.y = this.neck3.y + (float)Math.sin(this.neck3.xRot) * 9.0f;
        this.neck4.z = this.neck3.z - (float)Math.cos(this.neck3.xRot) * 9.0f;
        this.neck4.x = this.neck3.x - (float)Math.sin(this.neck3.yRot) * 9.0f * (float)Math.cos(this.neck3.xRot);
        this.neck5.y = this.neck4.y + (float)Math.sin(this.neck4.xRot) * 9.0f;
        this.neck5.z = this.neck4.z - (float)Math.cos(this.neck4.xRot) * 9.0f;
        this.neck5.x = this.neck4.x - (float)Math.sin(this.neck4.yRot) * 9.0f * (float)Math.cos(this.neck4.xRot);
        this.jaw1.y = this.head3.y = (this.head7.y = this.neck5.y + (float)Math.sin(this.neck5.xRot) * 9.0f);
        this.jaw5.y = this.head3.y;
        this.headfin.y = this.head3.y;
        this.jaw1.z = this.head3.z = (this.head7.z = this.neck5.z - (float)Math.cos(this.neck5.xRot) * 9.0f);
        this.jaw5.z = this.head3.z;
        this.headfin.z = this.head3.z;
        this.jaw1.x = this.head3.x = (this.head7.x = this.neck5.x - (float)Math.sin(this.neck5.yRot) * 9.0f * (float)Math.cos(this.neck5.xRot));
        this.jaw5.x = this.head3.x;
        this.headfin.x = this.head3.x;
        this.neck4L.y = this.neck3L.y + (float)Math.sin(this.neck3L.xRot) * 9.0f;
        this.neck4L.z = this.neck3L.z - (float)Math.cos(this.neck3L.xRot) * 9.0f;
        this.neck4L.x = this.neck3L.x - (float)Math.sin(this.neck3L.yRot) * 9.0f * (float)Math.cos(this.neck3L.xRot);
        this.neck5L.y = this.neck4L.y + (float)Math.sin(this.neck4L.xRot) * 9.0f;
        this.neck5L.z = this.neck4L.z - (float)Math.cos(this.neck4L.xRot) * 9.0f;
        this.neck5L.x = this.neck4L.x - (float)Math.sin(this.neck4L.yRot) * 9.0f * (float)Math.cos(this.neck4L.xRot);
        this.jaw1L.y = this.head3L.y = (this.head7L.y = this.neck5L.y + (float)Math.sin(this.neck5L.xRot) * 9.0f);
        this.jaw5L.y = this.head3L.y;
        this.headfinL.y = this.head3L.y;
        this.jaw1L.z = this.head3L.z = (this.head7L.z = this.neck5L.z - (float)Math.cos(this.neck5L.xRot) * 9.0f);
        this.jaw5L.z = this.head3L.z;
        this.headfinL.z = this.head3L.z;
        this.jaw1L.x = this.head3L.x = (this.head7L.x = this.neck5L.x - (float)Math.sin(this.neck5L.yRot) * 9.0f * (float)Math.cos(this.neck5L.xRot));
        this.jaw5L.x = this.head3L.x;
        this.headfinL.x = this.head3L.x;
        this.neck4R.y = this.neck3R.y + (float)Math.sin(this.neck3R.xRot) * 9.0f;
        this.neck4R.z = this.neck3R.z - (float)Math.cos(this.neck3R.xRot) * 9.0f;
        this.neck4R.x = this.neck3R.x - (float)Math.sin(this.neck3R.yRot) * 9.0f * (float)Math.cos(this.neck3R.xRot);
        this.neck5R.y = this.neck4R.y + (float)Math.sin(this.neck4R.xRot) * 9.0f;
        this.neck5R.z = this.neck4R.z - (float)Math.cos(this.neck4R.xRot) * 9.0f;
        this.neck5R.x = this.neck4R.x - (float)Math.sin(this.neck4R.yRot) * 9.0f * (float)Math.cos(this.neck4R.xRot);
        this.jaw1R.y = this.head3R.y = (this.head7R.y = this.neck5R.y + (float)Math.sin(this.neck5R.xRot) * 9.0f);
        this.jaw5R.y = this.head3R.y;
        this.headfinR.y = this.head3R.y;
        this.jaw1R.z = this.head3R.z = (this.head7R.z = this.neck5R.z - (float)Math.cos(this.neck5R.xRot) * 9.0f);
        this.jaw5R.z = this.head3R.z;
        this.headfinR.z = this.head3R.z;
        this.jaw1R.x = this.head3R.x = (this.head7R.x = this.neck5R.x - (float)Math.sin(this.neck5R.yRot) * 9.0f * (float)Math.cos(this.neck5R.xRot));
        this.jaw5R.x = this.head3R.x;
        this.headfinR.x = this.head3R.x;
        entity.setRenderInfo(r);
        this.body.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftleg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftleg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftleg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightleg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightleg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightleg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lshoulder.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rshoulder.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailspike1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailspike2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailspike3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headfin.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.backfin1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.backfin2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck3L.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck4L.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck3R.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck4R.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck5L.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck5R.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw5L.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw5R.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head7L.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headfinL.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headfinR.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head7R.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw1L.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw1R.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head3L.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head3R.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mem1.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.mem2.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.rmem1.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.rmem2.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.mem3.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.rmem3.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.mem4.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.rmem4.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
    }
}
