package com.astryxion.chaospersists.model;

import com.astryxion.chaospersists.entity.Dragon;
import com.astryxion.chaospersists.render.RenderInfo;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;
import com.mojang.math.Axis;

public class ModelDragon extends EntityModel<Dragon> {
    private final float wingspeed;
    private final ModelPart horn1;
    private final ModelPart horn2;
    private final ModelPart tail6;
    private final ModelPart wing15;
    private final ModelPart spike1;
    private final ModelPart spike2;
    private final ModelPart spike3;
    private final ModelPart spike4;
    private final ModelPart wing14;
    private final ModelPart spike5;
    private final ModelPart spike6;
    private final ModelPart spike7;
    private final ModelPart spike8;
    private final ModelPart spike9;
    private final ModelPart spike10;
    private final ModelPart head;
    private final ModelPart body;
    private final ModelPart leg1;
    private final ModelPart leg2;
    private final ModelPart leg3;
    private final ModelPart leg4;
    private final ModelPart body2;
    private final ModelPart neck1;
    private final ModelPart body3;
    private final ModelPart neck2;
    private final ModelPart neck3;
    private final ModelPart leg5;
    private final ModelPart leg6;
    private final ModelPart leg7;
    private final ModelPart leg9;
    private final ModelPart foot1;
    private final ModelPart foot2;
    private final ModelPart leg10;
    private final ModelPart leg11;
    private final ModelPart foot3;
    private final ModelPart foot4;
    private final ModelPart tail1;
    private final ModelPart tail2;
    private final ModelPart tail3;
    private final ModelPart mouth1;
    private final ModelPart mouth2;
    private final ModelPart tail5;
    private final ModelPart wing1;
    private final ModelPart wing2;
    private final ModelPart wing3;
    private final ModelPart wing4;
    private final ModelPart wing5;
    private final ModelPart wing6;
    private final ModelPart wing7;
    private final ModelPart wing8;
    private final ModelPart wing9;
    private final ModelPart wing10;
    private final ModelPart wing11;
    private final ModelPart wing12;
    private final ModelPart tail4;

    public ModelDragon(float f1) {
        this(f1, LayerDefinition.create(createMesh(), 512, 256).bakeRoot());
    }

    public ModelDragon(float wingspeed, ModelPart root) {
        this.wingspeed = wingspeed;
        this.horn1 = root.getChild("horn1");
        this.horn2 = root.getChild("horn2");
        this.tail6 = root.getChild("tail6");
        this.wing15 = root.getChild("wing15");
        this.spike1 = root.getChild("spike1");
        this.spike2 = root.getChild("spike2");
        this.spike3 = root.getChild("spike3");
        this.spike4 = root.getChild("spike4");
        this.wing14 = root.getChild("wing14");
        this.spike5 = root.getChild("spike5");
        this.spike6 = root.getChild("spike6");
        this.spike7 = root.getChild("spike7");
        this.spike8 = root.getChild("spike8");
        this.spike9 = root.getChild("spike9");
        this.spike10 = root.getChild("spike10");
        this.head = root.getChild("head");
        this.body = root.getChild("body");
        this.leg1 = root.getChild("leg1");
        this.leg2 = root.getChild("leg2");
        this.leg3 = root.getChild("leg3");
        this.leg4 = root.getChild("leg4");
        this.body2 = root.getChild("body2");
        this.neck1 = root.getChild("neck1");
        this.body3 = root.getChild("body3");
        this.neck2 = root.getChild("neck2");
        this.neck3 = root.getChild("neck3");
        this.leg5 = root.getChild("leg5");
        this.leg6 = root.getChild("leg6");
        this.leg7 = root.getChild("leg7");
        this.leg9 = root.getChild("leg9");
        this.foot1 = root.getChild("foot1");
        this.foot2 = root.getChild("foot2");
        this.leg10 = root.getChild("leg10");
        this.leg11 = root.getChild("leg11");
        this.foot3 = root.getChild("foot3");
        this.foot4 = root.getChild("foot4");
        this.tail1 = root.getChild("tail1");
        this.tail2 = root.getChild("tail2");
        this.tail3 = root.getChild("tail3");
        this.mouth1 = root.getChild("mouth1");
        this.mouth2 = root.getChild("mouth2");
        this.tail5 = root.getChild("tail5");
        this.wing1 = root.getChild("wing1");
        this.wing2 = root.getChild("wing2");
        this.wing3 = root.getChild("wing3");
        this.wing4 = root.getChild("wing4");
        this.wing5 = root.getChild("wing5");
        this.wing6 = root.getChild("wing6");
        this.wing7 = root.getChild("wing7");
        this.wing8 = root.getChild("wing8");
        this.wing9 = root.getChild("wing9");
        this.wing10 = root.getChild("wing10");
        this.wing11 = root.getChild("wing11");
        this.wing12 = root.getChild("wing12");
        this.tail4 = root.getChild("tail4");
    }

    private static MeshDefinition createMesh() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("horn1", CubeListBuilder.create().texOffs(0, 39).mirror().addBox(2.0f, -4.0f, 1.0f, 2, 2, 6), PartPose.offsetAndRotation(0.0f, 6.0f, -23.0f, 0.4089647f, 0.2602503f, 0.0f));
        root.addOrReplaceChild("horn2", CubeListBuilder.create().texOffs(0, 39).mirror().addBox(-4.0f, -4.0f, 1.0f, 2, 2, 6), PartPose.offsetAndRotation(0.0f, 6.0f, -23.0f, 0.4089647f, -0.2602503f, 0.0f));
        root.addOrReplaceChild("tail6", CubeListBuilder.create().texOffs(0, 49).mirror().addBox(-1.0f, 0.0f, -2.0f, 2, 6, 4), PartPose.offsetAndRotation(0.0f, 7.0f, 43.0f, 1.570796f, 0.0f, 0.0f));
        root.addOrReplaceChild("wing15", CubeListBuilder.create().texOffs(0, 62).mirror().addBox(1.0f, -1.0f, 1.0f, 12, 1, 8), PartPose.offsetAndRotation(4.0f, 3.0f, -5.0f, -0.0743572f, -0.4089594f, 0.0f));
        root.addOrReplaceChild("spike1", CubeListBuilder.create().texOffs(0, 73).mirror().addBox(-1.0f, -3.0f, -5.0f, 2, 2, 4), PartPose.offset(0.0f, 6.0f, -17.0f));
        root.addOrReplaceChild("spike2", CubeListBuilder.create().texOffs(0, 73).mirror().addBox(-1.0f, -3.0f, -5.0f, 2, 2, 4), PartPose.offset(0.0f, 6.0f, -11.0f));
        root.addOrReplaceChild("spike3", CubeListBuilder.create().texOffs(0, 73).mirror().addBox(-1.0f, -4.0f, 1.0f, 2, 2, 4), PartPose.offset(0.0f, 7.0f, 25.0f));
        root.addOrReplaceChild("spike4", CubeListBuilder.create().texOffs(0, 73).mirror().addBox(-1.0f, -2.0f, 0.0f, 2, 2, 4), PartPose.offset(0.0f, 3.0f, -7.0f));
        root.addOrReplaceChild("wing14", CubeListBuilder.create().texOffs(0, 62).mirror().addBox(-13.0f, -1.0f, 0.0f, 12, 1, 8), PartPose.offsetAndRotation(-4.0f, 3.0f, -5.0f, -0.0698132f, 0.4089656f, 0.0f));
        root.addOrReplaceChild("spike5", CubeListBuilder.create().texOffs(0, 73).mirror().addBox(-1.0f, -2.0f, 0.0f, 2, 2, 4), PartPose.offset(0.0f, 3.0f, -1.0f));
        root.addOrReplaceChild("spike6", CubeListBuilder.create().texOffs(0, 73).mirror().addBox(-1.0f, -2.0f, 0.0f, 2, 2, 4), PartPose.offset(0.0f, 3.0f, 5.0f));
        root.addOrReplaceChild("spike7", CubeListBuilder.create().texOffs(0, 73).mirror().addBox(-1.0f, -4.0f, 1.0f, 2, 2, 4), PartPose.offset(0.0f, 7.0f, 13.0f));
        root.addOrReplaceChild("spike8", CubeListBuilder.create().texOffs(0, 73).mirror().addBox(-1.0f, -2.0f, 1.0f, 2, 2, 4), PartPose.offset(0.0f, 5.0f, 19.0f));
        root.addOrReplaceChild("spike9", CubeListBuilder.create().texOffs(0, 73).mirror().addBox(-1.0f, -4.0f, 1.0f, 2, 2, 4), PartPose.offset(0.0f, 7.0f, 31.0f));
        root.addOrReplaceChild("spike10", CubeListBuilder.create().texOffs(0, 73).mirror().addBox(-1.0f, -4.0f, 2.0f, 2, 2, 4), PartPose.offset(0.0f, 7.0f, 36.0f));
        root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 81).mirror().addBox(-4.0f, -4.0f, -8.0f, 8, 8, 8), PartPose.offset(0.0f, 6.0f, -23.0f));
        root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(1, 99).mirror().addBox(-6.0f, -10.0f, -7.0f, 12, 18, 10), PartPose.offsetAndRotation(0.0f, 5.0f, 2.0f, 1.570796f, 0.0f, 0.0f));
        root.addOrReplaceChild("leg1", CubeListBuilder.create().texOffs(47, 112).mirror().addBox(-4.0f, -1.0f, -2.0f, 4, 9, 5), PartPose.offsetAndRotation(-4.0f, 11.0f, 8.0f, -0.6320364f, 0.0f, 0.0f));
        root.addOrReplaceChild("leg2", CubeListBuilder.create().texOffs(47, 112).mirror().addBox(1.0f, -1.0f, -2.0f, 4, 9, 5), PartPose.offsetAndRotation(3.0f, 11.0f, 8.0f, -0.6320364f, 0.0f, 0.0f));
        root.addOrReplaceChild("leg3", CubeListBuilder.create().texOffs(18, 47).mirror().addBox(-3.0f, -2.0f, -2.0f, 4, 9, 4), PartPose.offsetAndRotation(-4.0f, 11.0f, -5.0f, 0.5576792f, 0.0f, 0.0f));
        root.addOrReplaceChild("leg4", CubeListBuilder.create().texOffs(18, 47).mirror().addBox(0.0f, -2.0f, -2.0f, 4, 9, 4), PartPose.offsetAndRotation(3.0f, 11.0f, -5.0f, 0.5576792f, 0.0f, 0.0f));
        root.addOrReplaceChild("body2", CubeListBuilder.create().texOffs(68, 94).mirror().addBox(-5.0f, 0.0f, 0.0f, 10, 22, 10), PartPose.offsetAndRotation(0.0f, 12.0f, -10.0f, 1.570796f, 0.0f, 0.0f));
        root.addOrReplaceChild("neck1", CubeListBuilder.create().texOffs(43, 85).mirror().addBox(-3.0f, -3.0f, 0.0f, 6, 6, 6), PartPose.offset(0.0f, 7.0f, 25.0f));
        root.addOrReplaceChild("body3", CubeListBuilder.create().texOffs(70, 59).mirror().addBox(-4.0f, 0.0f, 0.0f, 8, 24, 8), PartPose.offsetAndRotation(0.0f, 11.0f, -11.0f, 1.570796f, 0.0f, 0.0f));
        root.addOrReplaceChild("neck2", CubeListBuilder.create().texOffs(43, 85).mirror().addBox(-3.0f, -2.0f, -6.0f, 6, 6, 6), PartPose.offset(0.0f, 6.0f, -11.0f));
        root.addOrReplaceChild("neck3", CubeListBuilder.create().texOffs(43, 85).mirror().addBox(-3.0f, -2.0f, -6.0f, 6, 6, 6), PartPose.offset(0.0f, 6.0f, -17.0f));
        root.addOrReplaceChild("leg5", CubeListBuilder.create().texOffs(47, 99).mirror().addBox(0.0f, 3.0f, 3.0f, 4, 8, 4), PartPose.offsetAndRotation(3.0f, 11.0f, -5.0f, -0.5576792f, 0.0f, 0.0f));
        root.addOrReplaceChild("leg6", CubeListBuilder.create().texOffs(47, 99).mirror().addBox(-3.0f, 3.0f, 3.0f, 4, 8, 4), PartPose.offsetAndRotation(-4.0f, 11.0f, -5.0f, -0.5576792f, 0.0f, 0.0f));
        root.addOrReplaceChild("leg7", CubeListBuilder.create().texOffs(38, 73).mirror().addBox(1.0f, 2.0f, -8.0f, 4, 5, 4), PartPose.offsetAndRotation(3.0f, 11.0f, 8.0f, 0.8922867f, 0.0f, 0.0f));
        root.addOrReplaceChild("leg9", CubeListBuilder.create().texOffs(38, 73).mirror().addBox(-4.0f, 2.0f, -8.0f, 4, 5, 4), PartPose.offsetAndRotation(-4.0f, 11.0f, 8.0f, 0.8922867f, 0.0f, 0.0f));
        root.addOrReplaceChild("foot1", CubeListBuilder.create().texOffs(43, 63).mirror().addBox(-3.0f, 11.0f, -5.0f, 4, 2, 6), PartPose.offset(-4.0f, 11.0f, -5.0f));
        root.addOrReplaceChild("foot2", CubeListBuilder.create().texOffs(43, 63).mirror().addBox(0.0f, 11.0f, -5.0f, 4, 2, 6), PartPose.offset(3.0f, 11.0f, -5.0f));
        root.addOrReplaceChild("leg10", CubeListBuilder.create().texOffs(39, 52).mirror().addBox(1.0f, 6.0f, 2.0f, 4, 5, 4), PartPose.offsetAndRotation(3.0f, 11.0f, 8.0f, -0.5576792f, 0.0f, 0.0f));
        root.addOrReplaceChild("leg11", CubeListBuilder.create().texOffs(39, 52).mirror().addBox(-4.0f, 6.0f, 2.0f, 4, 5, 4), PartPose.offsetAndRotation(-4.0f, 11.0f, 8.0f, -0.5576792f, 0.0f, 0.0f));
        root.addOrReplaceChild("foot3", CubeListBuilder.create().texOffs(43, 63).mirror().addBox(1.0f, 11.0f, -7.0f, 4, 2, 6), PartPose.offset(3.0f, 11.0f, 8.0f));
        root.addOrReplaceChild("foot4", CubeListBuilder.create().texOffs(43, 63).mirror().addBox(-4.0f, 11.0f, -7.0f, 4, 2, 6), PartPose.offset(-4.0f, 11.0f, 8.0f));
        root.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(43, 85).mirror().addBox(-3.0f, -3.0f, 0.0f, 6, 6, 6), PartPose.offset(0.0f, 7.0f, 13.0f));
        root.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(43, 85).mirror().addBox(-3.0f, -3.0f, 0.0f, 6, 6, 6), PartPose.offset(0.0f, 7.0f, 19.0f));
        root.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(56, 45).mirror().addBox(-3.0f, -3.0f, 0.0f, 4, 6, 6), PartPose.offset(1.0f, 7.0f, 31.0f));
        root.addOrReplaceChild("mouth1", CubeListBuilder.create().texOffs(90, 22).mirror().addBox(-3.0f, -1.0f, -15.0f, 6, 3, 8), PartPose.offset(0.0f, 6.0f, -23.0f));
        root.addOrReplaceChild("mouth2", CubeListBuilder.create().texOffs(90, 6).mirror().addBox(-2.0f, 1.0f, -5.0f, 4, 2, 8), PartPose.offsetAndRotation(0.0f, 7.0f, -32.0f, 0.0698132f, 0.0f, 0.0f));
        root.addOrReplaceChild("tail5", CubeListBuilder.create().texOffs(87, 36).mirror().addBox(0.0f, 0.0f, -5.0f, 0, 11, 10), PartPose.offsetAndRotation(0.0f, 7.0f, 49.0f, 1.570796f, 0.0f, 0.0f));
        root.addOrReplaceChild("wing1", CubeListBuilder.create().texOffs(26, 40).mirror().addBox(0.0f, -1.0f, -1.0f, 11, 2, 2), PartPose.offsetAndRotation(4.0f, 3.0f, -5.0f, 0.0f, -0.4833219f, 0.0f));
        root.addOrReplaceChild("wing2", CubeListBuilder.create().texOffs(110, 88).mirror().addBox(-1.0f, -1.0f, 0.0f, 2, 2, 36), PartPose.offsetAndRotation(19.0f, 3.0f, -23.0f, 0.0f, 1.041001f, 0.0f));
        root.addOrReplaceChild("wing3", CubeListBuilder.create().texOffs(109, 60).mirror().addBox(-1.0f, -1.0f, -24.0f, 2, 2, 24), PartPose.offsetAndRotation(12.0f, 3.0f, -1.0f, -0.0090881f, -0.3497888f, 0.0f));
        root.addOrReplaceChild("wing4", CubeListBuilder.create().texOffs(26, 40).mirror().addBox(-11.0f, -1.0f, -1.0f, 11, 2, 2), PartPose.offsetAndRotation(-4.0f, 3.0f, -5.0f, 0.0f, 0.4833166f, 0.0f));
        root.addOrReplaceChild("wing5", CubeListBuilder.create().texOffs(109, 60).mirror().addBox(-1.0f, -1.0f, -24.0f, 2, 2, 24), PartPose.offsetAndRotation(-12.0f, 3.0f, -1.0f, -0.0090932f, 0.3323281f, 0.0f));
        root.addOrReplaceChild("wing6", CubeListBuilder.create().texOffs(110, 88).mirror().addBox(-1.0f, -1.0f, 0.0f, 2, 2, 36), PartPose.offsetAndRotation(-20.0f, 3.0f, -23.0f, 0.0f, -1.041002f, 0.0f));
        root.addOrReplaceChild("wing7", CubeListBuilder.create().texOffs(124, 21).mirror().addBox(-8.0f, 0.0f, 1.0f, 8, 1, 36), PartPose.offsetAndRotation(19.0f, 2.0f, -23.0f, 0.0f, 1.041001f, 0.0f));
        root.addOrReplaceChild("wing8", CubeListBuilder.create().texOffs(122, 10).mirror().addBox(-11.0f, -1.0f, 0.0f, 28, 1, 8), PartPose.offsetAndRotation(12.0f, 3.0f, -1.0f, 0.002272f, 1.264073f, -0.0174533f));
        root.addOrReplaceChild("wing9", CubeListBuilder.create().texOffs(0, 10).mirror().addBox(-25.0f, -1.0f, 7.0f, 18, 1, 26), PartPose.offsetAndRotation(19.0f, 3.0f, -23.0f, 0.002272f, 1.264073f, 0.0f));
        root.addOrReplaceChild("wing10", CubeListBuilder.create().texOffs(122, 10).mirror().addBox(-23.0f, -1.0f, 0.0f, 33, 1, 8), PartPose.offsetAndRotation(-12.0f, 3.0f, -1.0f, -0.0022689f, -1.226894f, 0.0f));
        root.addOrReplaceChild("wing11", CubeListBuilder.create().texOffs(124, 21).mirror().addBox(0.0f, -1.0f, 1.0f, 8, 1, 36), PartPose.offsetAndRotation(-20.0f, 3.0f, -23.0f, 0.0f, -1.041002f, 0.0f));
        root.addOrReplaceChild("wing12", CubeListBuilder.create().texOffs(0, 10).mirror().addBox(7.0f, -1.0f, 7.0f, 18, 1, 26), PartPose.offsetAndRotation(-20.0f, 3.0f, -23.0f, 0.002272f, -1.264072f, 0.0f));
        root.addOrReplaceChild("tail4", CubeListBuilder.create().texOffs(56, 45).mirror().addBox(-3.0f, -3.0f, 0.0f, 4, 6, 6), PartPose.offset(1.0f, 7.0f, 37.0f));
        return mesh;
    }

    @Override
    public void setupAnim(Dragon e, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        RenderInfo r = e.getRenderInfo();
        float newangle = 0.0f;
        float lspeed = 0.0f;
        float tailspeed = 0.76f;
        float tailamp = 0.45f;
        if ((double)limbSwingAmount > 0.001) {
            lspeed = (float)((e.xo - e.getX()) * (e.xo - e.getX()) + (e.zo - e.getZ()) * (e.zo - e.getZ()));
            lspeed = (float)Math.sqrt(lspeed);
            newangle = Mth.cos((float)(ageInTicks * 1.25f * this.wingspeed)) * 3.1415927f * lspeed * 0.6f;
        } else {
            newangle = 0.0f;
        }
        if (e.getActivity() != 0) {
            newangle = 1.0f;
            this.leg4.xRot = 0.557f - newangle;
            this.leg5.xRot = -0.557f - newangle;
            this.foot2.xRot = - newangle;
            this.leg3.xRot = 0.557f - newangle;
            this.leg6.xRot = -0.557f - newangle;
            this.foot1.xRot = - newangle;
            this.leg2.xRot = -0.632f + newangle;
            this.leg7.xRot = 0.89f + newangle;
            this.leg10.xRot = -0.557f + newangle;
            this.foot3.xRot = newangle;
            this.leg1.xRot = -0.632f + newangle;
            this.leg9.xRot = 0.89f + newangle;
            this.leg11.xRot = -0.557f + newangle;
            this.foot4.xRot = newangle;
        } else {
            this.leg4.xRot = 0.557f + newangle;
            this.leg5.xRot = -0.557f + newangle;
            this.foot2.xRot = newangle;
            this.leg3.xRot = 0.557f - newangle;
            this.leg6.xRot = -0.557f - newangle;
            this.foot1.xRot = - newangle;
            this.leg2.xRot = -0.632f - newangle;
            this.leg7.xRot = 0.89f - newangle;
            this.leg10.xRot = -0.557f - newangle;
            this.foot3.xRot = - newangle;
            this.leg1.xRot = -0.632f + newangle;
            this.leg9.xRot = 0.89f + newangle;
            this.leg11.xRot = -0.557f + newangle;
            this.foot4.xRot = newangle;
        }
        newangle = e.getAttacking() != 0 ? (e.getActivity() != 0 ? Mth.cos((float)(ageInTicks * 0.75f * this.wingspeed)) * 3.1415927f * 0.28f : -0.45f + Mth.cos((float)(ageInTicks * 0.85f * this.wingspeed)) * 3.1415927f * 0.2f) : (e.getActivity() != 0 ? Mth.cos((float)(ageInTicks * 0.75f * this.wingspeed)) * 3.1415927f * 0.28f : -0.85f + Mth.cos((float)(ageInTicks * 0.2f * this.wingspeed)) * 3.1415927f * 0.028f);
        this.wing1.zRot = newangle;
        this.wing15.zRot = newangle;
        this.wing3.zRot = newangle * 4.0f / 3.0f;
        this.wing3.y = this.wing1.y + (float)Math.sin(this.wing1.zRot) * 7.0f;
        this.wing3.x = this.wing1.x + (float)Math.cos(this.wing1.zRot) * 7.0f;
        this.wing8.zRot = newangle * 4.0f / 3.0f;
        this.wing8.y = this.wing3.y;
        this.wing8.x = this.wing3.x;
        this.wing2.zRot = newangle * 3.0f / 2.0f;
        this.wing2.y = this.wing3.y + (float)Math.sin(this.wing3.zRot) * 6.0f;
        this.wing2.x = this.wing3.x + (float)Math.cos(this.wing3.zRot) * 6.0f;
        this.wing7.zRot = newangle * 3.0f / 2.0f;
        this.wing7.y = this.wing2.y;
        this.wing7.x = this.wing2.x;
        this.wing9.zRot = newangle * 3.0f / 2.0f;
        this.wing9.y = this.wing2.y;
        this.wing9.x = this.wing2.x;
        this.wing4.zRot = - newangle;
        this.wing14.zRot = - newangle;
        this.wing5.zRot = (- newangle) * 4.0f / 3.0f;
        this.wing5.y = this.wing4.y - (float)Math.sin(this.wing4.zRot) * 7.0f;
        this.wing5.x = this.wing4.x - (float)Math.cos(this.wing4.zRot) * 7.0f;
        this.wing10.zRot = (- newangle) * 4.0f / 3.0f;
        this.wing10.y = this.wing5.y;
        this.wing10.x = this.wing5.x;
        this.wing6.zRot = (- newangle) * 3.0f / 2.0f;
        this.wing6.y = this.wing5.y - (float)Math.sin(this.wing5.zRot) * 6.0f;
        this.wing6.x = this.wing5.x - (float)Math.cos(this.wing5.zRot) * 6.0f;
        this.wing11.zRot = (- newangle) * 3.0f / 2.0f;
        this.wing11.y = this.wing6.y;
        this.wing11.x = this.wing6.x;
        this.wing12.zRot = (- newangle) * 3.0f / 2.0f;
        this.wing12.y = this.wing6.y;
        this.wing12.x = this.wing6.x;
        if (e.getAttacking() != 0) {
            tailspeed = 0.96f;
            tailamp = 0.75f;
        }
        if (e.getActivity() == 0 && e.getAttacking() == 0) {
            tailspeed = 0.22f;
            tailamp = 0.22f;
        }
        if (e.isInSittingPose()) {
            tailspeed = 0.0f;
            tailamp = 0.0f;
        }
        this.tail1.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed)) * 3.1415927f * 0.04f;
        this.spike10.z = this.tail1.z;
        this.spike10.x = this.tail1.x;
        this.spike10.yRot = this.tail1.yRot;
        this.tail2.z = this.tail1.z + (float)Math.cos(this.tail1.yRot) * 6.0f;
        this.tail2.x = this.tail1.x + (float)Math.sin(this.tail1.yRot) * 6.0f;
        this.tail2.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed)) * 3.1415927f * tailamp * 0.125f;
        this.spike7.z = this.tail2.z;
        this.spike7.x = this.tail2.x;
        this.spike7.yRot = this.tail2.yRot;
        this.neck1.z = this.tail2.z + (float)Math.cos(this.tail2.yRot) * 6.0f;
        this.neck1.x = this.tail2.x + (float)Math.sin(this.tail2.yRot) * 6.0f;
        this.neck1.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed)) * 3.1415927f * tailamp * 0.25f;
        this.spike8.z = this.neck1.z;
        this.spike8.x = this.neck1.x;
        this.spike8.yRot = this.neck1.yRot;
        this.tail3.z = this.neck1.z + (float)Math.cos(this.neck1.yRot) * 6.0f;
        this.tail3.x = this.neck1.x + 1.0f + (float)Math.sin(this.neck1.yRot) * 6.0f;
        this.tail3.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed)) * 3.1415927f * tailamp * 0.375f;
        this.spike3.z = this.tail3.z;
        this.spike3.x = this.tail3.x - 1.0f;
        this.spike3.yRot = this.tail3.yRot;
        this.tail4.z = this.tail3.z + (float)Math.cos(this.tail3.yRot) * 6.0f;
        this.tail4.x = this.tail3.x + (float)Math.sin(this.tail3.yRot) * 6.0f;
        this.tail4.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed)) * 3.1415927f * tailamp * 0.5f;
        this.spike9.z = this.tail4.z;
        this.spike9.x = this.tail4.x - 1.0f;
        this.spike9.yRot = this.tail4.yRot;
        this.tail6.z = this.tail4.z + (float)Math.cos(this.tail4.yRot) * 6.0f;
        this.tail6.x = this.tail4.x - 1.0f + (float)Math.sin(this.tail4.yRot) * 6.0f;
        this.tail6.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed)) * 3.1415927f * tailamp * 0.625f;
        this.tail5.z = this.tail6.z + (float)Math.cos(this.tail6.yRot) * 6.0f;
        this.tail5.x = this.tail6.x - 0.5f + (float)Math.sin(this.tail6.yRot) * 6.0f;
        this.tail5.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed)) * 3.1415927f * tailamp * 0.75f;
        if (e.getActivity() == 1) {
            netHeadYaw = (e.yRotO - e.getYRot()) * 8.0f;
            netHeadYaw = - netHeadYaw;
            r.rf1 += (netHeadYaw - r.rf1) / 60.0f;
            if (r.rf1 > 50.0f) {
                r.rf1 = 50.0f;
            }
            if (r.rf1 < -50.0f) {
                r.rf1 = -50.0f;
            }
            netHeadYaw = r.rf1;
        } else {
            netHeadYaw /= 2.0f;
        }
        this.spike2.yRot = this.neck2.yRot = (float)Math.toRadians(netHeadYaw) * 0.25f;
        this.neck3.z = this.neck2.z - (float)Math.cos(this.neck2.yRot) * 6.0f;
        this.neck3.x = this.neck2.x - (float)Math.sin(this.neck2.yRot) * 6.0f;
        this.neck3.yRot = (float)Math.toRadians(netHeadYaw) * 0.5f;
        this.spike1.z = this.neck3.z;
        this.spike1.x = this.neck3.x;
        this.spike1.yRot = this.neck3.yRot;
        this.head.z = this.neck3.z - (float)Math.cos(this.neck3.yRot) * 6.0f;
        this.head.x = this.neck3.x - (float)Math.sin(this.neck3.yRot) * 6.0f;
        this.head.yRot = (float)Math.toRadians(netHeadYaw) * 0.75f;
        this.mouth1.z = this.head.z;
        this.mouth1.x = this.head.x;
        this.mouth1.yRot = this.head.yRot;
        this.horn1.z = this.head.z;
        this.horn1.x = this.head.x;
        this.horn1.yRot = this.head.yRot + 0.26f;
        this.horn2.z = this.head.z;
        this.horn2.x = this.head.x;
        this.horn2.yRot = this.head.yRot - 0.26f;
        this.mouth2.z = this.head.z - (float)Math.cos(this.head.yRot) * 9.0f;
        this.mouth2.x = this.head.x - (float)Math.sin(this.head.yRot) * 9.0f;
        this.mouth2.yRot = this.head.yRot;
        newangle = Mth.cos((float)(ageInTicks * 1.5f * this.wingspeed)) * 3.1415927f * 0.14f;
        this.mouth2.xRot = e.getAttacking() != 0 ? 0.4f + newangle : 0.07f;
        e.setRenderInfo(r);
    }

    @Override
    public void renderToBuffer(PoseStack poseStack, VertexConsumer buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        poseStack.pushPose();
        poseStack.mulPose(Axis.XP.rotationDegrees(90.0f));
        this.horn1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.horn2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing15.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing14.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike8.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike9.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike10.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg9.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.foot1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.foot2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg10.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg11.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.foot3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.foot4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mouth1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mouth2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing8.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing9.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing10.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing11.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing12.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        poseStack.popPose();
    }
}
