package com.astryxion.chaospersists.model;

import com.astryxion.chaospersists.entity.TheKing;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

public class ModelTheKing extends EntityModel<TheKing> {
    private final float wingspeed;
    private TheKing animEntity;
    private float animAgeInTicks;
    private float animLimbSwingAmount;
    private float animNetHeadYaw;
    private float animHeadPitch;
    private final ModelPart LCClaw1;
    private final ModelPart LThigh;
    private final ModelPart LUpperLeg;
    private final ModelPart TailTip;
    private final ModelPart Tail1;
    private final ModelPart Tail2;
    private final ModelPart Tail3;
    private final ModelPart Tail4;
    private final ModelPart Tail5;
    private final ModelPart Tail6;
    private final ModelPart Tail7;
    private final ModelPart Body1;
    private final ModelPart Chest;
    private final ModelPart NeckC1;
    private final ModelPart LLowerLeg;
    private final ModelPart LFoot;
    private final ModelPart LLClaw1;
    private final ModelPart LRClaw1;
    private final ModelPart LCClaw2;
    private final ModelPart LLClaw2;
    private final ModelPart TailSpike;
    private final ModelPart LRClaw2;
    private final ModelPart LClawRear;
    private final ModelPart NeckL1;
    private final ModelPart NeckR1;
    private final ModelPart RThigh;
    private final ModelPart RUpperLeg;
    private final ModelPart RLowerLeg;
    private final ModelPart RFoot;
    private final ModelPart RClawRear;
    private final ModelPart RLClaw1;
    private final ModelPart RCClaw1;
    private final ModelPart RRClaw1;
    private final ModelPart RLClaw2;
    private final ModelPart RCClaw2;
    private final ModelPart RRClaw2;
    private final ModelPart NeckL2;
    private final ModelPart NeckC2;
    private final ModelPart NeckR2;
    private final ModelPart NeckL3;
    private final ModelPart NeckC3;
    private final ModelPart NeckR3;
    private final ModelPart NeckL4;
    private final ModelPart LHead1;
    private final ModelPart LHead2;
    private final ModelPart LHead3;
    private final ModelPart LJaw1;
    private final ModelPart LJaw2;
    private final ModelPart LJaw3;
    private final ModelPart LTooth1;
    private final ModelPart LTooth2;
    private final ModelPart LTooth3;
    private final ModelPart LTooth4;
    private final ModelPart NeckC4;
    private final ModelPart NeckR4;
    private final ModelPart CHead1;
    private final ModelPart RHead1;
    private final ModelPart CHead2;
    private final ModelPart RHead2;
    private final ModelPart CHead3;
    private final ModelPart RHead3;
    private final ModelPart CJaw1;
    private final ModelPart CJaw2;
    private final ModelPart CJaw3;
    private final ModelPart RJaw1;
    private final ModelPart RJaw2;
    private final ModelPart RJaw3;
    private final ModelPart CTooth3;
    private final ModelPart CTooth4;
    private final ModelPart CTooth1;
    private final ModelPart CTooth2;
    private final ModelPart RTooth3;
    private final ModelPart RTooth4;
    private final ModelPart RTooth1;
    private final ModelPart RTooth2;
    private final ModelPart LLEye;
    private final ModelPart LREye;
    private final ModelPart CLEye;
    private final ModelPart CREye;
    private final ModelPart RLEye;
    private final ModelPart RREye;
    private final ModelPart LHeadMane;
    private final ModelPart CHeadMane;
    private final ModelPart RHeadMane;
    private final ModelPart LLNoseSpike;
    private final ModelPart LRNoseSpike;
    private final ModelPart CLNoseSpike;
    private final ModelPart CRNoseSpike;
    private final ModelPart RLNoseSpike;
    private final ModelPart RRNoseSpike;
    private final ModelPart Back1;
    private final ModelPart Back2;
    private final ModelPart Lwing1;
    private final ModelPart Lwing2;
    private final ModelPart Lwing3;
    private final ModelPart Lwing4;
    private final ModelPart Lwing5;
    private final ModelPart Lwing6;
    private final ModelPart Lwing7;
    private final ModelPart Lwing9;
    private final ModelPart Lwing8;
    private final ModelPart Lwing10;
    private final ModelPart Rwing1;
    private final ModelPart Rwing2;
    private final ModelPart Rwing3;
    private final ModelPart Rwing4;
    private final ModelPart Rwing5;
    private final ModelPart Rwing6;
    private final ModelPart Rwing7;
    private final ModelPart Rwing8;
    private final ModelPart Rwing9;
    private final ModelPart Rwing10;
    private final ModelPart TailTip2;
    private final ModelPart Ridge1;
    private final ModelPart Ridge2;
    private final ModelPart Ridge3;
    private final ModelPart Ridge4;
    private final ModelPart Ridge5;
    private final ModelPart Ridge6;
    public ModelTheKing(float f1) {
        this(f1, LayerDefinition.create(createMesh(), 2048, 2048).bakeRoot());
    }

    public ModelTheKing(float wingspeed, ModelPart root) {
        this.wingspeed = wingspeed;
        this.LCClaw1 = root.getChild("LCClaw1");
        this.LThigh = root.getChild("LThigh");
        this.LUpperLeg = root.getChild("LUpperLeg");
        this.TailTip = root.getChild("TailTip");
        this.Tail1 = root.getChild("Tail1");
        this.Tail2 = root.getChild("Tail2");
        this.Tail3 = root.getChild("Tail3");
        this.Tail4 = root.getChild("Tail4");
        this.Tail5 = root.getChild("Tail5");
        this.Tail6 = root.getChild("Tail6");
        this.Tail7 = root.getChild("Tail7");
        this.Body1 = root.getChild("Body1");
        this.Chest = root.getChild("Chest");
        this.NeckC1 = root.getChild("NeckC1");
        this.LLowerLeg = root.getChild("LLowerLeg");
        this.LFoot = root.getChild("LFoot");
        this.LLClaw1 = root.getChild("LLClaw1");
        this.LRClaw1 = root.getChild("LRClaw1");
        this.LCClaw2 = root.getChild("LCClaw2");
        this.LLClaw2 = root.getChild("LLClaw2");
        this.TailSpike = root.getChild("TailSpike");
        this.LRClaw2 = root.getChild("LRClaw2");
        this.LClawRear = root.getChild("LClawRear");
        this.NeckL1 = root.getChild("NeckL1");
        this.NeckR1 = root.getChild("NeckR1");
        this.RThigh = root.getChild("RThigh");
        this.RUpperLeg = root.getChild("RUpperLeg");
        this.RLowerLeg = root.getChild("RLowerLeg");
        this.RFoot = root.getChild("RFoot");
        this.RClawRear = root.getChild("RClawRear");
        this.RLClaw1 = root.getChild("RLClaw1");
        this.RCClaw1 = root.getChild("RCClaw1");
        this.RRClaw1 = root.getChild("RRClaw1");
        this.RLClaw2 = root.getChild("RLClaw2");
        this.RCClaw2 = root.getChild("RCClaw2");
        this.RRClaw2 = root.getChild("RRClaw2");
        this.NeckL2 = root.getChild("NeckL2");
        this.NeckC2 = root.getChild("NeckC2");
        this.NeckR2 = root.getChild("NeckR2");
        this.NeckL3 = root.getChild("NeckL3");
        this.NeckC3 = root.getChild("NeckC3");
        this.NeckR3 = root.getChild("NeckR3");
        this.NeckL4 = root.getChild("NeckL4");
        this.LHead1 = root.getChild("LHead1");
        this.LHead2 = root.getChild("LHead2");
        this.LHead3 = root.getChild("LHead3");
        this.LJaw1 = root.getChild("LJaw1");
        this.LJaw2 = root.getChild("LJaw2");
        this.LJaw3 = root.getChild("LJaw3");
        this.LTooth1 = root.getChild("LTooth1");
        this.LTooth2 = root.getChild("LTooth2");
        this.LTooth3 = root.getChild("LTooth3");
        this.LTooth4 = root.getChild("LTooth4");
        this.NeckC4 = root.getChild("NeckC4");
        this.NeckR4 = root.getChild("NeckR4");
        this.CHead1 = root.getChild("CHead1");
        this.RHead1 = root.getChild("RHead1");
        this.CHead2 = root.getChild("CHead2");
        this.RHead2 = root.getChild("RHead2");
        this.CHead3 = root.getChild("CHead3");
        this.RHead3 = root.getChild("RHead3");
        this.CJaw1 = root.getChild("CJaw1");
        this.CJaw2 = root.getChild("CJaw2");
        this.CJaw3 = root.getChild("CJaw3");
        this.RJaw1 = root.getChild("RJaw1");
        this.RJaw2 = root.getChild("RJaw2");
        this.RJaw3 = root.getChild("RJaw3");
        this.CTooth3 = root.getChild("CTooth3");
        this.CTooth4 = root.getChild("CTooth4");
        this.CTooth1 = root.getChild("CTooth1");
        this.CTooth2 = root.getChild("CTooth2");
        this.RTooth3 = root.getChild("RTooth3");
        this.RTooth4 = root.getChild("RTooth4");
        this.RTooth1 = root.getChild("RTooth1");
        this.RTooth2 = root.getChild("RTooth2");
        this.LLEye = root.getChild("LLEye");
        this.LREye = root.getChild("LREye");
        this.CLEye = root.getChild("CLEye");
        this.CREye = root.getChild("CREye");
        this.RLEye = root.getChild("RLEye");
        this.RREye = root.getChild("RREye");
        this.LHeadMane = root.getChild("LHeadMane");
        this.CHeadMane = root.getChild("CHeadMane");
        this.RHeadMane = root.getChild("RHeadMane");
        this.LLNoseSpike = root.getChild("LLNoseSpike");
        this.LRNoseSpike = root.getChild("LRNoseSpike");
        this.CLNoseSpike = root.getChild("CLNoseSpike");
        this.CRNoseSpike = root.getChild("CRNoseSpike");
        this.RLNoseSpike = root.getChild("RLNoseSpike");
        this.RRNoseSpike = root.getChild("RRNoseSpike");
        this.Back1 = root.getChild("Back1");
        this.Back2 = root.getChild("Back2");
        this.Lwing1 = root.getChild("Lwing1");
        this.Lwing2 = root.getChild("Lwing2");
        this.Lwing3 = root.getChild("Lwing3");
        this.Lwing4 = root.getChild("Lwing4");
        this.Lwing5 = root.getChild("Lwing5");
        this.Lwing6 = root.getChild("Lwing6");
        this.Lwing7 = root.getChild("Lwing7");
        this.Lwing9 = root.getChild("Lwing9");
        this.Lwing8 = root.getChild("Lwing8");
        this.Lwing10 = root.getChild("Lwing10");
        this.Rwing1 = root.getChild("Rwing1");
        this.Rwing2 = root.getChild("Rwing2");
        this.Rwing3 = root.getChild("Rwing3");
        this.Rwing4 = root.getChild("Rwing4");
        this.Rwing5 = root.getChild("Rwing5");
        this.Rwing6 = root.getChild("Rwing6");
        this.Rwing7 = root.getChild("Rwing7");
        this.Rwing8 = root.getChild("Rwing8");
        this.Rwing9 = root.getChild("Rwing9");
        this.Rwing10 = root.getChild("Rwing10");
        this.TailTip2 = root.getChild("TailTip2");
        this.Ridge1 = root.getChild("Ridge1");
        this.Ridge2 = root.getChild("Ridge2");
        this.Ridge3 = root.getChild("Ridge3");
        this.Ridge4 = root.getChild("Ridge4");
        this.Ridge5 = root.getChild("Ridge5");
        this.Ridge6 = root.getChild("Ridge6");
    }
    public static MeshDefinition createMesh() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();
        partdefinition.addOrReplaceChild("LCClaw1", CubeListBuilder.create().texOffs(0, 1450).addBox(-5.0f, -5.0f, -20.0f, 10, 10, 20), PartPose.offsetAndRotation(52.0f, -2.0f, -7.0f, 0.3839724f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("LThigh", CubeListBuilder.create().texOffs(0, 1050).addBox(0.0f, -14.0f, -21.0f, 25, 34, 42), PartPose.offsetAndRotation(40.0f, -91.0f, 2.0f, 0.7853982f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("LUpperLeg", CubeListBuilder.create().texOffs(0, 1137).addBox(0.0f, 12.0f, -16.0f, 24, 52, 24), PartPose.offsetAndRotation(40.0f, -91.0f, 2.0f, 0.7853982f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("TailTip", CubeListBuilder.create().texOffs(500, 102).addBox(-51.0f, -3.0f, 0.0f, 100, 6, 36), PartPose.offsetAndRotation(0.0f, -86.0f, 308.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Tail1", CubeListBuilder.create().texOffs(500, 614).addBox(-32.0f, 0.0f, 0.0f, 64, 52, 58), PartPose.offsetAndRotation(0.0f, -114.0f, 29.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Tail2", CubeListBuilder.create().texOffs(500, 520).addBox(-25.0f, -19.0f, -3.0f, 50, 42, 46), PartPose.offsetAndRotation(0.0f, -90.0f, 79.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Tail3", CubeListBuilder.create().texOffs(500, 432).addBox(-20.0f, -18.0f, 0.0f, 40, 36, 45), PartPose.offsetAndRotation(0.0f, -88.0f, 117.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Tail4", CubeListBuilder.create().texOffs(500, 355).addBox(-16.0f, -15.0f, 0.0f, 32, 30, 38), PartPose.offsetAndRotation(0.0f, -87.0f, 156.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Tail5", CubeListBuilder.create().texOffs(500, 286).addBox(-13.0f, -12.0f, 0.0f, 26, 24, 38), PartPose.offsetAndRotation(0.0f, -87.0f, 189.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Tail6", CubeListBuilder.create().texOffs(500, 218).addBox(-10.0f, -9.0f, 0.0f, 20, 18, 44), PartPose.offsetAndRotation(0.0f, -87.0f, 222.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Tail7", CubeListBuilder.create().texOffs(500, 150).addBox(-8.0f, -6.0f, -7.0f, 16, 12, 49), PartPose.offsetAndRotation(0.0f, -87.0f, 268.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Body1", CubeListBuilder.create().texOffs(500, 732).addBox(-40.0f, -32.0f, -36.0f, 80, 64, 72), PartPose.offsetAndRotation(0.0f, -89.0f, 1.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Chest", CubeListBuilder.create().texOffs(0, 73).addBox(-41.0f, -32.0f, -60.0f, 82, 44, 60), PartPose.offsetAndRotation(0.0f, -91.0f, -22.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("NeckC1", CubeListBuilder.create().texOffs(700, 1100).addBox(-12.0f, -12.0f, -24.0f, 24, 24, 24), PartPose.offsetAndRotation(0.0f, -113.0f, -76.0f, -0.1047198f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("LLowerLeg", CubeListBuilder.create().texOffs(0, 1220).addBox(-11.0f, 0.0f, -10.0f, 22, 59, 20), PartPose.offsetAndRotation(52.0f, -52.0f, 36.0f, -0.6283185f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("LFoot", CubeListBuilder.create().texOffs(0, 1307).addBox(-18.0f, 59.0f, -10.0f, 36, 12, 20), PartPose.offsetAndRotation(52.0f, -52.0f, 36.0f, -0.6283185f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("LLClaw1", CubeListBuilder.create().texOffs(0, 1400).addBox(-5.0f, -5.0f, -20.0f, 10, 10, 20), PartPose.offsetAndRotation(67.0f, -2.0f, -7.0f, 0.3839724f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("LRClaw1", CubeListBuilder.create().texOffs(0, 1500).addBox(-5.0f, -5.0f, -20.0f, 10, 10, 20), PartPose.offsetAndRotation(37.0f, -2.0f, -7.0f, 0.3839724f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("LCClaw2", CubeListBuilder.create().texOffs(0, 1600).addBox(-2.0f, -7.0f, -46.0f, 4, 7, 28), PartPose.offsetAndRotation(52.0f, -2.0f, -7.0f, 0.6457718f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("LLClaw2", CubeListBuilder.create().texOffs(0, 1550).addBox(-2.0f, -7.0f, -46.0f, 4, 7, 28), PartPose.offsetAndRotation(67.0f, -2.0f, -7.0f, 0.6457718f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("TailSpike", CubeListBuilder.create().texOffs(500, 0).addBox(-2.0f, -1.0f, -7.0f, 4, 4, 53), PartPose.offsetAndRotation(0.0f, -87.0f, 375.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("LRClaw2", CubeListBuilder.create().texOffs(0, 1650).addBox(-2.0f, -7.0f, -46.0f, 4, 7, 28), PartPose.offsetAndRotation(37.0f, -2.0f, -7.0f, 0.6457718f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("LClawRear", CubeListBuilder.create().texOffs(0, 1350).addBox(-2.0f, -3.0f, 0.0f, 4, 9, 28), PartPose.offsetAndRotation(52.0f, 4.0f, 4.0f, -0.9250245f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("NeckL1", CubeListBuilder.create().texOffs(500, 1100).addBox(-12.0f, -12.0f, -24.0f, 24, 24, 24), PartPose.offsetAndRotation(30.0f, -113.0f, -76.0f, -0.0523599f, -0.1047198f, 0.0f));
        partdefinition.addOrReplaceChild("NeckR1", CubeListBuilder.create().texOffs(900, 1100).addBox(-12.0f, -12.0f, -24.0f, 24, 24, 24), PartPose.offsetAndRotation(-30.0f, -113.0f, -76.0f, -0.0523599f, 0.1047198f, 0.0f));
        partdefinition.addOrReplaceChild("RThigh", CubeListBuilder.create().texOffs(200, 1050).addBox(0.0f, -14.0f, -21.0f, 25, 34, 42), PartPose.offsetAndRotation(-65.0f, -91.0f, 2.0f, 0.7853982f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RUpperLeg", CubeListBuilder.create().texOffs(200, 1137).addBox(0.0f, 12.0f, -16.0f, 24, 52, 24), PartPose.offsetAndRotation(-64.0f, -91.0f, 2.0f, 0.7853982f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RLowerLeg", CubeListBuilder.create().texOffs(200, 1220).addBox(-4.0f, 0.0f, -10.0f, 22, 59, 20), PartPose.offsetAndRotation(-59.0f, -52.0f, 36.0f, -0.6283185f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RFoot", CubeListBuilder.create().texOffs(200, 1307).addBox(-11.0f, 59.0f, -10.0f, 36, 12, 20), PartPose.offsetAndRotation(-59.0f, -52.0f, 36.0f, -0.6283185f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RClawRear", CubeListBuilder.create().texOffs(200, 1350).addBox(-2.0f, -3.0f, 0.0f, 4, 9, 28), PartPose.offsetAndRotation(-52.0f, 4.0f, 4.0f, -0.9250245f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RLClaw1", CubeListBuilder.create().texOffs(200, 1400).addBox(-5.0f, -5.0f, -20.0f, 10, 10, 20), PartPose.offsetAndRotation(-37.0f, -2.0f, -7.0f, 0.3839724f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RCClaw1", CubeListBuilder.create().texOffs(200, 1450).addBox(-5.0f, -5.0f, -20.0f, 10, 10, 20), PartPose.offsetAndRotation(-52.0f, -2.0f, -7.0f, 0.3839724f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RRClaw1", CubeListBuilder.create().texOffs(200, 1500).addBox(-5.0f, -5.0f, -20.0f, 10, 10, 20), PartPose.offsetAndRotation(-67.0f, -2.0f, -7.0f, 0.3839724f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RLClaw2", CubeListBuilder.create().texOffs(200, 1550).addBox(-2.0f, -7.0f, -46.0f, 4, 7, 28), PartPose.offsetAndRotation(-37.0f, -2.0f, -7.0f, 0.6457718f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RCClaw2", CubeListBuilder.create().texOffs(200, 1600).addBox(-2.0f, -7.0f, -46.0f, 4, 7, 28), PartPose.offsetAndRotation(-52.0f, -2.0f, -7.0f, 0.6457718f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RRClaw2", CubeListBuilder.create().texOffs(200, 1650).addBox(-2.0f, -7.0f, -46.0f, 4, 7, 28), PartPose.offsetAndRotation(-67.0f, -2.0f, -7.0f, 0.6457718f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("NeckL2", CubeListBuilder.create().texOffs(500, 1154).addBox(-11.0f, -11.0f, -40.0f, 22, 22, 40), PartPose.offsetAndRotation(32.0f, -114.0f, -95.0f, 0.0f, -0.1745329f, 0.0f));
        partdefinition.addOrReplaceChild("NeckC2", CubeListBuilder.create().texOffs(700, 1154).addBox(-11.0f, -11.0f, -40.0f, 22, 22, 40), PartPose.offsetAndRotation(0.0f, -115.0f, -95.0f, -0.1570796f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("NeckR2", CubeListBuilder.create().texOffs(900, 1154).addBox(-11.0f, -11.0f, -40.0f, 22, 22, 40), PartPose.offsetAndRotation(-32.0f, -114.0f, -95.0f, -0.0523599f, 0.1745329f, 0.0f));
        partdefinition.addOrReplaceChild("NeckL3", CubeListBuilder.create().texOffs(500, 1222).addBox(-10.0f, -10.0f, -40.0f, 20, 20, 40), PartPose.offsetAndRotation(38.0f, -114.0f, -131.0f, 0.0698132f, -0.2617994f, 0.0f));
        partdefinition.addOrReplaceChild("NeckC3", CubeListBuilder.create().texOffs(700, 1222).addBox(-10.0f, -10.0f, -40.0f, 20, 20, 40), PartPose.offsetAndRotation(0.0f, -120.0f, -131.0f, -0.2094395f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("NeckR3", CubeListBuilder.create().texOffs(900, 1222).addBox(-10.0f, -10.0f, -40.0f, 20, 20, 40), PartPose.offsetAndRotation(-37.0f, -116.0f, -128.0f, -0.0523599f, 0.3141593f, 0.0f));
        partdefinition.addOrReplaceChild("NeckL4", CubeListBuilder.create().texOffs(500, 1300).addBox(-9.0f, -9.0f, -40.0f, 18, 18, 40), PartPose.offsetAndRotation(46.0f, -112.0f, -163.0f, 0.1396263f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("LHead1", CubeListBuilder.create().texOffs(500, 1425).addBox(-13.0f, -13.0f, -30.0f, 26, 26, 30), PartPose.offsetAndRotation(59.0f, -114.0f, -195.0f, 0.1396263f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("LHead2", CubeListBuilder.create().texOffs(500, 1550).addBox(-10.0f, -7.0f, -58.0f, 20, 20, 28), PartPose.offsetAndRotation(59.0f, -114.0f, -195.0f, 0.1396263f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("LHead3", CubeListBuilder.create().texOffs(500, 1605).addBox(-8.0f, -3.0f, -83.0f, 16, 16, 26), PartPose.offsetAndRotation(59.0f, -114.0f, -195.0f, 0.1396263f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("LJaw1", CubeListBuilder.create().texOffs(500, 1660).addBox(-14.0f, -2.0f, -14.0f, 28, 7, 16), PartPose.offsetAndRotation(59.0f, -100.0f, -196.0f, 0.2443461f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("LJaw2", CubeListBuilder.create().texOffs(500, 1700).addBox(-12.0f, -2.0f, -55.0f, 24, 6, 46), PartPose.offsetAndRotation(59.0f, -100.0f, -196.0f, 0.2443461f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("LJaw3", CubeListBuilder.create().texOffs(500, 1765).addBox(-10.0f, -2.0f, -77.0f, 20, 6, 22), PartPose.offsetAndRotation(59.0f, -100.0f, -196.0f, 0.2443461f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("LTooth1", CubeListBuilder.create().texOffs(10, 0).addBox(-10.0f, -10.0f, -77.0f, 2, 8, 2), PartPose.offsetAndRotation(59.0f, -100.0f, -196.0f, 0.2443461f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("LTooth2", CubeListBuilder.create().texOffs(20, 0).addBox(8.0f, -10.0f, -77.0f, 2, 8, 2), PartPose.offsetAndRotation(59.0f, -100.0f, -196.0f, 0.2443461f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("LTooth3", CubeListBuilder.create().texOffs(30, 0).addBox(-12.0f, -8.0f, -55.0f, 2, 6, 2), PartPose.offsetAndRotation(59.0f, -100.0f, -196.0f, 0.2443461f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("LTooth4", CubeListBuilder.create().texOffs(40, 0).addBox(10.0f, -8.0f, -55.0f, 2, 6, 2), PartPose.offsetAndRotation(59.0f, -100.0f, -196.0f, 0.2443461f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("NeckC4", CubeListBuilder.create().texOffs(700, 1300).addBox(-9.0f, -9.0f, -40.0f, 18, 18, 40), PartPose.offsetAndRotation(0.0f, -126.0f, -162.0f, -0.2617994f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("NeckR4", CubeListBuilder.create().texOffs(900, 1300).addBox(-9.0f, -9.0f, -40.0f, 18, 18, 40), PartPose.offsetAndRotation(-47.0f, -118.0f, -161.0f, -0.1047198f, 0.3665191f, 0.0f));
        partdefinition.addOrReplaceChild("CHead1", CubeListBuilder.create().texOffs(700, 1425).addBox(-13.0f, -13.0f, -30.0f, 26, 26, 30), PartPose.offsetAndRotation(0.0f, -141.0f, -195.0f, -0.296706f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RHead1", CubeListBuilder.create().texOffs(900, 1425).addBox(-13.0f, -13.0f, -30.0f, 26, 26, 30), PartPose.offsetAndRotation(-60.0f, -128.0f, -195.0f, -0.122173f, 0.418879f, 0.0f));
        partdefinition.addOrReplaceChild("CHead2", CubeListBuilder.create().texOffs(700, 1550).addBox(-10.0f, -7.0f, -58.0f, 20, 20, 28), PartPose.offsetAndRotation(0.0f, -141.0f, -195.0f, -0.296706f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RHead2", CubeListBuilder.create().texOffs(900, 1550).addBox(-10.0f, -7.0f, -58.0f, 20, 20, 28), PartPose.offsetAndRotation(-60.0f, -128.0f, -195.0f, -0.122173f, 0.418879f, 0.0f));
        partdefinition.addOrReplaceChild("CHead3", CubeListBuilder.create().texOffs(700, 1605).addBox(-8.0f, -3.0f, -83.0f, 16, 16, 26), PartPose.offsetAndRotation(0.0f, -141.0f, -195.0f, -0.296706f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RHead3", CubeListBuilder.create().texOffs(900, 1605).addBox(-8.0f, -3.0f, -83.0f, 16, 16, 26), PartPose.offsetAndRotation(-60.0f, -128.0f, -195.0f, -0.122173f, 0.418879f, 0.0f));
        partdefinition.addOrReplaceChild("CJaw1", CubeListBuilder.create().texOffs(700, 1660).addBox(-14.0f, -2.0f, -14.0f, 28, 7, 16), PartPose.offsetAndRotation(0.0f, -130.0f, -201.0f, -0.1047198f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("CJaw2", CubeListBuilder.create().texOffs(700, 1700).addBox(-12.0f, -2.0f, -55.0f, 24, 6, 46), PartPose.offsetAndRotation(0.0f, -130.0f, -201.0f, -0.1047198f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("CJaw3", CubeListBuilder.create().texOffs(700, 1765).addBox(-10.0f, -2.0f, -77.0f, 20, 6, 22), PartPose.offsetAndRotation(0.0f, -130.0f, -201.0f, -0.1047198f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RJaw1", CubeListBuilder.create().texOffs(900, 1660).addBox(-14.0f, -2.0f, -14.0f, 28, 7, 16), PartPose.offsetAndRotation(-62.0f, -115.0f, -200.0f, 0.1570796f, 0.418879f, 0.0f));
        partdefinition.addOrReplaceChild("RJaw2", CubeListBuilder.create().texOffs(900, 1700).addBox(-12.0f, -2.0f, -55.0f, 24, 6, 46), PartPose.offsetAndRotation(-62.0f, -115.0f, -200.0f, 0.1570796f, 0.418879f, 0.0f));
        partdefinition.addOrReplaceChild("RJaw3", CubeListBuilder.create().texOffs(900, 1765).addBox(-10.0f, -2.0f, -77.0f, 20, 6, 22), PartPose.offsetAndRotation(-62.0f, -115.0f, -200.0f, 0.1570796f, 0.418879f, 0.0f));
        partdefinition.addOrReplaceChild("CTooth3", CubeListBuilder.create().texOffs(70, 0).addBox(-12.0f, -8.0f, -55.0f, 2, 6, 2), PartPose.offsetAndRotation(0.0f, -130.0f, -201.0f, -0.1047198f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("CTooth4", CubeListBuilder.create().texOffs(80, 0).addBox(10.0f, -8.0f, -55.0f, 2, 6, 2), PartPose.offsetAndRotation(0.0f, -130.0f, -201.0f, -0.1047198f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("CTooth1", CubeListBuilder.create().texOffs(50, 0).addBox(-10.0f, -10.0f, -77.0f, 2, 8, 2), PartPose.offsetAndRotation(0.0f, -130.0f, -201.0f, -0.1047198f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("CTooth2", CubeListBuilder.create().texOffs(60, 0).addBox(8.0f, -10.0f, -77.0f, 2, 8, 2), PartPose.offsetAndRotation(0.0f, -130.0f, -201.0f, -0.1047198f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RTooth3", CubeListBuilder.create().texOffs(110, 0).addBox(-12.0f, -8.0f, -55.0f, 2, 6, 2), PartPose.offsetAndRotation(-62.0f, -115.0f, -200.0f, 0.1570796f, 0.418879f, 0.0f));
        partdefinition.addOrReplaceChild("RTooth4", CubeListBuilder.create().texOffs(120, 0).addBox(10.0f, -8.0f, -55.0f, 2, 6, 2), PartPose.offsetAndRotation(-62.0f, -115.0f, -200.0f, 0.1570796f, 0.418879f, 0.0f));
        partdefinition.addOrReplaceChild("RTooth1", CubeListBuilder.create().texOffs(90, 0).addBox(-10.0f, -10.0f, -77.0f, 2, 8, 2), PartPose.offsetAndRotation(-62.0f, -115.0f, -200.0f, 0.1570796f, 0.418879f, 0.0f));
        partdefinition.addOrReplaceChild("RTooth2", CubeListBuilder.create().texOffs(100, 0).addBox(8.0f, -10.0f, -77.0f, 2, 8, 2), PartPose.offsetAndRotation(-62.0f, -115.0f, -200.0f, 0.1570796f, 0.418879f, 0.0f));
        partdefinition.addOrReplaceChild("LLEye", CubeListBuilder.create().texOffs(500, 1500).addBox(13.0f, -12.0f, -29.0f, 2, 6, 10), PartPose.offsetAndRotation(59.0f, -114.0f, -195.0f, 0.1396263f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("LREye", CubeListBuilder.create().texOffs(533, 1500).addBox(-15.0f, -12.0f, -29.0f, 2, 6, 10), PartPose.offsetAndRotation(59.0f, -114.0f, -195.0f, 0.1396263f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("CLEye", CubeListBuilder.create().texOffs(700, 1500).addBox(13.0f, -12.0f, -29.0f, 2, 6, 10), PartPose.offsetAndRotation(0.0f, -141.0f, -195.0f, -0.296706f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("CREye", CubeListBuilder.create().texOffs(733, 1500).addBox(-15.0f, -12.0f, -29.0f, 2, 6, 10), PartPose.offsetAndRotation(0.0f, -141.0f, -195.0f, -0.296706f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RLEye", CubeListBuilder.create().texOffs(900, 1500).addBox(13.0f, -12.0f, -29.0f, 2, 6, 10), PartPose.offsetAndRotation(-60.0f, -128.0f, -195.0f, -0.122173f, 0.418879f, 0.0f));
        partdefinition.addOrReplaceChild("RREye", CubeListBuilder.create().texOffs(933, 1500).addBox(-15.0f, -12.0f, -29.0f, 2, 5, 10), PartPose.offsetAndRotation(-60.0f, -128.0f, -195.0f, -0.122173f, 0.418879f, 0.0f));
        partdefinition.addOrReplaceChild("LHeadMane", CubeListBuilder.create().texOffs(500, 1375).addBox(0.0f, -14.0f, 0.0f, 1, 23, 19), PartPose.offsetAndRotation(59.0f, -114.0f, -195.0f, 0.5235988f, -0.3839724f, 0.0f));
        partdefinition.addOrReplaceChild("CHeadMane", CubeListBuilder.create().texOffs(700, 1375).addBox(0.0f, -14.0f, 0.0f, 1, 23, 19), PartPose.offsetAndRotation(0.0f, -141.0f, -195.0f, 0.1047198f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("RHeadMane", CubeListBuilder.create().texOffs(900, 1375).addBox(0.0f, -14.0f, 0.0f, 1, 23, 19), PartPose.offsetAndRotation(-60.0f, -128.0f, -195.0f, 0.3665191f, 0.418879f, 0.0f));
        partdefinition.addOrReplaceChild("LLNoseSpike", CubeListBuilder.create().texOffs(0, 300).addBox(24.0f, -23.0f, -76.0f, 1, 1, 17), PartPose.offsetAndRotation(59.0f, -114.0f, -195.0f, 0.4014257f, -0.1570796f, 0.0f));
        partdefinition.addOrReplaceChild("LRNoseSpike", CubeListBuilder.create().texOffs(0, 325).addBox(-26.0f, -24.0f, -75.0f, 1, 1, 17), PartPose.offsetAndRotation(59.0f, -114.0f, -195.0f, 0.418879f, -0.6283185f, 0.0f));
        partdefinition.addOrReplaceChild("CLNoseSpike", CubeListBuilder.create().texOffs(0, 350).addBox(24.0f, -23.0f, -76.0f, 1, 1, 17), PartPose.offsetAndRotation(0.0f, -141.0f, -195.0f, -0.0523599f, 0.2443461f, 0.0f));
        partdefinition.addOrReplaceChild("CRNoseSpike", CubeListBuilder.create().texOffs(0, 375).addBox(-26.0f, -24.0f, -75.0f, 1, 1, 17), PartPose.offsetAndRotation(0.0f, -141.0f, -195.0f, -0.0349066f, -0.2617994f, 0.0f));
        partdefinition.addOrReplaceChild("RLNoseSpike", CubeListBuilder.create().texOffs(0, 400).addBox(24.0f, -23.0f, -76.0f, 1, 1, 17), PartPose.offsetAndRotation(-60.0f, -128.0f, -195.0f, 0.1396263f, 0.6457718f, 0.0f));
        partdefinition.addOrReplaceChild("RRNoseSpike", CubeListBuilder.create().texOffs(0, 425).addBox(-26.0f, -24.0f, -75.0f, 1, 1, 17), PartPose.offsetAndRotation(-60.0f, -128.0f, -195.0f, 0.1570796f, 0.1745329f, 0.0f));
        partdefinition.addOrReplaceChild("Back1", CubeListBuilder.create().texOffs(167, 186).addBox(0.0f, 0.0f, 0.0f, 30, 15, 49), PartPose.offsetAndRotation(-45.0f, -127.0f, -58.0f, -0.0698132f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Back2", CubeListBuilder.create().texOffs(0, 186).addBox(0.0f, 0.0f, 0.0f, 30, 15, 49), PartPose.offsetAndRotation(15.0f, -127.0f, -58.0f, -0.0698132f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Lwing1", CubeListBuilder.create().texOffs(250, 1000).addBox(0.0f, 0.0f, 0.0f, 87, 5, 5), PartPose.offsetAndRotation(40.0f, -121.0f, -50.0f, 0.0f, 0.0349066f, 0.0f));
        partdefinition.addOrReplaceChild("Lwing2", CubeListBuilder.create().texOffs(1220, 782).addBox(0.0f, 2.0f, 0.0f, 87, 1, 110), PartPose.offsetAndRotation(40.0f, -121.0f, -49.0f, 0.0f, 0.0349066f, 0.0f));
        partdefinition.addOrReplaceChild("Lwing3", CubeListBuilder.create().texOffs(250, 975).addBox(0.0f, 0.0f, 0.0f, 188, 5, 5), PartPose.offsetAndRotation(124.0f, -121.0f, -53.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Lwing4", CubeListBuilder.create().texOffs(1341, 625).addBox(0.0f, 2.0f, 0.0f, 188, 1, 147), PartPose.offsetAndRotation(124.0f, -121.0f, -50.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Lwing5", CubeListBuilder.create().texOffs(245, 950).addBox(0.0f, 0.0f, 0.0f, 87, 5, 5), PartPose.offsetAndRotation(309.0f, -121.0f, -53.0f, 0.0f, -0.0349066f, 0.0f));
        partdefinition.addOrReplaceChild("Lwing6", CubeListBuilder.create().texOffs(1300, 1300).addBox(0.0f, 2.0f, 1.0f, 87, 1, 125), PartPose.offsetAndRotation(309.0f, -121.0f, -50.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Lwing7", CubeListBuilder.create().texOffs(250, 900).addBox(0.0f, 0.0f, 0.0f, 150, 5, 5), PartPose.offsetAndRotation(124.0f, -121.0f, -53.0f, 0.0f, 0.0f, 0.2617994f));
        partdefinition.addOrReplaceChild("Lwing9", CubeListBuilder.create().texOffs(250, 925).addBox(0.0f, 0.0f, 0.0f, 175, 5, 5), PartPose.offsetAndRotation(124.0f, -121.0f, -53.0f, 0.0f, 0.0f, -0.2617994f));
        partdefinition.addOrReplaceChild("Lwing8", CubeListBuilder.create().texOffs(1300, 1156).addBox(0.0f, 2.0f, 0.0f, 150, 1, 120), PartPose.offsetAndRotation(124.0f, -121.0f, -50.0f, 0.0f, 0.0f, 0.2617994f));
        partdefinition.addOrReplaceChild("Lwing10", CubeListBuilder.create().texOffs(1392, 326).addBox(0.0f, 2.0f, 0.0f, 176, 1, 136), PartPose.offsetAndRotation(124.0f, -121.0f, -50.0f, 0.0f, 0.0f, -0.2617994f));
        partdefinition.addOrReplaceChild("Rwing1", CubeListBuilder.create().texOffs(650, 1000).addBox(-87.0f, 0.0f, 0.0f, 87, 5, 5), PartPose.offsetAndRotation(-40.0f, -121.0f, -50.0f, 0.0f, -0.0349066f, 0.0f));
        partdefinition.addOrReplaceChild("Rwing2", CubeListBuilder.create().texOffs(1619, 782).addBox(-87.0f, 2.0f, 0.0f, 87, 1, 110), PartPose.offsetAndRotation(-40.0f, -121.0f, -49.0f, 0.0f, -0.0349066f, 0.0f));
        partdefinition.addOrReplaceChild("Rwing3", CubeListBuilder.create().texOffs(550, 950).addBox(-188.0f, 0.0f, 0.0f, 188, 5, 5), PartPose.offsetAndRotation(-124.0f, -121.0f, -53.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Rwing4", CubeListBuilder.create().texOffs(1341, 470).addBox(-188.0f, 2.0f, 0.0f, 188, 1, 147), PartPose.offsetAndRotation(-124.0f, -121.0f, -53.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Rwing5", CubeListBuilder.create().texOffs(750, 975).addBox(-87.0f, 0.0f, 0.0f, 87, 5, 5), PartPose.offsetAndRotation(-309.0f, -121.0f, -53.0f, 0.0f, 0.0349066f, 0.0f));
        partdefinition.addOrReplaceChild("Rwing6", CubeListBuilder.create().texOffs(1300, 1436).addBox(-87.0f, 2.0f, 1.0f, 87, 1, 125), PartPose.offsetAndRotation(-309.0f, -121.0f, -50.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Rwing7", CubeListBuilder.create().texOffs(650, 900).addBox(-150.0f, 0.0f, 0.0f, 150, 5, 5), PartPose.offsetAndRotation(-124.0f, -121.0f, -53.0f, 0.0f, 0.0f, -0.2617994f));
        partdefinition.addOrReplaceChild("Rwing8", CubeListBuilder.create().texOffs(1300, 1024).addBox(-150.0f, 2.0f, 0.0f, 150, 1, 120), PartPose.offsetAndRotation(-124.0f, -121.0f, -53.0f, 0.0f, 0.0f, -0.2617994f));
        partdefinition.addOrReplaceChild("Rwing9", CubeListBuilder.create().texOffs(621, 925).addBox(-175.0f, 0.0f, 0.0f, 175, 5, 5), PartPose.offsetAndRotation(-124.0f, -121.0f, -53.0f, 0.0f, 0.0f, 0.2617994f));
        partdefinition.addOrReplaceChild("Rwing10", CubeListBuilder.create().texOffs(1391, 184).addBox(-176.0f, 2.0f, 0.0f, 176, 1, 136), PartPose.offsetAndRotation(-124.0f, -121.0f, -53.0f, 0.0f, 0.0f, 0.2617994f));
        partdefinition.addOrReplaceChild("TailTip2", CubeListBuilder.create().texOffs(500, 63).addBox(-35.0f, -2.0f, 36.0f, 70, 4, 26), PartPose.offsetAndRotation(0.0f, -86.0f, 308.0f, 0.0f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Ridge1", CubeListBuilder.create().texOffs(850, 717).addBox(-1.0f, 0.0f, 0.0f, 3, 10, 24), PartPose.offsetAndRotation(0.0f, -122.0f, -75.0f, 0.3665191f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Ridge2", CubeListBuilder.create().texOffs(850, 676).addBox(-1.0f, 0.0f, 0.0f, 3, 10, 24), PartPose.offsetAndRotation(0.0f, -122.0f, -50.0f, 0.3665191f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Ridge3", CubeListBuilder.create().texOffs(800, 600).addBox(-1.0f, 0.0f, 0.0f, 3, 20, 49), PartPose.offsetAndRotation(0.0f, -120.0f, -20.0f, 0.3665191f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Ridge4", CubeListBuilder.create().texOffs(800, 550).addBox(-1.0f, 3.0f, 9.0f, 3, 10, 22), PartPose.offsetAndRotation(0.0f, -114.0f, 29.0f, 0.3665191f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Ridge5", CubeListBuilder.create().texOffs(800, 500).addBox(-1.0f, 13.0f, 33.0f, 3, 10, 20), PartPose.offsetAndRotation(0.0f, -114.0f, 29.0f, 0.3665191f, 0.0f, 0.0f));
        partdefinition.addOrReplaceChild("Ridge6", CubeListBuilder.create().texOffs(638, 165).addBox(-1.0f, 2.0f, 20.0f, 3, 10, 20), PartPose.offsetAndRotation(0.0f, -87.0f, 268.0f, 0.3665191f, 0.0f, 0.0f));
        return meshdefinition;
    }
    @Override
    public void setupAnim(TheKing entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.animEntity = entity;
        this.animAgeInTicks = ageInTicks;
        this.animLimbSwingAmount = limbSwingAmount;
        this.animNetHeadYaw = netHeadYaw;
        this.animHeadPitch = headPitch;
    }

    @Override
    public void renderToBuffer(PoseStack poseStack, VertexConsumer buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        TheKing entity = this.animEntity;
        float ageInTicks = this.animAgeInTicks;
        float limbSwingAmount = this.animLimbSwingAmount;
        float netHeadYaw = this.animNetHeadYaw;
        float headPitch = this.animHeadPitch;
float newangle = 0.0f;
                float tailspeed = 0.26f;
        float tailamp = 0.08f;
        float pi4 = 0.7853982f;
        float Lheadlr = 0.0f;
        float Lheadud = 0.0f;
        float Ljawangle = 0.0f;
        float Cheadlr = 0.0f;
        float Cheadud = 0.0f;
        float Cjawangle = 0.0f;
        float Rheadlr = 0.0f;
        float Rheadud = 0.0f;
        float Rjawangle = 0.0f;
                newangle = entity.getAttacking() != 0 ? Mth.cos((float)(ageInTicks * 0.75f * this.wingspeed)) * 3.1415927f * 0.21f : Mth.cos((float)(ageInTicks * 0.35f * this.wingspeed)) * 3.1415927f * 0.15f;
        this.Lwing1.zRot = newangle;
        this.Lwing2.zRot = newangle;
        this.Lwing3.zRot = newangle * 5.0f / 3.0f;
        this.Lwing3.y = this.Lwing1.y + (float)Math.sin(this.Lwing1.zRot) * 84.0f;
        this.Lwing3.x = this.Lwing1.x + (float)Math.cos(this.Lwing1.zRot) * 84.0f;
        this.Lwing4.zRot = this.Lwing3.zRot;
        this.Lwing4.y = this.Lwing3.y;
        this.Lwing4.x = this.Lwing3.x;
        this.Lwing5.zRot = newangle * 7.0f / 3.0f;
        this.Lwing5.y = this.Lwing3.y + (float)Math.sin(this.Lwing3.zRot) * 184.0f;
        this.Lwing5.x = this.Lwing3.x + (float)Math.cos(this.Lwing3.zRot) * 184.0f;
        this.Lwing6.zRot = this.Lwing5.zRot;
        this.Lwing6.y = this.Lwing5.y;
        this.Lwing6.x = this.Lwing5.x;
        this.Lwing7.y = this.Lwing9.y = this.Lwing3.y;
        this.Lwing7.x = this.Lwing9.x = this.Lwing3.x;
        this.Lwing8.y = this.Lwing10.y = this.Lwing3.y;
        this.Lwing8.x = this.Lwing10.x = this.Lwing3.x;
        this.Lwing7.zRot = this.Lwing8.zRot = 0.261f + this.Lwing3.zRot;
        this.Lwing9.zRot = this.Lwing10.zRot = -0.261f + this.Lwing3.zRot;
        this.Rwing1.zRot = - newangle;
        this.Rwing2.zRot = - newangle;
        this.Rwing3.zRot = (- newangle) * 5.0f / 3.0f;
        this.Rwing3.y = this.Rwing1.y - (float)Math.sin(this.Rwing1.zRot) * 84.0f;
        this.Rwing3.x = this.Rwing1.x - (float)Math.cos(this.Rwing1.zRot) * 84.0f;
        this.Rwing4.zRot = this.Rwing3.zRot;
        this.Rwing4.y = this.Rwing3.y;
        this.Rwing4.x = this.Rwing3.x;
        this.Rwing5.zRot = (- newangle) * 7.0f / 3.0f;
        this.Rwing5.y = this.Rwing3.y - (float)Math.sin(this.Rwing3.zRot) * 184.0f;
        this.Rwing5.x = this.Rwing3.x - (float)Math.cos(this.Rwing3.zRot) * 184.0f;
        this.Rwing6.zRot = this.Rwing5.zRot;
        this.Rwing6.y = this.Rwing5.y;
        this.Rwing6.x = this.Rwing5.x;
        this.Rwing7.y = this.Rwing9.y = this.Rwing3.y;
        this.Rwing7.x = this.Rwing9.x = this.Rwing3.x;
        this.Rwing8.y = this.Rwing10.y = this.Rwing3.y;
        this.Rwing8.x = this.Rwing10.x = this.Rwing3.x;
        this.Rwing7.zRot = this.Rwing8.zRot = -0.261f + this.Rwing3.zRot;
        this.Rwing9.zRot = this.Rwing10.zRot = 0.261f + this.Rwing3.zRot;
        newangle = entity.getAttacking() != 0 ? Mth.cos((float)(ageInTicks * 0.75f * this.wingspeed)) * 3.1415927f * 0.25f : 0.0f;
        this.LClawRear.xRot = this.RClawRear.xRot = -0.925f + newangle;
        this.LLClaw1.xRot = 0.384f - newangle;
        this.LLClaw2.xRot = 0.645f - newangle;
        this.LCClaw1.xRot = 0.384f - newangle;
        this.LCClaw2.xRot = 0.645f - newangle;
        this.LRClaw1.xRot = 0.384f - newangle;
        this.LRClaw2.xRot = 0.645f - newangle;
        this.RLClaw1.xRot = 0.384f - newangle;
        this.RLClaw2.xRot = 0.645f - newangle;
        this.RCClaw1.xRot = 0.384f - newangle;
        this.RCClaw2.xRot = 0.645f - newangle;
        this.RRClaw1.xRot = 0.384f - newangle;
        this.RRClaw2.xRot = 0.645f - newangle;
        newangle = entity.getAttacking() != 0 ? Mth.cos((float)(ageInTicks * 0.6f * this.wingspeed)) * 3.1415927f * 0.45f : 0.0f;
        this.LThigh.xRot = this.LUpperLeg.xRot = 0.785f + newangle / 4.0f;
        this.LLowerLeg.xRot = this.LFoot.xRot = -0.628f + newangle / 2.0f;
        this.LLowerLeg.y = this.LFoot.y = this.LUpperLeg.y + (float)Math.cos(this.LUpperLeg.xRot) * 50.0f;
        this.LLowerLeg.z = this.LFoot.z = this.LUpperLeg.z + (float)Math.sin(this.LUpperLeg.xRot) * 50.0f;
        this.LLClaw1.y = this.LLClaw2.y = this.LLowerLeg.y + (float)Math.cos(this.LLowerLeg.xRot - 0.1f) * 66.0f;
        this.LLClaw1.z = this.LLClaw2.z = this.LLowerLeg.z + (float)Math.sin(this.LLowerLeg.xRot - 0.1f) * 66.0f;
        this.LCClaw1.y = this.LCClaw2.y = this.LLClaw1.y;
        this.LRClaw1.y = this.LRClaw2.y = this.LLClaw1.y;
        this.LCClaw1.z = this.LCClaw2.z = this.LLClaw1.z;
        this.LRClaw1.z = this.LRClaw2.z = this.LLClaw1.z;
        this.LClawRear.y = this.LLowerLeg.y + (float)Math.cos(this.LLowerLeg.xRot + 0.15f) * 66.0f;
        this.LClawRear.z = this.LLowerLeg.z + (float)Math.sin(this.LLowerLeg.xRot + 0.15f) * 66.0f;
        this.RThigh.xRot = this.RUpperLeg.xRot = 0.785f - newangle / 4.0f;
        this.RLowerLeg.xRot = this.RFoot.xRot = -0.628f - newangle / 2.0f;
        this.RLowerLeg.y = this.RFoot.y = this.RUpperLeg.y + (float)Math.cos(this.RUpperLeg.xRot) * 50.0f;
        this.RLowerLeg.z = this.RFoot.z = this.RUpperLeg.z + (float)Math.sin(this.RUpperLeg.xRot) * 50.0f;
        this.RLClaw1.y = this.RLClaw2.y = this.RLowerLeg.y + (float)Math.cos(this.RLowerLeg.xRot - 0.1f) * 66.0f;
        this.RLClaw1.z = this.RLClaw2.z = this.RLowerLeg.z + (float)Math.sin(this.RLowerLeg.xRot - 0.1f) * 66.0f;
        this.RCClaw1.y = this.RCClaw2.y = this.RLClaw1.y;
        this.RRClaw1.y = this.RRClaw2.y = this.RLClaw1.y;
        this.RCClaw1.z = this.RCClaw2.z = this.RLClaw1.z;
        this.RRClaw1.z = this.RRClaw2.z = this.RLClaw1.z;
        this.RClawRear.y = this.RLowerLeg.y + (float)Math.cos(this.RLowerLeg.xRot + 0.15f) * 66.0f;
        this.RClawRear.z = this.RLowerLeg.z + (float)Math.sin(this.RLowerLeg.xRot + 0.15f) * 66.0f;
        if (entity.getAttacking() != 0) {
            tailspeed = 0.56f;
            tailamp = 0.19f;
        }
        this.Ridge4.yRot = this.Ridge5.yRot = (this.Tail1.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed)) * 3.1415927f * tailamp / 2.0f);
        this.Tail2.z = this.Tail1.z + (float)Math.cos(this.Tail1.yRot) * 54.0f;
        this.Tail2.x = this.Tail1.x - 1.0f + (float)Math.sin(this.Tail1.yRot) * 54.0f;
        this.Tail2.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed - pi4)) * 3.1415927f * tailamp;
        this.Tail3.z = this.Tail2.z + (float)Math.cos(this.Tail2.yRot) * 42.0f;
        this.Tail3.x = this.Tail2.x + (float)Math.sin(this.Tail2.yRot) * 42.0f;
        this.Tail3.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed - 2.0f * pi4)) * 3.1415927f * tailamp;
        this.Tail4.z = this.Tail3.z + (float)Math.cos(this.Tail3.yRot) * 41.0f;
        this.Tail4.x = this.Tail3.x + (float)Math.sin(this.Tail3.yRot) * 41.0f;
        this.Tail4.yRot = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed - 3.0f * pi4)) * 3.1415927f * tailamp;
        newangle = Mth.cos((float)(ageInTicks * tailspeed * this.wingspeed - 3.0f * pi4)) * 3.1415927f * tailamp;
        this.Tail5.z = this.Tail4.z + (float)Math.cos(this.Tail4.yRot) * 34.0f;
        this.Tail5.x = this.Tail4.x + (float)Math.sin(this.Tail4.yRot) * 34.0f;
        this.Tail5.yRot = this.Tail4.yRot + (newangle /= 2.0f);
        this.Tail6.z = this.Tail5.z + (float)Math.cos(this.Tail5.yRot) * 34.0f;
        this.Tail6.x = this.Tail5.x + (float)Math.sin(this.Tail5.yRot) * 34.0f;
        this.Tail6.yRot = this.Tail5.yRot + newangle;
        this.Tail7.z = this.Ridge6.z = this.Tail6.z + (float)Math.cos(this.Tail6.yRot) * 40.0f;
        this.Tail7.x = this.Ridge6.x = this.Tail6.x + (float)Math.sin(this.Tail6.yRot) * 40.0f;
        this.Tail7.yRot = this.Ridge6.yRot = this.Tail6.yRot + newangle;
        this.TailTip.z = this.TailTip2.z = this.Tail7.z + (float)Math.cos(this.Tail7.yRot) * 43.0f;
        this.TailTip.x = this.TailTip2.x = this.Tail7.x + (float)Math.sin(this.Tail7.yRot) * 43.0f;
        this.TailTip.yRot = this.TailTip2.yRot = this.Tail7.yRot + newangle;
        this.TailSpike.z = this.TailTip.z + (float)Math.cos(this.TailTip.yRot) * 58.0f;
        this.TailSpike.x = this.TailTip.x + (float)Math.sin(this.TailTip.yRot) * 58.0f;
        this.TailSpike.yRot = this.TailTip.yRot + newangle;
        if (entity.getAttacking() != 0) {
            Lheadlr = Mth.sin((float)(ageInTicks * 0.3f * this.wingspeed)) * 3.1415927f * 0.25f;
            Lheadud = Mth.sin((float)(ageInTicks * 0.2f * this.wingspeed)) * 3.1415927f * 0.25f;
            Ljawangle = Mth.sin((float)(ageInTicks * 0.85f * this.wingspeed)) * 3.1415927f * 0.12f;
            Rheadlr = Mth.sin((float)(ageInTicks * 0.32f * this.wingspeed)) * 3.1415927f * 0.25f;
            Rheadud = Mth.sin((float)(ageInTicks * 0.21f * this.wingspeed)) * 3.1415927f * 0.25f;
            Rjawangle = Mth.sin((float)(ageInTicks * 0.95f * this.wingspeed)) * 3.1415927f * 0.12f;
            Cheadlr = Mth.sin((float)(ageInTicks * 0.28f * this.wingspeed)) * 3.1415927f * 0.25f;
            Cheadud = Mth.sin((float)(ageInTicks * 0.19f * this.wingspeed)) * 3.1415927f * 0.25f;
            Cjawangle = Mth.sin((float)(ageInTicks * 0.75f * this.wingspeed)) * 3.1415927f * 0.12f;
            Ljawangle += 0.5f;
            Ljawangle += Lheadud;
            Cjawangle += 0.5f;
            Cjawangle += Cheadud;
            Rjawangle += 0.5f;
            Rjawangle += Rheadud;
        } else {
            Lheadlr = Mth.sin((float)(ageInTicks * 0.17f * this.wingspeed)) * 3.1415927f * 0.08f;
            Lheadud = Mth.sin((float)(ageInTicks * 0.13f * this.wingspeed)) * 3.1415927f * 0.1f;
            Ljawangle = Mth.sin((float)(ageInTicks * 0.45f * this.wingspeed)) * 3.1415927f * 0.04f;
            Rheadlr = Mth.sin((float)(ageInTicks * 0.19f * this.wingspeed)) * 3.1415927f * 0.08f;
            Rheadud = Mth.sin((float)(ageInTicks * 0.12f * this.wingspeed)) * 3.1415927f * 0.1f;
            Rjawangle = Mth.sin((float)(ageInTicks * 0.55f * this.wingspeed)) * 3.1415927f * 0.04f;
            Cheadlr = Mth.sin((float)(ageInTicks * 0.13f * this.wingspeed)) * 3.1415927f * 0.08f;
            Cheadud = Mth.sin((float)(ageInTicks * 0.08f * this.wingspeed)) * 3.1415927f * 0.1f;
            Cjawangle = Mth.sin((float)(ageInTicks * 0.65f * this.wingspeed)) * 3.1415927f * 0.04f;
            Ljawangle += 0.25f;
            Ljawangle += Lheadud;
            Cjawangle += 0.25f;
            Cjawangle += Cheadud;
            Rjawangle += 0.25f;
            Rjawangle += Rheadud;
        }
        if (Lheadlr > Cheadlr) {
            Lheadlr = Cheadlr;
        }
        if (Rheadlr < Cheadlr) {
            Rheadlr = Cheadlr;
        }
        this.moveLeftHead(Lheadlr, Lheadud, Ljawangle);
        this.moveCenterHead(Cheadlr, Cheadud, Cjawangle);
        this.moveRightHead(Rheadlr, Rheadud, Rjawangle);
        this.LCClaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LThigh.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LUpperLeg.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.TailTip.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tail1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tail2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tail3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tail4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tail5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tail6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tail7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Body1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Chest.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.NeckC1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LLowerLeg.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LFoot.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LLClaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LRClaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LCClaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LLClaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.TailSpike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LRClaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LClawRear.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.NeckL1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.NeckR1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RThigh.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RUpperLeg.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RLowerLeg.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RFoot.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RClawRear.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RLClaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RCClaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RRClaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RLClaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RCClaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RRClaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.NeckL2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.NeckC2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.NeckR2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.NeckL3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.NeckC3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.NeckR3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.NeckL4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LHead1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LHead2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LHead3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LJaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LJaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LJaw3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LTooth1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LTooth2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LTooth3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LTooth4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.NeckC4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.NeckR4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CHead1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RHead1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CHead2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RHead2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CHead3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RHead3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CJaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CJaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CJaw3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RJaw1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RJaw2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RJaw3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CTooth3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CTooth4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CTooth1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CTooth2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RTooth3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RTooth4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RTooth1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RTooth2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LLEye.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LREye.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CLEye.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CREye.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RLEye.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RREye.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LHeadMane.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CHeadMane.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RHeadMane.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LLNoseSpike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LRNoseSpike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CLNoseSpike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.CRNoseSpike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RLNoseSpike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RRNoseSpike.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Back1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Back2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lwing1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lwing3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lwing5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lwing7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lwing9.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Rwing1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Rwing3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Rwing5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Rwing7.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Rwing9.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.TailTip2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Ridge1.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Ridge2.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Ridge3.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Ridge4.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Ridge5.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Ridge6.render(poseStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lwing2.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.Lwing4.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.Lwing6.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.Lwing8.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.Lwing10.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.Rwing2.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.Rwing4.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.Rwing6.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.Rwing8.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
        this.Rwing10.render(poseStack, buffer, packedLight, packedOverlay, 0.75f, 0.75f, 0.75f, 0.55f);
    }

private void moveLeftHead(float Lheadlr, float Lheadud, float Ljawangle) {
        this.LJaw1.xRot = Ljawangle;
        this.LJaw2.xRot = Ljawangle;
        this.LJaw3.xRot = Ljawangle;
        this.LTooth1.xRot = Ljawangle;
        this.LTooth2.xRot = Ljawangle;
        this.LTooth3.xRot = Ljawangle;
        this.LTooth4.xRot = Ljawangle;
        this.NeckL1.yRot = Lheadlr * 0.125f;
        this.NeckL2.z = this.NeckL1.z - (float)Math.cos(this.NeckL1.yRot) * 20.0f;
        this.NeckL2.x = this.NeckL1.x - (float)Math.sin(this.NeckL1.yRot) * 20.0f;
        this.NeckL2.yRot = Lheadlr * 0.25f;
        this.NeckL3.z = this.NeckL2.z - (float)Math.cos(this.NeckL2.yRot) * 36.0f;
        this.NeckL3.x = this.NeckL2.x - (float)Math.sin(this.NeckL2.yRot) * 36.0f;
        this.NeckL3.yRot = Lheadlr * 0.38f;
        this.NeckL4.z = this.NeckL3.z - (float)Math.cos(this.NeckL3.yRot) * 36.0f;
        this.NeckL4.x = this.NeckL3.x - (float)Math.sin(this.NeckL3.yRot) * 36.0f;
        this.NeckL4.yRot = Lheadlr * 0.5f;
        this.LHead1.z = this.NeckL4.z - (float)Math.cos(this.NeckL4.yRot) * 36.0f;
        this.LHead1.x = this.NeckL4.x - (float)Math.sin(this.NeckL4.yRot) * 36.0f;
        this.LHead1.yRot = Lheadlr;
        this.LHead2.yRot = Lheadlr;
        this.LHead2.z = this.LHead1.z;
        this.LHead2.x = this.LHead1.x;
        this.LHead3.yRot = Lheadlr;
        this.LHead3.z = this.LHead1.z;
        this.LHead3.x = this.LHead1.x;
        this.LHeadMane.yRot = Lheadlr;
        this.LHeadMane.z = this.LHead1.z;
        this.LHeadMane.x = this.LHead1.x;
        this.LLEye.yRot = Lheadlr;
        this.LLEye.z = this.LHead1.z;
        this.LLEye.x = this.LHead1.x;
        this.LREye.yRot = Lheadlr;
        this.LREye.z = this.LHead1.z;
        this.LREye.x = this.LHead1.x;
        this.LLNoseSpike.yRot = 0.244f + Lheadlr;
        this.LLNoseSpike.z = this.LHead1.z;
        this.LLNoseSpike.x = this.LHead1.x;
        this.LRNoseSpike.yRot = -0.261f + Lheadlr;
        this.LRNoseSpike.z = this.LHead1.z;
        this.LRNoseSpike.x = this.LHead1.x;
        this.LJaw1.yRot = Lheadlr;
        this.LJaw1.z = this.NeckL4.z - (float)Math.cos(this.NeckL4.yRot) * 37.0f;
        this.LJaw1.x = this.NeckL4.x - (float)Math.sin(this.NeckL4.yRot) * 37.0f;
        this.LJaw2.yRot = Lheadlr;
        this.LJaw2.z = this.LJaw1.z;
        this.LJaw2.x = this.LJaw1.x;
        this.LJaw3.yRot = Lheadlr;
        this.LJaw3.z = this.LJaw1.z;
        this.LJaw3.x = this.LJaw1.x;
        this.LTooth1.yRot = Lheadlr;
        this.LTooth1.z = this.LJaw1.z;
        this.LTooth1.x = this.LJaw1.x;
        this.LTooth2.yRot = Lheadlr;
        this.LTooth2.z = this.LJaw1.z;
        this.LTooth2.x = this.LJaw1.x;
        this.LTooth3.yRot = Lheadlr;
        this.LTooth3.z = this.LJaw1.z;
        this.LTooth3.x = this.LJaw1.x;
        this.LTooth4.yRot = Lheadlr;
        this.LTooth4.z = this.LJaw1.z;
        this.LTooth4.x = this.LJaw1.x;
        this.NeckL1.xRot = Lheadud * 0.125f;
        this.NeckL2.y = this.NeckL1.y + (float)Math.sin(this.NeckL1.xRot) * 20.0f;
        this.NeckL2.z = this.NeckL1.z + (this.NeckL2.z - this.NeckL1.z) * (float)Math.cos(this.NeckL1.xRot);
        this.NeckL2.x = this.NeckL1.x + (this.NeckL2.x - this.NeckL1.x) * (float)Math.cos(this.NeckL1.xRot);
        this.NeckL2.xRot = Lheadud * 0.25f;
        this.NeckL3.y = this.NeckL2.y + (float)Math.sin(this.NeckL2.xRot) * 36.0f;
        this.NeckL3.z = this.NeckL2.z + (this.NeckL3.z - this.NeckL2.z) * (float)Math.cos(this.NeckL2.xRot);
        this.NeckL3.x = this.NeckL2.x + (this.NeckL3.x - this.NeckL2.x) * (float)Math.cos(this.NeckL2.xRot);
        this.NeckL3.xRot = Lheadud * 0.38f;
        this.NeckL4.y = this.NeckL3.y + (float)Math.sin(this.NeckL3.xRot) * 36.0f;
        this.NeckL4.z = this.NeckL3.z + (this.NeckL4.z - this.NeckL3.z) * (float)Math.cos(this.NeckL3.xRot);
        this.NeckL4.x = this.NeckL3.x + (this.NeckL4.x - this.NeckL3.x) * (float)Math.cos(this.NeckL3.xRot);
        this.NeckL4.xRot = Lheadud * 0.5f;
        this.LHead1.y = this.NeckL4.y + (float)Math.sin(this.NeckL4.xRot) * 36.0f;
        this.LHead1.z = this.NeckL4.z + (this.LHead1.z - this.NeckL4.z) * (float)Math.cos(this.NeckL4.xRot);
        this.LHead1.x = this.NeckL4.x + (this.LHead1.x - this.NeckL4.x) * (float)Math.cos(this.NeckL4.xRot);
        this.LHead1.xRot = Lheadud;
        this.LHead2.xRot = Lheadud;
        this.LHead2.z = this.LHead1.z;
        this.LHead2.x = this.LHead1.x;
        this.LHead2.y = this.LHead1.y;
        this.LHead3.xRot = Lheadud;
        this.LHead3.z = this.LHead1.z;
        this.LHead3.x = this.LHead1.x;
        this.LHead3.y = this.LHead1.y;
        this.LHeadMane.xRot = 0.384f + Lheadud;
        this.LHeadMane.z = this.LHead1.z;
        this.LHeadMane.x = this.LHead1.x;
        this.LHeadMane.y = this.LHead1.y;
        this.LLEye.xRot = Lheadud;
        this.LLEye.z = this.LHead1.z;
        this.LLEye.x = this.LHead1.x;
        this.LLEye.y = this.LHead1.y;
        this.LREye.xRot = Lheadud;
        this.LREye.z = this.LHead1.z;
        this.LREye.x = this.LHead1.x;
        this.LREye.y = this.LHead1.y;
        this.LLNoseSpike.xRot = 0.244f + Lheadud;
        this.LLNoseSpike.z = this.LHead1.z;
        this.LLNoseSpike.x = this.LHead1.x;
        this.LLNoseSpike.y = this.LHead1.y;
        this.LRNoseSpike.xRot = 0.261f + Lheadud;
        this.LRNoseSpike.z = this.LHead1.z;
        this.LRNoseSpike.x = this.LHead1.x;
        this.LRNoseSpike.y = this.LHead1.y;
        this.LJaw1.y = this.LHead1.y + (float)Math.cos(this.LHead1.xRot) * 14.0f;
        this.LJaw1.z = this.NeckL4.z + (this.LJaw1.z - this.NeckL4.z) * (float)Math.cos(this.NeckL4.xRot);
        this.LJaw1.z += (float)Math.sin(this.LHead1.xRot) * 14.0f;
        this.LJaw1.x = this.NeckL4.x + (this.LJaw1.x - this.NeckL4.x) * (float)Math.cos(this.NeckL4.xRot);
        this.LJaw2.z = this.LJaw1.z;
        this.LJaw2.x = this.LJaw1.x;
        this.LJaw2.y = this.LJaw1.y;
        this.LJaw3.z = this.LJaw1.z;
        this.LJaw3.x = this.LJaw1.x;
        this.LJaw3.y = this.LJaw1.y;
        this.LTooth1.z = this.LJaw1.z;
        this.LTooth1.x = this.LJaw1.x;
        this.LTooth1.y = this.LJaw1.y;
        this.LTooth2.z = this.LJaw1.z;
        this.LTooth2.x = this.LJaw1.x;
        this.LTooth2.y = this.LJaw1.y;
        this.LTooth3.z = this.LJaw1.z;
        this.LTooth3.x = this.LJaw1.x;
        this.LTooth3.y = this.LJaw1.y;
        this.LTooth4.z = this.LJaw1.z;
        this.LTooth4.x = this.LJaw1.x;
        this.LTooth4.y = this.LJaw1.y;
    }

    private void moveCenterHead(float Cheadlr, float Cheadud, float Cjawangle) {
        this.CJaw1.xRot = Cjawangle;
        this.CJaw2.xRot = Cjawangle;
        this.CJaw3.xRot = Cjawangle;
        this.CTooth1.xRot = Cjawangle;
        this.CTooth2.xRot = Cjawangle;
        this.CTooth3.xRot = Cjawangle;
        this.CTooth4.xRot = Cjawangle;
        this.NeckC1.yRot = Cheadlr * 0.125f;
        this.NeckC2.z = this.NeckC1.z - (float)Math.cos(this.NeckC1.yRot) * 20.0f;
        this.NeckC2.x = this.NeckC1.x - (float)Math.sin(this.NeckC1.yRot) * 20.0f;
        this.NeckC2.yRot = Cheadlr * 0.25f;
        this.NeckC3.z = this.NeckC2.z - (float)Math.cos(this.NeckC2.yRot) * 36.0f;
        this.NeckC3.x = this.NeckC2.x - (float)Math.sin(this.NeckC2.yRot) * 36.0f;
        this.NeckC3.yRot = Cheadlr * 0.38f;
        this.NeckC4.z = this.NeckC3.z - (float)Math.cos(this.NeckC3.yRot) * 36.0f;
        this.NeckC4.x = this.NeckC3.x - (float)Math.sin(this.NeckC3.yRot) * 36.0f;
        this.NeckC4.yRot = Cheadlr * 0.5f;
        this.CHead1.z = this.NeckC4.z - (float)Math.cos(this.NeckC4.yRot) * 36.0f;
        this.CHead1.x = this.NeckC4.x - (float)Math.sin(this.NeckC4.yRot) * 36.0f;
        this.CHead1.yRot = Cheadlr;
        this.CHead2.yRot = Cheadlr;
        this.CHead2.z = this.CHead1.z;
        this.CHead2.x = this.CHead1.x;
        this.CHead3.yRot = Cheadlr;
        this.CHead3.z = this.CHead1.z;
        this.CHead3.x = this.CHead1.x;
        this.CHeadMane.yRot = Cheadlr;
        this.CHeadMane.z = this.CHead1.z;
        this.CHeadMane.x = this.CHead1.x;
        this.CLEye.yRot = Cheadlr;
        this.CLEye.z = this.CHead1.z;
        this.CLEye.x = this.CHead1.x;
        this.CREye.yRot = Cheadlr;
        this.CREye.z = this.CHead1.z;
        this.CREye.x = this.CHead1.x;
        this.CLNoseSpike.yRot = 0.244f + Cheadlr;
        this.CLNoseSpike.z = this.CHead1.z;
        this.CLNoseSpike.x = this.CHead1.x;
        this.CRNoseSpike.yRot = -0.261f + Cheadlr;
        this.CRNoseSpike.z = this.CHead1.z;
        this.CRNoseSpike.x = this.CHead1.x;
        this.CJaw1.yRot = Cheadlr;
        this.CJaw1.z = this.NeckC4.z - (float)Math.cos(this.NeckC4.yRot) * 37.0f;
        this.CJaw1.x = this.NeckC4.x - (float)Math.sin(this.NeckC4.yRot) * 37.0f;
        this.CJaw2.yRot = Cheadlr;
        this.CJaw2.z = this.CJaw1.z;
        this.CJaw2.x = this.CJaw1.x;
        this.CJaw3.yRot = Cheadlr;
        this.CJaw3.z = this.CJaw1.z;
        this.CJaw3.x = this.CJaw1.x;
        this.CTooth1.yRot = Cheadlr;
        this.CTooth1.z = this.CJaw1.z;
        this.CTooth1.x = this.CJaw1.x;
        this.CTooth2.yRot = Cheadlr;
        this.CTooth2.z = this.CJaw1.z;
        this.CTooth2.x = this.CJaw1.x;
        this.CTooth3.yRot = Cheadlr;
        this.CTooth3.z = this.CJaw1.z;
        this.CTooth3.x = this.CJaw1.x;
        this.CTooth4.yRot = Cheadlr;
        this.CTooth4.z = this.CJaw1.z;
        this.CTooth4.x = this.CJaw1.x;
        this.NeckC1.xRot = Cheadud * 0.125f;
        this.NeckC2.y = this.NeckC1.y + (float)Math.sin(this.NeckC1.xRot) * 20.0f;
        this.NeckC2.z = this.NeckC1.z + (this.NeckC2.z - this.NeckC1.z) * (float)Math.cos(this.NeckC1.xRot);
        this.NeckC2.x = this.NeckC1.x + (this.NeckC2.x - this.NeckC1.x) * (float)Math.cos(this.NeckC1.xRot);
        this.NeckC2.xRot = Cheadud * 0.25f;
        this.NeckC3.y = this.NeckC2.y + (float)Math.sin(this.NeckC2.xRot) * 36.0f;
        this.NeckC3.z = this.NeckC2.z + (this.NeckC3.z - this.NeckC2.z) * (float)Math.cos(this.NeckC2.xRot);
        this.NeckC3.x = this.NeckC2.x + (this.NeckC3.x - this.NeckC2.x) * (float)Math.cos(this.NeckC2.xRot);
        this.NeckC3.xRot = Cheadud * 0.38f;
        this.NeckC4.y = this.NeckC3.y + (float)Math.sin(this.NeckC3.xRot) * 36.0f;
        this.NeckC4.z = this.NeckC3.z + (this.NeckC4.z - this.NeckC3.z) * (float)Math.cos(this.NeckC3.xRot);
        this.NeckC4.x = this.NeckC3.x + (this.NeckC4.x - this.NeckC3.x) * (float)Math.cos(this.NeckC3.xRot);
        this.NeckC4.xRot = Cheadud * 0.5f;
        this.CHead1.y = this.NeckC4.y + (float)Math.sin(this.NeckC4.xRot) * 36.0f;
        this.CHead1.z = this.NeckC4.z + (this.CHead1.z - this.NeckC4.z) * (float)Math.cos(this.NeckC4.xRot);
        this.CHead1.x = this.NeckC4.x + (this.CHead1.x - this.NeckC4.x) * (float)Math.cos(this.NeckC4.xRot);
        this.CHead1.xRot = Cheadud;
        this.CHead2.xRot = Cheadud;
        this.CHead2.z = this.CHead1.z;
        this.CHead2.x = this.CHead1.x;
        this.CHead2.y = this.CHead1.y;
        this.CHead3.xRot = Cheadud;
        this.CHead3.z = this.CHead1.z;
        this.CHead3.x = this.CHead1.x;
        this.CHead3.y = this.CHead1.y;
        this.CHeadMane.xRot = 0.384f + Cheadud;
        this.CHeadMane.z = this.CHead1.z;
        this.CHeadMane.x = this.CHead1.x;
        this.CHeadMane.y = this.CHead1.y;
        this.CLEye.xRot = Cheadud;
        this.CLEye.z = this.CHead1.z;
        this.CLEye.x = this.CHead1.x;
        this.CLEye.y = this.CHead1.y;
        this.CREye.xRot = Cheadud;
        this.CREye.z = this.CHead1.z;
        this.CREye.x = this.CHead1.x;
        this.CREye.y = this.CHead1.y;
        this.CLNoseSpike.xRot = 0.244f + Cheadud;
        this.CLNoseSpike.z = this.CHead1.z;
        this.CLNoseSpike.x = this.CHead1.x;
        this.CLNoseSpike.y = this.CHead1.y;
        this.CRNoseSpike.xRot = 0.261f + Cheadud;
        this.CRNoseSpike.z = this.CHead1.z;
        this.CRNoseSpike.x = this.CHead1.x;
        this.CRNoseSpike.y = this.CHead1.y;
        this.CJaw1.y = this.CHead1.y + (float)Math.cos(this.CHead1.xRot) * 14.0f;
        this.CJaw1.z = this.NeckC4.z + (this.CJaw1.z - this.NeckC4.z) * (float)Math.cos(this.NeckC4.xRot);
        this.CJaw1.z += (float)Math.sin(this.CHead1.xRot) * 14.0f;
        this.CJaw1.x = this.NeckC4.x + (this.CJaw1.x - this.NeckC4.x) * (float)Math.cos(this.NeckC4.xRot);
        this.CJaw2.z = this.CJaw1.z;
        this.CJaw2.x = this.CJaw1.x;
        this.CJaw2.y = this.CJaw1.y;
        this.CJaw3.z = this.CJaw1.z;
        this.CJaw3.x = this.CJaw1.x;
        this.CJaw3.y = this.CJaw1.y;
        this.CTooth1.z = this.CJaw1.z;
        this.CTooth1.x = this.CJaw1.x;
        this.CTooth1.y = this.CJaw1.y;
        this.CTooth2.z = this.CJaw1.z;
        this.CTooth2.x = this.CJaw1.x;
        this.CTooth2.y = this.CJaw1.y;
        this.CTooth3.z = this.CJaw1.z;
        this.CTooth3.x = this.CJaw1.x;
        this.CTooth3.y = this.CJaw1.y;
        this.CTooth4.z = this.CJaw1.z;
        this.CTooth4.x = this.CJaw1.x;
        this.CTooth4.y = this.CJaw1.y;
    }

    private void moveRightHead(float Rheadlr, float Rheadud, float Rjawangle) {
        this.RJaw1.xRot = Rjawangle;
        this.RJaw2.xRot = Rjawangle;
        this.RJaw3.xRot = Rjawangle;
        this.RTooth1.xRot = Rjawangle;
        this.RTooth2.xRot = Rjawangle;
        this.RTooth3.xRot = Rjawangle;
        this.RTooth4.xRot = Rjawangle;
        this.NeckR1.yRot = Rheadlr * 0.125f;
        this.NeckR2.z = this.NeckR1.z - (float)Math.cos(this.NeckR1.yRot) * 20.0f;
        this.NeckR2.x = this.NeckR1.x - (float)Math.sin(this.NeckR1.yRot) * 20.0f;
        this.NeckR2.yRot = Rheadlr * 0.25f;
        this.NeckR3.z = this.NeckR2.z - (float)Math.cos(this.NeckR2.yRot) * 36.0f;
        this.NeckR3.x = this.NeckR2.x - (float)Math.sin(this.NeckR2.yRot) * 36.0f;
        this.NeckR3.yRot = Rheadlr * 0.38f;
        this.NeckR4.z = this.NeckR3.z - (float)Math.cos(this.NeckR3.yRot) * 36.0f;
        this.NeckR4.x = this.NeckR3.x - (float)Math.sin(this.NeckR3.yRot) * 36.0f;
        this.NeckR4.yRot = Rheadlr * 0.5f;
        this.RHead1.z = this.NeckR4.z - (float)Math.cos(this.NeckR4.yRot) * 36.0f;
        this.RHead1.x = this.NeckR4.x - (float)Math.sin(this.NeckR4.yRot) * 36.0f;
        this.RHead1.yRot = Rheadlr;
        this.RHead2.yRot = Rheadlr;
        this.RHead2.z = this.RHead1.z;
        this.RHead2.x = this.RHead1.x;
        this.RHead3.yRot = Rheadlr;
        this.RHead3.z = this.RHead1.z;
        this.RHead3.x = this.RHead1.x;
        this.RHeadMane.yRot = Rheadlr;
        this.RHeadMane.z = this.RHead1.z;
        this.RHeadMane.x = this.RHead1.x;
        this.RLEye.yRot = Rheadlr;
        this.RLEye.z = this.RHead1.z;
        this.RLEye.x = this.RHead1.x;
        this.RREye.yRot = Rheadlr;
        this.RREye.z = this.RHead1.z;
        this.RREye.x = this.RHead1.x;
        this.RLNoseSpike.yRot = 0.244f + Rheadlr;
        this.RLNoseSpike.z = this.RHead1.z;
        this.RLNoseSpike.x = this.RHead1.x;
        this.RRNoseSpike.yRot = -0.261f + Rheadlr;
        this.RRNoseSpike.z = this.RHead1.z;
        this.RRNoseSpike.x = this.RHead1.x;
        this.RJaw1.yRot = Rheadlr;
        this.RJaw1.z = this.NeckR4.z - (float)Math.cos(this.NeckR4.yRot) * 37.0f;
        this.RJaw1.x = this.NeckR4.x - (float)Math.sin(this.NeckR4.yRot) * 37.0f;
        this.RJaw2.yRot = Rheadlr;
        this.RJaw2.z = this.RJaw1.z;
        this.RJaw2.x = this.RJaw1.x;
        this.RJaw3.yRot = Rheadlr;
        this.RJaw3.z = this.RJaw1.z;
        this.RJaw3.x = this.RJaw1.x;
        this.RTooth1.yRot = Rheadlr;
        this.RTooth1.z = this.RJaw1.z;
        this.RTooth1.x = this.RJaw1.x;
        this.RTooth2.yRot = Rheadlr;
        this.RTooth2.z = this.RJaw1.z;
        this.RTooth2.x = this.RJaw1.x;
        this.RTooth3.yRot = Rheadlr;
        this.RTooth3.z = this.RJaw1.z;
        this.RTooth3.x = this.RJaw1.x;
        this.RTooth4.yRot = Rheadlr;
        this.RTooth4.z = this.RJaw1.z;
        this.RTooth4.x = this.RJaw1.x;
        this.NeckR1.xRot = Rheadud * 0.125f;
        this.NeckR2.y = this.NeckR1.y + (float)Math.sin(this.NeckR1.xRot) * 20.0f;
        this.NeckR2.z = this.NeckR1.z + (this.NeckR2.z - this.NeckR1.z) * (float)Math.cos(this.NeckR1.xRot);
        this.NeckR2.x = this.NeckR1.x + (this.NeckR2.x - this.NeckR1.x) * (float)Math.cos(this.NeckR1.xRot);
        this.NeckR2.xRot = Rheadud * 0.25f;
        this.NeckR3.y = this.NeckR2.y + (float)Math.sin(this.NeckR2.xRot) * 36.0f;
        this.NeckR3.z = this.NeckR2.z + (this.NeckR3.z - this.NeckR2.z) * (float)Math.cos(this.NeckR2.xRot);
        this.NeckR3.x = this.NeckR2.x + (this.NeckR3.x - this.NeckR2.x) * (float)Math.cos(this.NeckR2.xRot);
        this.NeckR3.xRot = Rheadud * 0.38f;
        this.NeckR4.y = this.NeckR3.y + (float)Math.sin(this.NeckR3.xRot) * 36.0f;
        this.NeckR4.z = this.NeckR3.z + (this.NeckR4.z - this.NeckR3.z) * (float)Math.cos(this.NeckR3.xRot);
        this.NeckR4.x = this.NeckR3.x + (this.NeckR4.x - this.NeckR3.x) * (float)Math.cos(this.NeckR3.xRot);
        this.NeckR4.xRot = Rheadud * 0.5f;
        this.RHead1.y = this.NeckR4.y + (float)Math.sin(this.NeckR4.xRot) * 36.0f;
        this.RHead1.z = this.NeckR4.z + (this.RHead1.z - this.NeckR4.z) * (float)Math.cos(this.NeckR4.xRot);
        this.RHead1.x = this.NeckR4.x + (this.RHead1.x - this.NeckR4.x) * (float)Math.cos(this.NeckR4.xRot);
        this.RHead1.xRot = Rheadud;
        this.RHead2.xRot = Rheadud;
        this.RHead2.z = this.RHead1.z;
        this.RHead2.x = this.RHead1.x;
        this.RHead2.y = this.RHead1.y;
        this.RHead3.xRot = Rheadud;
        this.RHead3.z = this.RHead1.z;
        this.RHead3.x = this.RHead1.x;
        this.RHead3.y = this.RHead1.y;
        this.RHeadMane.xRot = 0.384f + Rheadud;
        this.RHeadMane.z = this.RHead1.z;
        this.RHeadMane.x = this.RHead1.x;
        this.RHeadMane.y = this.RHead1.y;
        this.RLEye.xRot = Rheadud;
        this.RLEye.z = this.RHead1.z;
        this.RLEye.x = this.RHead1.x;
        this.RLEye.y = this.RHead1.y;
        this.RREye.xRot = Rheadud;
        this.RREye.z = this.RHead1.z;
        this.RREye.x = this.RHead1.x;
        this.RREye.y = this.RHead1.y;
        this.RLNoseSpike.xRot = 0.244f + Rheadud;
        this.RLNoseSpike.z = this.RHead1.z;
        this.RLNoseSpike.x = this.RHead1.x;
        this.RLNoseSpike.y = this.RHead1.y;
        this.RRNoseSpike.xRot = 0.261f + Rheadud;
        this.RRNoseSpike.z = this.RHead1.z;
        this.RRNoseSpike.x = this.RHead1.x;
        this.RRNoseSpike.y = this.RHead1.y;
        this.RJaw1.y = this.RHead1.y + (float)Math.cos(this.RHead1.xRot) * 14.0f;
        this.RJaw1.z = this.NeckR4.z + (this.RJaw1.z - this.NeckR4.z) * (float)Math.cos(this.NeckR4.xRot);
        this.RJaw1.z += (float)Math.sin(this.RHead1.xRot) * 14.0f;
        this.RJaw1.x = this.NeckR4.x + (this.RJaw1.x - this.NeckR4.x) * (float)Math.cos(this.NeckR4.xRot);
        this.RJaw2.z = this.RJaw1.z;
        this.RJaw2.x = this.RJaw1.x;
        this.RJaw2.y = this.RJaw1.y;
        this.RJaw3.z = this.RJaw1.z;
        this.RJaw3.x = this.RJaw1.x;
        this.RJaw3.y = this.RJaw1.y;
        this.RTooth1.z = this.RJaw1.z;
        this.RTooth1.x = this.RJaw1.x;
        this.RTooth1.y = this.RJaw1.y;
        this.RTooth2.z = this.RJaw1.z;
        this.RTooth2.x = this.RJaw1.x;
        this.RTooth2.y = this.RJaw1.y;
        this.RTooth3.z = this.RJaw1.z;
        this.RTooth3.x = this.RJaw1.x;
        this.RTooth3.y = this.RJaw1.y;
        this.RTooth4.z = this.RJaw1.z;
        this.RTooth4.x = this.RJaw1.x;
        this.RTooth4.y = this.RJaw1.y;
    }
}
