package com.astryxion.chaospersists.core;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.event.RegistryEvent;

/**
 * All Chaos Persists / OreSpawn sound events. Mapped from 1.7.10 orespawn sounds.json.
 * Register in FML init; entities use these constants instead of REGISTRY.getObject().
 */
public class ChaosSounds {

    private static final String MODID = "chaospersists";

    public static SoundEvent ALIEN_HURT;
    public static SoundEvent ALIEN_DEATH;
    public static SoundEvent ALIEN_LIVING;
    public static SoundEvent ALO_HURT;
    public static SoundEvent ALO_DEATH;
    public static SoundEvent ALO_LIVING;
    public static SoundEvent B_DARK;
    public static SoundEvent B_DEATH_BOYFRIEND;
    public static SoundEvent B_DEATH_SINGLE;
    public static SoundEvent B_FIGHT;
    public static SoundEvent B_HAPPY;
    public static SoundEvent B_HURT;
    public static SoundEvent B_OW;
    public static SoundEvent B_RAIN;
    public static SoundEvent B_TAUNT;
    public static SoundEvent B_THUNDER;
    public static SoundEvent B_WATER;
    public static SoundEvent B_WOOHOO;
    public static SoundEvent BASILISK_LIVING;
    public static SoundEvent BB_HAPPY;
    public static SoundEvent BEEBUZZ;
    public static SoundEvent BIG_SPLAT;
    public static SoundEvent BIRDS;
    public static SoundEvent CATERKILLER_DEATH;
    public static SoundEvent CATERKILLER_HIT;
    public static SoundEvent CATERKILLER_LIVING;
    public static SoundEvent CHAIN_RATTLES;
    public static SoundEvent CHAINSAW;
    public static SoundEvent CHAINSAWSHORT;
    public static SoundEvent CLATTER;
    public static SoundEvent CLIFFRACER;
    public static SoundEvent CREEPINGHORROR_DEAD;
    public static SoundEvent CREEPINGHORROR_HIT;
    public static SoundEvent CREEPINGHORROR_LIVING;
    public static SoundEvent CRICKET;
    public static SoundEvent CRUNCH;
    public static SoundEvent CRYO_DEATH;
    public static SoundEvent CRYO_HURT;
    public static SoundEvent CRYO_LIVING;
    public static SoundEvent DBDEAD;
    public static SoundEvent DBHIT;
    public static SoundEvent DRAGONFLY_DEATH;
    public static SoundEvent DRAGONFLY_HURT;
    public static SoundEvent DRAGONFLY_LIVING;
    public static SoundEvent DUCK_HURT;
    public static SoundEvent EMPERORSCORPION_DEATH;
    public static SoundEvent FART;
    public static SoundEvent FROG;
    public static SoundEvent GHOST_SOUND;
    public static SoundEvent GLASSDEAD;
    public static SoundEvent GLASSHIT;
    public static SoundEvent GODZILLA_DEATH;
    public static SoundEvent GODZILLA_LIVING;
    public static SoundEvent HAMMERHEAD_DEATH;
    public static SoundEvent HAMMERHEAD_LIVING;
    public static SoundEvent HERCULES_DEATH;
    public static SoundEvent HOVER;
    public static SoundEvent KING_HIT;
    public static SoundEvent KING_LIVING;
    public static SoundEvent KRAKEN_LIVING;
    public static SoundEvent KYUUBI_LIVING;
    public static SoundEvent LEAVES_DEATH;
    public static SoundEvent LEAVES_HIT;
    public static SoundEvent LEON_DEATH;
    public static SoundEvent LEON_HIT;
    public static SoundEvent LEON_LIVING;
    public static SoundEvent LITTLE_SPLAT;
    public static SoundEvent LURKINGHORROR_DEAD;
    public static SoundEvent LURKINGHORROR_HIT;
    public static SoundEvent LURKINGHORROR_LIVING;
    public static SoundEvent MOLENOID_DEATH;
    public static SoundEvent MOLENOID_HIT;
    public static SoundEvent MOLENOID_LIVING;
    public static SoundEvent MOSQUITO;
    public static SoundEvent MOTHRA_WINGS;
    public static SoundEvent O_DARK;
    public static SoundEvent O_DEATH_GIRLFRIEND;
    public static SoundEvent O_DEATH_SINGLE;
    public static SoundEvent O_FIGHT;
    public static SoundEvent O_HAPPY;
    public static SoundEvent O_HURT;
    public static SoundEvent O_OW;
    public static SoundEvent O_RAIN;
    public static SoundEvent O_TAUNT;
    public static SoundEvent O_THUNDER;
    public static SoundEvent O_WATER;
    public static SoundEvent O_WOOHOO;
    public static SoundEvent PEACOCKDEAD;
    public static SoundEvent PEACOCKHIT;
    public static SoundEvent PEACOCKLIVE;
    public static SoundEvent PITCHBLACK_DEAD;
    public static SoundEvent PITCHBLACK_HIT;
    public static SoundEvent PITCHBLACK_LIVING;
    public static SoundEvent RATDEAD;
    public static SoundEvent RATHIT;
    public static SoundEvent RATLIVE;
    public static SoundEvent ROAR;
    public static SoundEvent ROBOT_DEATH;
    public static SoundEvent ROBOT_HURT;
    public static SoundEvent ROBOT_LIVING;
    public static SoundEvent ROBOT1_DEATH;
    public static SoundEvent ROBOTSPIDER;
    public static SoundEvent ROBOTSPIDERMOUNT;
    public static SoundEvent RUBYBIRD;
    public static SoundEvent SCORPION_ATTACK;
    public static SoundEvent SCORPION_HIT;
    public static SoundEvent SCORPION_LIVING;
    public static SoundEvent SEAMONSTER_DEATH;
    public static SoundEvent SEAMONSTER_HIT;
    public static SoundEvent SEAMONSTER_LIVING;
    public static SoundEvent SEAVIPER_DEATH;
    public static SoundEvent SEAVIPER_HIT;
    public static SoundEvent SEAVIPER_LIVING;
    public static SoundEvent SQUID_DEATH;
    public static SoundEvent SQUID_HURT;
    public static SoundEvent TERRIBLETERROR_DEAD;
    public static SoundEvent TERRIBLETERROR_HIT;
    public static SoundEvent TERRIBLETERROR_LIVING;
    public static SoundEvent TREX_DEATH;
    public static SoundEvent TREX_LIVING;
    public static SoundEvent TRIFFID_DEAD;
    public static SoundEvent TRIFFID_HIT;
    public static SoundEvent TRIFFID_LIVING;
    public static SoundEvent VORTEXLIVE;
    public static SoundEvent WATERDRAGON_DEATH;
    public static SoundEvent WATERDRAGON_HURT;
    public static SoundEvent WTF_HURT;
    public static SoundEvent WTF_LIVING;

    private static SoundEvent create(String name) {
        ResourceLocation loc = new ResourceLocation(MODID, name);
        return new SoundEvent(loc).setRegistryName(loc);
    }

    /** Call from ChaosPersists @SubscribeEvent for Register&lt;SoundEvent&gt; */
    public static void registerSounds(RegistryEvent.Register<SoundEvent> event) {
        event.getRegistry().register(ALIEN_HURT = create("alien_hurt"));
        event.getRegistry().register(ALIEN_DEATH = create("alien_death"));
        event.getRegistry().register(ALIEN_LIVING = create("alien_living"));
        event.getRegistry().register(ALO_HURT = create("alo_hurt"));
        event.getRegistry().register(ALO_DEATH = create("alo_death"));
        event.getRegistry().register(ALO_LIVING = create("alo_living"));
        event.getRegistry().register(B_DARK = create("b_dark"));
        event.getRegistry().register(B_DEATH_BOYFRIEND = create("b_death_boyfriend"));
        event.getRegistry().register(B_DEATH_SINGLE = create("b_death_single"));
        event.getRegistry().register(B_FIGHT = create("b_fight"));
        event.getRegistry().register(B_HAPPY = create("b_happy"));
        event.getRegistry().register(B_HURT = create("b_hurt"));
        event.getRegistry().register(B_OW = create("b_ow"));
        event.getRegistry().register(B_RAIN = create("b_rain"));
        event.getRegistry().register(B_TAUNT = create("b_taunt"));
        event.getRegistry().register(B_THUNDER = create("b_thunder"));
        event.getRegistry().register(B_WATER = create("b_water"));
        event.getRegistry().register(B_WOOHOO = create("b_woohoo"));
        event.getRegistry().register(BASILISK_LIVING = create("basilisk_living"));
        event.getRegistry().register(BB_HAPPY = create("bb_happy"));
        event.getRegistry().register(BEEBUZZ = create("Beebuzz"));
        event.getRegistry().register(BIG_SPLAT = create("big_splat"));
        event.getRegistry().register(BIRDS = create("birds"));
        event.getRegistry().register(CATERKILLER_DEATH = create("caterkiller_death"));
        event.getRegistry().register(CATERKILLER_HIT = create("caterkiller_hit"));
        event.getRegistry().register(CATERKILLER_LIVING = create("caterkiller_living"));
        event.getRegistry().register(CHAIN_RATTLES = create("chain_rattles"));
        event.getRegistry().register(CHAINSAW = create("chainsaw"));
        event.getRegistry().register(CHAINSAWSHORT = create("chainsawshort"));
        event.getRegistry().register(CLATTER = create("clatter"));
        event.getRegistry().register(CLIFFRACER = create("cliffracer"));
        event.getRegistry().register(CREEPINGHORROR_DEAD = create("creepinghorror_dead"));
        event.getRegistry().register(CREEPINGHORROR_HIT = create("creepinghorror_hit"));
        event.getRegistry().register(CREEPINGHORROR_LIVING = create("creepinghorror_living"));
        event.getRegistry().register(CRICKET = create("cricket"));
        event.getRegistry().register(CRUNCH = create("crunch"));
        event.getRegistry().register(CRYO_DEATH = create("cryo_death"));
        event.getRegistry().register(CRYO_HURT = create("cryo_hurt"));
        event.getRegistry().register(CRYO_LIVING = create("cryo_living"));
        event.getRegistry().register(DBDEAD = create("dbdead"));
        event.getRegistry().register(DBHIT = create("dbhit"));
        event.getRegistry().register(DRAGONFLY_DEATH = create("dragonfly_death"));
        event.getRegistry().register(DRAGONFLY_HURT = create("dragonfly_hurt"));
        event.getRegistry().register(DRAGONFLY_LIVING = create("dragonfly_living"));
        event.getRegistry().register(DUCK_HURT = create("duck_hurt"));
        event.getRegistry().register(EMPERORSCORPION_DEATH = create("emperorscorpion_death"));
        event.getRegistry().register(FART = create("fart"));
        event.getRegistry().register(FROG = create("frog"));
        event.getRegistry().register(GHOST_SOUND = create("ghost_sound"));
        event.getRegistry().register(GLASSDEAD = create("glassdead"));
        event.getRegistry().register(GLASSHIT = create("glasshit"));
        event.getRegistry().register(GODZILLA_DEATH = create("godzilla_death"));
        event.getRegistry().register(GODZILLA_LIVING = create("godzilla_living"));
        event.getRegistry().register(HAMMERHEAD_DEATH = create("hammerhead_death"));
        event.getRegistry().register(HAMMERHEAD_LIVING = create("hammerhead_living"));
        event.getRegistry().register(HERCULES_DEATH = create("hercules_death"));
        event.getRegistry().register(HOVER = create("hover"));
        event.getRegistry().register(KING_HIT = create("king_hit"));
        event.getRegistry().register(KING_LIVING = create("king_living"));
        event.getRegistry().register(KRAKEN_LIVING = create("kraken_living"));
        event.getRegistry().register(KYUUBI_LIVING = create("kyuubi_living"));
        event.getRegistry().register(LEAVES_DEATH = create("leaves_death"));
        event.getRegistry().register(LEAVES_HIT = create("leaves_hit"));
        event.getRegistry().register(LEON_DEATH = create("leon_death"));
        event.getRegistry().register(LEON_HIT = create("leon_hit"));
        event.getRegistry().register(LEON_LIVING = create("leon_living"));
        event.getRegistry().register(LITTLE_SPLAT = create("little_splat"));
        event.getRegistry().register(LURKINGHORROR_DEAD = create("lurkinghorror_dead"));
        event.getRegistry().register(LURKINGHORROR_HIT = create("lurkinghorror_hit"));
        event.getRegistry().register(LURKINGHORROR_LIVING = create("lurkinghorror_living"));
        event.getRegistry().register(MOLENOID_DEATH = create("molenoid_death"));
        event.getRegistry().register(MOLENOID_HIT = create("molenoid_hit"));
        event.getRegistry().register(MOLENOID_LIVING = create("molenoid_living"));
        event.getRegistry().register(MOSQUITO = create("mosquito"));
        event.getRegistry().register(MOTHRA_WINGS = create("MothraWings"));
        event.getRegistry().register(O_DARK = create("o_dark"));
        event.getRegistry().register(O_DEATH_GIRLFRIEND = create("o_death_girlfriend"));
        event.getRegistry().register(O_DEATH_SINGLE = create("o_death_single"));
        event.getRegistry().register(O_FIGHT = create("o_fight"));
        event.getRegistry().register(O_HAPPY = create("o_happy"));
        event.getRegistry().register(O_HURT = create("o_hurt"));
        event.getRegistry().register(O_OW = create("o_ow"));
        event.getRegistry().register(O_RAIN = create("o_rain"));
        event.getRegistry().register(O_TAUNT = create("o_taunt"));
        event.getRegistry().register(O_THUNDER = create("o_thunder"));
        event.getRegistry().register(O_WATER = create("o_water"));
        event.getRegistry().register(O_WOOHOO = create("o_woohoo"));
        event.getRegistry().register(PEACOCKDEAD = create("peacockdead"));
        event.getRegistry().register(PEACOCKHIT = create("peacockhit"));
        event.getRegistry().register(PEACOCKLIVE = create("peacocklive"));
        event.getRegistry().register(PITCHBLACK_DEAD = create("pitchblack_dead"));
        event.getRegistry().register(PITCHBLACK_HIT = create("pitchblack_hit"));
        event.getRegistry().register(PITCHBLACK_LIVING = create("pitchblack_living"));
        event.getRegistry().register(RATDEAD = create("ratdead"));
        event.getRegistry().register(RATHIT = create("rathit"));
        event.getRegistry().register(RATLIVE = create("ratlive"));
        event.getRegistry().register(ROAR = create("roar"));
        event.getRegistry().register(ROBOT_DEATH = create("robot_death"));
        event.getRegistry().register(ROBOT_HURT = create("robot_hurt"));
        event.getRegistry().register(ROBOT_LIVING = create("robot_living"));
        event.getRegistry().register(ROBOT1_DEATH = create("robot1_death"));
        event.getRegistry().register(ROBOTSPIDER = create("robotspider"));
        event.getRegistry().register(ROBOTSPIDERMOUNT = create("robotspidermount"));
        event.getRegistry().register(RUBYBIRD = create("rubybird"));
        event.getRegistry().register(SCORPION_ATTACK = create("scorpion_attack"));
        event.getRegistry().register(SCORPION_HIT = create("scorpion_hit"));
        event.getRegistry().register(SCORPION_LIVING = create("scorpion_living"));
        event.getRegistry().register(SEAMONSTER_DEATH = create("seamonster_death"));
        event.getRegistry().register(SEAMONSTER_HIT = create("seamonster_hit"));
        event.getRegistry().register(SEAMONSTER_LIVING = create("seamonster_living"));
        event.getRegistry().register(SEAVIPER_DEATH = create("seaviper_death"));
        event.getRegistry().register(SEAVIPER_HIT = create("seaviper_hit"));
        event.getRegistry().register(SEAVIPER_LIVING = create("seaviper_living"));
        event.getRegistry().register(SQUID_DEATH = create("squid_death"));
        event.getRegistry().register(SQUID_HURT = create("squid_hurt"));
        event.getRegistry().register(TERRIBLETERROR_DEAD = create("terribleterror_dead"));
        event.getRegistry().register(TERRIBLETERROR_HIT = create("terribleterror_hit"));
        event.getRegistry().register(TERRIBLETERROR_LIVING = create("terribleterror_living"));
        event.getRegistry().register(TREX_DEATH = create("trex_death"));
        event.getRegistry().register(TREX_LIVING = create("trex_living"));
        event.getRegistry().register(TRIFFID_DEAD = create("triffid_dead"));
        event.getRegistry().register(TRIFFID_HIT = create("triffid_hit"));
        event.getRegistry().register(TRIFFID_LIVING = create("triffid_living"));
        event.getRegistry().register(VORTEXLIVE = create("vortexlive"));
        event.getRegistry().register(WATERDRAGON_DEATH = create("waterdragon_death"));
        event.getRegistry().register(WATERDRAGON_HURT = create("waterdragon_hurt"));
        event.getRegistry().register(WTF_HURT = create("wtf_hurt"));
        event.getRegistry().register(WTF_LIVING = create("wtf_living"));
    }
}
